### ISSUE TITLE
Think about TurnInputIntoReferencesOperator

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1002]
#998 gives an example where we misuse a TableScan to generate get hold of a ReferenceColumn.

**Comment by mrks** [comment]
That is only a test case though. In the non-test world, there should be no need for this.

**Comment by Bensk1** [comment]
Right, but it would be nice to have it for tests and avoid the current hacks.

**Comment by mrzzzrm** [comment]
@Bensk1 Closing this, we had plenty of time to think about this and yet haven't reached a conclusion. It's probably a minor thing

**Comment by Bensk1** [comment]
+1 for cleaning up the issue list.
