### ISSUE TITLE
Predicate on aliased subquery

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1021]
```
(debug)> load src/test/tables/tpch/sf-0.001/region.tbl region
Loading src/test/tables/tpch/sf-0.001/region.tbl into table "region" ...
(debug)!> SELECT *, (SELECT MAX(r_regionkey) FROM region) AS max FROM region WHERE r_regionkey < max AND r_regionkey > 0
Invalid input error: Couldn't resolve identifier 'max' or it is ambiguous
```

**Comment by mrzzzrm** [comment]
Intentional, this referencing names from the SELECT list doesn't work in other dbs either.

MySQL and Postgres reject `SELECT 5 + 3 AS x FROM Table1 WHERE x > 5`, e.g.

**Comment by mrks** [comment]
I would have sworn that that was legal. :(

**Comment by mrzzzrm** [comment]
Think `SELECT t1.x AS b FROM t1, a_table_containing_a_column_x WHERE x > 5`.

Is the x in the WHERE clause ambiguous or not? What gets "processed" first, the SELECT or the WHERE? I went with the WHERE.

**Comment by mrzzzrm** [comment]
A similar question: https://github.com/hyrise/hyrise/issues/946#issuecomment-401608309
