### ISSUE TITLE
OR in DELETE throws error

### ISSUE THREAD

**Issue by dimitri-schmidt** [hyrise/hyrise#1033]
In HyriseConsole and HyriseServer:

```
> load src/test/tables/int_string.tbl a_table;
> DELETE FROM a_table WHERE a = 4 or b = 'test16';
```

throws an error, but both values exist. Two successive deletes without 'or' doesn't throw.
Error in delete.cpp:
```
std::shared_ptr<const Table> Delete::_on_execute(std::shared_ptr<TransactionContext> context) {
   DebugAssert(_execution_input_valid(context), "Input to Delete isn't valid");
```

since _execution_input_valid returnes false:
```
bool Delete::_execution_input_valid(const std::shared_ptr<TransactionContext>& context) const {
  ...
  const auto values_to_delete = input_table_left();
  ...
  const auto table = StorageManager::get().get_table(_table_name);
  ...
  for (ChunkID chunk_id{0}; chunk_id < values_to_delete->chunk_count(); ++chunk_id) {
    const auto chunk = values_to_delete->get_chunk(chunk_id);

    ...

    const auto first_column = std::static_pointer_cast<const ReferenceColumn>(chunk->get_column(ColumnID{0}));

    if (table != first_column->referenced_table()) return false;
  }

  return true;
}
```

**Comment by mrzzzrm** [comment]
`a = 4 or b = 'test16'` doesn't produce ReferenceColumns anymore since #882

**Comment by mrzzzrm** [comment]
Short term solution: Re-enable UnionPositions for ORs in DELETEs
Long term solution: ExpressionEvaluator should get evaluate-to-pos-lists support, Delete should use ExpressionEvaluator instead of sub-plan.

**Comment by mrks** [comment]
What does the table that comes out of the TableScan look like?

Generally, I think we should stick with the concept that delete simply takes a referencing table.

**Comment by mrzzzrm** [comment]
It contains ReferenceColumns that point to a temporary table.

**Comment by mrzzzrm** [comment]
Let me hack a quick fix for this

**Comment by mrks** [comment]
@mrzzzrm - Could you give me an example of that temporary table, please?

**Comment by mrzzzrm** [comment]
`SELECT * FROM a_table WHERE a = 4 or b = 'test16'`

will be computed by a ProjectionNode computing `a = 4 or b = 'test16'` into a temporary bool column and a PredicateNode scanning this temporary column for `!= false`.

Thus the temporary table will be the original table with another column containing the result of `a = 4 or b = 'test16'`

**Comment by mrks** [comment]
Ok, got it for now.

**Comment by mrzzzrm** [comment]
We could in theory just use the ReferenceColumn's PosList and ignore the fact that it points to a temporary table. 
Still hacky.
