### ISSUE TITLE
Find better _radix_bits

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1045]
Comparing `_radix_bits = 9` to `_radix_bits = 0`:

```
+-----------+------------------+------+-----------------+------+---------+---------------------------------+
| Benchmark | prev. iter/s     | runs | new iter/s      | runs | change  | p-value (significant if <0.001) |
+-----------+------------------+------+-----------------+------+---------+---------------------------------+
| TPC-H 1   | 1.77056348324    | 213  | 1.75972640514   | 212  | -1%     |                          0.0054 |
| TPC-H 2   | 29.8127670288    | 3578 | 48.1226806641   | 5775 | +61%    |                          0.0000 |
| TPC-H 3   | 20.0760822296    | 2410 | 26.5160713196   | 3182 | +32%    |                          0.0000 |
| TPC-H 4   | 0.210900396109   | 26   | 0.212299197912  | 26   | +1%     |                          0.2118 |
| TPC-H 5   | 13.5522403717    | 1627 | 17.2646770477   | 2072 | +27%    |                          0.0000 |
| TPC-H 6   | 59.9964408875    | 7200 | 60.3719596863   | 7245 | +1%     |                          0.0000 |
| TPC-H 7   | 4.98639345169    | 599  | 5.51244926453   | 662  | +11%    |                          0.0000 |
| TPC-H 8   | 3.92327094078    | 471  | 2.94422745705   | 354  | -25%    |                          0.0000 |
| TPC-H 9   | 2.18278455734    | 262  | 2.23703861237   | 269  | +2%     |                          0.0000 |
| TPC-H 10  | 14.7751970291    | 1774 | 17.1352806091   | 2057 | +16%    |                          0.0000 |
| TPC-H 11  | 43.4202919006    | 5211 | 42.485622406    | 5099 | -2%     |                          0.0000 |
| TPC-H 12  | 21.1038837433    | 2533 | 30.5092163086   | 3662 | +45%    |                          0.0000 |
| TPC-H 13  | 12.131726265     | 1456 | 12.6561632156   | 1519 | +4%     |                          0.0000 |
| TPC-H 14  | 47.1568641663    | 5659 | 67.6981430054   | 8124 | +44%    |                          0.0000 |
| TPC-H 15  | 0.245661795139   | 30   | 51.6224479675   | 6195 | +20914% |                          0.0000 |
| TPC-H 16  | 9.42947769165    | 1132 | 10.8437166214   | 1302 | +15%    |                          0.0000 |
| TPC-H 17  | 1.95363533497    | 235  | 1.8807322979    | 226  | -4%     |                          0.0000 |
| TPC-H 18  | 0.0124519411474  | 2    | 1.78255414963   | 214  | +14215% |        (not enough runs) 0.0000 |
| TPC-H 19  | 2.05173134804    | 247  | 1.95750486851   | 235  | -5%     |                          0.0000 |
| TPC-H 20  | 0.00828054361045 | 1    | 0.0082748318091 | 1    | -0%     |           (not enough runs) nan |
| TPC-H 21  | 0.126209974289   | 16   | 0.127985700965  | 16   | +1%     |                          0.0722 |
| TPC-H 22  | 0.479876816273   | 58   | 0.480097740889  | 58   | +0%     |                          0.9111 |
| average   |                  |      |                 |      | +1607%  |                                 |
+-----------+------------------+------+-----------------+------+---------+---------------------------------+
```

Scale factor was `0.1`. For small tables, it is expected that a low number of buckets works better than `2^9=512`, but this...

And yes, all tests pass.

**Comment by mrzzzrm** [comment]
lul :rofl: would it be possible to get before-after PQP visualizations for TPC-H 15 and 18? Just to see which joins (just one; multiple) get faster, how much input/output rows the have etc.

**Comment by TwoLaid** [comment]
Muahahahaha

**Comment by mrzzzrm** [comment]
(Is this possible because the TPC-H data is so uniformely distributed?)

**Comment by Bouncner** [comment]
Yeah, I know. I will push a WIP PR today that covers exactly that.

Small joins (that means the left size is small, which is pretty much always the case) will be up much faster than. And there is still room for improvement, but something small blocked me since last week.

Bigger joins however (the figure does not really show "BIG" tables) require radix partitioning (what was its major goal all along: OLAP joins). But finding the ideal radix partitioning here was rather surprising to me here, to be honest.

![image](https://user-images.githubusercontent.com/1745857/43886406-e6b5d57e-9bbb-11e8-9dc0-e39c34fb368d.png)
Graph shows runtime vs. max runtime over all radix bit configurations (no scheduling).

I will post a Jupyter notebook later as well.

**Comment by mrks** [comment]
@mrzzzrm - good that you asked.

[Archive.zip](https://github.com/hyrise/hyrise/files/2273336/Archive.zip)

If you compare TPC-H 18, you will see that while there is some difference in the hash join, it is the projection that goes berserk. With one input chunk (_radix_bits==1), it takes 488ms, with 512 chunks (_radix_bits==9), it takes 1 min 23s.

My quick guess is this:
https://github.com/hyrise/hyrise/blob/82d00de170a424e08133842e552df8328aab8150/src/lib/operators/projection.cpp#L78
together with this:
https://github.com/hyrise/hyrise/blob/82d00de170a424e08133842e552df8328aab8150/src/lib/expression/evaluation/expression_evaluator.cpp#L684

Currently, we evaluate non-correlated subqueries once per expression, but the ExpressionEvaluator is called once per chunk. When dividing the runtime by the number of chunks, both end up in the same ballpark.

Any thoughts on how to address this?

**Comment by Bouncner** [comment]
Concerning the number of partitions ...
Marcus, as we shortly discussed last week, it might be a nice seminar topic to get a better understanding of the trade-off between nicely parallel radix joins with many partitions and slightly slower joins but with less partitioning/chunk overhead.
And especially a potential operator to solve the issue (it don't know what came out of the seminar discussion last week).

Besides that, currently the radix partitioning will be 0-bit for many many joins while it can be up to 1-bit-per-1M rows. But for such large joins, the resulting overhead in the following operators might be neglectable. What to do you think?
Does 10bit for 10M rows sound too much? It's the fastest for a 1k-10M join.

**Comment by mrks** [comment]
I have no intuition for those numbers. Whatever the benchmarks tell us. We don't have to come up with the perfect number here, especially if you want to compare other hashmap implementations later. Something better than "9" works.
