### ISSUE TITLE
Uncorrelated subqueries get executed once per chunk

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1046]
[Archive.zip](https://github.com/hyrise/hyrise/files/2273336/Archive.zip)

If you compare TPC-H 18, you will see that while there is some difference in the hash join, it is the projection that goes berserk. With one input chunk (_radix_bits==1), it takes 488ms, with 512 chunks (_radix_bits==9), it takes 1 min 23s.

My quick guess is this:
https://github.com/hyrise/hyrise/blob/82d00de170a424e08133842e552df8328aab8150/src/lib/operators/projection.cpp#L78
together with this:
https://github.com/hyrise/hyrise/blob/82d00de170a424e08133842e552df8328aab8150/src/lib/expression/evaluation/expression_evaluator.cpp#L684

Currently, we evaluate non-correlated subqueries once per expression, but the ExpressionEvaluator is called once per chunk. When dividing the runtime by the number of chunks, both end up in the same ballpark.

**Comment by mrks** [comment]
I made some experiments and found an 8x improvement for query 18. The way I see it, we should first execute all uncorrelated queries once before we look at the single chunks. Kind of like this:

```
  using UncorrelatedSelectResults = std::unordered_map<std::shared_ptr<AbstractOperator>, std::shared_ptr<const Table>>;

  auto uncorrelated_select_results = std::make_shared<ExpressionEvaluator::UncorrelatedSelectResults>();
  auto evaluator = ExpressionEvaluator{};
  for (const auto& expression : expressions) {
    visit_expression(expression, [&](const auto& sub_expression) {
      const auto pqp_select_expression = std::dynamic_pointer_cast<PQPSelectExpression>(sub_expression);
      if (pqp_select_expression && pqp_select_expression->parameters.empty()) {
        auto result = evaluator.evaluate_uncorrelated_select_expression(*pqp_select_expression);
        uncorrelated_select_results->emplace(pqp_select_expression->pqp, std::move(result));
        return ExpressionVisitation::DoNotVisitArguments;
      }

      return ExpressionVisitation::VisitArguments;
    });
  }
```

Now I see two options:
a) Do this in projection.cpp and pass `uncorrelated_select_results` into the evaluators that are created per chunk. This means that `ExpressionEvaluator::_column_materializations` is lost and columns used in subqueries are potentially materialized one more time than necessary.
b) First, create an evaluator without a table and a chunk and store the results in a `shared_ptr<UncorrelatedSelectResults>`. Then, copy this evaluator per chunk so that it keeps both the results and the materialized columns.

I think I like b) better, but before I change my implementation from a), I would like your opinion on whether I am thinking in the right direction.

**Comment by mrzzzrm** [comment]
I read b) as the following, please confirm:

* `ExpressionEvaluator` takes no contstructor args anymore, but gets a `set_current_chunk()` function
* `set_current_chunk()` will update a pointer to the current chunk, and clear all materialized column data
* The results of expressions that do not access the current chunk and that we deem expensive (i.e., probably only uncorrelated subselects) will be cached.

If this is what you mean, go ahead. Should be minimally invasive and while not elegant, will still be okay.
