### ISSUE TITLE
LQP JoinNode returns wrong column definitions for outer joins

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#1051]
Output columns of joins can become `nullable`, if the join type is `outer`, `left` or `right`.
This behaviour is not implemented in the LQP `JoinNode`.
The current implementation of only the LQP `JoinNode` only copies the column definitions and does not change `nullable` behaviour of the column, if necessary.
I have not found a trivial solution for this problem as a column definition is represented by an `Expression` and I think that we currently cannot just create a column definition from scratch. I thought that this could be realised with a `MockNode` but it does not support `nullable`.

Bug found via running hyriseSystemTest with the jittable operators.
This bug was not found before as the normal hyrise operators take the column input definitions from the input table in comparison to the `JitAwareLQPTranslator`, which creates already specified type operators.

**Comment by FabianWiebe** [comment]
Example test case: 3ea29ee0eb3b015251faaaf5f19221f90f016b2d
Fails: [Jenkins](https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/fabian%2Fbug%2Fouter_join_output_column_types_not_nullable/1/pipeline)

**Comment by mrks** [comment]
In addition to fixing this, we should add debug checks that make sure that LQP and PQP types match.

**Comment by FabianWiebe** [comment]
@mrzzzrm Any idea how to integrate a solution into the `Expression` architecture.

**Comment by mrzzzrm** [comment]
I didn't think of this, bummer. The Expression system doesn't provide a mechanism to override the nullability of a column/expression. I would really need to think this through, how pressing is this for you?

**Comment by FabianWiebe** [comment]
@mrzzzrm It's not pressing as outer joins are not regularly used. I will just disable the one failing test case for now. I just wanted to check, if I had overseen an easy solution for this problem.

**Comment by mrzzzrm** [comment]
Remove this hack in tpch_test once fixed:

```c++
  std::shared_ptr<LQPTranslator> lqp_translator;
  if (use_jit) {
    // TPCH query 13 can currently not be run with Jit Operators because of wrong output column definitions for outer
    // Joins. See: Issue #1051 (https://github.com/hyrise/hyrise/issues/1051)
    if (tpch_idx == 13) {
      std::cerr << "Test of TPCH query 13 with JIT is currently disabled (Issue #1051)" << std::endl;
      return;
    }
    lqp_translator = std::make_shared<JitAwareLQPTranslator>();
  } else {
    lqp_translator = std::make_shared<LQPTranslator>();
 }

```
