### ISSUE TITLE
Upgrade to LLVM 8

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1077]
* remove LLVM lib files from coverage, see #1074
* remove experimental/filesystem (reopen #1151)
* update JIT (on a first glance, this doesn't look too bad this time)

**Comment by Bensk1** [comment]
We will do this once Ubuntu 19.04 is released.

> Ubuntu 19.04's release date is the 18th of April, 2019. The official stable version of Ubuntu 19.04 will be released on 18.04.2019.

**Comment by mrks** [comment]
With a bit of luck, we might have llvm 8 by then.

**Comment by mrks** [comment]
Changed this to LLVM 8
