### ISSUE TITLE
CMake creates new file with dtrace every time

### ISSUE THREAD

**Issue by timzimmermann** [hyrise/hyrise#1094]
On macOS, when I call `make`, it looks like every time the file `provider.hpp` is rebuilt.
This one is included by `probes.hpp`, which is included by `current_scheduler.hpp`, which is included in a bunch of files. All these files have to be compiled every time I call `make`, even if they don't change.
This is super annoying. Does anyone else have that problem? When do we absolutely need to rebuild `provider.hpp`? I assume only if we change `provider.d`?

**Comment by mrks** [comment]
Correct, only when provider.d changed. Maybe this already fixes it?

```
# Generate header file in order to define probes needed for dtrace
set(PROVIDER_FILE "${CMAKE_BINARY_DIR}/provider.hpp")
add_custom_command (
    OUTPUT ${PROVIDER_FILE}
    DEPENDS utils/tracing/provider.d
    COMMAND dtrace -h -s ${CMAKE_SOURCE_DIR}/src/lib/utils/tracing/provider.d -o ${PROVIDER_FILE}
)
```

**Comment by mrks** [comment]
Also pulling @toniSta into this discussion

**Comment by toniSta** [comment]
Generating a new `provider.hpp` is only necessary when `provider.d` has changed. Hence, @mrks's solution should fix this issue.

**Comment by mrks** [comment]
Can't reproduce on my machine though

**Comment by timzimmermann** [comment]
It does fix it for me. Opened a PR. Thanks, guys!
