### ISSUE TITLE
Revisit UnionPositions

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1099]
* Do we still need it?
* If yes, remove the prior use of "segment(s)", because segments now exclusively means "column parts" in a chunk.

**Comment by mrzzzrm** [comment]
A very rough test (debug build) shows that the extreme case of TPCH 19 (look at that OR statement!) can be performed a lot faster (3s @ sf=0.2) with UnionPositions and multiple scans for the conjunctive chains than the Expression Evaluator can (12s)

![tpc-h_19-pqp-0](https://user-images.githubusercontent.com/2679018/47793139-e0cb2580-dd1d-11e8-9d10-4b18927915d9.png)
![tpc-h_19-pqp-0](https://user-images.githubusercontent.com/2679018/47793157-eb85ba80-dd1d-11e8-82fb-709de45ef938.png)

Okay, so we probably want to keep the UnionPositions operator, at least until the ExpressionEvaluator can catch up, which it may once it doesn't pre-materialize and supports "only scan these positions" to speed up conjunctive chains.

**Comment by mrks** [comment]
Interesting. That plan, however, does not use the push-down of the common conditions, which was enabled by #1246.

This will probably have a couple of implications, for example, most rules don't work well with non-tree DAGs. Feel free to have more than a cursory look at this, but before we spend a lot of time on it, we should discuss the costs and benefits.

**Comment by mrzzzrm** [comment]
> most rules don't work well with non-tree DAGs 

Exactly my fear and the reason I want to get rid of non-trees, if possible.

> before we spend a lot of time on it, we should discuss the costs and benefits.

yep.

**Comment by mrzzzrm** [comment]
```
SELECT * FROM lineitem WHERE l_orderkey < 100 OR l_orderkey > 299900;
SELECT * FROM lineitem WHERE l_orderkey < 500 OR l_orderkey > 299500;
SELECT * FROM lineitem WHERE l_orderkey < 5000 OR l_orderkey > 295000;
SELECT * FROM lineitem WHERE l_orderkey < 50000 OR l_orderkey > 250000;
SELECT * FROM lineitem WHERE l_orderkey < 130000 OR l_orderkey > 160000;

SELECT * FROM lineitem WHERE l_shipinstruct = 'COLLECT COD' OR l_shipinstruct = 'TAKE BACK RETURN' OR l_shipmode = 'AIR';
SELECT * FROM lineitem WHERE l_comment LIKE '%packages%' OR l_comment LIKE '%beans%';

SELECT * FROM lineitem WHERE (l_orderkey = 512 AND l_partkey > 5000 AND l_shipinstruct LIKE '%COLLECT%') OR (l_orderkey = 299717 AND l_partkey > 5000 AND l_shipinstruct LIKE '%NONE%') OR (l_orderkey = 113090 AND l_partkey = 7809);
```

Improvement from ExpressionEvaluator --> UnionPositions
```
+-----------+---------------+------+---------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s  | runs | new iter/s    | runs | change | p-value (significant if <0.001) |
+-----------+---------------+------+---------------+------+--------+---------------------------------+
| queries.0 | 27.5816936493 | 10   | 944.040161133 | 10   | +3323% |     (run time too short) 0.0000 |
| queries.1 | 27.7487468719 | 10   | 878.095825195 | 10   | +3064% |     (run time too short) 0.0000 |
| queries.2 | 27.5967884064 | 10   | 743.103759766 | 10   | +2593% |     (run time too short) 0.0000 |
| queries.3 | 27.4111633301 | 10   | 211.592269897 | 10   | +672%  |     (run time too short) 0.0000 |
| queries.4 | 26.7670440674 | 10   | 88.7445144653 | 10   | +232%  |     (run time too short) 0.0000 |
| queries.5 | 12.9498062134 | 10   | 35.6537895203 | 10   | +175%  |     (run time too short) 0.0000 |
| queries.6 | 26.8007736206 | 10   | 47.372303009  | 10   | +77%   |     (run time too short) 0.0000 |
| queries.7 | 6.80615139008 | 10   | 47.9608078003 | 10   | +605%  |     (run time too short) 0.0000 |
| average   |               |      |               |      | +1343% |                                 |
+-----------+---------------+------+---------------+------+--------+---------------------------------+
```

**Comment by mrzzzrm** [comment]
Not conclusive, but it seems there is a good point to be made for dedicated TableScans + UnionPositions over the ExpressionEvaluator.

**Comment by mrks** [comment]
Ok, so it does seem to make a difference and we shouldn't get rid of the possibility of doing this.

Looking at TPC-H 19, we could also profit from merging `>=` and `<=` into `between`.

In the future, we might want to do this. Maybe we won't get around this if we look at TPC-DS. For now, however, I think that we have potential improvements that are less work, improve more than a single query, and lead to fewer breaking changes.

**Comment by mrzzzrm** [comment]
Does "In the future..." refer to including UnionPositions into queries again (which is not a breaking change?) or about re-writing into between?

**Comment by mrzzzrm** [comment]
I'm torn here... I'd really like for query plans to just be trees, since it makes writing rules easier. On the other hand I don't wanna waste performance.

I think the ExpressionEvaluator could be optimized to reach close-to-UnionPositions, or even better (since it doesn't have to sort PosLists before merging them) performance, so maybe we wanna pursue that road further?

**Comment by mrzzzrm** [comment]
>  However, I don't see the current support for generalized DAGs causing any issues right now, so I'm not sure if ripping that out is worth the time.

They have the big downside that rules need to explicitly check that a node doesn't have multiple outputs before operations can be moved past it. This makes rules counter-intuitive to read and hard to write. I.e., just writing rules with a tree LQP in mind would potentially break the plan, rules need to explicitly check that the part of the LQP that they work on is indeed a tree.

The JoinGraphBuilder painstakingly re-constructs complex AND/OR expressions by clustering nodes within a diamond shape. Such stuff wouldn't be necessary if there weren't any.

> What's your idea here? What I remember from running that through the profiler is that the materialization is by far the most expensive step in the evaluator.

Instead of materialization, the ExpressionEvaluator should use the iterators. For this to work, we need to avoid creating instantiations that are never used (e.g., `int + int = double`), otherwise the compile time for the ExpressionEvaluator goes through the roof. 
We could also optionally pass a `position_filter` to `evaluate_to_poslist` to speed up conjunction chains.

> We should do this.

I will do this

**Comment by mrks** [comment]
> Instead of materialization, the ExpressionEvaluator should use the iterators. For this to work, we need to avoid creating instantiations that are never used (e.g., int + int = double), otherwise the compile time for the ExpressionEvaluator goes through the roof.

Is the cost of the materialization writing to the vector or extracting the value from the encoding? In Q19 as shown above, you have three string columns in each path. Not being able to do the dictionary scan optimization might also contribute to the performance hit. Based on the failed post-evaluation predicates that I tried to build a while ago, I think I'd start with some hacky micro benchmarks here.

**Comment by mrzzzrm** [comment]
So far, I have mostly looked at unencoded datasets, so I assume its the (cache)cost of writing out a large chunk of data and then reading it again.

> Not being able to do the dictionary scan optimization might also contribute to the performance hit.
 
I think it will, that's why I want to allow the ExpressionEvaluator to use the specialized TableScan impls when doing evaluate_to_poslist.
