### ISSUE TITLE
Tests for the console

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1103]
These should at the very least include a number of console commands in a console script that shouldn't crash the console. 
Full output checks are probably hard to realize (e.g., checking generated image data), but checking that the text output is correct is probably doable?

What do you think?

**Comment by mrks** [comment]
Agreed. Maybe this is something that we want to test from the outside, e.g., using `expect`?

**Comment by mrzzzrm** [comment]
Okay, but we'll just test text output, right? Testing the visualizations is out of the question, amirite?

**Comment by mrks** [comment]
If anything, we can just make sure that *something* is visualized (i.e., a png is created)

**Comment by mrks** [comment]
d'oh

**Comment by mrzzzrm** [comment]
We need this, and we need it for the benchmarks, too: https://github.com/hyrise/hyrise/pull/1356#discussion_r244670617

**Comment by mrzzzrm** [comment]
Have you used `expect` before, @mrks?

**Comment by mrzzzrm** [comment]
Where did you find docs about the `default {` part? The man page only vaguely mentions it and I do not want to risk missing a crucial source of documentation.

**Comment by mrks** [comment]
<pre>
<strong>expect</strong> [[-opts] pat1 body1] ... [-opts] patn [bodyn]
    waits until one of the patterns matches the output of a spawned process, a specified time period has passed, or an end-of-file is seen. If the final body is empty, it may be omitted. 
Patterns from the most recent
    expect_before command are implicitly used before any other patterns. Patterns from the most recent expect_after command are implicitly used after any other patterns. 
If the arguments to the entire
    expect statement require more than one line, all the arguments may be "braced" into one so as to avoid terminating each line with a backslash. In this one case, the usual Tcl substitutions will occur despite the braces. 
If a pattern is the keyword
    eof, the corresponding body is executed upon end-of-file. If a pattern is the keyword timeout, the corresponding body is executed upon timeout. If no timeout keyword is used, an implicit null action is executed upon timeout. The default timeout period is 10 seconds but may be set, for example to 30, by the command "set timeout 30". An infinite timeout may be designated by the value -1. <strong>If a pattern is the keyword default, the corresponding body is executed upon either timeout or end-of-file. </strong>
</pre>

I haven't found a way to say "this and nothing else", only "wait until the program prints ...".

**Comment by mrzzzrm** [comment]
I tinkered with this a bit and found the tcl-expect a pain. Maybe this: https://pypi.org/project/pyexpect/?

**Comment by mrks** [comment]
I find their DSL to be very unintuitive. `expect(3).to.equal(4)`? You can't run around and violate a language's syntax just because you want to write nice sentences.

```
expect(foo).not_.to_equal(bar)
expect(foo).not_to.equal(bar)
expect(foo).to_not.equal(bar)
expect(foo).to_not_be.equal(bar)
```

WTF? "There should be one -- and preferably only one -- obvious way to do it."

Surprisingly, there don't seem to be many tools that perform that simple task. I wonder how difficult it would be to write a small wrapper using subprocess.

**Comment by mrzzzrm** [comment]
Sorry, i first linked to pyexpect, which is not the project that I actually meant. I meant pexpect, which looks like this:

```
import pexpect
child = pexpect.spawn('ftp ftp.openbsd.org')
child.expect('Name .*: ')
child.sendline('anonymous')
child.expect('Password:')
child.sendline('noah@example.com')
child.expect('ftp> ')
child.sendline('lcd /tmp')
child.expect('ftp> ')
child.sendline('cd pub/OpenBSD')
child.expect('ftp> ')
child.sendline('get README')
child.expect('ftp> ')
child.sendline('bye')
```

but I haven't looked into it further yet.

**Comment by mrks** [comment]
That looks a lot better. Does "expect" work the way we expect (hehe) it to, though. I.e., does it fail if it doesn't see the expected string?
