### ISSUE TITLE
In LQP, remove columns that are no longer needed

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1105]
The ColumnPruningRule "does NOT eliminate columns added as temporary columns later in the plan or columns that become useless after a certain point in the LQP."

Why not?

```
load src/test/tables/int4.tbl t1;
load src/test/tables/int.tbl t2;
visualize lqp SELECT * FROM t1 WHERE NOT EXISTS (SELECT a FROM t2 WHERE t1.a = t2.a) AND EXISTS (SELECT a FROM t2 WHERE t1.a = t2.a)
```

![lqp](https://user-images.githubusercontent.com/575106/45251255-482eaf80-b343-11e8-9322-b27e2c08c2fc.png)

In the projection in the middle, there is no need for the `EXISTS ...828` subselect. Having it still in there hinders optimization, because if we somehow get rid of the need for it in the lower parts of the LQP, this projection finds that it is no longer calculated and calculates it itself:

![lqpopt](https://user-images.githubusercontent.com/575106/45251277-8deb7800-b343-11e8-9197-c0b0c48a482e.png)

Getting rid of an LQPSelect that should not be there in the first place should not be the job of an unrelated optimizer rule.

**Comment by mrzzzrm** [comment]
I cannot quite follow your example. Anyway, I know what problem you are referring to: Temporary columns are never removed until the last Projection and needlessly dragged along by previous operators. Here is why the ColumnPruningRule doesn't remove them as early as possible:

* The bulk(!) of prunable columns are "stored-table" columns anyway. temporary columns are much rarer than the fifty-something columns your typical TPC-H query has in its base tables and never references.

* Determining whether an expression is not needed "above" a certain node (i.e. where is it safe to remove it?) is haaaard. I tried to implement it two or three times and failed to come up with a clean solution.
  * Why is this hard? I can't quite remember the subtle, but general examples are: 
     * What makes an expression "needed"? Each LQPNode type has different criteria for what it "needs" and what it can compute itself.
     * Determining what nodes are above a node which is within or below a diamond shape is ugly.

* Once we have evaluate_to_poslist, temporary expressions computed by Projections should largely be a thing of the past, as complex scan predicates to not need them anymore. Joins with complex predicates, e.g., `t1.a +t1.b = t2.a`, would still need them, but those are a lot rarer.

**Comment by mrks** [comment]
> What makes an expression "needed"? Each LQPNode type has different criteria for what it "needs" and what it can compute itself.

Isn't this what `AbstractLQPNode::node_expressions` is for?

> Determining what nodes are above a node which is within or below a diamond shape is ugly.

What if we start from the top and keep a list of these node_expressions. Whenever we see a new one, we add it to our list. When we encounter a split (i.e., two inputs), we copy the list and go both ways. When we see a merge (i.e., two outputs), we also merge the lists.

Since you said that you already tried to implement that, I am sure that I am missing something - what is it?

**Comment by mrzzzrm** [comment]
Nope, `node_expressions()` cannot do that. Every node type has its own rules for what expressions it needs available in columns and which it can compute itself, and the effort and error-proneness of hardcoding these in a rule is what kept me from doing it.

For example: Aggregates need all *arguments* of their AggregateExpressions to be available as columns, and all GroupBy expressions. Projections can compute everything but AggregateExpressions. Predicate and Joins need the arguments to their predicates available as columns. Sort again needs all the expressions.

So I decided to go for lower effort, 80% of the performance gain and only 20% of the error-proneness. ;)

**Comment by mrks** [comment]
But isn't that what the documentation of `node_expressions()` says?

```
   * @return    All expressions that this node USES (and doesn't just forward)
   *            (e.g., predicates, projections, ...).
   *            Intended, e.g., for the optimizer to have ONE function to call recursively on a plan and see ALL
   *            expressions used in that plan
   */
  virtual std::vector<std::shared_ptr<AbstractExpression>> node_expressions() const;

```

**Comment by mrzzzrm** [comment]
"use" is ambiguous in this doc, I think. 

It is basically a utility function that returns all expressions somehow involved in the operation of that node; in opposition to expressions/columns that are just forwarded. In the case of Predicate/Join it includes the predicate expressions that isn't even visible in `column_expressions()`

**Comment by mrzzzrm** [comment]
Afaik, now temporary columns are ONLY added for
* Aggregates on non-column expressions: `SUM(a+b)`
* GroupBy on non-column expressions: `GROUP BY a + c`
* Complex join predicates `ON a.a + a.b = b.c * 3`

From the experience of how cumbersome it is to detect when a column is no longer needed and how rare these temporary columns have become, I'll close this issue.
