### ISSUE TITLE
question about radix hash join and non-partitioned hash join

### ISSUE THREAD

**Issue by XuHuaiyu** [hyrise/hyrise#1117]
Hi, all.
Is there any tests for benchmarking CPU and memory performance you've done between radix-based hash join and non-partitioned hash join. （like TPC-H 50G, or other big enough dataset）

**Comment by Bouncner** [comment]
Hey XuHuaiyu,

there are performance tests and benchmarks which are rather easy to setup.
However, from a performance point of view, the radix-partitioning joins are not done yet.

There are upcoming changes which will improve performance, but it has not been a major focus for us so far. NUMA-awareness -- just as an example -- is only handled in one of the sort-merge joins but not in the hash-join implementation.

However, it should be straightforward to test TPC-H with scale factor 50 using the provided benchmarks.

Does that answer your question?

**Comment by Bouncner** [comment]
Hey XuHuaiyu,
I am going to close this issue. In case you have any further questions, just let us now!
