### ISSUE TITLE
Investigate random benchmark results

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1122]
For a change that does basically nothing, I got this on nemea (sf 0,1, gcc, `numactl -N 1 -m 1`):

```
 Benchmark | prev. iter/s | new iter/s | change
-----------+--------------+------------+---------------
 TPC-H 1   | 3.687        | 3.699      | +0%
 TPC-H 2   | 87.483       | 86.221     | -1%
 TPC-H 3   | 38.535       | 37.773     | -2%
 TPC-H 4   | 0.669        | 0.517      | -23%
 TPC-H 5   | 24.291       | 24.388     | +0%
 TPC-H 6   | 59.987       | 59.307     | -1%
 TPC-H 7   | 7.441        | 7.234      | -3%
 TPC-H 8   | 32.941       | 32.73      | -1%
 TPC-H 9   | 15.277       | 15.15      | -1%
 TPC-H 10  | 21.114       | 21.153     | +0%
 TPC-H 11  | 114.21       | 115.255    | +1%
 TPC-H 12  | 33.018       | 32.618     | -1%
 TPC-H 13  | 25.033       | 24.549     | -2%
 TPC-H 14  | 84.968       | 83.996     | -1%
 TPC-H 15  | 40.822       | 41.063     | +1%
 TPC-H 16  | 16.641       | 16.469     | -1%
 TPC-H 17  | 4.404        | 4.416      | +0%
 TPC-H 18  | 3.09         | 3.087      | -0%
 TPC-H 19  | 2.795        | 2.768      | -1%
 TPC-H 20  | 0.032        | 0.032      | -1%
 TPC-H 21  | 0.403        | 0.307      | -24%
 TPC-H 22  | 1.152        | 1.17       | +2%
 average   |              |            | -3%
```

No idea why queries 4 and 21 act weird here. We had a similar effect in #1095.

This makes it really difficult to work on performance optimizations. :/

**Comment by mrzzzrm** [comment]
Do you have anything to kick this off? For example query plan visualizations for the queries in question that show which operator(s) differ in performance?

**Comment by mrks** [comment]
Here are the two benchmark outputs that produced the result above.

[old.txt](https://github.com/hyrise/hyrise/files/2383029/old.txt) - commit 25955e34b2982e3e72f1b90a41c5daaa99d6ebe6
[new.txt](https://github.com/hyrise/hyrise/files/2383028/new.txt) - commit 8f10e62394652739cb5f6be42b43ca32c40042ad

For TPC-H 4, every query became slower, it's not that we have a particularly slow one in there:

<img width="267" alt="screen shot 2018-09-14 at 12 59 06" src="https://user-images.githubusercontent.com/575106/45546602-18d5e200-b81e-11e8-84e2-ee7112756628.png">

 I don't have query plans available yet.

**Comment by mrks** [comment]
One thing that we could also look at is if it makes a difference if we disable the query cache

**Comment by mrks** [comment]
Here you go:

![25955e34b2982e3e72f1b90a41c5daaa99d6ebe6-pqp-4 svg](https://user-images.githubusercontent.com/575106/45547087-d90ffa00-b81f-11e8-8314-81dd977d0004.png)
![8f10e62394652739cb5f6be42b43ca32c40042ad-pqp-4 svg](https://user-images.githubusercontent.com/575106/45547086-d90ffa00-b81f-11e8-84b9-6c1cf62d4ab6.png)

As you can see, the projection becomes randomly more expensive on the same PQP. Unfortunately, we don't have any more details about that (#1019).

**Comment by mrks** [comment]
I am seeing the same results when pinning to one NUMA node.

Also, I am quite sure that it is related to correlated subqueries. All queries that act weird have a correlated subquery.

**Comment by mrks** [comment]
```
analyzing CPU 118:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 118
  CPUs which need to have their frequency coordinated by software: 118
  maximum transition latency: 4294.55 ms.
  hardware limits: 1000 MHz - 3.80 GHz
  available cpufreq governors: performance, powersave
  current policy: frequency should be within 1000 MHz and 3.80 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
```

Maybe this

**Comment by Bouncner** [comment]
Can we set this governor as part of the benchmark script?

**Comment by mrks** [comment]
Even with the max power governor and binding it to a single CPU (instead of a single node), I still get those random outliers.

**Comment by mrks** [comment]
Setting the governor didn't change anything. By now, I am 90% sure that this has something to do with correlated subqueries (or generally executing a lot of queries).

Also, the performance regression is consistent for a given code base. We can rerun the benchmark and even recompile as much as we want and it will remain the same.

The only thing I can think of right now is that adding code at an unrelated position causes the compiler to, e.g., push hot code down and split it across a page.

**Comment by mrks** [comment]
Yepp, this is definitely unrelated to pretty much everything. This change here reduces the TPC-H 2 performance by roughly 15% but doesn't really do anything in this case:

```
Markus.Dreseler@nemea:~/hyrise$ git diff origin/master origin/mrks/tpch-qgen-rebase -- src/lib/sql
diff --git a/src/lib/sql/sql_translator.cpp b/src/lib/sql/sql_translator.cpp
index 122ccd955..fccddfcde 100644
--- a/src/lib/sql/sql_translator.cpp
+++ b/src/lib/sql/sql_translator.cpp
@@ -1047,8 +1047,9 @@ std::shared_ptr<AbstractLQPNode> SQLTranslator::_translate_prepare(const hsql::P
 }

 std::shared_ptr<AbstractLQPNode> SQLTranslator::_translate_execute(const hsql::ExecuteStatement& execute_statement) {
-  auto parameters = std::vector<std::shared_ptr<AbstractExpression>>{execute_statement.parameters->size()};
-  for (auto parameter_idx = size_t{0}; parameter_idx < execute_statement.parameters->size(); ++parameter_idx) {
+  const auto num_parameters = execute_statement.parameters ? execute_statement.parameters->size() : 0;
+  auto parameters = std::vector<std::shared_ptr<AbstractExpression>>{num_parameters};
+  for (auto parameter_idx = size_t{0}; parameter_idx < num_parameters; ++parameter_idx) {
     parameters[parameter_idx] = translate_hsql_expr(*(*execute_statement.parameters)[parameter_idx], _use_mvcc);
   }
```

I wrote a small script that switches back and forth:

```
while true
do
	modus=RANDOM
	if (( modus % 2 ))
	then
		echo -n "               master - "
		git checkout origin/master -- ../src/lib/sql
	else
		echo -n "mrks/tpch-qgen-rebase - "
		git checkout origin/mrks/tpch-qgen-rebase -- ../src/lib/sql
	fi
	make -j hyriseBenchmarkTPCH >/dev/null 2>/dev/null
	./hyriseBenchmarkTPCH -v -q 2 2>/dev/null | grep Executed
done
```

Results:
```
mrks/tpch-qgen-rebase -   -> Executed 6531 times in 60.0008 seconds (108.849 iter/s)
               master -   -> Executed 8112 times in 60.0052 seconds (135.188 iter/s)
               master -   -> Executed 8072 times in 60.0073 seconds (134.517 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6607 times in 60.0004 seconds (110.116 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6813 times in 60.0082 seconds (113.535 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6643 times in 60.0077 seconds (110.702 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6652 times in 60.0035 seconds (110.86 iter/s)
               master -   -> Executed 7920 times in 60.007 seconds (131.985 iter/s)
               master -   -> Executed 8165 times in 60.0067 seconds (136.068 iter/s)
               master -   -> Executed 8008 times in 60.0002 seconds (133.466 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6775 times in 60.0018 seconds (112.913 iter/s)
mrks/tpch-qgen-rebase -   -> Executed 6601 times in 60.0073 seconds (110.003 iter/s)
```

This will be fun to investigate...

dis_gon_b_gud.gif

**Comment by mrks** [comment]
I did some benchmarks with `perf` and found that the performance regressions are in unchanged compilation units. In my understanding, this means that this is not an issue of inline limits or alike, but simply the linker moving around hot functions. If you add unrelated code above, chances are that hot code is now split across a page boundary or a jump target is in a different cache line.

**Comment by mrks** [comment]
Yepp, it's really the alignment. Here is a perf report for two builds, where the scan has a better alignment on the left side. #1396 will fix this.
 
<img width="1920" alt="alignment_variation" src="https://user-images.githubusercontent.com/575106/51073799-8e3fab00-1676-11e9-9654-0b4b598b3119.png">

I rebased the change into the chain of commits and re-ran a couple of commits from the past to see if those variations can be reduced:

<img width="1033" alt="screenshot 2019-01-12 at 14 31 18" src="https://user-images.githubusercontent.com/575106/51073809-bdeeb300-1676-11e9-855a-bbd4cdf57cdc.png">
