### ISSUE TITLE
JIT (NOT) LIKE ignores case

### ISSUE THREAD

**Issue by timzimmermann** [hyrise/hyrise#1126]
Is there any reason why we match case-insensitively in JIT for (NOT) LIKE predicates?

From [jit_operations.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/operators/jit_operator/jit_operations.hpp#L92:L102):

```c++
const auto jit_like = [](const std::string a, const std::string b) -> bool {
  const auto regex_string = LikeMatcher::sql_like_to_regex(b);
  const auto regex = std::regex{regex_string, std::regex_constants::icase};
  return std::regex_match(a, regex);
};

const auto jit_not_like = [](const std::string a, const std::string b) -> bool {
  const auto regex_string = LikeMatcher::sql_like_to_regex(b);
  const auto regex = std::regex{regex_string, std::regex_constants::icase};
  return !std::regex_match(a, regex);
};
```

**Comment by mrks** [comment]
I am not sure if the standard has any requirements for this. Comparing case-insensitive is the default collation for MySQL.

In any case, this should be consistent to the non-JIT code. Because we have some special cases there, it is probably easier to change this to be case-sensitive.

**Comment by timzimmermann** [comment]
> I am not sure if the standard has any requirements for this. Comparing case-insensitive is the default collation for MySQL.

Interesting, for postgres it's case-sensitive. They actually have `ILIKE`, which does case-insensitive matching.

> In any case, this should be consistent to the non-JIT code. Because we have some special cases there, it is probably easier to change this to be case-sensitive.

PR is coming up.
