### ISSUE TITLE
Replace error in TableStatistics

### ISSUE THREAD

**Issue by timzimmermann** [hyrise/hyrise#1130]
From the diff of #1076:

```diff
} else if (is_column_id(value)) {
-  const auto value_column_id = boost::get<ColumnID>(value);
-
+  const auto column_id = boost::get<ColumnID>(value);
   const auto estimation = left_operand_column_statistics->estimate_predicate_with_column(
-        predicate_condition, *_column_statistics[value_column_id]);
+        predicate_condition, *_column_statistics[column_id]);

   predicated_column_statistics[column_id] = estimation.left_column_statistics;
-  predicated_column_statistics[value_column_id] = estimation.right_column_statistics;
+  predicated_column_statistics[column_id] = estimation.right_column_statistics;
    predicated_row_count *= estimation.selectivity;
} else if (is_variant(value)) {
```

This is a problem because `column_id` now shadows a variable, and we loose the left column statistics.
While this is easy to revert, I have two concerns:
1. Why is this not tested?
2. Where else have these search&replace errors happened with the column->segment PR?

**Comment by Bensk1** [comment]
> Where else have these search&replace errors happened with the column->segment PR?

Good point!

**Comment by mrks** [comment]
Mmmh, I can't remember doing exact this replacement automatically.

Let me also add question 3: Why doesn't the compiler complain about this shadowing?

**Comment by timzimmermann** [comment]
> Mmmh, I can't remember doing exact this replacement automatically.

To be clear, I renamed `value_column_id` to `cxlumn_id` in my review, which was then replaced to `column_id`. So it was my fault because I did not check whether there was an existing variable named `cxlumn_id` or `column_id`.
The question remains, though, if that happened in another place.
I have thought about this quite a bit and I can't think of a great way to search for it.

> Let me also add question 3: Why doesn't the compiler complain about this shadowing?

I like that question.

**Comment by mrks** [comment]
https://kristerw.blogspot.com/2017/09/useful-gcc-warning-options-not-enabled.html

Are you kidding me?

**Comment by timzimmermann** [comment]
So interesting, great find.

**Comment by timzimmermann** [comment]
If I understand the [clang docs](http://clang.llvm.org/docs/DiagnosticsReference.html#wshadow) correctly, there are a bunch of shadow options, none of which are enabled with `-Wall` or `-Wextra`.

**Comment by mrzzzrm** [comment]
AFAICT shadowing is now an error.
