### ISSUE TITLE
SQLQueryPlan is an imprecise name

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1141]
The `SQLQueryPlan` is not a really descriptive name. This query plan does not have much to do with SQL. Even though it is not perfect, `PhysicalQueryPlan` is a bit closer to the actual entity. We might have had a naming discussion about this before, but I don't remember the result.

**Comment by mrzzzrm** [comment]
Very much what I'd say. I will remove the entire class as part of #991
