### ISSUE TITLE
Return types of functions connected to custom types

### ISSUE THREAD

**Issue by timzimmermann** [hyrise/hyrise#1142]
We use types such as `ColumnID` and `ChunkOffset` often, but kind of lack a way to have consistent return types for functions related to them.

Here are two examples.

From [table.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/table.hpp):

```c++
size_t column_count() const;

// return the maximum chunk size (cannot exceed ChunkOffset (uint32_t))
uint32_t max_chunk_size() const;
```

From [chunk.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/chunk.hpp):

```c++
// returns the number of columns, which is equal to the number of segments (cannot exceed ColumnID (uint16_t))
uint16_t column_count() const;

// returns the number of rows (cannot exceed ChunkOffset (uint32_t))
uint32_t size() const;
```
From [chunk.cpp](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/chunk.cpp):

```c++
uint32_t Chunk::size() const {
  if (_segments.empty()) return 0;
  auto first_segment = get_segment(ColumnID{0});
  return first_segment->size();
}
```

From [base_segment.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/base_segment.hpp):

```c++
// returns the number of values
virtual size_t size() const = 0;
```

Column count returns either a `size_t` or `uint16_t`, depending on whether you call it on a chunk or table.
The `ChunkOffset`-related `size()` methods do return the same type across the different files, except for `BaseSegment`. That's pretty interesting, since there should be type narrowing in `Chunk::size()` (`size_t` to `uint32_t`) and I would have expected a compiler warning, or what am I missing?

In any case, I came across this same question of what return type to use for histograms.
The maximum number of elements in a bin is `ChunkOffset`, since histograms are per segment.
However, using that as a type in histogram files is confusing, so I decided to define an alias type (`using HistogramCountType = ChunkOffset`.

Similarly, we might want to think about defining aliases such as `using ChunkSize = ChunkOffset`, and using that as the return type.
I know that this adds more types and there might be a little confusion about the difference between `ChunkOffset` and `ChunkSize`, but the advantage is that changing types will not lead to overflow errors if we use those aliases rigidly.

Do you guys have any opinions on that?

**Comment by timzimmermann** [comment]
Yep, duplicate.

I do vaguely remember those discussions now, but it keeps annoying me.
I'm hesitant to invest lots of time into it before we agree on some naming conventions because I feel like there is going to be some debate about that.

**Comment by timzimmermann** [comment]
That works for me for the things I can think about right now, but we will probably have to see case by case.
Anyone else has an opinion on that?

**Comment by mrks** [comment]
> I think this came up in one of the last fortnightlies. If I remember correctly the consensus was "Yes, this makes sense, but no one feels strongly enough about it to do something."

It's been another year and a half and the situation does not seem to have changed.
