### ISSUE TITLE
Plugin Warning

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1147]
```
You have called ADD_LIBRARY for library TestPlugin without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library TestNonInstantiablePlugin without any source files. This typically indicates a problem with your CMakeLists.txt file
```

**Comment by Bensk1** [comment]
What is your CMake version?

Since CMake 3.11:

> add_library() and add_executable() commands can now be called without any sources and will not complain as long as sources are added later via the target_sources() command.

**Comment by mrks** [comment]
We are seeing this on nemea and CI as well. Apparently, the cmake version in apt is not up-to-date. Unless this is a major thing, we should get this fixed so that we don't have any warnings in our officially supported builds.
