### ISSUE TITLE
Rewrite Statistics Component

### ISSUE THREAD

**Issue by timzimmermann** [hyrise/hyrise#1153]
To be used for discussions around the statistics component.

**Comment by mrzzzrm** [comment]
### Follow ups
* [ ] Re-integrate EqualWidthHistogram and EqualHeightHistogram
* [ ] Histogram generation is horrendously slow.
* [ ] Histogram bins shouldn't store their height/distinct_count, but their height/distinct count PLUS the height/distinct count of all previous bins. This makes, e.g. LessThan estimation possible in O(1) instead O(n)
