### ISSUE TITLE
Pagination dies with SIGBUS

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1158]
This kills the console with a SIGBUS if pagination is enabled:
```
generate_tpch 0.01
SELECT p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt FROM partsupp, "part" WHERE p_partkey = ps_partkey AND p_brand <> 'Brand#45' AND p_type not like 'MEDIUM POLISHED%' AND p_size in (49, 14, 23, 45, 19, 3, 36, 9) AND ps_suppkey not in (SELECT s_suppkey FROM supplier WHERE s_comment like '%Customer%Complaints%') GROUP BY p_brand, p_type, p_size ORDER BY supplier_cnt DESC, p_brand, p_type, p_size;
```

**Comment by timzimmermann** [comment]
I had a similar issue yesterday and wanted to file it today after investigating a bit further.
I suspect that whenever pagination is enabled, any query result that needs pagination kills the console.
For example, if I do

```sql
generate_tpch 0.01
select top 50 * from lineitem;
```

in a full-screen terminal, stuff works fine.
If I run the same thing on a half-sized window, it crashes.

**Comment by mrks** [comment]
2b8ac840a3939d6588b9294f7aa69f88d0b88f81 broke it.

**Comment by mrks** [comment]
... and this "fixes" it, even if that method is never called:

```
 int Console::_generate_tpch(const std::string& args) {
+  Fail("WAT?");
   auto input = args;
```

Also, on nemea, I am only getting that with clang. I'll take "Linker Bugs" for 200, Alex.

**Comment by mrks** [comment]
Ok, here's the culprit in `third-party/tpch-dbgen/dss.h`:

```
int refresh;
```

And here is the culprit in ncurses:

```
int refresh(void);
```

Well... yeah... that does not work. Even if C does not have namespaces, those names could at least have been prefixed. This goes again to show why global names suck. :/
