### ISSUE TITLE
Deduplicate code in {SingleColumn|Between)TableScanImpl

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1164]
The code for these methods looks very similar and can likely be improved:

```
void SingleColumnTableScanImpl::handle_segment(const BaseValueSegment& base_segment,
                                               std::shared_ptr<SegmentVisitorContext> base_context);

void SingleColumnTableScanImpl::handle_segment(const BaseEncodedSegment& base_segment,
                                               std::shared_ptr<SegmentVisitorContext> base_context);
```

Also, include #1145 once it's done

**Comment by mrzzzrm** [comment]
As briefly discussed in https://github.com/hyrise/hyrise/pull/1210/files#r226855574 getting rid of the visitor-pattern remnants, specifically the Context that gets handed around, would probably increase readability of the TableScanImpls.
