### ISSUE TITLE
Inconsistent naming in vector compression

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1168]
<pre>
class FixedSizeByteAlignedVector {
  auto on_create_<strong>decoder</strong>() const {
    return std::make_unique&lt;FixedSizeByteAligned<strong>Decompressor</strong>&lt;UnsignedIntType>>(_data);
  }
}
</pre>

Same for encoder/compressor.

Since the whole thing is called "vector compression" and we already use "encoding" for dictionary, run-length, etc., I would suggest to consistently use compressor/decompressor here.

**Comment by Bouncner** [comment]
Ack.
