### ISSUE TITLE
Split up TableScan into multiple Operators based on Impl

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1169]
After #1154 and EvaluateToPosList, we'll have 6 different TableScan impls (Between, IsNull, ColumnToValue, ColumnToColumn, FallbackViaExpressionEvaluator, Like). So just from seeing a "TableScan" in a PQP, you have no idea what code will actually run the scan. Especially, you won't know whether a (faster) specialized scan is used or whether the (slower) fallback to the `ExpressionEvaluator::evaluate_expression_to_pos_list()` is used.

Should we split the TableScan into multiple different scan operators and let the LQPTranslator decide which one is used, based on the predicate expression? Or should we just differentiate between "SpecializedTableScan" (which uses one of our current `BaseTableScanImpl`s) and "FallbackTableScan" (which uses the expression evaluator)?

**Comment by mrks** [comment]
I see a value in saying "This is the table scan. It scans tables.". In Hyrise1, we had different scan types and no one had an idea what they were doing.

With the *Impls, I believe that the code paths are separated enough. If this is only about understanding the PQP, why don't we let the *Impl add its information to the description?

**Comment by mrzzzrm** [comment]
That seems fine, just wanted to get some input about this. I like the "implementation adds information to description()" bit.
