### ISSUE TITLE
Fix tpch-dbgen linkage

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1173]
#1158 has been fixed by removing `int refresh(void);` from tpch-dbgen. That does it for now, but the next time someone has the idea of calling a function `verbose`, everything will go up in flames again.

Can't blame tpch-dbgen, because it was not built to be a library. Not sure what to do here, but we can't have tpch-dbgen pollute the entire global space.

The actual problem lies with ncurses, but that is probably even more complicated to fix. If I understand this correctly, each program with a global variable "refresh" breaks ncurses. This sounds like really bad behavior for a library...

**Comment by mrzzzrm** [comment]
Maybe we can c++-ify tpch-dbgen and put everything in there into a namespace?

**Comment by mrks** [comment]
That would fix it, yes.

**Comment by mrks** [comment]
It might be faster to prefix all variables and macros. Finally, a job for an IDE ;)

**Comment by mrzzzrm** [comment]
Prefix every global variable/function in dbgen with `tpch_dbgen_*` - or is `dbgen_*` sufficient?

**Comment by mrks** [comment]
Yes. The former, as I believe it's dbgen for TPC-DS, too.

**Comment by mrzzzrm** [comment]
In order to polute the tpch_dbgen files as little as possible, maybe just add a header that defines new names for all symbols in the lib?

```c++
#define mk_order tpch_dbgen_mk_order
```

We need to do the same for tpcds_dbgen, so I'd rather pick a good solution. And making verifying we didn't change the library code easy is something we should strife for imo - renaming a lot of symbols would pollute the diff.

**Comment by mrks** [comment]
Wouldn't that pollute each Hyrise file that includes a TPC-H file?

**Comment by mrzzzrm** [comment]
ah, right. sad. I would have liked that solution... Alright, renaming everything it is...

**Comment by mrks** [comment]
Given that TPC-DS is in for a while and we do not anticipate any new benchmarks, let's close this for now. We have bigger fish to fry.
