### ISSUE TITLE
RemoveUselessOperationsRule

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1186]
Name to be determined, obviously.

There is a number of operations that we can safely remove from LQPs without having to work hard to detect them. Imo it is best if there is one rule to handle them all, otherwise we'll have a lot of very small rules, but I am happy to split this into multiple rules as well.

* [ ] Secondary AliasNodes
Here, e.g., in TPC-H 9
![image](https://user-images.githubusercontent.com/2679018/46893493-5b1c2e80-ce71-11e8-9175-bd20b1712520.png)

* [ ] Reordering Projections in suqueries can always go

* [ ] Reordering Projections can go if there is another Projection/Aggregate/AliasNode above them

* [ ] Sorts 
SortNodes in EXISTS(...)/IN(...) subqueries can go
People may be silly enough to write `ORDER by ..., x, x`, hyrise shouldn't look silly, too, by actually sorting twice.

* [ ] IS NOT NULL and another scan: #1494

**Comment by mrks** [comment]
While working on the TPC-H paper, I did not see any of these useless operators become a problem. They might exist, but we still have bigger fish to fry than removing a 9 μs operation.

I'm tempted to move this to the Trello list of long-term ideas. In cases where these useless operations actually have a performance impact, I'd expect people to come up with the idea of removing them without this issue being open.

Any objections?
