### ISSUE TITLE
Extend CREATE/DROP Table support

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1189]
#1178 introduces basic CREATE/DROP table support. A number of features is missing.

* [x] SQLParser is missing support for Hyrise's other types, apart from INT, DOUBLE and TEXT (in #1209)
* [x] SQLParser is missing support for NULL/NOT NULL qualifiers (in #1209)
* [x] Create Table from SELECT
* [x] DROP TABLE IF EXISTS
* [x] CREATE TABLE IF NOT EXISTS
* [x] Check for table existence in console before running plan containing CreateTable 
* [ ] UNIQUE / PRIMARY Constraints (same row and multi-column)

**Comment by mrzzzrm** [comment]
@d-justen 
Regarding `Create Table from SELECT` (for completeness, the two syntax are shown [here](https://www.w3schools.com/sql/sql_create_table.asp)):
Let's call the syntax that Hyrise supports "CreateTableFromLayout" (`CREATE TABLE t (a INT, b FLOAT)`) and the new one "CreateTableFromQuery" (`CREATE TABLE t AS SELECT * FROM another_table WHERE a > 5`). I think it should be possible to support both syntaxes via the same `CreateTableNode` and `CreateTable`-operator. 
For CreateTableFromLayout the `CreateTable` operator would receive a Table with no rows and just the requested column layout from its input operator. For CreateTableFromQuery the input would be the query producing the Table. `CreateTable[Node]::column_definitions` would then be obsolete and could be removed. 

For the empty input table of CreateTableFromLayout we'd need a new concept in the LQP, one that we'd need for #1546 as well: Static/ConstantTableNodes - just a node wrapping a static table. For #1546 this would be a table containing the IN list, for CreateTableFromLayout this would be a table with no rows and just the column layout.

@mrks what do you think?

**Comment by mrks** [comment]
To me, it sounds like you are forcing two things that don't have too much in common into one entity.

Trying to predict what the CreateTableNode will have to do in the future, I see indexes, default values and constraints. None of these apply to the `CREATE TABLE ... AS` path.

I'd suggest a StoreTable operator, similar to the GetTable operator, which deals with this new path. Keeping those separate should also make it easier to support `SELECT INTO`. After SQL translations, these should end up going down the same road.

Finally, and a bit unrelated to this, please consider SQL queries similar to TPC-H Q 15, where you don't have all information a priori, e.g., `CREATE VIEW v AS (SELECT ...); CREATE TABLE t AS SELECT * FROM v WHERE ...`.

**Comment by mrks** [comment]
Mmmh, ok, I checked the standard, and `CREATE TABLE ... AS` can actually have most of these properties as well. In fact, that only makes my point stronger. If the "empty" `CREATE TABLE` takes those properties from a dummy input table, how would we pass it into the operator for the version with input?

**Comment by mrzzzrm** [comment]
StoreTable sounds like a great idea and you're right about default values etc, of course. Didn't consider those, maybe I should actually learn SQL at some point :( But StoreTable could also support the "old" CreateTableFromLayout syntax via my proposed empty input table, right?

StoreTable could simply take all additional properties as an additional attribute. They wouldn't need to be "derived" from the input table.

And... SELECT INTO would not use StoreTable, right? SELECT INTO could be done with pure INSERT, right?

> If the "empty" CREATE TABLE takes those properties from a dummy input table, how would we pass it into the operator for the version with input?

Please rephrase, I do not follow. My (misinformed) proposal did not include additional column properties and indexes.

**Comment by mrks** [comment]
> StoreTable could simply take all additional properties as additional attributes. They wouldn't need to be "derived" from the input table.

Default values would be part of the column definitions. This sound like we are building two separate parts of that definition in different places just to put them back together again later.

> And... SELECT INTO would not use StoreTable, right? SELECT INTO could be done with pure INSERT, right?

My bad. The tables has to exist, yes. Buuuut, good that you mention it. Won't the discussed approach take the input table, which contains references, and try to store them in the StorageManager? What happens to the MVCC data? What happens if the referenced table gets deleted? Maybe we should create the table first and then insert into it? Does the SQLTranslator have all needed information to create a table without executing the query first?

> Please rephrase, I do not follow. My (misinformed) proposal did not include additional column properties and indexes.

Never mind, I did not understand that you wanted to add those extra properties as flags to the CreateTable op.

**Comment by mrzzzrm** [comment]
> Default values would be part of the column definitions. This sound like we are building two separate parts of that definition in different places just to put them back together again later.

I think it would come out cleaner than having two "CreateTable" operators, both supporting the same set of additional properties.

>My bad[...]

I think about it this way:

StoreTable would need to materialize
StoreTable would assume its input to be validated
StoreTable would create MVCC info for the Table/Column it creates
The SQLTranslator does not need to create a Table? StoreTable has the attributes `table_name` and `additional_table_properties` (indices, maybe default values etc). It creates the stored table when it executes.

**Comment by mrks** [comment]
That's another operator that writes data. Given how much work it is to get MVCC right, I'd rather keep the places where we modify tables to an absolute minimum.

Could you please describe the advantage of that approach over create + insert?

> The SQLTranslator does not need to create a Table?

That was easy to misunderstand. I don't want it to create the table, I wanted to see if it had all the information at the time it was running to create a CreateTableNode.

**Comment by mrzzzrm** [comment]
> Could you please describe the advantage of that approach over create + insert?

I didn't mean to propose to not have a single operator inserting the data... Yes, sure, if Store/CreateTable needs to *insert* data it can use the *Insert* operator, just as Update does...

>  I don't want it to create the table, I wanted to see if it had all the information at the time it was running to create a CreateTableNode. 

After #1599 the SQLTranslator will not have nullability info anymore. That will not be a problem, as far as I can tell, if we choose "my" approach (i.e. Create/StoreTable creates a new Table from the Table that it get's from its input operator. Plus some additional info (indexes, primary key stuff, maybe nullability, maybe default values))

Just to be clear: I don't feel like I am proposing anything evil/hacky/over-generalised here. All I am proposing is: Let's have a single operator/lqp-node handling CREATE TABLE statements instead of two distinct pairs (i.e. one for each CREATE TABLE syntax).

**Comment by mrzzzrm** [comment]
Advantages of a single node/operator pair: I feel it's going to be less code duplication, that's all. Also a single code-path for "Create Table via Query" is likely easier to test/debug than two. Overhead of creating the empty table for the CreateTableFromLayout case should be really, really minimal.

**Comment by mrks** [comment]
Now that you clarified how inserts are done, my biggest concern is gone. The part that I still don't like is how we arbitrarily split up the `CREATE TABLE` statement in things that we can handle as part of the input table and things that are given to the operator, just for those to end up in the same column definition.

**Comment by mrzzzrm** [comment]
That is a minor point, imo. And I don't find it all that unclean: The input operator delivers the raw data, the Create/StoreTable supplies all additional info required for this table to become a proper stored table (name, default values, indexes etc).

**Comment by mrks** [comment]
Ok, so for the `CREATE TABLE` statement without an input table, all table would come from the outside and none from the dummy input table?

What about NULL? Is the newly created table supposed to have the same nullability information as the input table? Where would that come from?

**Comment by mrzzzrm** [comment]
> Ok, so for the CREATE TABLE statement without an input table, *all table would come from the outside and none from the dummy input table?*

Please rephrase, I do not follow.

> What about NULL? Is the newly created table supposed to have the same nullability information as the input table? Where would that come from?

The newly created table will have the same nullability info as the input table. That would come from... well, the input table, right? I do not see a problem here?

**Comment by mrks** [comment]
>  In case you meant "all additional table attributes would come form the outside": Column Data Type, name and nullability come from the dummy input table (i.e. everything in TableColumnDefinition). Everything else (table name, default values etc.) comes from the outside.

That's what I was thinking about, yes. I guess that would work. I don't like it too much, but the alternatives don't seem better.

> Or are you implying there is a syntax for CreateTableFromQuery where columns could be assigned different nullability than the query result table would have?

I can't find it (this whole `CREATE TABLE [AS] SELECT` thing) in sql92, but MySQL seems to support it: https://dev.mysql.com/doc/refman/8.0/en/create-table-select.html Not saying that we have to, but we should be aware of it and assert that the types match.

**Comment by d-justen** [comment]
Does that mean that CreateTable now becomes a ReadWriteOperator? Because now it eventually needs a transaction context and write MvccData via Insert.

**Comment by mrzzzrm** [comment]
Yes, I'd think so, since it will have to initialize the mvcc data to a specific transaction ID. (Still, we don't really consider concurrency between CREATE TABLE and SELECT from the same table.)

**Comment by d-justen** [comment]
Do you mean something like `create table t as select * from t` (probably syntactically incorrect)? In this case I would expect the statement to fail, since there is no table t to select from, right?

**Comment by mrzzzrm** [comment]
No, what I mean is that if you have two transactions T0 and T1 and both have a `CREATE TABLE t AS ... IF NOT EXISTS` statement, the outcome is undefined, either transaction could succeed in publishing "their" table `t`. And this is fine in the context of Hyrise! I just wanted to mention it.

Now, to reiterate, for a statement like `CREATE TABLE t1 AS SELECT * FROM t0 WHERE a > 5`, we have to decide which initial **begin CommitIDs** the rows in `t1` should have. 
1st option: Initialize to zero. This is simple and in line with the principle that `CREATE/DROP/...` statements are not managed by mvcc
2nd option: initialize them to the transaction ID of the statement. This is slightly more correct - but still, see opening paragraph - not entirely correct.

@mrks?

**Comment by mrks** [comment]
Currently, concurrent schema modifications are undefined behavior. Being a research database, I don't see any need to change that.

**Comment by mrzzzrm** [comment]
Alright, let's keep it simple then and initialize the BeginCommitIDs to zero when a table is created via `CREATE TABLE t AS ... `.

**Comment by d-justen** [comment]
Well, I wrote a test for the SQLTranslator and found out that SQLParser doesn't support this `CREATE TABLE t AS SELECT * FROM s` syntax. How are we going to deal with this? I just had a look into the parser and must say that I'm completely clueless.

**Comment by mrzzzrm** [comment]
Adjusting the parser to support this will be a piece of cake! (TM) Well, maybe not, but it's really not as hard as it might seem. Take a look at bison_parser.y, that's the central file of the parser. Some of the other files are generated and therefore look terrifying. @julianmenzler can probably help you as well, I'm not 100% sure when I am going to be in again. Maybe Friday before lunch, maybe next week Tuesday/Wednesday.
