### ISSUE TITLE
HistogramUtilsExtendedTest needed to that extent?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1201]
After looking at the runtime of hyriseSystemTest in the CI, I wonder if `HistogramUtilsExtendedTest` needed is to that extent. Does it make a difference if we only use two characters and/or reduce the set of supported characters?

**Comment by timzimmermann** [comment]
Both is possible, feel free to limit it in a way you feel comfortable with.
Two characters is the absolute minimum, though.

**Comment by mrks** [comment]
Looking again at it , I don't think we get enough value out of the tests even in the system tests. This is not some type of stress test, where we can come up with any reason why this should fail after a couple of thousand passes.

My suggestion would be to limit the supported characters to `acef` (leave a gap so that we are not accidentally profiting from the charset) and three total characters. That should be fast enough to use it in the regular test suite.

**Comment by timzimmermann** [comment]
We currently do not support gaps in the character set, but if you are fine with it I can change it to `abcd` and three characters.
