### ISSUE TITLE
Evaluate abandoning iterative Optimizer architecture

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1211]
We initially designed the Optimizer to repeatedly apply its rules until the LQP converges. After #1170, there will be no iterative batches anymore and some rules (JoinOrderingRule, PredicatePlacementRule) make no effort in determining whether they changed the LQP and simply claim that they didn't. 

I think we should acknowledge this development and at least allow explicit non-iterative rules. Maybe even abandon the iterative concept altogether.

**Comment by mrks** [comment]
Also: Get rid of JoinDetectionRule?

**Comment by Bouncner** [comment]
Hmm, and we are sure that will still work when we optimize more complex queries as the ones in TPC-DS?

**Comment by mrks** [comment]
Most of the rules don't follow the iterative approach anyway.
