### ISSUE TITLE
Print Tests: one-to-one comparison?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1219]
As seen in #1209, we can add data to the print output without changing the test. Right now, these tests check for the existence of some fragments in the output. Wouldn't it be more straight forward to simply compare them with an expected result?

**Comment by Bouncner** [comment]
Well, right now we test rather if there is the expected content which also works with minor optical changes of the print operator.

I am happy to change it or add new tests if that's something we want to do. Concerning the PR discussion: I think it makes sense that printing additional information does not brake the print tests.
But that probably a matter of taste?

**Comment by mrks** [comment]
I am not aware of any best practice in this case. Generally, it should be difficult to modify the code without breaking tests. Adding things is in a grey area, but in this case I don't see how we profit from being able to add things without breaking tests. One-to-one string comparisons (similar to what we do with the CSV export) seem to cover more and should be easier to maintain.

**Comment by Bouncner** [comment]
I got an email with your response, but Github does not show it.

However: ok, I'll take a look at it.
