### ISSUE TITLE
DpCcp cannot handle uncorrelated predicate

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1229]
Though of questionable usefulness, predicates not referencing anything from the FROM clause are possible: `SELECT * FROM a, b, c WHERE 1 IN (3, 2, 1)`. 

DpCcp doesn't know what to do with the predicate `1 IN (3, 2, 1)` since it is neither a local predicate not a join predicate

**Comment by mrks** [comment]
Isn't that something that should be removed before by the constant calculation rule?

**Comment by mrzzzrm** [comment]
Yeah, it could. But the JoinOrderingRule should be able to handle any LQP not matter what rules touched it before.

**Comment by mrks** [comment]
Agreed.

**Comment by mrks** [comment]
What happens right now, anyway?

**Comment by mrzzzrm** [comment]
DPccp goes boom

```
    if (edge.vertex_set.count() == 1) continue;
    Assert(edge.vertex_set.count() == 2, "Can't place complex predicates yet");
```

**Comment by mrzzzrm** [comment]
`edge.vertex_set.count()` in this case would be zero
