### ISSUE TITLE
JoinOrdering cannot handle Validates gracefully

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1230]
Currently a ValidateNode is treated as opaque when building a JoinGraph. That means any predicates/joins below it are not included in the JoinGraph.

Currently this is not a big problem because we do not have Validates above Joins. 

There are some downsides, however: DpCcp is triggered multiple times: Once for the stuff "above" the validates and then for any sub-LQP below each Validate, if this sub-LQP includes one or more predicates.

Also, JoinGraph visualization will not include local predicates in the "main" JoinGraph:

![joins copy](https://user-images.githubusercontent.com/2679018/47349746-9100b480-d6b4-11e8-8735-817546270ccd.png)

**Comment by mrzzzrm** [comment]
@mrks Since Validates are "just" scans on a specialized set of columns, what do you think about a "ValidateExpression" that can gracefully model Validates as normal local predicates in the JoinGraph? Keeping the Validate(Node), obviously.

**Comment by mrks** [comment]
How is it handled right now?

**Comment by mrks** [comment]
Ah, sorry. Didn't see the text before your comment

**Comment by mrzzzrm** [comment]
> If the validation is so similar to a scan, maybe it's meant to be one?

I'm afraid it might be so... It performs the same thing semantically (selecting a subset of rows), we want to tread it the same way in the Optimizer (PredicateReordering, JoinOrdering)

So, does Validate just become another TableScanImpl?

**Comment by mrks** [comment]
Basically, yes. If it makes sense. We need to see if the code in table_scan.cpp needs to be adapted for that. It shouldn't make "regular" scans more complicated. Once we are done with #1164 / #1242, we can have a look at this.

**Comment by mrzzzrm** [comment]
I tried refactoring this a while ago and found it impossible to treat a Validate the same as a normal PredicateExpression. The reason for this was mostly that the "columns" Validate scans on are not referenceable in the LQP in a meaningful way - so the only thing binding a Validate to the columns it scans on is its location in the query plan. Once you remove it from that location, e.g. when building a JoinGraph, you loose the information which vertex the Validate references. 

Left this open for a while after attempting this and no new ideas popped up in my head, so I am closing this. We just have to live with having to treat both Predicates and Validates.
