### ISSUE TITLE
Linter script think singleton.hpp violates itself

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1247]
I'm getting this on both my Ubuntu 18.04 machines when linting. 

Same for you @lanice?

![image](https://user-images.githubusercontent.com/2679018/47641202-bd5d7a80-db65-11e8-8389-26c345e16358.png)

It seems like the `exclude` in `grep -rn 'static[^:]*instance;' --exclude src/lib/utils/singleton.hpp` is not working...

**Comment by mrks** [comment]
Funnily enough, this does not happen on OS X.

**Comment by Bensk1** [comment]
And it does not make our CI fail...

**Comment by mrks** [comment]
on it
