### ISSUE TITLE
SQLPipelineStatement::get_optimized_plan() may differ from query cache entry

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1261]
So when a query is in the cache, the cache entry will be used as the plan that will get executed and returned from `SQLPipelineStatement::get_query_plan()` and it may differ from the LQP returned from `SQLPipelineStatement::get_optimized_plan()`, which is potentially confusing. 

(a different optimizer was used when the query in the cache was optimized, the data statistics may have changed...)

Are we okay with this?

**Comment by mrks** [comment]
In the master, we have never used more than one optimizer. Personally, I would say that a comment describing that behavior would be sufficient.
