### ISSUE TITLE
Memory consumption tests fail on macOS

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1266]
```
[  FAILED  ] BTreeIndexTest.MemoryConsumptionVeryShortString
[  FAILED  ] BTreeIndexTest.MemoryConsumptionShortString
[  FAILED  ] BTreeIndexTest.MemoryConsumptionLongString
```

**Comment by mrks** [comment]
When fixing this, please don't check for darwin, but for `#ifdef __GLIBCXX__`

**Comment by adi64** [comment]
Oh damn. Didn't think of that 🤦‍♂️

**Comment by julianmenzler** [comment]
Unfortunately, I'm having trouble with the current state of `master`  under *macOS 10.14.3*.

```
[----------] Global test environment tear-down
[==========] 2683 tests from 207 test cases ran. (58015 ms total)
[  PASSED  ] 2680 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] BTreeIndexTest.MemoryConsumptionVeryShortString
[  FAILED  ] BTreeIndexTest.MemoryConsumptionShortString
[  FAILED  ] BTreeIndexTest.MemoryConsumptionLongString
```

**Comment by Bouncner** [comment]
Can you paste the actual failed tests as well, please?

**Comment by julianmenzler** [comment]
Sure, here is the console ouput:
```
[ RUN      ] BTreeIndexTest.MemoryConsumptionVeryShortString
/Users/julianmenzler/Repositories_local/hpi_hyrise/src/test/storage/btree_index_test.cpp:91: Failure
Expected equality of these values:
  index->memory_consumption()
    Which is: 916
  876u
    Which is: 876
[  FAILED  ] BTreeIndexTest.MemoryConsumptionVeryShortString (1 ms)
[ RUN      ] BTreeIndexTest.MemoryConsumptionShortString
/Users/julianmenzler/Repositories_local/hpi_hyrise/src/test/storage/btree_index_test.cpp:113: Failure
Expected equality of these values:
  index->memory_consumption()
    Which is: 320
  304u
    Which is: 304
[  FAILED  ] BTreeIndexTest.MemoryConsumptionShortString (0 ms)
[ RUN      ] BTreeIndexTest.MemoryConsumptionLongString
/Users/julianmenzler/Repositories_local/hpi_hyrise/src/test/storage/btree_index_test.cpp:147: Failure
Expected equality of these values:
  index->memory_consumption()
    Which is: 345
  329u
    Which is: 329
[  FAILED  ] BTreeIndexTest.MemoryConsumptionLongString (0 ms)
```

**Comment by mrks** [comment]
This might be related to the pmr_string commit #1506. I thought I also tested it with OS X, but maybe I didn't. If the allocator takes a different amount of memory on libc++, this would explain it.

**Comment by Bensk1** [comment]
I have just built Hyrise from scratch and got the same error. @julianmenzler are you on llvm/clang 7 or 8? I just updated from 7 to 8 but did not try a pre-#1506-build with clang 7.

**Comment by Bensk1** [comment]
@FabianWiebe just said that he has the same problems with clang 6. It might be a problem with the `pmr_string` then.

**Comment by Bensk1** [comment]
Could introducing a debug build with libc++ to the CI help preventing such problems in the future?

**Comment by mrks** [comment]
Probably. I think I thought about it a while ago, can't remember why I ended up not doing it though.

**Comment by FabianWiebe** [comment]
We tried using libc++ on Linux last year: https://github.com/hyrise/hyrise/issues/920#issuecomment-400295022
Maybe it could work now as we do not use `experimental::filesystem` anymore.

**Comment by julianmenzler** [comment]
> I have just built Hyrise from scratch and got the same error. @julianmenzler are you on llvm/clang 7 or 8? I just updated from 7 to 8 but did not try a pre-#1506-build with clang 7.

I experienced this issue with llvm/clang 7.
With the current state of master (`95561eca`), however, the issue seems to be solved on my side.

**Comment by Bensk1** [comment]
Really? I cannot confirm that on macOS.

**Comment by julianmenzler** [comment]
> Really? I cannot confirm that on macOS.
Sorry, bug still persists. I mixed-up some builds.
