### ISSUE TITLE
Run TPC-H/SQLite Tests with encoding as part of system tests.

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1269]
Anyone against this? This will get some coverage on both encodings and chunk pruning

Make sure to test VectorCompression schemes as well. https://github.com/hyrise/hyrise/pull/1323#discussion_r235933637

**Comment by mrks** [comment]
Good idea. You don't mean "coverage" as the KPI though, right? `hyriseSystemTest` righfully does not contribute to the coverage calculation.

**Comment by mrks** [comment]
(and even in `hyriseTest`, the sqlite runner does not count as a proper test w.r.t. the coverage calculation)

**Comment by mrzzzrm** [comment]
With coverage. I mean my feeling of comfort and safety when stating "hyrise works!". I don't mean that artificial number that we feel good about if its displayed on a green background.

**Comment by mrzzzrm** [comment]
@mrks @FabianWiebe Running the JIT version of the SQLite tests has more than doubled the runtime of hyriseTest:

![image](https://user-images.githubusercontent.com/2679018/48670382-69680500-eb17-11e8-9890-157ca510a7dd.png)

Would you consent to running the JITted SQLiteTestrunner tests only as part of the hyriseSystemTest?

**Comment by FabianWiebe** [comment]
> Would you consent to running the JITted SQLiteTestrunner tests only as part of the hyriseSystemTest?

@mrzzzrm I do not mind where they run as long as they are being executed once with every pr.
A possible alternative could be to disable JIT (and JIT tests) with cmake flag: `-DENABLE_JIT_SUPPORT=OFF`

**Comment by mrzzzrm** [comment]
#1323 makes it a matter of a line to enable testing the SQLiteTestRunner/TPCHTests with Encodings. 

There are, however, some bugs being triggered if you enable this:

* [ ] #1083
* [ ] #1324

**Comment by Bouncner** [comment]
Close because they are executed now or are there still issues?

**Comment by mrzzzrm** [comment]
Already closed because they are executed now.
