### ISSUE TITLE
AggregateContext monotonic_buffer_resource

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#1272]
TPC-H 18 (scale 1) drops to 0 iter/s when using 224 cores and 100 clients on nemea, which is caused by many concurrent allocations during the aggregation phase, when constructing the elements in the `AggregateContext::results` map.
With a monotonic_buffer_resource (as used in a different spot before already), we can pre-allocate the needed memory block, and the performance goes up to about 25 iter/s.

Just leaving this as a note here, I will make it PR-ready once I'm done with my thesis.

**Comment by mrzzzrm** [comment]
@lanice done? saw an aggregate prs from you.

**Comment by lanice** [comment]
Yup, thanks!
