### ISSUE TITLE
No chunk_size specified in CSV meta, benchmark runner complains anyway

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1289]
`Maximum chunk size defined in benchmark (100000) and in csv meta file (4294967294) differ`

**Comment by mrzzzrm** [comment]
Prbably #1274

**Comment by mrks** [comment]
Hmm, I was not aware that that setting was optional. :/

**Comment by mrzzzrm** [comment]
it should not exist at all, imo

**Comment by mrzzzrm** [comment]
Would you agree on removing the chunk_size CSV meta info? I think being able to specify it in multiple places, with possible contradictions is a bad idea. And it feels misplaced in the CSV config anyway. Can't the json config of the benchmarks specify per-table chunk sizes as well, shouldn't that suffice?
