### ISSUE TITLE
Consider extracting for loop conditions

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1293]
#1292 indicates that non-trivial loop conditions might cause perf problems. A quick `grep -rin "for (.*;.*().*;.*)"` (TODO: Check if multi-line is covered) reveals there are 132 `for` loops in `src/operators` alone that issue function calls in their loop condition. 
We should investigate whether extracting them improves performance.

**Comment by mrks** [comment]
Maybe we even want to put that regex into lint.sh?

**Comment by mrks** [comment]
@engelfa - if I remember correctly, you mentioned that you were basically done with this? While it might not have brought any performance benefits, we should bring it in anyway.

**Comment by mrks** [comment]
@engelfa ping?

**Comment by mrks** [comment]
These look like candidates, too:

https://github.com/hyrise/hyrise/blob/da63eecf05e9793164c212cdc7ce716a01d4054a/src/lib/sql/sql_translator.cpp#L603

https://github.com/hyrise/hyrise/blob/da63eecf05e9793164c212cdc7ce716a01d4054a/src/lib/sql/sql_translator.cpp#L671

**Comment by Bouncner** [comment]
It is now part of the guidelines and we should have handled all cases where it matters (operators etc.; not tests).
