### ISSUE TITLE
Automatic dumping of binary files after CSV loading

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1298]
(@mrks @Bensk1, mostly to keep you in the loop)

As previously discussed, CSV loading is horrendously slow and loading binaries is reasonably fast. The idea, as discussed, when running a filebasedbenchmark, is to 

* if "a.bin" and "a.csv" exist, load "a.bin"
* if only "a.csv" exists, load it and immediately dump "a.bin" with unencoded data

...this is simple, but will perform the requested encoding every time the benchmark loads its table files, still. However, since encoding can be specified on a per-column level, I see no easy way of indicating, in the file name of the binary, which encoding config was used. So, I would just live with the repeated re-encoding.

Also, while it might be desirable to use the binary caching for the TPCH benchmark as well at some point, for now I'd just implement it for the file based benchmark. Agreed?

**Comment by Bensk1** [comment]
I think I do not really understand why we cannot avoid the re-encoding.

**Comment by Bensk1** [comment]
You are right, we don't want that. For larger benchmarks it would also consume a significant amount of storage.

Your proposal would be fine for me.

**Comment by Bouncner** [comment]
My understanding was that we are currently not able to export all supported encodings as binary.
