### ISSUE TITLE
Speed up CSVParser

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1301]
E.g., by using memory mapped files instead of char-by-char reading via iterators.

**Comment by mrks** [comment]
https://lemire.me/blog/2012/06/26/which-is-fastest-read-fread-ifstream-or-mmap/

> Conclusion: For sequential access, both fread and ifstream are equally fast. Unbuffered IO (read) is slower, as expected. Memory mapping is not beneficial.

There are certainly other things that can be sped up, but let's look at that once it actually slows us down. Closing this issue as it is not immediately actionable.
