### ISSUE TITLE
BenchmarkRunner should visualize as soon as possible (fixed in #1597)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1302]
not at the very end of the benchmark. 

* while the benchmark is still running, you might already want to look at the plans of queries that completed. 

* If a query gets stuck and you have to kill the benchmark, e.g. because the plan is inefficient, you might want to look at the optimized LQP anyway, to get a clue why the query was inefficient.

**Comment by mrks** [comment]
Since the visualization takes some time, this would only make sense if we imply `-r 1` and discard the results.

**Comment by mrzzzrm** [comment]
You mean visualize only once per query? Of course, I'd just visualize the first run, for now. Or what do you mean?
