### ISSUE TITLE
BenchmarkRunner reports 2x the actual table size

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1303]
Running the JOB (6GB of data, Unencoded) yields `"table_size_in_bytes": 12088189001` in the report

**Comment by mrzzzrm** [comment]
Might be the nulls:

![image](https://user-images.githubusercontent.com/2679018/48718806-60149080-ec1c-11e8-9865-82373d1e41b3.png)

**Comment by mrks** [comment]
`tbb::concurrent_vector<bool>` does not do the optimization that `std::vector<bool>` does.

**Comment by mrks** [comment]
We could discuss #749 this Wednesday.

**Comment by mrks** [comment]
I have put the general concurrent_vector issue on the agenda. I would close this as this is not an actionable issue.
