### ISSUE TITLE
Rewrite trivial IN predicate to equals

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1304]
Because IN is slow:

![image](https://user-images.githubusercontent.com/2679018/48716814-74ef2500-ec18-11e8-973b-e4e84ac39bc6.png)

**Comment by mrzzzrm** [comment]
This is JOB 3b

```
SELECT MIN(t.title) AS movie_title
FROM keyword AS k,
     movie_info AS mi,
     movie_keyword AS mk,
     title AS t
WHERE k.keyword LIKE '%sequel%'
  AND mi.info IN ('Bulgaria')
  AND t.production_year > 2010
  AND t.id = mi.movie_id
  AND t.id = mk.movie_id
  AND mk.movie_id = mi.movie_id
  AND k.id = mk.keyword_id;
```

**Comment by mrks** [comment]
What is your idea on where to do this? Theoretically, this could be its own rule, but having a separate rule for that, which has to traverse the entire LQP seems quite expensive. Maybe this is something that is so blatantly obvious that it should be done in the SQLTranslator?

**Comment by mrzzzrm** [comment]
I'd probably re-purpose the LogicalReductionRule to be a PredicateSimplificationRule, or similarily named.

**Comment by mrks** [comment]
Where do we draw the line to the constant elimination?

**Comment by Bouncner** [comment]
One task in the seminar will (if chosen) the optimization of subselects with IN to join queries. What do you think about including this issue in the upcoming optimizer rule?

**Comment by mrzzzrm** [comment]
Sounds unrelated to this particular case, this is just a predicate rewrite done because we know our operators are faster at executing "=" than "IN"

**Comment by Bouncner** [comment]
Is it that simple? Would about rewrites with two IN literals? Would we rewrite this to `mi.info = Bulgaria OR mi.info = Slovania` as well or is this something totally different?

I am asking because the seminar group has to think about issues like "when do we switch from subqueries to joins because the left side is really large" and find the break-even points here.
If this OR thing is something totally different, please ignore me. :)

**Comment by mrks** [comment]
If I understand this correctly, it is exclusively about INs with a single value in the list

**Comment by mrzzzrm** [comment]
The rewrite from `a IN (b, c)` to `a = b OR a = c` is done by the ExpressionEvaluator itself already. the reason why we want to rewrite `a IN (b)` in the Optimizer already is because by doing so we can avoid calling the ExpressionEvaluator altogether, because the ColumnToValueTableScanImpl is then able to take care of the scan.
