### ISSUE TITLE
Type conversions are incorrect

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1306]
Currently, the scan converts the parameter into the type of the column that we scan on. This means that for an int column, the search parameter is first converted to an int - this is a problem if it was originally a long:

```
CREATE TABLE t (a INT, b LONG);
INSERT INTO t (a, b) VALUES (1000, 1000);
SELECT * FROM t WHERE a < 1000000000000
-- no results
SELECT * FROM t WHERE b < 1000000000000
-- one result
```

Pretty sure this is the case for other operators as well. We should have a careful look at what the SQL standard does, fix the issues, and write tests for mismatching data types.

In #1148, we have disabled a test `SELECT * FROM mixed WHERE a = 'a' AND c < 65.31;` that showed differing behavior for JIT and non-JIT.

**Comment by FabianWiebe** [comment]
I checked `ISO/IEC 9075-1:2011(E)` but could not find anything in the standard in the section for numeric types:

> 4.4.3.1 Numeric types
There are two classes of numeric type: exact numeric, which includes integer types and types with specified precision and scale; and approximate numeric, which is essentially floating point, and for which a precision may optionally be specified.
Every number has a precision (number of digits), and exact numeric types also have a scale (digits after the radix point). Arithmetic operations may be performed on operands of different or the same numeric type, and the result is of a numeric type that depends only on the numeric type of the operands. If the result cannot be represented exactly in the result type, then whether it is rounded or truncated is implementation-defined. An exception condition is raised if the result is outside the range of numeric values of the result type, or if the arithmetic operation is not defined for the operands.
