### ISSUE TITLE
BenchmarkRunner seems to ignore its own default chunk_size (fixed in mrks/benchmark-csv)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1307]
This was run without a chunk_size and states one chunk for 29M rows

![image](https://user-images.githubusercontent.com/2679018/48719034-d2857080-ec1c-11e8-906a-d5fd38e1f300.png)

on startup, the benchmark runner claimed it would use 100k rows per Chunk:

```
- Writing benchmark results to stdout
- MVCC is disabled                                         
- Running in single-threaded mode
- 1 simulated clients are scheduling queries in parallel  
- Running benchmark in 'IndividualQueries' mode
- Visualization is on                                      
- Encoding is 'Unencoded'                    
- Chunk size is 100000
```

**Comment by mrks** [comment]
The chunk_size is currently not passed into the csv parser:
https://github.com/hyrise/hyrise/blob/06dcc3b2b244b046a8be3a8a119116f198e49017/src/benchmark/file_based_benchmark.cpp#L56
