### ISSUE TITLE
Allow numbers to be used as a predicate

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1308]
It should be quite simple to rewrite `WHERE 1` to `WHERE 1 > 0` and `WHERE a` to `WHERE a > 0`, shouldn't?

**Comment by mrzzzrm** [comment]
Would need to happen in the SQLTranslator, to be able to run queries unoptimizes, but yeah. I'd rewrite to `WHERE a != 0`, though

**Comment by mrks** [comment]
Nope, `!= 0` makes sense, too.

**Comment by mrks** [comment]
I was about to have a look at this, but checked the SQL standard first. Looks like this is an extension that MySQL does.

```
         <predicate> ::=
                <comparison predicate>
              | <between predicate>
              | <in predicate>
              | <like predicate>
              | <null predicate>
              | <quantified comparison predicate>
              | <exists predicate>
              | <unique predicate>
              | <match predicate>
              | <overlaps predicate>
```

As our issue list is long enough, let's postpone it until someone actually needs it.
