### ISSUE TITLE
Don't use random values in tests

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1321]
I just got this in CI:
![image](https://user-images.githubusercontent.com/2679018/48894494-2ffb0680-ee43-11e8-9b14-30c2f70978f3.png)

the test in question wasn't touched by me and uses random value generation. This is highly anti idiomatic, imo. Test should test explicit values, random values are not reproducible. And no, I don't think fixed seeds solve that, test values should be hand picked and thus comprehensible just from reading the test code.

*Update MD: Using a fixed-seed PRNG is also a bad fix because it involves implementation-dependent behavior.*

**Comment by Bouncner** [comment]
Well, it helped a lot recently to find all sorts of edge-cases. I agree for unit tests, but it would still be nice to have some more fuzzing in Hyrise's tests.

I redo the test next week.

**Comment by mrzzzrm** [comment]
I am not opposed to "fuzzing" tests at a higher level, maybe in the system tests. But the unit tests should not use randomly generated values.

Just as random values can (accidentally one could say) trigger edge cases, they might also test entirely uninteresting values and specifically not the edge cases. I think we're always better of to put some brains into a handful or two handpicked, explicit test values than to rely on random generation to find edge cases for us.

Then there is the case of test-readability. I will always prefer explicit values over a for loop, for some reasons:

E.g., here you can get an intuitive idea of which values are covered, i.e., how "good" the test tests.
```
EXPECT_TRUE(can_prune(filter, 5.0));
EXPECT_TRUE(can_prune(filter, 5.1)); // You get a test Failure here, you know exactly which value doesn't work
EXPECT_FALSE(can_prune(filter, 5.2));
EXPECT_FALSE(can_prune(filter, 15.3)):
```

Here, just from having a glimpse at this code you cannot tell how good the test is.
```
// You get a test Failure here, you have no idea what value didn't work. Run the test again in the debugger, you might get a different random value. Place a breakpoint in the loop body and you have to skip over a ton of values that do work.
for (auto v : gen_random_prunable_values()) EXPECT_TRUE(can_prune(filter, v)) ;
for (auto v : gen_random_non_prunable_values()) EXPECT_FALSE(can_prune(filter, v));
```

Also, with randomly generated values, there is always the temptation to just generate many, many random values because "better coverage" which results in the test running longer than it would need to, but no one daring to reduce the number of values generated because the original author surely had a reason to include so many.

**Comment by Bouncner** [comment]
Moritz:
>  I'd like to see a handful more fine granular tests around with values around the bounds of ranges

> You tested that BETWEEN this->_max_value - 1 AND this->_after_range can not be pruned - good! Why not do due diligence and test BETWEEN this->_max_value AND this->_after_range and BETWEEN this->_max_value + 1 AND this->_after_range as well? Why not do the same for the lower end of the value range? And for one or two gaps?

**Comment by mrks** [comment]
@Bouncner @mrzzzrm - Is this still an issue?

**Comment by mrzzzrm** [comment]
![image](https://user-images.githubusercontent.com/2679018/50156560-5d669300-02cf-11e9-98a7-6d988ef95ffb.png)

Three tests still use random values, I think its worth changing these so this is consistent.

**Comment by mrks** [comment]
Here's an addition to lint.sh for this:

```

# Tests should not include any type of random behavior, see #1321.
output=$(grep -rEn '#include <random>|std::random|std::[a-z_]+_engine|std::[a-z_]+_distribution' src/test | grep -v std::random_access_iterator_tag | sed 's/^\([a-zA-Z/._]*:[0-9]*\).*/\1  Tests should not include any type of random behavior, see #1321./')
if [ ! -z "$output" ]; then
	echo "$output"
	exitcode=1
fi 
```
