### ISSUE TITLE
Directory structure: Test tables

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1341]
I noticed that our directory structure is rather unintuitive in some places. Seeminly minor, but easy to fix and hopefully helps with navigating the code base.

So we have `.tbl` files in `src/test/tables`, `.csv` files in `src/test/csv` and `.bin`s in `src/test/binary`.

I would put these all under `.../tables/{tbl,csv,bin}/...`

Second, I would, and this is maybe controversial, move them out of `src` (as they aren't code) and into `<hyrise-checkout>/data`.

Opinions?

**Comment by mrks** [comment]
Agreeing on the first; for the second I worry that this looks too much like "real" data. Maybe we could add a root folder for non-code files? That could also include also those pesky xy-ignore files that litter the root directory.
