### ISSUE TITLE
MVCC: Store is_validated in Table?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1344]
A seminar group wrote the attached code, which fails with:

```
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: /hyrise/src/lib/concurrency/transaction_context.cpp:150 All read/write operators need to be in state Executed (especially not Failed).
```

The reason for this is that the input to `Update` was not validated, thus they were trying to update the rows twice. This rightfully failed.

If we add a field `Table::_is_validated` which is only set by the `Validate` operator, we should be able to prevent this. Any objections?

[mvcc_benchmark.txt](https://github.com/hyrise/hyrise/files/2644786/mvcc_benchmark.txt)

**Comment by mrzzzrm** [comment]
Nitpicking: Store in Table or in Chunk? (and Table::is_validated() returning true if all chunks are validated)

If in Chunk, then `Chunk::is_validated() { return !mvcc_data }`

**Comment by mrks** [comment]
mmh, the code that you suggest would also mark a table as "validated" if an operator forgets to pass the MVCC data along. I think explicitly setting it is better.

As for table or chunk, I can't come up with a good reason why a table should be partly validated. Yes, you could have a union, but I would simply say that operators should not accept tables with a non-equal validation status.
