### ISSUE TITLE
ColumnVSColumnScan and JoinNestedLoop won't scale if we add more encodings

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1350]
...since they both nest the iteration over one column into the iteration over the other, which results in n^2 instantiations.

I will  (and you can, too!)  update this issue with ideas to tackle this.

**Comment by Bouncner** [comment]
I still wonder what this thing called `compiler` does. But is there a way to parallelize all these template instantiations?

**Comment by mrks** [comment]
https://stackoverflow.com/questions/48830137/c-parallelize-template-instantiation :/

**Comment by mrzzzrm** [comment]
Some ideas:

* Evaluate >, >= scans with <, <=
* Only inline if left encoding/datatype == right encoding/datatype
* Do not inline for expensive encodings (zlib was discussed, right?) - the cost of a virtual function call is negible here.

**Comment by mrks** [comment]
@Bouncner Once your group brings in the more expensive encodings, we might want to think about the last part again. Also, we should check if we always want to erase the iterator for those encodings if the virtual method call is negligible compared to the cost of decoding the data.

**Comment by mrks** [comment]
The rest is done.
