### ISSUE TITLE
Binary import/export: Support all encoding types

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1367]
Currently only ValueSegments and DictionarySegments are supported, seemingly

**Comment by mrks** [comment]
As far as I can see, only the FixedStringDictionarySegment is missing. Dumping the FixedStringVector (which is just a vector of characters) into a binary file should not be too difficult, so maybe we could get this done, too, and finally close this issue?

**Comment by dey4ss** [comment]
If @j-tr is not quicker, I can do this after vacation.
