### ISSUE TITLE
Support Segment Re-Encoding

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1368]
After #1356 it will become annoying that we cannot create a, e.g., FrameOfReference encoded segment from a DictionarySegment. Should be simple to implement, BaseSegment should probably receive a virtual getter for the memory resource it is associated with and that's it.

**Comment by Bouncner** [comment]
Is that a regression of #1356 or was that not possible before either?

**Comment by mrzzzrm** [comment]
not possible before either

**Comment by mrzzzrm** [comment]
The reference to #1356 stems from the fact that if you have a table cached on disk as a Dictionary binary and then run the Benchmark in FrameOfReference mode, you'll get an error message and have to delete your binary tables and create them anew from CSV data
