### ISSUE TITLE
exists (select 1) returns one element instead of all

### ISSUE THREAD

**Issue by pascalhpi** [hyrise/hyrise#1373]
in hyriseConsole: `select * from customer where exists (select 1)` should return all customers but returns only one customer. this seems to be true for all uncorrelated subqueries: if the subquery returns anything we get the first element instead of all, if it does not return anything we get nothing.

**Comment by mrzzzrm** [comment]
Yep, `ExpressionEvaluator::evaluate_expression_to_pos_list` looks like it would do that. Will fix asap.

**Comment by mrzzzrm** [comment]
#1375 should fix this. One question though:
> this seems to be true for all uncorrelated subqueries: if the subquery returns anything we get the first element instead of all, if it does not return anything we get nothing.

is this referring specifically to subqueries in EXISTS or to subqueries in general. Because the aforementioned fix only addresses EXISTS, if you encountered problems with them anywhere else, please let me know.

**Comment by pascalhpi** [comment]
we only encountered this for uncorrelated subqueries as argument to EXISTS, nowhere else
