### ISSUE TITLE
Iterator for Table::_chunks

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1384]
A seminar group is working on cleaning up (almost) empty chunks. Once most of a chunk is deleted, the remaining rows are migrated to (i.e., re-inserted into) the last chunk. Later, the original chunk can be deleted. We plan to set `_chunks[n] = nullptr` for that.

Currently, all operators iterate over the list of chunks by using a `ChunkID` index. If we were to keep it that way, we would need to add a `if (... == nullptr) continue` check everywhere.

An alternative would be an iterator (as originally proposed in #697, paragraph 1). The iterator would return a `pair<ChunkID, shared_ptr<Chunk>>`. Furthermore, `get_chunk` would have a debug assertion making sure that it is only called on existing chunks.

@Bensk1, @Bouncner and I talked about this and agreed that the iterator model would be better. Since it changes one of our core data structures, we still want to put it out for discussion.

P.S.: Another argument in favor of this is that we might be able to use it for pipelining. The iterator might wait for the next chunk to be completed.
P.P.S.: An argument against it is that we will have to adapt the seminar material for next year... ;)

**Comment by mrzzzrm** [comment]
We are sure a many-read-exclusive-write (I am sure there is a better term...) lock on `Table::_chunks` is going to be too slow?

**Comment by mrks** [comment]
You mean to clean up the vector? That's not the issue - the issue is that it invalidates every PosList that might be out there.

**Comment by mrzzzrm** [comment]
oh gosh.

**Comment by mrks** [comment]
This won't be a noticeable issue though. Having gaps in the vector of chunks is not nice, but it means that PosLists remain valid. Aside from the iterator approach outlined above, it does not really break anything.

Sure, having those gaps feels a bit untidy, but I am almost sure that it does not have any noticeable performance or architectural impacts. Having lots of "dead" chunks is certainly a bigger issue.

All of this is up for discussion, though, either here or in person.

**Comment by mrzzzrm** [comment]
How would it work? Would `Table::get_chunks()` return a custom wrapper around `Table::_chunks` that provides the custom iterator?

**Comment by mrks** [comment]
yes

**Comment by mrks** [comment]
In our meeting today we had a different idea: Why not modify `GetTable` so that it prunes chunks that do not exist? It could also skip chunks that are guaranteed to be entirely invalid for a given commit id. That way, we do not have to touch the operators at all.

**Comment by mrzzzrm** [comment]
That sounds like it could work. 

If no operator ever works on a stored Table object, then we could actually remove nullptrs from the stored Table's `_chunks` vector occasionally, maybe?

**Comment by Bouncner** [comment]
The GetTable idea sounds reasonable to me. It doesn't cover the pipelining aspect, but that's going to happen anyways the next couple of months, I'd guess.
