### ISSUE TITLE
DictionaryEncoder could avoid separate compression step; might use a HashMap?

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1389]
Briefly looked at the `DictionaryEncoder`, noticed two things.

1: It always builds the AttributeVector with maximum width (`pmr_vector<uint32_t>{values.get_allocator()};`) even though the dictionary length and the requested compression type are already known. Could use `pmr_vector<uint16_t>{values.get_allocator()};` or `pmr_vector<uint8_t>{values.get_allocator()};` via static polymorphism if the FixedSizeByteAligned (quite a bloated name...) compression is requested. Might safe us a bit of perf.

2: Also `_get_value_id()` uses a binary search for each lookup in the dictionary - are we really sure a HashMap wouldn't be faster here?

**Comment by mrks** [comment]
Re 1: Yes, but as you mentioned that only works for FixedSizeByteAligned. Rewriting the vector shouldn't be the expensive part, so unless this pops up in the profiler, I wouldn't worry about it.
Re 2: No idea, feel free to test it. My guess is that the cost of building the hash map is only amortized for strings.

**Comment by mrks** [comment]
Status Quo for a lineitem chunk:

```
(single chunk, example)
Copy values: 781 µs 354 ns
Build dictionary: 2 ms 821 µs
Lookup value ids: 4 ms 107 µs
Compress attribute vector: 177 µs 453 ns

Total for single-threaded encoding of lineitem: 19 s 604 ms
```

As the compression is not that expensive, I'll skip the first suggestion in the interest of keeping the code simple.

Compressing using unordered_map (again, just a single chunk, so we have some variance):

```
Copy values: 1 ms 373 µs
Build dictionary: 3 ms 856 µs
Build unordered_map: 4 ms 667 µs
Lookup value ids: 1 ms 731 µs
Compress attribute vector: 178 µs 197 ns

Total for single-threaded encoding of lineitem: 17 s 188 ms
```

When comparing the multi-threaded generation, it looks like this:

status quo:
```
Encoding of lineitem: 2 s 880 ms
	Command being timed: "./hyriseBenchmarkTPCH --dont_cache_binary_tables -r 0"
	User time (seconds): 83.85
	Maximum resident set size (kbytes): 5663616
```

unordered_map-based:
```
	User time (seconds): 80.11
	Maximum resident set size (kbytes): 5930140
```

So while we save some time, we also need more memory. This will have an even bigger effect on machines with more than 8 cores.

Finally, here are numbers with a chunk size of 9,999,999 (i.e., one chunk per table):

Encoding `19 s 90 ms -> 25 s 256 ms`
Max RSS `5617256 -> 5911336`

As such, I conclude that using an unordered_map is not more efficient in any case and will close this issue.

**Comment by mrks** [comment]
Correction: "As such, I conclude that using an unordered_map is not more efficient in <s>any</s> **every** case and will close this issue."
