### ISSUE TITLE
Benchmarks: get rid of --verbose, don't print JSON to console

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1392]
Does anyone have a need for the non-verbose mode? In the last months, I have *always* used `-v` to see the progress and I can't come up with a reason not to make that the only option. That would also make it easier for new users who might not know how helpful `-v` is.

**Comment by mrzzzrm** [comment]
Wanted to open the same issue after accidentally running a benchmark without -v and wondering whether it got stuck somehow. let's remove it.

**Comment by Bouncner** [comment]
Ack.

**Comment by mrks** [comment]
Also, I think we should only write the JSON result if `-o` is set. No one ever said "Oh nice, three hundred pages of iteration durations."

**Comment by mrks** [comment]
Alternatively, let it default to `-o /dev/lp`. ;)
