### ISSUE TITLE
SQL{Logical,Physical}PlanCache should not be global (fixed in #1615)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1402]
Currently, the query caches are always used by the SQLPipelineStatement, the only option to influence what cache the SQLPipeline uses is to manipulate the global cache. The caches should be normal parameters of the SQLPipeline, just as the Optimizer etc are.

In benchmarks, e.g., I want to be able to disable query caching in order to be able to benchmark the optimizer as well. There should be a CLI option for this.

**Comment by mrks** [comment]
In the TPC-C, the caches attribute for 22% of the execution time but never have a hit. This should really be done.

Also, we should measure if they have a noticeable benefit anywhere. If they don't, we should deactivate them by default until we can reuse them for different parameters.
