### ISSUE TITLE
Console style things

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1406]
As noted [here](https://github.com/hyrise/hyrise/pull/1400#discussion_r247517757), I take issue with the console overusing try/catch. 

Also, this:

```
    Assert(!_sql_pipeline->failed_pipeline_statement(),
           "The transaction has failed. This should never happen in the console, where only one statement gets "
           "executed at a time.");
```

implies `_sql_pipeline->failed_pipeline_statement(),` is always false in the console, yet `Console::_handle_rollback()` thinks it might be true. Speaking of `_handle_rollback`, the name implies mvcc rollback(?) but is called even after optimization threw an exception (`Console::_visualize`) or after PQP visualization failed. 

My takeaway would be to get rid of all non-InvalidInputException handling, because it evidently just leads into confusion. I'd rather have the console exit more than necessary than it continuing to operate with hyrise in undefined state or it performing totally unrelated error handling (`_handle_rollback`) after arbitrary exceptions.

**Comment by mrks** [comment]
@Bensk1 - Please have a look at this so that we can discuss it.

**Comment by mrks** [comment]
With #2118, the first part should have been resolved. `_handle_rollback` is gone and we do not deal with transaction conflicts in the console any more.
