### ISSUE TITLE
TPC-H Query instance for testing/demo

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1411]
Since 0bc175be95 tpch_queries.cpp does not contain actual TPC-H queries that can be executed in the console anymore. This was really handy for demos or to try out ideas. However, it's not always obvious which parameters make sense to fill in to form reasonably-sized result sets.

Any ideas whether/how we want to handle that? We could provide an example TPC-H query file or add a commented out executable version for each query to tpch_queries.cpp.

**Comment by mrzzzrm** [comment]
As already pointed out in the corresponding PR, I think having the option to run TPC-H queries with the default/validation parameters would be nice. I think `TPCHQueryGenerator::get_validation_options(QueryID)` and/or `TPCHQueryGenerator::get_validation_query(QueryID)` should be a thing.

**Comment by Bensk1** [comment]
I agree. But this does not help with quickly executing something in the console, does it?

**Comment by mrzzzrm** [comment]
Ah, you c/p'ed them from that cpp into the console? For that use case, should we maybe provide the validation queries in resources/tpch_validation_queries.sql?

**Comment by Bensk1** [comment]
Exactly! I would be fine with that

**Comment by mrzzzrm** [comment]
Though I personally think every real programmer should know, use and love the playground over the console.

**Comment by Bensk1** [comment]
Right. We had a couple of presentations where we used the console for demos as described above.

**Comment by Bensk1** [comment]
You can bet on that! This annoyed me way too much in the past

**Comment by mrks** [comment]
Alternative: `run_tpch n`, which first prints the query and then executes it?

**Comment by mrzzzrm** [comment]
yay for straight-forwardness, nay for yet another console command. But I would be fine with it.
How about a pseudo table? `SELECT q FROM SYS_TPCH_QUERIES WHERE query_id = ?`?

**Comment by mrks** [comment]
Not sure if serious :D

**Comment by mrzzzrm** [comment]
not serious ;)

**Comment by Bensk1** [comment]
Any strong opinions on what we want? I could imagine both, the `run_tpch n` command or putting the queries into `resources/tpch_validation_queries.sql`.

**Comment by mrzzzrm** [comment]
I can see virtue and malice in both. Yet another console command for something so non-standard seems overboard, but on the other hand it's handy and c/p is cumbersome. I'd probably be conservative and choose the .sql file if I had to.

**Comment by Bouncner** [comment]
What would be the argument against the SQL file? Sounds good to me, too.

**Comment by mrks** [comment]
Let's do the file then.
