### ISSUE TITLE
Test code coverage lacks colours

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1423]
There are no colours at: https://hyrise-ci.epic-hpi.de/job/Hyrise/job/hyrise/job/master/lastStableBuild/Llvm-cov_5fReport/

The content security policy seems to be the issue.

**Comment by mrks** [comment]
Changed /etc/default/jenkins as follows:

```
JAVA_ARGS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox; style-src 'self' https://hyrise-ci.epic-hpi.de;\""
```
