### ISSUE TITLE
Loading Plugins in hyrisePlayground fails

### ISSUE THREAD

**Issue by d-justen** [hyrise/hyrise#1434]
I'm trying to use the PluginManager to load a plugin in hyrisePlayground. Therefore, I added `CMAKE_DL_LIBS` and `FILESYSTEM_LIBRARY` to my `bin/CMakeLists.txt`, and defined `TEST_PLUGIN_DIR` in the same way it is defined in `test/CMakeLists.txt`. My hyrisePlayground looks like this:
```cpp
#ifdef __APPLE__
#define DYNAMIC_LIBRARY_SUFFIX ".dylib"
#elif __linux__
#define DYNAMIC_LIBRARY_SUFFIX ".so"
#endif

int main() {
  auto& pm = PluginManager::get();
  pm.load_plugin(std::string(TEST_PLUGIN_DIR) + "libTestPlugin" + DYNAMIC_LIBRARY_SUFFIX);
  pm.unload_plugin("TestPlugin");
  return 0;
}
```

If I execute the playground, I get the following error (the displayed path to the plugin is correct):
```shell
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/utils/plugin_manager.cpp:28 Loading plugin failed: /home/david/Studium/HPI/01/DYOD/hyrise/hyrise/cmake-build-debug/lib/libTestPlugin.so:
undefined symbol: _ZN7opossum14StorageManager9add_tableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10shared_ptrINS_5TableEE
```

Is there anything I have missed in order to use the PluginManager properly?

**Comment by Bensk1** [comment]
Could you show (parts of) the source code of the plugin or send a link to a branch/commit containing the plugin?

**Comment by mrks** [comment]
If I remember correctly, this is the test plugin that is already part of Hyrise.

**Comment by mrks** [comment]
Quick thought: What happens if you load and add a table in the playground? It might be the case that because the StorageManager::add_table method is not used, it is not linked into the binary.

**Comment by Bensk1** [comment]
> What happens if you grep for the symbol in the nm output?

It's there.
