### ISSUE TITLE
ColumnPruningRule partially broken

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1440]
This looks wrong:

https://github.com/hyrise/hyrise/blob/e9036384dd30c462637e07ca4aa80d6d615edf39/src/lib/optimizer/strategy/column_pruning_rule.cpp#L76

It should try a cast to `InsertNode`, not `UpdateNode`. Also, there should be a test for this.

**Comment by mrzzzrm** [comment]
wth? I'm sure I saw and fixed this before... :(
