### ISSUE TITLE
Access to constant_mappings.cpp is subject to static init order fiasco

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1441]
This only works by accident:

```
INSTANTIATE_TEST_CASE_P(TableScanBetweenTestInstances, TableScanBetweenTest, testing::ValuesIn(create_test_params()),
                        TypedOperatorBaseTest::format);
```

The way that google tests' tests register automatically is subject to the static initialization order fiasco, i.e., we have no guarantee that `encoding_type_to_string` and others have already been initialized.

I have a fix in mind, just wanted to track it here.

**Comment by mrzzzrm** [comment]
wait, are you implying gtest calls create_test_param() before main()? Because here it is called from `::testing::InitGoogleTest(&argc, argv);`

**Comment by mrks** [comment]
Nevermind, I messed up somewhere else and did not get around to close this.
