### ISSUE TITLE
jemalloc linking problem on macOS?

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1448]
After getting the latest master, hyriseTest and hyriseConsole report:

```
dyld: Library not loaded: /usr/local/lib/libjemalloc.2.dylib
  Referenced from: /Users/jan/Coding/hyrise_alter/./cmake-build-debug/hyriseTest
  Reason: image not found
[1]    89422 abort      ./cmake-build-debug/hyriseTest
```

when executed on macOS. This does also happen on a freshly checkout version.

**Comment by mrks** [comment]
Weird. I checked that this morning on my old laptop, otherwise I wouldn't have merged it.

**Comment by mrks** [comment]
`brew install autoconf`?

**Comment by lanice** [comment]
Does that only happen with those two targets?

**Comment by Bensk1** [comment]
> brew install autoconf?

Without autoconf you don't get to the point where you can execute the binaries. So that's not the reason.


> Does that only happen with those two targets?
I haven't checked.

**Comment by Bensk1** [comment]
Yes!

**Comment by mrks** [comment]
Argh. While it builds the lib correctly, it doesn't link it:

```
otool -L ./build/hyriseTest
./build/hyriseTest:
[...]
	/usr/local/lib/libjemalloc.2.dylib (compatibility version 0.0.0, current version 0.0.0)
```

It just happens to work for me because I already have jemalloc installed.

**Comment by julianmenzler** [comment]
I just checked out our repo again and built from scratch. Same issue.

**Comment by julianmenzler** [comment]
> Apparently jemalloc finished building: `[ 2%] Built target libjemalloc-build`... Is there a file `libjemalloc.dylib` lying somewhere?

No, there is no `libjemalloc.dylib` on my system after the build.

**Comment by julianmenzler** [comment]
Not yet. How does this tool help?

**Comment by janehmueller** [comment]
@lanice on Ubuntu (e.g., the build vms for the DYOD seminar) the [following](https://github.com/hyrise/hyrise/pull/1460/files#diff-dbd0895c6efd8b8ccd12633c0b4342d3R177) does not work:
`BUILD_COMMAND bash -c "output=$(make 2>&1) || (printf \"$output\\n\" && /usr/bin/false)"`

The `false` binary is located in `/usr/bin/false` on macOS while it is located in `/bin/false` on linux (or at least ubuntu). Is there a reason to not simply use `false`?

**Comment by mrks** [comment]
Argh. Could you open a PR and change that to `false`?
