### ISSUE TITLE
JIT expressions do not check for mod/division by zero.

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#1450]
In the current implementation of `JitExpression` it is not checked whether the right operand of a division or modulo operation is zero. If this is the case, the result value should be null.
The non-jittable expression evaluator implements this behaviour correctly.

This issue was found during the review of the expression evaluator code in pr #1444.

**Comment by mrzzzrm** [comment]
Probably a good idea to add some queries containing division/mod zero to the SQLiteTestRunner
