### ISSUE TITLE
Remove (necessity to call) AbstractLQPNode::is_column_nullable() from JIT

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1451]
As discussed, the only place where we currently need to figure out the nullability of  an expression in the LQP is the JITAwareLQPTranslator (Strg+F "is_column_nullable"). 
We should consider removing this necessity and make the JIT obtain nullability of an expression during operator execution, when the input table and with it proper nullability information is available.

(The reason we/I want "AbstractLQPNode::is_column_nullable" removed is because it is a rather awkward setup necessary because outer joins might unexpectedly introduce nullability into otherwise non-nullable columns/expression. It consists of altogether 27 overrides of `AbstractExpression::on_is_nullable_on_lqp` and `AbstractLQPNode::is_column_nullable()` that should be removed if it is feasible to refactor the JIT as described above.)

**Comment by FabianWiebe** [comment]
@mrzzzrm The functionality `AbstractLQPNode::is_column_nullable` is not used anymore by JIT and can be removed from the JIT perspective.
