### ISSUE TITLE
ValueID inconsistencies and problems (fixed in #1626)

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1471]
When encoding a ValueSegment with 2^32 unique values we should get into trouble because the resulting dictionary would have a size of 2^32 and the DictionaryEncoder does `const auto max_value = dictionary.size() + 1u;` which is problematic since `max_value` is passed to `compress_vector()` which expects a `uint32_t`. In addition, we would have no way to indicate NULL or `INVALID_VALUE_ID` without overflow.

In addition, `INVALID_VALUE_ID` (i.e. `constexpr ValueID INVALID_VALUE_ID{std::numeric_limits<ValueID::base_type>::max()};`) is used to indicate that a certain value is not part of the dictionary and returned by `lower/upper_bound()` when no corresponding `ValueID` can be found. The size of the dictionary (i.e. the largest used ValueID for this particular segment + 1) is used to indicate NULL. Not only could we see cases where NULL and `INVALID_VALUE_ID` are indicated by the same number, but also does this seem inconsistent in general and could lead to some confusion. Especially since it should not break anything because of NULL semantics.

**Comment by Bensk1** [comment]
See also #1283

**Comment by mrks** [comment]
> When encoding a ValueSegment with 2^32 unique values [...]

That should never happen because of this:

```
  // The last chunk offset is reserved for NULL as used in ReferenceSegments.
  static constexpr ChunkOffset MAX_SIZE = std::numeric_limits<ChunkOffset>::max() - 1;
```

I'll still add an assertion.

> In addition, `INVALID_VALUE_ID` (i.e. `constexpr ValueID INVALID_VALUE_ID{std::numeric_limits<ValueID::base_type>::max()};`) is used to indicate that a certain value is not part of the dictionary and returned by `lower/upper_bound()` when no corresponding `ValueID` can be found. The size of the dictionary (i.e. the largest used ValueID for this particular segment + 1) is used to indicate NULL. Not only could we see cases where NULL and `INVALID_VALUE_ID` are indicated by the same number

Negative, same reason as above.

> (cont.), but also does this seem inconsistent in general and could lead to some confusion. Especially since it should not break anything because of NULL semantics.

I don't see any inconsistency here, as NULL will never be stored in the dictionary. We need INVALID_VALUE_ID so that we can do "smaller than every value in the dictionary" shortcuts. It is the caller's job to rule out NULL values whenever necessary. Example: https://github.com/hyrise/hyrise/blob/eca9c67e1efd461bde94aad47817fe130f9c2218/src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp#L117-L126
