### ISSUE TITLE
compare_benchmarks.py is heavily biased towards the "after" benchmark results

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1492]
Look at [this](https://gist.github.com/mrzzzrm/490398319555676a50cdc5b8c14c4054) benchmark output, +75% tx/s, sounds good, right? Except that this is only the average of the tx/s change where `+1000%` has a much higher impact than `-90%` except that, actually,  `-90%`  is about as bad as `+1000%` is good.

So this "average" should be a different measure, one that actually reflects whether the db performance increased or not.

**Comment by Bouncner** [comment]
But we should only change that if we maintain the six digit improvement over the first TPH-C benchmark run!

Good catch, never really thought about this number. Maybe switch away from percentage altogether?!? Same as percentage metric such as MAPE, there is an unfair lower bound.

**Comment by mrks** [comment]
Currently, our percentage value is (new/old - 1). For two queries where one doubles its performance and the second halfs it, this is +100% and -50% respectively. Our current script would output +25%.

How about we take the relative performance and calculate the average on that. This would be 2 and .5, resulting in an relative performance of 1. Only for displaying, we would subtract 1 and display it as 0%.

Need to keep an eye out for DIV/0.

**Comment by Bouncner** [comment]
Sounds reasonable to me, but I might even favor something else. The problem for me is, that 0.1 and 10 are somewhat hard to compare (at least without really thinking about it) for a 10x change.

Maybe use factors ( `max(throughput1,througput2) / min(throughput1,througput2)` ) that are posive for improvements and negative for throughput decreases? So it's a -10x for something getting 10x worst, and a 10x for something getting 10x better.

Average will be super easy as well.

**Comment by mrks** [comment]
Works for me.

**Comment by Bouncner** [comment]
@mrzzzrm : do you still have both json files? If so, could use gist/slack them to me?

**Comment by mrzzzrm** [comment]
I'm changing the format of the benchmark output JSON to include optimization times etc per query iteration in #1489 so I don't have files valid for the master at hand atm.

**Comment by mrzzzrm** [comment]
But anyway: Here is the file from #1489: https://gist.github.com/mrzzzrm/eaa81ed3b70935b71172560d6dab26a0
And here the one from the current master: https://gist.github.com/mrzzzrm/be4d6db94af82c229d1884a45b1ca6e5

1489->master: +123%
master->1489: +2%

**Comment by Bensk1** [comment]
> Works for me.

I agree.

**Comment by mrks** [comment]
> 1489->master: +123%
> master->1489: +2%

Nice!

```
while true
do
  git merge feature/cardinality_estimator_lenient_histograms
  git merge master
done
```

Infinite performance!

**Comment by Bouncner** [comment]
I am not really too happy with factors either, because they are less obvious.

![image](https://user-images.githubusercontent.com/1745857/53035847-ae813780-3476-11e9-9943-995af22e0217.png)

Please ignore the average. I still think factors are better, but I don't like that parsing the results is so much harder.

Would do you guys think about keeping percent changes without an average and further adding the factors with the (hopefully correct) average.

**Comment by Bouncner** [comment]
> How about we take the relative performance and calculate the average on that. This would be 2 and .5, resulting in an relative performance of 1. Only for displaying, we would subtract 1 and display it as 0%.

What would you aggregate and how do you get the result exactly? 2 and 0.5 wouldn't be 1?!?

**Comment by mrks** [comment]
https://www.youtube.com/watch?v=8b4n1CDuR64
