### ISSUE TITLE
IS NOT NULL and another predicate on the same column is redundant

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1494]
![image](https://user-images.githubusercontent.com/2679018/52787578-98cad700-305e-11e9-81ab-58f83c082b31.png)

`kind IS NOT NULL` is not necessary here, right? Because `kind != ....` has already thrown out the NULL values?

Maybe an optimizer should remove the IS NOT NULL scan then....

**Comment by mrks** [comment]
Correct. But how common is that? Should we really build a RemovePredicatesThatTheStupidUserUnnecessarilyInsertedRule?

**Comment by mrzzzrm** [comment]
I'd call it the DontLookStupidHyriseRule, which is short: https://github.com/hyrise/hyrise/issues/1186
