### ISSUE TITLE
TPCH Query Generator generates invalid parameters for TPCH 22

### ISSUE THREAD

**Issue by SvenLehmann** [hyrise/hyrise#1501]
For TPC-H Query 22, the `TPCHQueryGenerator` generates parameters that lead to empty intermediate results and most likely incorrect final results.

For the predicate `SUBSTR(c_phone,1,2) IN (?, ?, ?, ?, ?, ?, ?))`, the generator generates the following parameters `SUBSTR(c_phone, 1, 2) IN (13, 31, 21, 24, 27, 12, 26)`, which should be escaped strings `SUBSTR(c_phone, 1, 2) IN ('13', '31', '21', '24', '27', '12', '26')`.

I will follow up with a fix.
I haven't checked, though, whether this problem applies to other queries as well.

**Comment by Bensk1** [comment]
How did this get through verification?

**Comment by Bouncner** [comment]
Does SQL require to complain about the IN comparison between a string a some numbers?

**Comment by Bensk1** [comment]
By verification I didn't mean any checks in our code but the `--verify` flag that executes everything in Hyrise and SQLite and compares the results. But maybe SQLite does the same thing (return empty intermediate) results and then returns also the same final results as Hyrise.

**Comment by Bouncner** [comment]
That's what I meant.
