### ISSUE TITLE
Clang on MacOS generate useless ColumnVsColumns Scans

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1505]
I was loading CSV files on MacOS and (apart from its general sub-optimal performance) it was unexpectedly slow. I profiled the file-based benchmark and found the following unexpected `std::function`s:
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/1745857/53235205-95080780-3691-11e9-80de-73c7cb44d86a.png">

Talking to @mrks , he recommended to iterate over the `__atribute__` flags in the abstract table scan. The test was loading a wide table with 200 attributes and 5.000 lines. This is the result:
```
>> hot
(5000 rows; 213 ms 872 µs)
>> flatten
(5000 rows; 229 ms 432 µs)
>> aligned(256)
(5000 rows; 2 s 975 ms)
>> noinline
(5000 rows; 223 ms 752 µs)
>> hot, flatten
(5000 rows; 240 ms 930 µs)
>> hot, aligned(256)
(5000 rows; 3 s 105 ms)
>> hot, noinline
(5000 rows; 218 ms 414 µs)
>> flatten, aligned(256)
(5000 rows; 2 s 909 ms)
>> flatten, noinline
(5000 rows; 219 ms 708 µs)
>> aligned(256), noinline
(5000 rows; 3 s 198 ms)
>> hot, flatten, aligned(256)
(5000 rows; 3 s 445 ms)
>> hot, flatten, noinline
(5000 rows; 217 ms 472 µs)
>> hot, aligned(256), noinline
(5000 rows; 3 s 0 ms)
>> flatten, aligned(256), noinline
(5000 rows; 3 s 131 ms)
>> hot, flatten, aligned(256), noinline
(5000 rows; 3 s 171 ms)
```

So the `aligned(256)` flag appears to cause trouble.

**Comment by mrks** [comment]
Hmm. I don't think that that code is actually executed. Instruments is probably misrepresenting something, but the issue is still there. You ran ASAN on that same configuration, correct?

Does that happen on Linux as well? What happens if you increase/decrease the alignment?

Maybe some actually used code is co-located with the aligned code and is erroneously moved around in a way that the instruction cache does not like at all.

**Comment by Bouncner** [comment]
Yeah, it's apparently never really executed (lldb does not break) but there is still a somewhat significant runtime overhead.

Still running the other tests. GCC under Linux does not show anything similar and is fast on the current master. I have never worked with alignments, so that's something I'll might take a look at at the very end.

**Comment by Bouncner** [comment]
ASAN did neither complain on MacOS nor Linux.

**Comment by mrzzzrm** [comment]
So is this actually an issue or is XCode just buggy here?

**Comment by Bouncner** [comment]
The runtime is measurable so it is not just instruments. I am still on it.

**Comment by mrks** [comment]
If this is a clang issue, we should look into it.
If this is a Mach-O issue, I'd say we simply remove that attribute for OSX and continue with our lives. After all, it's only there to reduce the fluctuations due to differently aligned hot functions.

**Comment by mrzzzrm** [comment]
```
>> flatten
(5000 rows; 229 ms 432 µs)
>> aligned(256)
(5000 rows; 2 s 975 ms)
```

Bear with me, this is a otherwise unchanged master release/debug build loading csv files and all you're doing it changing attribute flags of a totally unrelated function (...in the AbstractTableScanImpl)? 

Does this happen with Linux and Clang (you already tested GCC and it didn't happen, right)?
Does overall (tpch, e.g.) benchmark perf decrease with `aligned(256)` or is it really just the CSVParser that suffers?

**Comment by Bouncner** [comment]
> Does this happen with Linux and Clang?

From what I remember it was solely Clang on MacOS, but I am guessing right now.

> Does overall (tpch, e.g.) benchmark perf decrease with aligned(256) or is it really just the CSVParser that suffers?

Haven’t measured it. :-/

**Comment by mrks** [comment]
Here's how long `load ../imdb_data/movie_info.csv mi` takes:

configuration | aligned | unaligned
--- | --- | ---
gcc 8.2 on ubuntu | 1m19.236s | 1m23.706s
clang 7.1 on ubuntu | 1m23.172s | 1m26.362s
clang 7.0.1 on OSX | 9m37.720s | 1m22.796s

(Based on 5050ff20f37ae0bc8626ac3ac3b7e5c1ca7c634a, The system was not 100% idle)

In total, the alignment seems to hurt the performance anyway. When I introduced it initially, I tested different configurations and [the current one was best](https://github.com/hyrise/hyrise/pull/1396).

```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.514372348785 | 31   | 0.493524551392 | 30   | -4%    |                          0.0000 |
| TPC-H 2   | 6.7894821167   | 408  | 6.58724546432  | 396  | -3%    |                          0.0000 |
| TPC-H 3   | 6.35070705414  | 382  | 5.74031448364  | 345  | -10%   |                          0.0000 |
| TPC-H 4   | 2.26171517372  | 136  | 2.22050094604  | 134  | -2%    |                          0.0000 |
| TPC-H 5   | 3.17908143997  | 191  | 3.1585586071   | 190  | -1%    |                          0.1198 |
| TPC-H 6   | 25.801864624   | 1549 | 24.9784870148  | 1499 | -3%    |                          0.0000 |
| TPC-H 7   | 1.25577676296  | 76   | 1.06687235832  | 65   | -15%   |                          0.0000 |
| TPC-H 8   | 3.69552755356  | 222  | 3.46070313454  | 208  | -6%    |                          0.0000 |
| TPC-H 9   | 1.2770383358   | 77   | 1.06027710438  | 64   | -17%   |                          0.0000 |
| TPC-H 10  | 2.69823265076  | 162  | 2.12393093109  | 128  | -21%   |                          0.0000 |
| TPC-H 11  | 19.1244335175  | 1148 | 19.0165061951  | 1141 | -1%    |                          0.0000 |
| TPC-H 12  | 6.6251168251   | 398  | 6.1342253685   | 369  | -7%    |                          0.0000 |
| TPC-H 13  | 2.13980698586  | 129  | 2.00433325768  | 121  | -6%    |                          0.0000 |
| TPC-H 14  | 19.7114009857  | 1183 | 16.4922504425  | 990  | -16%   |                          0.0000 |
| TPC-H 15  | 15.9331235886  | 956  | 13.0989141464  | 786  | -18%   |                          0.0000 |
| TPC-H 16  | 6.91763973236  | 416  | 6.8821644783   | 413  | -1%    |                          0.0137 |
| TPC-H 17  | 1.15024495125  | 70   | 1.04981637001  | 63   | -9%    |                          0.0000 |
| TPC-H 18  | 1.49797916412  | 90   | 1.46213686466  | 88   | -2%    |                          0.0035 |
| TPC-H 19  | 5.11680650711  | 308  | 4.762403965    | 286  | -7%    |                          0.0000 |
| TPC-H 20  | 1.89963114262  | 114  | 1.66741335392  | 101  | -12%   |                          0.0000 |
| TPC-H 21  | 0.422179222107 | 26   | 0.405038893223 | 25   | -4%    |                          0.0000 |
| TPC-H 22  | 12.8088855743  | 769  | 10.8093175888  | 649  | -16%   |                          0.0000 |
| average   |                |      |                |      | -8%    |                                 |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
```

Given the issues that we are seeing here, I'd suggest dropping the alignment, even if it might make the benchmark results a bit more jittery again. It's not like they are 100% stable right now, anyway.
