### ISSUE TITLE
Improve Fail() in assert.hpp (fixed in 1605)

### ISSUE THREAD

**Issue by julianmenzler** [hyrise/hyrise#1507]
As suggested by @mrks in https://github.com/hyrise/hyrise/pull/1462/files#r257565136:
> That was not what I meant. Have a look at assert.hpp. There, `Assert` builds the file/line/msg string and passes it to `Fail`. If we move that part to `Fail`, we would have line information for both asserts and fails. Only `assert.hpp` needs to change.

**Comment by mrks** [comment]
You mentioned problems with this. What is the issue?

**Comment by julianmenzler** [comment]
Well, this was a suggestion by you – not really an issue. I'd take care of it in March.
For details, see the comments referenced above.

**Comment by mrks** [comment]
This is what I meant: "Ok, I did not succeed in changing this right away."

**Comment by julianmenzler** [comment]
Well, this improvement is not a copy & paste job it seems. We probabably have to create a `Fail()` macro instead of a function to use the `__FILE__` and `__LINE__` macros. So that is why I postponed this.
