### ISSUE TITLE
SegmentIterators are not suited for standard algorithms

### ISSUE THREAD

**Issue by cmfcmf** [hyrise/hyrise#1512]
Working at #1394, we are currently refactoring the code to use the SegmentIterators instead of custom code for each segment. When a segment is sorted, we'd like to call `std::lower_bound` on the segment iterator. However, this currently leads to compile-time errors, because the iterators are not copy-assignable. 

Code example of what we try to achieve:
```cpp
auto segment_iterable = create_iterable_from_segment(typed_segment);
segment_iterable.with_iterators(position_filter, [&](auto begin, auto end) {
auto result = std::lower_bound(begin, end, 27);
});
```

Excerpt of the error message:

```
/home/Christian.Flach/hyrise/src/lib/storage/segment_sorted_search.hpp:39:12: error: use of deleted function 'opossum::ValueSegmentIterable<int>::PointAccessIterator& opossum::ValueSegmentIterable<int>::PointAccessIterator::operator=(opossum::ValueSegmentIterable<int>::PointAccessIterator&&)'
     _begin = std::lower_bound(_begin, _end, false,
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               [](const auto& segment_position, const auto& _) { return segment_position.is_null(); });
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/Christian.Flach/hyrise/src/lib/storage/create_iterable_from_segment.hpp:7,
                 from /home/Christian.Flach/hyrise/src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp:8:
/home/Christian.Flach/hyrise/src/lib/storage/value_segment/value_segment_iterable.hpp:167:9: note: 'opossum::ValueSegmentIterable<int>::PointAccessIterator& opossum::ValueSegmentIterable<int>::PointAccessIterator::operator=(opossum::ValueSegmentIterable<int>::PointAccessIterator&&)' is implicitly deleted because the default definition would be ill-formed:
   class PointAccessIterator : public BasePointAccessSegmentIterator<PointAccessIterator, SegmentPosition<T>> {
         ^~~~~~~~~~~~~~~~~~~
/home/Christian.Flach/hyrise/src/lib/storage/value_segment/value_segment_iterable.hpp:167:9: error: use of deleted function 'opossum::BasePointAccessSegmentIterator<opossum::ValueSegmentIterable<int>::PointAccessIterator, opossum::SegmentPosition<int> >& opossum::BasePointAccessSegmentIterator<opossum::ValueSegmentIterable<int>::PointAccessIterator, opossum::SegmentPosition<int> >::operator=(opossum::BasePointAccessSegmentIterator<opossum::ValueSegmentIterable<int>::PointAccessIterator, opossum::SegmentPosition<int> >&&)'
```

The `operator=` is implicitly deleted, because the `PointAccessIterator` (and almost all segment iterators) contains `const` members: 
https://github.com/hyrise/hyrise/blob/262ead52992bb61558d8e63a72510b08cb44b9fa/src/lib/storage/value_segment/value_segment_iterable.hpp#L195-L196

We thought of several possible solutions:
1. Making all members of all segment iterators non-const, so that they can be assigned in the `operator=`. This, however, also requires that the segments the iterators are created of are non-const.
2. Transforming all members `const T` into `std::shared_ptr<const T>`, so that the shared pointer can be assigned, but the underlying objects remain const.
3. Using `const_cast` in `operator=` to force-assign the values.

We don't like any of the options. Maybe you have an idea?

For now, we can also implement `std::lower_bound` and `std::upper_bound` in a way that doesn't require copy-assignment ourselves. But that certainly should only be an intermediary solution.

**Comment by mrzzzrm** [comment]
I think it would be very valuable for our segment iterators to be usable with the std::algorithms, i.e., for them to adhere to the [iterator requirements](https://en.cppreference.com/w/cpp/named_req) wherever possible.

E.g., we could implement our iterators just as the std iterators are implemented, by directly pointing into the underlying data structure. I'm going to have a quick look whether this might be possible.

**Comment by mrzzzrm** [comment]
I think it should be possible to refactor our iterators accordingly, but even if I make it a priority, it would probably take a day or two. What would be the best way for you to go forward @cmfcmf? Can you use your own impl of lower/upper_bound and we drop in the std:: algorithm once the refactoring is done? Or are there more (not so easy to reimplement) std algorithms that you need?

**Comment by cmfcmf** [comment]
> I think it should be possible to refactor our iterators accordingly, but even if I make it a priority, it would probably take a day or two.

Amazing 🎉 🎉 🎉 

> What would be the best way for you to go forward @cmfcmf? Can you use your own impl of lower/upper_bound and we drop in the std:: algorithm once the refactoring is done? 

Yes, that'll work for us. We're going to implement them now and report back if we face any problems.

**Comment by cmfcmf** [comment]
For reference, these are the custom versions we have implemented right now and need to remove once this issue is fixed: https://github.com/hyrise/hyrise/blob/cb9e2bd49439b602718c7c8094a8b43a1dd5e3df/src/lib/storage/segment_sorted_search.hpp#L31-L73
