### ISSUE TITLE
Benchmark plan visualization takes ages

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1513]
Generating plan visualizations for the JOB is a pain and takes literal hours. Could probably be done in parallel

**Comment by mrzzzrm** [comment]
This is a good opportunity to think about a thread pool system the works even when the scheduler is disabled for a benchmark

**Comment by mrks** [comment]
wtf? How many plans are there? What exactly is it that takes so long?

**Comment by mrzzzrm** [comment]
113 queries and two visualizations (LQP + PQP) per query. Might be a mixture of the graphviz renderer and the cardinality (urrghs, always) estimations done during visualization. Benchmarking is running, but have to leave now.

**Comment by mrzzzrm** [comment]
I think it's the recursive Cardinality Estimation during the LQP visualization:

```
   Running renderer took 29 ms 373 µs
LQP Visualization took 2 s 796 ms
   Running renderer took 33 ms 484 µs
PQP Visualization took 39 ms 282 µs
```

"Running renderer" is the graphviz call. After #1489 we can active a CardinalityEstimationCache during visualization and all should be fine

**Comment by mrzzzrm** [comment]
After #1489 visualization of all JOB plans takes ~6 Minutes which should be fine for now, given the size of the issue list. But we should come back to this once we have a scheduler-independent job system.
