### ISSUE TITLE
Run Length encoding and SIMDBP128 compression can't handle empty integer segments

### ISSUE THREAD

**Issue by janehmueller** [hyrise/hyrise#1522]
In #1521 a test for the encoding of empty integer segments is added. This causes a segfault for both the Dictionary- and Frame Of Reference-Encoding with SIMDBP128 compression as well as the Run Length Encoding.

**Comment by mrzzzrm** [comment]
As mentioned in the PR

> @janehmueller I was able to reproduce a bug in the RunLengthEncoder as well as LZ4 - the SIMDBP128 doesn't creash for me when compressing an empty Segment. Can you provide a compilable, crashing test/playground for this problem?

**Comment by mrzzzrm** [comment]
#1528 will fix this, but is blocked by #1521 fixing the same problem for LZ4

**Comment by mrks** [comment]
#1521 should now contain both.
