### ISSUE TITLE
Sort-Merge Join cannot compare float with double

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1529]
**Query**
```sql
SELECT *
FROM orders
JOIN (
  SELECT SUM(o_totalprice) s
  FROM orders
) order_price_sum
ON o_totalprice <= order_price_sum.s;
```

**Actual behavior**
It crashes:
`src/lib/operators/join_sort_merge.cpp:64 Left and right column types do not match. The sort merge join requires matching column types`

**Expected behavior**
The query should return all orders.

**Explanation**
`o_totalprice` is a `float`, while `SUM(o_totalprice)` is a `double`. The sort-merge join should be able to handle this.

**Comment by mrzzzrm** [comment]
We should not support float-vs-double joins, they are just too error prone: `3.1 != 3.1f`, but `3.0 == 3.0f`. The issue as described in the OP, however, also occurs for int-vs-long.

**Comment by mrks** [comment]
I feel like we should have a general discussion about this in the next fortnightly. Maybe we should just introduce a `Cast` operator (which many databases have) and let operators such as the join deal with well-defined types only.

**Comment by mrzzzrm** [comment]
Writing this on my pester-markus-with-this-next-week list in this very moment ;)

**Comment by Bouncner** [comment]
@mrzzzrm : did we agree that the Hash Join type traits can be removed?

If I remember correctly, we agreed to remove the ability to join non-equal types?

**Comment by mrzzzrm** [comment]
cannot be removed, yet, but I think @mrks and me agreed operators shouldn't handle multiple column types for one predicate. But this is quite a refactor, I think.

**Comment by mrks** [comment]
Can't remember if we reached a final decision on that. Unless we positively know that we won't need those for the TPC-DS or we have an alternative in place, I'd wait for a second. Ultimately, some type of cast operator would be better, but that will require changes all over the place.

**Comment by mrzzzrm** [comment]
Will add fallback to JNL for otherwise unsupported join predicates after #1577
