### ISSUE TITLE
Compile times are through the roof (again)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1534]
Single threaded build times:

Commit | Clang-Debug | Clang-Release
------ | ----------- | -------------
9cdd14dde Compile time: Don't instantiate  (#1628) | 30m1,058s | 56m24,493s 
d65e68134 Update ExpressionReductionRule  | |
f9b8de0ad Make LIKE rewrite emit a  (#1638 | |
36910944e Naming: Add 'Segment' to FoR- and (#1639) | |
486f145f1 CI for Mac (#1637) | |
2c75839dd Fix multi-threaded multi-predicate join (#1625) | |
298cfa517 Clarify INVALID_VALUE_ID (#1626) | |
346ca70b6 Remove print in test (#1634) | |
30fb1df47 Print: Remove handling of empty chunks (#1629) | |
d36f9c424 Fix lossless tests on OS X (#1630) | |
eca9c67e1 Safer handling of cross-type operations with lossless | |
01bee9b17 TPC-H 6: Calculate discount only once (#1624) | |
e86add934 Remove scan alignment (#1621) | |
52c8a7f8e Enable TSan for NUMA builds (#1618) | |
560df6656 Use indexes for SQLite verification of join order ben | |
ac4e44549 Create resources link only once (#1620) | |
09ce0cff7 Remove unused return value of  | |
beb1e0adb Add new Between modes to ColumnStatistics (#1616) | |
0aeda11d6 Improve benchmark script (#1584) | 30m28,065s |  59m35,528s
771c5b4fe Add IF EXISTS support for DROP TABLE and DROP |  | 
5f048d3b3 Fix btree_index_test for libc++ (#1612) |  | 
89f2824a9 Fix TPC-H for larger scale factors  (#1608) |  | 
43d2b5460 Cmake: add link to resources (#1604) |  | 
8d5e2a487 Fix MVCC performance regression, fix MVCC data |  | 
5050ff20f Print file/line info for Fail() (#1605) |  | 
055b1fba4 Unified handling of operator<<(std::ostream, . |  | 
2628fbfd0 Compile time: More type erasure in ColumnVsCol |  | 
0222b0e3b JoinHash for semi/anti: Insert values just onc |  | 
0065b2530 Better documentation for --table_path option ( |  | 
6943c012c Fix make clean (#1594) |  | 
31aea916a Between: Make order of inserted predicates det |  | 
0ab91cf34 Fix Multi-threading support for Insert (#1585) |  | 
00c87d129 Fix master: Last JIT commit did not know about |  | 
8830d4243 [DYOD18/19] Between Composition Rule (#1481) |  | 
cc29edb1a EXPECT_LQP_EQ now requires a semicolon as well |  | 
7d6fd6882 [JIT] Correct default value of ENABLE_JIT_SUPP |  | 
f0d316cb0 [DYOD18/19] Subquery to Join Reformulation (#1 |  | 
d789437e4 Update SQLParser, support expressions in LIMIT |  | 
40899a2d4 Fix CI build that claimed to be Release, but w |  | 
3fa9885d2 Make Assert() and DebugAssert() require semico |  | 
8df96d507 [JIT] Add dictionary support for jittable tabl |  | 
555fc8acc [JIT] Add option to use JIT in console and ben |  | 
209facc4f Remove unnecessary getters and setters in jit |  | 
f6570f57f [DYOD18/19] Add LZ4 test for (de)compressing w |  | 
d6f534359 [DYOD18/19] Add LZ4 Point Access (also fixes # |  | 
6ef2a548b Use implicit pointer/optional-bool conversion |  | 
38aab7f2d Replace boost::variant with std::variant in Li |  | 
94a1bc42d [JIT] Correct div/mod by zero (issue #1450) (# |  | 
45572121e [DYOD18/19] Sort-based aggregate Operator (#14 |  | 
09f574a42 FileBasedBenchmark, JOB: Support -q (#1564) |  | 
effcfb611 JoinNestedLoop: MultiPredicate- and Semi/Anti- |  | 
95561eca4 [DYOD18/19] Multi Predicate Join Support (#148 |  | 
1dc7ac96d Add test queries verifying that #1527 was fixe |  | 
fbf7479d9 [DYOD18/19] Like Replacement Rule (#1480) |  | 
a3a5c4c6b Reduce JoinNestedLoop compile time (#1543) |  | 
bf7aac4c6 Remove obsolete docs for Join operators (#1545 |  | 
4595b6728 Fix SortMerge/NestedLoop joins for Outer Joins |  | 
7081afb2f Add auto completion for visualize and setting |  | 
14f01fa5 [DYOD18/19] MvccDeletePlugin prep)  (#1468) | 28m14,021s | 57m47,161s
b6d911b9 Speed up Segment write-out  (#1539) |  | 
cc3f6bb7 Reduce ColumnVsColumnScan compile time (#1537)|  | 
a3febac29 [DYOD18/19] Sorted Chunks | 28m40,163s | 68m28,928s
b24a11433 Finer grained benchmark metrics |  | 
1665144f6 Remove JitBaseSegmentIterator  | 28m11,800s | 66m9,670s
98c1144c7 [DYOD18/19] MvccDeletePlugin  |  | 
5998cf202 Remove tpch_tbl_header.py (# |  | 
c299f63b8 Rewindable segment iterators (#1517 |  | 
b43db124b Allow ChunkPruningRule to prune past non | 28m11,441s | 65m52,163s
ef5bdf2de Strict EXPECT_LQP_EQ to avoid mistakes in  |  | 
951d8a6eb Force erasure of LZ4Segment (# | 28m11,162s | 65m48,969s
72aeb2063 Make Segment iterators LegacyForwardIterator compatible ( | 28m9,706s | 65m5,096s
170e91b59 Add missing Ascending/DescendingNullsLast to  | 28m6,266s | 60m4,149s0
61c53bc45 [DYOD18/19] Add LZ4  | 28m6,664s | 60m4,251s
e24c7a170 Introduce pmr_string (#1506) | 27m50,169s | 55m21,758s
ca2d13953 JIT Improve JitExpression Evaluation (# |  | 
be0436ac3 Retire NUMAPlacementManager (#1508) |  | 
ca5f3093d Compare Benchmarks: Handle mismatching names  |  | 
e6cae0b87 Fixes incorrect parameter generation for TPCH  |  | 
95d3d3044 LQP Utils: Correct order of  |  | 
eecc9bd4b Remove obsolete comment in SQLiteTestrunnerTest ( |  | 
451798b93 Include all symbols when linking against  |  | 
02b0752d3 Rewrite IN expression to equality check  |  | 
a6b8ad43d Retire JoinDetectionRule (#1487) |  | 
ac1c117e5 move test file to resource ( |  | 
93370954c JIT - Enable outputting table data  |  | 
de5556f3b Index join: change pos list  |  | 
cf5c0c3fe Fix ColumnPruningRule for Insert and Delete  |  | 
118d8b680 Optimizer: store rules as unique_ptr  |  | 
0bf7d52ef SIMD support, Take 2 ( | 28m1,603s | 55m36,623s
fc0a240fc JIT - Add parameter support for  | 27m55,223s | 48m57,113s0
3a1bca53a Fix query_analyzer.stp and remove  |  | 
f01fcd08f Fix SQLite verification on subset of  |  | 
c0d59dddd Fix concurrent access to _chunks  |  | 
9411a0816 Worker sleep times (Follow- |  | 
d253c8ff3 Call false without path to binary  |  | 
cd7d40fc5 Add TPC-H example query  |  | 
0b13a0366 Fix ASAN issue in sort- |  | 
4f2dc8634 Reduce hyriseTest runtime (#1459 |  | 
aa6b27bf9 Fail if config or build step  |  | 
c795db7b2 compare_benchmarks.py: fix " |  | 
2c496e18e Rename querys to queries (# |  | 
05f194fd0 Only link libhyrise against CMAKE_DL_LIBS.  |  | 
d96c5ca71 Fix jemalloc linking under OS X  |  | 
29fb9097d Rename SelectExpression to SubqueryExpression (# |  | 
568c6a4b7 Fix nullability of columns from null |  | 
bb071f97a Add jittable Limit Operator (# |  | 
5512fe08b Replace default memory allocator with jemalloc  |  | 
b42aef7c6 Add optimization rule to add a  |  | 
374b81493 Proper libHyrise linking for plugins ( |  | 
e9036384d Fail on unsupported outer join ( |  | 
9ed00f6be Delete only visible rows (# |  | 
a26145c59 Fix Delete'ing from pruned  |  | 
d803736e0 Fix sampling in sort-merge  |  | 
26bb16e81 Aggregate: Use accessors, not  |  | 
031fd22e4 Fix Pagination CTRL+C behaviour  |  | 
f345117e9 Fix sort merge join when joining  |  | 
2f86c2422 Fix NULL behavior (#1421)  |  | 
9a60098b0 TPC-H-based micro  |  | 
92f810644 Reduce compile time of Aggregate (# | 25m55,285s | 46m52,449s
f40ab80e9 Reduce compile time of ColumnVsColumnTableScanImpl (# |  | 
b77b20994 Reduce compile time of ExpressionEvaluator (# |  | 
617675d4c Fix logging whether tables were encoded  |  | 
98469e13c Fix SQLiteWrapper loading for special chars  |  | 
608b44c07 Add encodings to Console and Print  |  | 
3581f3431 Improve handling of uncorrelated subselects (# |  | 
bc2b55df2 Add transaction context assert to forbid  |  | 
e937123a4 Moved and cleared up hash join  |  | 
73aea137b Add iterators to cache implementations (# |  | 
331ebeb0c Faster type erasure for iterators (# |  | 
1edf561f4 Fix plugin unload behaviour. (# |  | 
47c11e060 Fix cmake include path for TargetLinkLibrariesSystem  |  | 
e8bc9fe08 monotonic_buffer_resource for Aggregate result map (# |  | 
b13713a90 Remove --verbose, cleanup output  |  | 
d899b601f WIP: Improve table scan alignment  |  | 
d89126466 Update join_order_benchmark.cpp (# |  | 
b4a8c8092 Make TPC-H Generation  |  | 
1246378f7 Supports loading of different table  |  | 
6930b35e6 memcheck: remove leak check  |  | 
bb5925600 Randomize TPC-H,  |  | 
a6c9d5f54 Join Order Benchmark (#1391 |  | 
1bdbae195 Fix NotEquals scan on Dictionaries  |  | 
224492076 Reverse check if tasks are  |  | 
444080068 Console: Override tables when  |  | 
cb1477b4d Add visualization artifacts to . |  | 
880456c1d Fix link for build status  |  | 
d63c7d570 Benchmarks: Option to cache  |  | 
7f903804b Change keepRunning to range for  |  | 
bf73bdb0b ColumnVsValueScan: Fix MatchesAll optimization  |  | 
0bc175be9 Change TPC-H to  |  | 
c68a02114 More type erasure for AnySegmentIterable  | 25m35,743s | 56m35,150s
20306efeb Fix EvaluateToPosList for uncorrelated EXISTS  |  | 
8f802db8d Reduce clutter in project root  |  | 
4c57c0683 Different classes for Placeholders and  |  | 
25ebcc369 Disable ServerTestRunner (#1372) |  | 
350dbc459 Fix/unrandomized range filter  |  | 
f3ec2460d Remove build-essential from  |  | 
5e805fde0 Generate comparative graphs for multi |  | 
493fb8bd6 Change hashing in Counting Quotient  |  | 
5c0e5e6a8 Skip SchedulerTest.VerifyTaskQueueSetup on  |  | 
12c851b35 DictionarySegment scan early out with  |  | 
95c4f1984 Faster CSV loading (#1355 |  | 
682847ee9 Fix check for PR (# |  | 
98e177862 Remove unnecessary TearDowns, doc  |  | 
f95bacaf6 Improve testing, handle isNull |  | 
fdd2eacad Fix deleting zero rows (# |  | 
ed1197ce0 Jenkins: Really fix the  |  | 
a9464ea41 Jenkins: Fix master build  |  | 
e6ca6c8aa Retire iterative Optimizer architecture (# |  | 
22a8b02b9 Update googletest, use GTEST_SKIP  |  | 
b97aba022 Do not build PRs of  |  | 
fd9408023 Benchmarks: When using global  |  | 
1c72d09e0 Only build a topology of  |  | 
5859b5bf4 Fix TableTest (#1338) |  | 
f3e17f07a No more SOURCE_FILE_SIZE (#1335 |  | 
70fc9018c Use configure_file to generate jit_llvm_bundle |  | 
061da49ab Rename IS_DEBUG to HYRISE_IS_DEBUG (# |  |

**Comment by mrks** [comment]
Uuuh, most likely, the SIMD scan is to blame. I'm up for anything that reduces that compile time without sacrificing (too much) scan performance.

**Comment by mrzzzrm** [comment]
Not so sure, JNL and ExpressionEvaluator increased as well, and they don't use SIMD.
https://github.com/hyrise/hyrise/pull/1337#discussion_r238182754

**Comment by Bouncner** [comment]
Does the JNL increase with the “AnySegmented” LZ4 segments?

**Comment by mrzzzrm** [comment]
It should have, the question is how much. I'm binary searching through the commit log manually now.

(...and am convinced to the core that we absolutely need a Benchmarking CI)

**Comment by mrzzzrm** [comment]
"Make Segment iterators LegacyForwardIterator compatible" = +5 Minutes
"Add LZ4" = +5 Minutes
"SIMD support, Take" = +7 Minutes

**Comment by mrzzzrm** [comment]
Worst offenders (pella, clang, -j1, release), even after #1537 
```
column_vs_column_table_scan_impl.cpp.o: 14.6MiB 316.048s
column_vs_value_table_scan_impl.cpp.o: 7.5MiB 276.056s
join_nested_loop.cpp.o: 4.6MiB 273.552s
expression_evaluator.cpp.o: 11.9MiB 223.542s
aggregate.cpp.o: 6.7MiB 114.523s
join_hash.cpp.o: 5.0MiB 85.167s
column_between_table_scan_impl.cpp.o: 1.4MiB 56.229s
jit_read_tuples.cpp.o: 2.1MiB 54.118s
column_like_table_scan_impl.cpp.o: 1.5MiB 51.884s
column_is_null_table_scan_impl.cpp.o: 1.2MiB 48.044s
join_index.cpp.o: 1.3MiB 40.22s
join_sort_merge.cpp.o: 1.6MiB 37.084s
segment_statistics.cpp.o: 874.7KiB 35.939s
join_mpsm.cpp.o: 1.5MiB 33.572s
any_segment_iterable.cpp.o: 1.9MiB 33.496s
server_session.cpp.o: 4.1MiB 33.296s
```

**Comment by mrks** [comment]
As discussed in #1573, we could also look into selectively type-erasing certain encodings. For people who are not working on encoding-related stuff, dictionary encoding is sufficient. By erasing all other types even in release mode, we could save some compile time.

**Comment by mrks** [comment]
The `_scan_generic_segment` methods look like they should rule out reference and dictionary segments, as those are handled by other methods. The compiler doesn't know that, so an `if constexpr` should save us some time there.

**Comment by mrzzzrm** [comment]
Update first post, 2min compile time increase in the last 5 weeks.

**Comment by mrzzzrm** [comment]
Updated first post. Moving in the right direction, still substantially slower than we once were

**Comment by mrks** [comment]
> still substantially slower than we once were

We should be realistic here. Every minute we save is good, but we will not return to building the project in a minute.

**Comment by mrks** [comment]
However, I'm surprised to see that the last commit changed only so little. :(

**Comment by mrks** [comment]
I don't think there is anything actionable in here right now. We should keep the compile time in mind and try to reduce it, but for now I'd close this.
