### ISSUE TITLE
RangeFilter not available for string

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1536]
```c++
static_assert(std::is_arithmetic_v<T>, "RangeFilter should not be instantiated for strings.");
```

Do you know why @Bouncner ?

**Comment by Bouncner** [comment]
Range Filters optimize for the gap sizes (maximize) between the histogram bins. Back in the days, we did not have a clue how to determine distances between strings.

Now with Tim’s work, that should actually be possible. Good point.
I can take a look at it if you want.

**Comment by mrzzzrm** [comment]
Not urgent, but there is some special handling in #1489 because of this which could be removed if RangeFilter were available for all types.

**Comment by mrks** [comment]
Make sure you don't miss this part:
https://github.com/hyrise/hyrise/blob/51edfa5dcc7fd34d67cc79b885474802bfa81d99/src/lib/optimizer/strategy/chunk_pruning_rule.cpp#L181

**Comment by Bouncner** [comment]
We won't implement range filters any time soon for strings.
