### ISSUE TITLE
ExpressionEvaluator should work independently of Chunk size

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1538]
(Mostly note to self)

Consider `l_extendedprice*(1-l_discount)*(1+l_tax)`. When computing this expression on a Chunk, the ExpressionEvaluator will first materialize the three columns and then compute the result of the "expression tree" from the bottom up. 
This materialize-the-complete-segment-then-start-computing approach will probably produce a lot of cache traffic if the materialized segments plus the size of the temporary expression results (e.g. `(1-l_discount)`) don't fit in L1 (or L2?).

I have quickly tested this particular expression and (barring any errors I made, the rows/µs seems very high to me), while a Chunk size of 100'000, as we currently use it, is still okay, performance drops significantly for larger Chunks:

```
BlockSize: 500: 470510176 rows processed in 5000003us. 94 rows per us
BlockSize: 1000: 688374659 rows processed in 5000007us. 137 rows per us
BlockSize: 4000: 986448088 rows processed in 5000014us. 197 rows per us
BlockSize: 4500: 997708772 rows processed in 5000004us. 199 rows per us
BlockSize: 5000: 980407746 rows processed in 5000009us. 196 rows per us
BlockSize: 6000: 981924417 rows processed in 5000015us. 196 rows per us
BlockSize: 7000: 893037287 rows processed in 5000012us. 178 rows per us
BlockSize: 8000: 929738339 rows processed in 5000023us. 185 rows per us
BlockSize: 9000: 937994352 rows processed in 5000049us. 187 rows per us
BlockSize: 10000: 835098538 rows processed in 5000020us. 167 rows per us
BlockSize: 50000: 849406893 rows processed in 5000184us. 169 rows per us
BlockSize: 100000: 780914460 rows processed in 5000178us. 156 rows per us
BlockSize: 1000000: 670926633 rows processed in 5006402us. 134 rows per us
BlockSize: 2000000: 623931568 rows processed in 5000499us. 124 rows per us

```

[code](https://gist.github.com/mrzzzrm/3443f17ce012a55e604dfecc3366315f)

Imo the ExpressionEvaluator should ignore the Chunk size and process expressions in blocks (think: Sub-Chunks) of a size that depends on both L1 or L2 size and the "size" of the expression itself.

**Comment by Bouncner** [comment]
Don’t know much about the expression evaluation, but the current approach you describe with “first materialize, the calculate” sounds highly sequential. Where do you think the cache comes into play?

**Comment by mrzzzrm** [comment]
The problem is that we're materializing 100Ks of values. By the time we have materialized the last one and start doing calculations with the first one, the first one will have already left the upper caches. At least so would be my speculation. And to speculate even further: I have a L1 of 128KB and we need 28 Bytes per row in the example expression for segment values and temporary values - this somewhat alignes with the throughput peak at 4k-6k rows per "block"

**Comment by Bouncner** [comment]
Sounds like MonetDB’s vectorized processing.
I am surprised that it makes such a difference as it is purely sequential.

**Comment by mrks** [comment]
When profiling the ExpressionEvaluator, I repeatedly found that _materialize_segment_if_not_yet_materialized is the most expensive step. That would not improved by this change. Moving this to Trello, as it is not an optimization that we will work on any time soon.
