### ISSUE TITLE
Use SIMD scans more selectively to reduce compilation time

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1540]
Commenting out `_simd_scan_with_iterators` leads to several minutes of saved compile time. 

**Before**

TableScanImpl | With SIMD | Without SIMD  | SIMD impact
------ | ----------- | ------------- | -------------
column_vs_column_table_scan_impl.cpp.o | 14.7MiB 314.205s | 9.4MiB 123.244s | +191s
column_vs_value_table_scan_impl.cpp.o | 7.5MiB 276.272s | 5.8MiB 212.714s  | +65s
column_between_table_scan_impl.cpp.o | 1.4MiB 56.121s | 1.1MiB 43.714s | +12s
column_is_null_table_scan_impl.cpp.o | 1.2MiB 48.143s | 873.8KiB 37.239s | +11s
column_like_table_scan_impl.cpp.o | 1.1MiB 41.312s | 1.1MiB 39.892s | +1s

**After #1578?** (Same order as above, though ranking has changed)

TableScanImpl | With SIMD | Without SIMD | SIMD impact
------ | ----------- | ------------- | -------------
column_vs_column_table_scan_impl.cpp.o | 8.5MiB 207.142s | 6.2MiB 110.117s | +97s
column_vs_value_table_scan_impl.cpp.o | 8.0MiB 296.315s | 6.3MiB 232.329s | +64s
column_between_table_scan_impl.cpp.o | 3.1MiB 111.343s | 1.9MiB 68.728s | +43s
column_is_null_table_scan_impl.cpp.o | 1.2MiB 50.313s | 906.1KiB 38.034s | +12s
column_like_table_scan_impl.cpp.o | 1.6MiB 58.838s | 1.2MiB 46.49s | +12s

* Are we sure SIMD is beneficial for ColumnVSColumn at all?  *I'd keep it (see below) ~MD*
* <s>We instantiate SIMD for string columns afaict, are we sure this is beneficial?</s> (see below)
* What about SIMDBP128 compressed attribute vectors? *Inconclusive (see below) ~MD*
* <s>std::vector<bool> for nulls?</s> (unclear, see below)
* <s>Non-sequential access, i.e. when a position_filter is present?</s> (very beneficial, see below)

Do we need SIMD for all these cases? Can we maybe only activate it cases were we are very sure the performance benefit justifies the compile time increase?

**Comment by mrks** [comment]
> Non-sequential access, i.e. when a position_filter is present?

In this case: Yes, I have measured that a while back and have seen improvements even beyond the first table scan in TPC-H query 6.

**Comment by mrks** [comment]
Non SIMDying string comparisons saves us one minute in the ColumnVsColumnScan, but is bad for the unencoded TPC-H performance:

```
Time taken to compile from scratch on nemea, gcc 8, all cores

d8a3a44920f4e61d9109aff50150cce97d050c01 (Type-erase the accessor in type-erased reference segments, erase more aggressively in ColumnVsColumnScan)
real    5m35,670s
user    82m8,795s
sys     12m35,370s

57b3c68a8dc33ce6bd1973f8892c26e05348393d (Don't use SIMD scan for strings)
real    4m24,367s
user    78m56,167s
sys     12m22,081s
```

```
+-----------+------------------+------+------------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s     | runs | new iter/s       | runs | change | p-value (significant if <0.001) |
+-----------+------------------+------+------------------+------+--------+---------------------------------+
| TPC-H 1   | 0.512034535408   | 31   | 0.523402273655   | 32   | +2%    |                          0.0477 |
| TPC-H 2   | 1.48223984241    | 89   | 1.45583701134    | 88   | -2%    |                          0.0665 |
| TPC-H 3   | 4.54435777664    | 273  | 4.32564401627    | 260  | -5%    |                          0.0000 |
| TPC-H 4   | 2.00598359108    | 121  | 1.98978388309    | 120  | -1%    |                          0.1314 |
| TPC-H 5   | 4.01064014435    | 241  | 3.89064526558    | 234  | -3%    |                          0.0000 |
| TPC-H 6   | 8.35738372803    | 502  | 7.04914331436    | 423  | -16%   |                          0.0000 |
| TPC-H 7   | 1.24535226822    | 75   | 1.22694957256    | 74   | -1%    |                          0.0007 |
| TPC-H 8   | 5.22135019302    | 314  | 5.20826292038    | 313  | -0%    |                          0.6311 |
| TPC-H 9   | 1.72009003162    | 104  | 1.76310300827    | 106  | +3%    |                          0.0000 |
| TPC-H 10  | 2.40260481834    | 145  | 2.31737828255    | 140  | -4%    |                          0.0000 |
| TPC-H 11  | 33.7463607788    | 2025 | 34.2645568848    | 2056 | +2%    |                          0.0000 |
| TPC-H 12  | 2.93853712082    | 177  | 2.71927690506    | 164  | -7%    |                          0.0000 |
| TPC-H 13  | 2.56644129753    | 155  | 2.56237220764    | 154  | -0%    |                          0.7639 |
| TPC-H 14  | 6.33503246307    | 381  | 5.27993297577    | 317  | -17%   |                          0.0000 |
| TPC-H 15  | 3.49922800064    | 210  | 2.74918746948    | 165  | -21%   |                          0.0000 |
| TPC-H 16  | 6.77251577377    | 407  | 6.48462295532    | 390  | -4%    |                          0.0000 |
| TPC-H 17  | 0.0227144174278  | 2    | 0.0218374729156  | 2    | -4%    |        (not enough runs) 0.5472 |
| TPC-H 18  | 1.97770226002    | 119  | 1.92807173729    | 116  | -3%    |                          0.0050 |
| TPC-H 19  | 2.7752392292     | 167  | 2.53921175003    | 153  | -9%    |                          0.0000 |
| TPC-H 20  | 0.0159646179527  | 1    | 0.0155624579638  | 1    | -3%    |           (not enough runs) nan |
| TPC-H 21  | 0.00192877650261 | 1    | 0.00166365003679 | 1    | -14%   |           (not enough runs) nan |
| TPC-H 22  | 11.1300516129    | 668  | 11.137506485     | 669  | +0%    |                          0.5045 |
| average   |                  |      |                  |      | -5%    |                                 |
+-----------+------------------+------+------------------+------+--------+---------------------------------+
```

**Comment by mrks** [comment]
> std::vector for nulls?

What do you mean?

**Comment by mrzzzrm** [comment]
Don't know, didn't remember anything when looking at the SIMD scan.

**Comment by mrks** [comment]
** Are we sure SIMD is beneficial for ColumnVSColumn at all? **

```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.595511674881 | 36   | 0.620906829834 | 38   | +4%    |                          0.0000 |
| TPC-H 2   | 8.30933952332  | 499  | 8.50214767456  | 511  | +2%    |                          0.0000 |
| TPC-H 3   | 6.53850317001  | 393  | 6.64727497101  | 399  | +2%    |                          0.0000 |
| TPC-H 4   | 3.14941859245  | 189  | 3.04922533035  | 183  | -3%    |                          0.0000 |
| TPC-H 5   | 4.31633281708  | 260  | 4.34820413589  | 262  | +1%    |                          0.2591 |
| TPC-H 6   | 29.3708209991  | 1763 | 29.1742172241  | 1751 | -1%    |                          0.0000 |
| TPC-H 7   | 1.39644372463  | 84   | 1.38247144222  | 83   | -1%    |                          0.0472 |
| TPC-H 8   | 5.52601718903  | 332  | 5.57868003845  | 335  | +1%    |                          0.2515 |
| TPC-H 9   | 1.61903071404  | 98   | 1.63329207897  | 98   | +1%    |                          0.0814 |
| TPC-H 10  | 3.01883077621  | 182  | 2.96372294426  | 178  | -2%    |                          0.0000 |
| TPC-H 11  | 33.5126876831  | 2011 | 33.3788719177  | 2003 | -0%    |                          0.0038 |
| TPC-H 12  | 10.4763860703  | 629  | 10.0025978088  | 601  | -5%    |                          0.0000 |
| TPC-H 13  | 2.33310866356  | 140  | 2.31912946701  | 140  | -1%    |                          0.3132 |
| TPC-H 14  | 25.7622795105  | 1546 | 26.7819328308  | 1607 | +4%    |                          0.0000 |
| TPC-H 15  | 20.4020729065  | 1225 | 20.1690769196  | 1211 | -1%    |                          0.0000 |
| TPC-H 16  | 7.80176973343  | 469  | 7.78776597977  | 468  | -0%    |                          0.3310 |
| TPC-H 17  | 1.39347290993  | 84   | 1.33050465584  | 80   | -5%    |                          0.0000 |
| TPC-H 18  | 1.94859564304  | 117  | 1.99042415619  | 120  | +2%    |                          0.0193 |
| TPC-H 19  | 5.78491973877  | 348  | 5.85377883911  | 352  | +1%    |                          0.0001 |
| TPC-H 20  | 2.03546261787  | 123  | 2.00495672226  | 121  | -1%    |                          0.0000 |
| TPC-H 21  | 0.49018278718  | 30   | 0.460757762194 | 28   | -6%    |                          0.0000 |
| TPC-H 22  | 13.621846199   | 818  | 13.3695373535  | 803  | -2%    |                          0.0000 |
| average   |                |      |                |      | -0%    |                                 |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
```

ColumnVsColumn is used here:
```
Markus.Dreseler@nemea:~/hyrise3/build-release$ grep -r ColumnVsColumn *.dot
TPC-H_12-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_12-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_21-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_21-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_4-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_5-PQP-0.dot:Impl: ColumnVsColumn
TPC-H_9-PQP-0.dot:Impl: ColumnVsColumn
```

For queries where ColVsCol is an important operator, there are some benefits. Not a lot, but since #1578 made the compile time linearly dependent on the number of segment types and similar to ColVsValue, I'd keep it.

**Comment by mrks** [comment]
** Non-sequential access, i.e. when a position_filter is present? **

```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.595511674881 | 36   | 0.597884058952 | 36   | +0%    |                          0.6022 |
| TPC-H 2   | 8.30933952332  | 499  | 8.32709598541  | 500  | +0%    |                          0.3215 |
| TPC-H 3   | 6.53850317001  | 393  | 6.43136024475  | 386  | -2%    |                          0.0000 |
| TPC-H 4   | 3.14941859245  | 189  | 3.10268902779  | 187  | -1%    |                          0.0000 |
| TPC-H 5   | 4.31633281708  | 260  | 4.1691365242   | 251  | -3%    |                          0.0000 |
| TPC-H 6   | 29.3708209991  | 1763 | 23.562122345   | 1414 | -20%   |                          0.0000 |
| TPC-H 7   | 1.39644372463  | 84   | 1.37077927589  | 83   | -2%    |                          0.0000 |
| TPC-H 8   | 5.52601718903  | 332  | 5.58546924591  | 336  | +1%    |                          0.2094 |
| TPC-H 9   | 1.61903071404  | 98   | 1.62064385414  | 98   | +0%    |                          0.7945 |
| TPC-H 10  | 3.01883077621  | 182  | 2.93961191177  | 177  | -3%    |                          0.0000 |
| TPC-H 11  | 33.5126876831  | 2011 | 32.9601707458  | 1978 | -2%    |                          0.0000 |
| TPC-H 12  | 10.4763860703  | 629  | 10.0909519196  | 606  | -4%    |                          0.0000 |
| TPC-H 13  | 2.33310866356  | 140  | 2.28189945221  | 137  | -2%    |                          0.0008 |
| TPC-H 14  | 25.7622795105  | 1546 | 23.7948379517  | 1428 | -8%    |                          0.0000 |
| TPC-H 15  | 20.4020729065  | 1225 | 17.7142658234  | 1063 | -13%   |                          0.0000 |
| TPC-H 16  | 7.80176973343  | 469  | 7.60989904404  | 457  | -2%    |                          0.0000 |
| TPC-H 17  | 1.39347290993  | 84   | 1.20879018307  | 73   | -13%   |                          0.0000 |
| TPC-H 18  | 1.94859564304  | 117  | 1.86959135532  | 113  | -4%    |                          0.0000 |
| TPC-H 19  | 5.78491973877  | 348  | 5.52194833755  | 332  | -5%    |                          0.0000 |
| TPC-H 20  | 2.03546261787  | 123  | 1.82990920544  | 110  | -10%   |                          0.0000 |
| TPC-H 21  | 0.49018278718  | 30   | 0.474489420652 | 29   | -3%    |                          0.0000 |
| TPC-H 22  | 13.621846199   | 818  | 12.2797689438  | 737  | -10%   |                          0.0000 |
| average   |                |      |                |      | -5%    |                                 |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
```

**Comment by mrks** [comment]
**What about SIMDBP128 compressed attribute vectors?**

+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.571031272411 | 35   | 0.603258252144 | 37   | +6%    |                          0.0000 |
| TPC-H 2   | 6.35537004471  | 382  | 6.48790311813  | 390  | +2%    |                          0.0000 |
| TPC-H 3   | 5.50569820404  | 331  | 5.60356092453  | 337  | +2%    |                          0.0000 |
| TPC-H 4   | 2.91089844704  | 175  | 2.88250684738  | 173  | -1%    |                          0.0000 |
| TPC-H 5   | 3.4441113472   | 207  | 3.54930400848  | 213  | +3%    |                          0.0000 |
| TPC-H 6   | 16.6395759583  | 999  | 13.5831336975  | 816  | -18%   |                          0.0000 |
| TPC-H 7   | 1.23399949074  | 75   | 1.25962817669  | 76   | +2%    |                          0.0000 |
| TPC-H 8   | 4.72632265091  | 284  | 4.61825609207  | 278  | -2%    |                          0.0124 |
| TPC-H 9   | 0.863588392735 | 52   | 0.88063710928  | 53   | +2%    |                          0.0008 |
| TPC-H 10  | 2.27523994446  | 137  | 2.294008255    | 138  | +1%    |                          0.0002 |
| TPC-H 11  | 28.6311836243  | 1718 | 28.5773582458  | 1715 | -0%    |                          0.1566 |
| TPC-H 12  | 7.91062688828  | 475  | 8.75217819214  | 526  | +11%   |                          0.0000 |
| TPC-H 13  | 1.23445475101  | 75   | 1.2643147707   | 76   | +2%    |                          0.0000 |
| TPC-H 14  | 9.18646907806  | 552  | 9.96181297302  | 598  | +8%    |                          0.0000 |
| TPC-H 15  | 10.8828754425  | 653  | 12.7683362961  | 767  | +17%   |                          0.0000 |
| TPC-H 16  | 7.263007164    | 436  | 7.32590246201  | 440  | +1%    |                          0.0000 |
| TPC-H 17  | 1.15786421299  | 70   | 1.13248932362  | 68   | -2%    |                          0.0000 |
| TPC-H 18  | 1.80254590511  | 109  | 1.84522104263  | 111  | +2%    |                          0.0018 |
| TPC-H 19  | 3.20609259605  | 193  | 3.19534945488  | 192  | -0%    |                          0.4752 |
| TPC-H 20  | 1.77595806122  | 107  | 1.77948892117  | 107  | +0%    |                          0.6039 |
| TPC-H 21  | 0.381972879171 | 23   | 0.389288336039 | 24   | +2%    |                          0.0001 |
| TPC-H 22  | 11.6439161301  | 699  | 11.5297412872  | 692  | -1%    |                          0.0000 |
| average   |                |      |                |      | +2%    |                                 |
+-----------+----------------+------+----------------+------+--------+---------------------------------+

**Comment by mrks** [comment]
@mrzzzrm: How easy is it for you to update the table in the first post?

**Comment by mrzzzrm** [comment]
> How easy is it for you to update the table in the first post?

Not hard, I've got a bit of tooling by now: https://github.com/mrzzzrm/ninjaprof - I'll try to do it soon
I'll defer my assessment of your measurements until then.

**Comment by mrzzzrm** [comment]
Table updated.

**Comment by mrks** [comment]
We have disabled SIMD for places that obviously do not profit from it. Is there anything that can be done here? Otherwise, I'd close it together with #1534.
