### ISSUE TITLE
Join Operator tests need improvement

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1542]
As mentioned in #1541 our join tests failed to catch some relatively simple bugs. Such bugs in our basic operators **need to stop happening**. JoinFullTest, which is responsible for testing non-equi joins tests only 55 JoinMode/Predicate combinations, some of which are "wasted" on testing dictionary inputs, which the join operators are agnostic about. I have two ideas for this for improving this.

## Brute force testing with pre-generated tables
Write a performance-agnostic JNL in python, let it generate tbl files for manifold (all) combinations of predicatecondition/joinmode/{empty-table,small-table,medium-table) for each DataType. Make sure null values are emitting for non-matching tuples in outer joins. The cpp-test code handles flipping input sides, generating reference-segment input and such.

## Cross Validation between Join Operators.
Maybe in the system test, generate A LOT of join operations and verify all our operators (as they support them) produce the same output. This would have caught #1541, e.g., and should be relatively simple to do.

Once this is finished for the Join Operators, consider a similar approach for the TableScan. Once again, imo, we cannot afford having bugs in these fundamental operators. We had two seminar groups working with joins, we should have given them an absolutely stable basis to build on.

**Comment by mrks** [comment]
> Such bugs in our basic operators need to stop happening.

Agreed. I like the first approach better - we should end up with maybe 100 tests per operator, which is still doable. Would you generate the expected tbls automatically, too?

**Comment by mrzzzrm** [comment]
>  Would you generate the expected tbls automatically, too?

The result tbls, yes, that's what I meant
