### ISSUE TITLE
Rewrite constant IN lists

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1546]
Optimize queries like
```sql
SELECT * FROM customer WHERE c_custkey IN (1, 2, 3)
```
by using a semijoin, which would improve the performance for large (auto-generated) lists.

**Comment by mrzzzrm** [comment]
TPC-H 16 and 19 have small lists there. Any (TPC-something) examples where the list is long enough to warrant this rewrite? Would need to be big enough to justify the SortMerge/JoinHash startup overhead...

**Comment by Bouncner** [comment]
JOB 14a has ten elements. Could be interesting, I wouldn’t bet what’s faster.
