### ISSUE TITLE
RangeFilter: Properly support exclusive Betweens

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1553]
After #1481 they fall back to BetweenInclusive

**Comment by mrks** [comment]
We expect the impact of this to be limited. While it's possible to construct edge cases where this (1) actually improves the statistics and (2) the improvement is significant enough to change the plan, these cases are currently not important enough for us to justify the work on this.

As discussed with @Bouncner and @Bensk1, estimating all types of between as inclusive is sufficient for now and we will not invest any resources into this until it actually becomes an issue.
