### ISSUE TITLE
(Hash?)Join: Clarify comments

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1557]
Comments talking about the "left" and "right" table are confusing as tables may be flipped. This is not only the case for regular joins, but also for anti joins such as `WHERE a IN (1, 2)`. I would never call `a` the "right side".

Maybe "probed" and "hashed side" are better?

Not sure if this applies to other operators that deal with multiple columns, too.

**Comment by mrzzzrm** [comment]
will try to have a look at this. To preempt a prolonged in-PR discussion: The JoinHash uses the terms "build" side and "probe" side - and from my gut feeling those are also the commonly used names. Are you ok with those @mrks?

**Comment by mrzzzrm** [comment]
Ah, and I am going to talk about "build/probe **columns**" to emphasize that we do not radix/materialize/build/probe the entire tables but just one specific column.

**Comment by mrks** [comment]
> The JoinHash uses the terms "build" side and "probe" side - and from my gut feeling those are also the commonly used names. Are you ok with those @mrks?

Yes.

> Ah, and I am going to talk about "build/probe columns" to emphasize that we do not radix/materialize/build/probe the entire tables but just one specific column.

Ok.
