### ISSUE TITLE
Question: Is it possible to convert LQP to SQL

### ISSUE THREAD

**Issue by jackvincenow** [hyrise/hyrise#1558]
I'm learning about LQP, and would like to compare SQL before and after the LQP steps.
Is it possible to convert an LQP back to SQL (vs just SQL to LQP only)

tnx :-) keep up the amazing work
Vince

**Comment by mrks** [comment]
Hi Vince,

this is not easily possible. Part of the reason is that there is no single SQL statement for an LQP. Example: `SELECT * FROM a, b WHERE a.id = b.id` and `SELECT * FROM a JOIN b ON a.id = b.id` end up as the same (optimized) LQP.

When you say that you want to look at the different LQP steps, I assume you mean the optimizer rules. The whole idea of these is that they produce the same result before and after, so the corresponding SQL statement is unchanged.

If you let us know what you are looking at, maybe we can find a different way to help you.

Best
Markus

**Comment by jackvincenow** [comment]
Tnx for the fast response Markus,

You are correct about stating that each step will produce the same results, but my thoughts here were more about showing how the sql would look like in each lqp step, not the results.

For example, applying a predicate push down would generate a sql with the WHERE statement inside the join vs outside of the join, or having multiple joins (join reordering) that generate a pairwise join statement with the ordering applied just like the LQP ordering would do.

Finally, in your example:, given the two statements:
(1) SELECT * FROM a, b WHERE a.id = b.id 
(2 )SELECT * FROM a JOIN b ON a.id = b.id

I would assume that the generated sql would be the second statement because it explicitly describes how the join gets executed vs the first example which does it implicitly.
Eventually, the goal would be to show how an optimized sql statement would look like if it had to emulate a given step in the lqp

**Comment by mrks** [comment]
I think I get what you mean. For most rules, this would be possible (e.g., join ordering, predicate pushdown, ...), but for others, it would not. An example is the `NOT IN` statement, which will get optimized into a anti join by #1473. Anti joins are not part of the SQL syntax, so after executing that rule we could no longer print a SQL statement that properly reflects the execution.

A second example are inclusive and exclusive betweens. With #1481, we rewrite `WHERE a > 5 AND a <= 7` into a right-inclusive between, which is also not part of SQL.

Have you looked at our LQP visualization (`visualize lqp SELECT ...`)? There, you can show both the LQP before and after the optimization. We believe that this is not only more complete, but also better readable than SQL.

**Comment by jackvincenow** [comment]
Tnx Markus,

I will explore the LQP visualization tool in more detail, and will follow your recommendation.

have a great day,
Vince
