### ISSUE TITLE
JIT compilation fails on MacOS

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#1569]
The JIT query compilation of specialized code fails on MacOS with:
````
LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target
````
during `_compile_layer.addModule(module, resolver)` in [src/lib/operators/jit_operator/specialization/jit_compiler.cpp:44](https://github.com/hyrise/hyrise/blob/master/src/lib/operators/jit_operator/specialization/jit_compiler.cpp)

In the past this was only the case for optimized builds with optimization levels `-O2` and `-O3`. Now this is also the case for unoptimized debug builds.
I think that I first noticed this after a minor update of the MacOS operating system in late 2018.

**Comment by mrks** [comment]
```
cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++ -GNinja -DENABLE_JIT_SUPPORT=On ..
```

```
./hyriseTest
[...]
[----------] 3 tests from JitCodeSpecializerTest
[ RUN      ] JitCodeSpecializerTest.InlinesVirtualCalls
[       OK ] JitCodeSpecializerTest.InlinesVirtualCalls (5 ms)
[ RUN      ] JitCodeSpecializerTest.ReplacesLoadInstructions
[       OK ] JitCodeSpecializerTest.ReplacesLoadInstructions (3 ms)
[ RUN      ] JitCodeSpecializerTest.UnrollsLoops
[       OK ] JitCodeSpecializerTest.UnrollsLoops (6 ms)
[----------] 3 tests from JitCodeSpecializerTest (14 ms total)
[...]
```

Any chance this fixed itself?

**Comment by FabianWiebe** [comment]
Unfortunately, it did not fix itself. The error occurs in debug and release builds of the system tests:
````
./hyriseSystemTest
[...]
[----------] 536 tests from SQLiteTestRunnerJIT/SQLiteTestRunner
[...]
[ RUN      ] SQLiteTestRunnerJIT/SQLiteTestRunner.CompareToSQLite/12
LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target
````
