### ISSUE TITLE
Make expressions and LQP nodes easier to use in containers

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1571]
> On another note: I had to replace a `std::map` with a `std::vector` again, this time to keep the order of join predicates reproducible. Is there any reason that expressions/LQP nodes cannot have an `operator <` (except that nobody has needed it enough to implemented it)? I can't imagine this is the only place where this would be useful.

_Originally posted by @Felerius in https://github.com/hyrise/hyrise/pull/1473#issuecomment-478120970_

> No real reason, except that's like 30 classes needing 30 new functions. (@mrzzzrm)

I had that issue in the past as well. To make further rules easier to write, we should take that time and write those functions.

**Comment by mrzzzrm** [comment]
Agreed, those would be good to have.

Just to make clear what this would mean: We will never be able to use `std::map<std::shared_ptr<AbstractLQPNode>, ValueType>` and expect reproducible orders. We will always have to use `std::map<std::shared_ptr<AbstractLQPNode>, ValueType, LQPNodeCmp>` or an alias, similar to those providing `unordered_map/set` for expressions:

```c++
template <typename Value>
using ExpressionUnorderedMap =
    std::unordered_map<std::shared_ptr<AbstractExpression>, Value, ExpressionSharedPtrHash, ExpressionSharedPtrEqual>;
using ExpressionUnorderedSet =
    std::unordered_set<std::shared_ptr<AbstractExpression>, ExpressionSharedPtrHash, ExpressionSharedPtrEqual>;
```

It always bothered me that `ExpressionUnorderedMap<ValueType>` doesn't look like, from writing STL code, I'd expect a expression->value map to look like, but there seems no way around it: [At least on this page I cannot find a bullet point allowing us to specialize `std::hash` for `std::shared_ptr<AbstractLQPNode>`](https://en.cppreference.com/w/cpp/language/extending_std)

**Comment by mrks** [comment]
Since #1795, we have `LQPNodeUnorderedMap`. Adding support for `std::map` does not seem like a good idea. "Smaller" and "larger" are semantically undefined for both expressions and LQP. Also, it would likely be much more expensive than an `unordered_map`, because comparisons would be more expensive than a one-time hash computation.
