### ISSUE TITLE
Improve Compile Time

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1573]
Two ideas:

### Specify encodings that will not be used at cmake time, erase those iterators

Even with our previous efforts, building in release mode is no fun. For me, I often stick to the default encoding (i.e., dictionary) as I am testing something mostly unrelated to the encodings. Having an option to disable encodings as a cmake flag (`-DENABLE_ENCODINGS=Dictionary,...`) would make this much easier. I don't even think that we need to entirely remove files from the compilation - it should be sufficient to translate this into `-DENABLE_DICTIONARY_ENCODING=0/1` and check, for example, in resolve_type.

Some tests will need to be adapted to skip encodings that are disabled.

(also read my follow-up comment)

### Benchmark whether SIMD has any advantages for Frame-of-Reference, RLE, ... and disable it if it doesn't.

**Comment by mrks** [comment]
Mmmh, even better: Do the same but force the type-erasure for non-enabled types. That way, we don't even have to touch the tests. We should check if that has the same performance benefit.

**Comment by mrzzzrm** [comment]
> Do the same but force the type-erasure for non-enabled types.

Way better than not including storage types in the build.

(But from my measurements in #1534 and especially #1540 I'd say the main compile performance culprit right now are the SIMD-scans. We compile SIMD-scans for Frame-Of-Reference double segments - are we even remotely sure that does anything good? SIMD should be a special path for ValueSegment and AttributeVector scans, not the generic solution)

**Comment by mrks** [comment]
Fun fact: This is the assembly of the column-vs-column scan:

```
-rw------- 1 Markus.Dreseler users 1,9G Apr  5 12:58 /tmp/ccPb7H6A.s
```

`as` brings that down to 26M. I'll also do some experiments if using a ramdisk helps here.

**Comment by mrzzzrm** [comment]
Would it be better to collect general ideas for compile time in #1534 and SIMD-related in #1540 and close this one?

**Comment by mrks** [comment]
Yes.
