### ISSUE TITLE
TPC-H generator freezes with SF=150

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1574]
> In the function mk_order in third_party/tpch-dbgen/build.c, the following loop never terminates:
> 
> ```
> while (o->custkey % CUST_MORTALITY == 0)
> {
> o->custkey += delta;
> o->custkey = MIN(o->custkey, O_CKEY_MAX);
> delta *= -1;
> }
> ```
> 
> The O_CKEY_MAX macro is defined as `#define O_CKEY_MAX (tdefs[CUST].base * scale)`.
> While there is global variable "scale", in this instance the code expanded from the macro will use the local function parameter "scale" of mk_order, which has type "float".
> 
> Now, `o->custkey` has integral type `DSS_HUGE` (which is "long long"), and thus the MIN macro expands to a ternary operator (? : ) where the second operand is integral and the third operand is float. According to C type promotion rules, this means that `o->custkey` is converted to float, and if it is smaller than `O_CKEY_MAX`, the resulting float value is converted back to long long.
> 
> And this is where the problem comes in. At the time where the endless loop occurs, `o->custkey` happens to have the value 18388620 for me. The loop tries to change that to either 18388619 or 18388621. Now, both values are smaller than `O_CKEY_MAX`. But converting either of those two values to float and then back to long long results in 18388620 again (due to limited precison of the 32-bit IEEE float data type).
> 
> Thus o->custkey stays forever at this value and the loop never terminates.

Here's a proposed patch:

> ```
> diff --git a/third_party/tpch-dbgen/build.c b/third_party/tpch-dbgen/build.c
> index 5c97b04c9..3c5e4a04d 100644
> --- a/third_party/tpch-dbgen/build.c
> +++ b/third_party/tpch-dbgen/build.c
> @@ -184,7 +184,7 @@ mk_order(DSS_HUGE index, order_t * o, long upd_num, float scale)
>  	while (o->custkey % CUST_MORTALITY == 0)
>  	{
>  		o->custkey += delta;
> -		o->custkey = MIN(o->custkey, O_CKEY_MAX);
> +		o->custkey = MIN(o->custkey, (DSS_HUGE) O_CKEY_MAX);
>  		delta *= -1;
>  	}
> ```

My worry is that there are similar float-to-long conversions somewhere in the modified code that have not caused any problems yet. Originally, dbgen only supported integral scale factors. We enabled floats because we couldn't even handle SF1 back then. In the debug build, some queries still need minutes to execute with SF1, but the release build runs the TPC-H tests in hyriseSystemTest in 

Thus, my suggestion is to get rid of non-integral scale factors and skip the TPC-H tests of hyriseSystemTest in the debug build. When we do that, we can generate the data once instead of 22 times, saving us some time there. 

With #1473, this would result in the following execution times for `./build-release/hyriseSystemTest --gtest_filter=TPC*`:

<img width="348" alt="Screen Shot 2019-04-04 at 1 45 48 PM" src="https://user-images.githubusercontent.com/575106/55553299-1a92c480-56e0-11e9-8133-fe9007d6d2c6.png">

Currently, this takes 12 seconds, so it would become 16x slower. However, as this is just system test, which is somewhat expected to take longer, I would be willing to live with that.

The alternative would be to work our way through the generator and check all uses of the float for correctness. I am not confident that I would get that right on the first try.

**Comment by Bouncner** [comment]
Ack.

**Comment by mrzzzrm** [comment]
> Originally, dbgen only supported integral scale factors

dbgen supports scale factors < 1, at least the [version](https://github.com/electrum/tpch-dbgen) I forked from does, just tested it. Since it originally stores `scale` in a long, it does the following to support scale factors < 1 when parsing command line args (MIN_SCALE == 1.0):

```c++
		case 's':				/* scale by Percentage of base rowcount */
		case 'P':				/* for backward compatibility */
			flt_scale = atof (optarg);
			if (flt_scale < MIN_SCALE)
			{
				int i;
				int int_scale;

				scale = 1;
				int_scale = (int)(1000 * flt_scale);
				for (i = PART; i < REGION; i++)
				{
					tdefs[i].base = (DSS_HUGE)(int_scale * tdefs[i].base)/1000;
					if (tdefs[i].base < 1)
						tdefs[i].base = 1;
				}
			}
			else
				scale = (long) flt_scale;
                        // [...]
			break;
```

What we should do - instead of using a float-scale param - is probably the same reduction of the `tdefs[i].base` numbers.

Supporting scale-factors smaller than 1.0 is something we should keep. It's very useful - at least to me - to be able to generate small tables when experimenting in the playground.

**Comment by mrzzzrm** [comment]
@mrks are you on this; should I be? seems like this is something we should tackle...

**Comment by mrks** [comment]
Go for it
