### ISSUE TITLE
Optimize JOIN ON with Multi Predicate Join

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1579]
The query
```sql
SELECT *
FROM customer
JOIN orders
ON c_custkey = o_custkey
AND c_acctbal < o_totalprice
```
is currently not optimized. However, a Multi Predicate Join could be used.

**Comment by mrks** [comment]
I believe this is by design, as the multi-predicate join is actually slower than a single-predicate join with a follow up scan (which can make benefit from the dictionary encoding). The multi-predicate join is good in cases where there is no syntactically equivalent plan with a regular predicate.

**Comment by janetzki** [comment]
Ah, right. I forgot about that.
