### ISSUE TITLE
OR support for Multi Predicate Joins

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1580]
The Multi Predicate Join should be able to handle queries like:
```sql
SELECT *
FROM customer
JOIN orders
ON c_custkey = o_custkey
OR c_acctbal < o_totalprice
```

**Comment by mrzzzrm** [comment]
Any query (TPC-DS?) that we will encounter soon that would require this? Otherwise I'd close this issue, there are many, many SQL features that we do not support (and never will).

**Comment by mrks** [comment]
Agreed. The common join implementations won't be too happy about this, so it would probably be a nested loop join playing on the ExpressionEvaluator keyboard. It will be either unsupported or really sloooow. ;)

**Comment by Bouncner** [comment]
Moritz, have we ever talked about using the Expression Evaluation within the joins?

**Comment by mrzzzrm** [comment]
It is - in theory - possible. Create a temporary table with one row which contains a tuple from the left and the right side (i.e., a row `T0.a, T0.b, T1.a, T1.b, T1.c`) and run the ExpressionEvaluator inside the MultiPredicateEvaluator. It would be quite slow, but it would work.

**Comment by Bouncner** [comment]
Looking at the current complexity within the joins (leaving aside that we only support simple conjunctive chains) and considering the confusion of the NULL handling, reusing battle-proven (i.e., tested for a handful cases :D) parts here sounds like a decent idea to me.

Might it be possible to circumvent the temp-table part?

**Comment by mrzzzrm** [comment]
> Might it be possible to circumvent the temp-table part?

With a bit of hacking, maybe.

But first off, for which queries would we need it?

**Comment by Bouncner** [comment]
My motivation is rather not having this code mess (and that's what MP joins are to me) in every join operator but rather leverage existing code throughout all join implementations. 

If it turns out that this enables arbitrary queries, fine. But that's not why I am asking.

**Comment by mrzzzrm** [comment]
Wait, the current way of having a MultiPredicateEvaluator is what you want to remove? I didn't know that this is what we're talking about. 

I don't think a solution which uses the ExpressionEvaluator would be cleaner than the current one. In fact, what I was assuming during this conversation was that we would call the ExpressionEvaluator FROM the MultiPredicateEvaluator.

**Comment by Bouncner** [comment]
Yeah, just realized that I wrote nonsense. I was thinking about the Anti-Modes and how they pollute the joins, but that's probably not something we can easily "fix" since it touches the actual join process. And it's not "multi predicate" at all. Sorry for the confusion.

Concerning the ExpressionEvaluation: yes, calling it might be a good idea as a fallback. But probably not worth the effort until we see this as an issue in some queries.
