### ISSUE TITLE
Harmonize _it and _iter?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1588]
This should be a simply search-and-replace and could be enforced by the linter

**Comment by mrzzzrm** [comment]
I'd vote for "iter". It cannot be confused with the pronoun "it" [sic]

**Comment by mrks** [comment]
I started looking at this. The key is to search for `_it\b` (or `\bit\b`). Most can be done automatically, but ~200 lines need to be looked at manually. However, I found not a single place where this actually made a difference.

While code styles are important, I think this does not affect anyone's life.

Feel free to discuss / reopen if you disagree.
