### ISSUE TITLE
Get rid of mvcc_data()

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1602]
It seems unsafe to have an unlocked access method in addition to `get_scoped_mvcc_data_lock`. `Chunk::mvcc_data()` should go.

For example, this looks dangerous:
https://github.com/hyrise/hyrise/blob/2628fbfd09408563d3ca60f0e15f04b42e03a3da/src/lib/operators/projection.cpp#L100

While refactoring that part of the projection, we might also pass in the MVCC data directly instead of making the chunk resize the vectors first and replace them afterwards.

#749 might make the `mvcc_data()` part superfluous, but we should still look at the projection.

**Comment by mrzzzrm** [comment]
This can be done very easily after #1647, I'm taking this.

**Comment by mrks** [comment]
@mrzzzrm Still on this?

**Comment by mrzzzrm** [comment]
Ah, forgot about this. I'm trying to step back a bit from tackling "small" issues. I think it's better if the new forces start working on these things, to gain some experience with Hyrise.
