### ISSUE TITLE
TPC-H 6 wrong discount range calculation (fixed in #1624)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1622]
0.01 is subtracted and added twice (once in the generator, once in the query template), leading to an incorrect discount range

![image](https://user-images.githubusercontent.com/2679018/56474887-8dda5b80-6480-11e9-822a-6a8e5551f8f3.png)

**Comment by mrks** [comment]
As it is the job of the DB to handle that constant expression correctly, it should be removed from the query generator.
