### ISSUE TITLE
OS X: Console crashes when exiting

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1635]
```
(release)> load resources/test_data/tbl/int5.tbl t
Loading resources/test_data/tbl/int5.tbl into table "t"
Encoding "t" using Unencoded
(release)> SELECT * FROM t WHERE b < 4
=== Columns
|       b|
|     int|
|not null|
=== Chunk 0 ===
|<ReferS>|
|       1|
|       3|
===
2 rows total
Execution info: [PARSE: 5 µs 676 ns, SQL TRANSLATE: 73 µs 116 ns, OPTIMIZE: 204 µs 500 ns, LQP TRANSLATE: 30 µs 635 ns, EXECUTE: 100 µs 915 ns (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]
(release)> Bye.
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```

**Comment by mrks** [comment]
Static destruction order... -.-

The console is static so that the signal handler can find it. The console gets initialized first. The SQL pipeline needs a transaction context, so it calls `TransactionManager::get().new_transaction_context()`, which initializes the static transaction manager. On destruction, the transaction manager was created last and gets destructed first. Next, the console, and with it, the last SQL pipeline is destructed. The pipeline has a context which cannot be deregistered in the now defunct transaction manager.

**Comment by mrzzzrm** [comment]
Globals are great, longjmp is great.

**Comment by mrks** [comment]
Happy to use any other method that can handle Ctrl+C. :(

**Comment by mrzzzrm** [comment]
It's called "repeated smashing of Ctrl+C, Ctrl+D and Ctrl+Z", and produces a more mature Console user that has now, by the effort of having to restart the Console and re-load all his tables, learned to think before issuing a cross join.

**Comment by mrzzzrm** [comment]
Does the longjmp method even "work" if the scheduler is enabled?

**Comment by mrks** [comment]
With regards to running queries? No idea, good chance it doesn't. Most of the time, I use it not to cancel something but to get rid of the line that I just mistyped.
