### ISSUE TITLE
Column pruning in Projection takes unexpectedly long

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1645]
![image](https://user-images.githubusercontent.com/2679018/56847839-479e5580-68e1-11e9-8dff-1ea906e5f6db.png)

![image](https://user-images.githubusercontent.com/2679018/56847831-32292b80-68e1-11e9-8b87-4d38ed80781d.png)

\> 1'000'000ns to select three segments from a chunk? This is a release build with sf=5

**Comment by Bouncner** [comment]
That takes definitely too long. Talked about that issue with @mrks yesterday as well (email with the real-world query). It took “only” 15ms for a 10M table but even that sounds ridiculous.

**Comment by mrzzzrm** [comment]
I'll look into it.

**Comment by mrks** [comment]
The LQP visualization is much more interesting for things like that. Is it difficult to get the same information here?

**Comment by mrzzzrm** [comment]
got it, fix will follow later today, hopefully
