### ISSUE TITLE
PQP visualization relies on CleanupTemporaries::No

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1646]
Otherwise we lose almost all information  like timings, table sizes - that could be gained from visualization:

CleanupTemporaries::Yes
![image](https://user-images.githubusercontent.com/2679018/56850951-96f87c00-6909-11e9-95ab-73c45f48199a.png)

CleanupTemporaries::No
![image](https://user-images.githubusercontent.com/2679018/56850961-d45d0980-6909-11e9-8826-c081daa5f888.png)

Tables sizes should be stored in the OperatorPerformanceData and visualization shouldn't check for get_output_table != nullptr when deciding whether this meta data should be visualized

**Comment by mrks** [comment]
Where is this a problem?

**Comment by mrzzzrm** [comment]
1. You don't want to keep gigabytes of temporary tables around just to be able to visualize row counts
2. In the ~15 Minutes it took me to figure this rather unintuitive fact out

**Comment by mrks** [comment]
One thing to keep in mind: If we store the information in the OperatorPerformanceData, we have to call estimate_memory_usage on every intermediate table without knowing if we want to visualize the data. With a higher number of chunks and more accurate estimations (#1600), this is a non-trivial job.

**Comment by mrzzzrm** [comment]
Why can nothing ever be easy :( But I can live with the memory usage estimation not being included when the temporaries are cleaned up before visualization. I want row_count/chunk_count, though.

**Comment by Bouncner** [comment]
I have to admit that I never understood the mem consumption anyways.

It is data, pos list, theoretical data when materialized?

**Comment by mrzzzrm** [comment]
Actual memory occupied by whatever the Table is comprised of. So PosLists if it's a reference Table, actual data (in whatever encoding it is stored) if it is a data Table

**Comment by Bouncner** [comment]
Doesn’t sound ~170MB too much for the result of the first scan?

**Comment by mrks** [comment]
Have another look

**Comment by mrzzzrm** [comment]
I can make that 170 **GB** if I pick another scale factor.

**Comment by mrks** [comment]
@Bensk1 @Bouncner @krichly 

Storing the output chunk and row count in the OperatorPerformanceData should not be too expensive. Estimating the table size is. Do we really need that information in the visualization? I feel like it is more misleading than it is helpful. For example, when looking at a scan, the input "table size" might differ by orders of magnitude depending on whether the input is a data table or a reference table that references all rows. The effort required by the scan, however, is the same.

**Comment by Bouncner** [comment]
I've never considered the memory estimations to be of any value to be honest.

The other values can easily be set in the performance data structs. I can take that part as I am already working on a PR that extends the performance data structs substantially.

**Comment by Bensk1** [comment]
I have never used the table size in the visualization.

**Comment by mrks** [comment]
> The other values can easily be set in the performance data structs. I can assign the issue to myself if there are not vetos as I am already working on a PR that extends the performance data structs substantially.

I don't think the overlap will be too big. Please self-assign the ticket when you start working on it; otherwise I might pick it up one of these days.
