### ISSUE TITLE
Allow visualizer to visualize multiple LQPs/PQPs

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1654]
minor: why one file per statement instead of all planviz of a query in a single file? doc? (e.g., I'd like it better to have all 3 plans of TPC-H 15 in one file instead of in 3)

_Originally posted by @mrzzzrm in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjMwMTMxMDY2/pull_request_reviews/more_threads_

**Comment by d-justen** [comment]
I just tried this in the console by inputting `CREATE TABLE t (a INT, b INT); SELECT * FROM t;` first and `visualize` after. From this I'm getting a png with both queries in it. Could you specify in which cases I would get different files for the queries?

**Comment by mrks** [comment]
I think @mrzzzrm was talking about `./hyriseBenchmarkTPCH -r 1 --visualize`.

**Comment by mrks** [comment]
The creation of multiple files is part of `benchmark_sql_executor.cpp`.
