### ISSUE TITLE
linter and formatter disagree on 'auto [a,b] = std::pair{4, 2}'

### ISSUE THREAD

**Issue by pascalhpi** [hyrise/hyrise#1655]
The linter says the space between 'auto' and '[' is unnecessary, but the formatter inserts that space if it is not there.

I'm on Ubuntu 18.04, the actual code is 
`const auto [call_center_first, call_center_count] = prepare_for_table(CALL_CENTER);`.

**Comment by mrks** [comment]
Fixed in #1614

**Comment by mrzzzrm** [comment]
#1614 was merged, closing this
