### ISSUE TITLE
FixedStringVector's size() behavior

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1666]
For a vector of empty strings, the value of size() is always 1, no matter how many elements have been added.

Since we mostly mimic the behavior of std::vectors, this is super confusing.

Is there any reason to not change this behavior?

**Comment by mrks** [comment]
Please remember to properly use “fixes”. Github does not recognize “fixes a and b”.

**Comment by Bouncner** [comment]
Github müffelt.
