### ISSUE TITLE
Extend Plugin Interface

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#1670]
While fiddling with the [PCM](https://github.com/opcm/pcm) plugin, two issues came up:

1. The `AbstractPlugin` interface is very limited, as it provides only the two methods `void start()` and `void stop()`, both called during load/unload of the plugin. For something like additional benchmarking metrics, like with PCM, it would be useful if not necessary to have something more interactive, to start/stop performance counting, and to gather the results. One possibility would be to have one generic method, like `trigger`, `lap`, or `result`, that returns an (optional) variant that could contain, well, anything, or maybe it returns a JSON. This method could be used by various plugins for their specific purpose, and in the case of this PCM plugin to trigger the metric collection, returning the result of the last lap. Plugins that don't need that method would just not implement/override it.

2. Even with an extended plugin interface, there is (as far as I've seen) no way to access it from outside the `PluginManager`. I would suggest something like`PluginManager::plugin("PluginName")` that returns the PluginHandle.

Any thoughts on this, @mrks, @Bensk1?

**Comment by mrks** [comment]
1. The whole point of plugins is that the core should not have to know about their presence. If we introduce `PCMPlugin::trigger()` at a defined point in the benchmark, this is not a plug-and-playable plugin anymore. If anything, we might have event listeners that plugins can subscribe to.

2. Same thing. Adding it would not be difficult, but having to access a specific plugin from the core seems to be a smell.

Maybe you could describe what you are trying to achieve?

**Comment by lanice** [comment]
> Maybe you could describe what you are trying to achieve?

Two things: A way to sync the additional metric collection with the benchmark runs/items, and a way to return the results in the end. The results _could_ be stored in a separate files, although I feel like that wouldn't be the most elegant solution.

Event listeners you suggested could work too I guess. But wouldn't we have a similar problem there, that we put specified events into the benchmark, making it not 100% plug-and-playable anymore?

I do think for a plugin like that, enhancing benchmark metric collection, we have to make a compromise somewhere (i.e., give up some of the plug-and-playability).
The only way I see that does not need any change in the interface would be to start metric collection upon plugin `load`, and dump the results into a file upon `unload`. Start metric collection would mean start a separate thread, and read the performance counters e.g. every second.
But then the benchmark runs/items and the plugin results are completely disconnected, and we'd have to manually piece them together for evaluation.

**Comment by mrks** [comment]
How about this (building on #1597 and making BenchmarkRunner inherit from some Listenable interface):

```
BenchmarkRunner.add_listener(ItemStarted, [&](ItemID id) { _id = id; });
BenchmarkRunner.add_listener(ItemFinished, [&](ItemID id) { write_result(); });
```

We could also add `BenchmarkRunner::add_to_run_json` (or similar) to write directly into the JSON. The difference here would be that it is a function that is theoretically used by other plugins as well and the runner does not have to know about PCM.

*On a side note: How would you handle the shuffled mode?*

**Comment by lanice** [comment]
So, just that I understand your suggestion correctly, the plugin would be the listener in this case,  `ItemStarted` / `ItemFinished` are the events that trigger the functions passed by the plugin?

Where would `BenchmarkRunner::add_listener` be called from? From the plugin?

> How would you handle the shuffled mode?

I'm not sure if PCM measurements are really suitable for the shuffled mode, or for that matter, for single item collection in general. In theory we could collect one performance counter when an item starts, and one when it finishes, and get the result for that. That falls apart as soon as we start using multiple threads though. In my MA experiments I used PCM to collect the data of a "full" benchmark consisting of multiple runs of the same item. This is only possible in the ordered mode.

**Comment by mrks** [comment]
Correct. Not saying that it's perfect,  but I feel like it does a better 
job at decoupling the two.

Regarding shuffled mode: That's what i was expecting. As long as these 
illegal modes lead to an error explaining why it can't be done, that should 
be fine.

Am 20. Mai 2019 06:45:24 schrieb Leander Neiss <notifications@github.com>:

**Comment by mrks** [comment]
Can't see the underlying plugin (PCM) being finished any time soon. If someone needs it, it will be me, and I will know where to pick off.
