### ISSUE TITLE
Hyrise singleton instance

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1677]
@mrzzzrm and I just had a discussion about global state. The problems are
1. No one knows which variables hold state, as things like the singleton PluginManager are easily overseen
2. As a result, properly resetting the globally state in tests is difficult
3. The Static Initialization Order Fiasco

Having an instance that is constantly passed around bloats the interfaces unnecessarily. Also, we will likely never have more than one instance.

How about a single `Hyrise` class that holds the entire global state? Instead of `StorageManager::get()`, we would use `Hyrise::get().storage_manager`. Also, we could easily reset everything using `get() = Hyrise{}`.

**Comment by julianmenzler** [comment]
Great idea!

**Comment by Bensk1** [comment]
That sounds like a good solution to me. Does it have any downsides?

**Comment by mrks** [comment]
Can't think of any

**Comment by d-justen** [comment]
I'm working on this right now. Is there any reason why `StorageManager`, `TransactionManager` and `PluginManager` should stay Singletons or can this go away?

**Comment by mrks** [comment]
As discussed: They should be regular classes, but constructible only by the Hyrise super class.
