### ISSUE TITLE
IndexScan does not properly handle doubles

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1688]
If an IndexScan operates on a float column but a number with double precision (wrapped in an AllTypeVariant) is passed to it (this might happen when executing the TPC-H Benchmark), the double is not handled properly, passed to the dictionary and the dictionary's call to `boost::get()` crashes.

This did not come up because there was no test for index scans on data types other than int. Apparently, this does not happen with the TableScan as its `create_impl` method calls `lossless_variant_cast` to solve that issue. Simply replicating it seems odd.

**Comment by mrks** [comment]
See #1790
