### ISSUE TITLE
check_table_equal does not check 'nullable'

### ISSUE THREAD

**Issue by pascalhpi** [hyrise/hyrise#1698]
- extend check_table_equal in check_table_equal.cpp to check whether the columns in the given table and the expected table are equal regarding their nullable flags
- add nullable flags to the output of check_table_equal
- fix all tests depending on check_table_equalto NOT check nullable flags (probably just have to change the expected tables TableColumnDefinitions)

**Comment by mrzzzrm** [comment]
why is the nullability-attribute important? Important is whether the NULL values are in the same places in both tables, and that is tested. SQLite will probably not mark columns as "nullable" at all/if they don't contain NULL values - and we want to compare Hyrise tables with SQLite.

**Comment by pascalhpi** [comment]
My use-case did not involve SQLite and I didn't expect it was only meant for that. I wanted to check that the TableBuilder created a Table with the correct column nullability. Feel free to close this issue if that is not something we want to cover with check_table_equal.

**Comment by pascalhpi** [comment]
@mrzzzrm do you think we should check column nullability in check_table_equal for that use case?

**Comment by mrks** [comment]
> why is the nullability-attribute important?

Because it would have prevented #1769.

> SQLite will probably not mark columns as "nullable" at all/if they don't contain NULL values - and we want to compare Hyrise tables with SQLite.

Adding an ignore flag for that.
