### ISSUE TITLE
`--cache_binary_tables` ignores `--chunk_size`

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1699]
When reusing `.bin` files but specifying a different chunk size, the latter is ignored.

**Comment by mrzzzrm** [comment]
I think we discussed this out when implementing --cache_binary_tables and since we didn't want to encode chunk sizes in file names we decided this was by design?

**Comment by mrks** [comment]
At the very least, we should assert that the chunk sizes match and throw an error if they don't.

**Comment by mrks** [comment]
fixed in #1744

**Comment by Bensk1** [comment]
Actually, now that I have run into this and the warnings are in the middle of more than 50 lines (for TPC-H, more for JOB and TPC-DS) boilerplate output, I would vote for an assert.

**Comment by mrks** [comment]
Go for it.
