### ISSUE TITLE
Ensure that chunks added after LQP translation are handled

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1700]
In #1697 @mrks mentioned that we should add a test which ensures that chunks added after LQP translation of index scans are taken into account.

**Comment by mrks** [comment]
@Bensk1 @mweisgut Can you explain why the LQPTranslator only cares about GroupKeyIndexes?

https://github.com/hyrise/hyrise/blob/e71169a1e18f73b03ac9054af0f5e3e1d04cf944/src/lib/logical_query_plan/lqp_translator.cpp#L208-L215

There should be a comment on that. Feel free to edit the upcoming PR to include it.

**Comment by Bensk1** [comment]
I think that originates from a time where we only had the GroupKey index or where it was the only one properly and efficiently working.

**Comment by mweisgut** [comment]
It was introduced with #661.

**Comment by mrks** [comment]
Open question is part of #1790.
