### ISSUE TITLE
Verify that pruning works as expected

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1703]
I am running some encoding benchmarks and was trying to avoid the effects of dictionary pruning. An extreme case would be the `o_orderkey` column, on which `orders` is sorted and which is the key.

But rather surprisingly, I found that the pruning of chunks does not work as expected. The orderkeys are generated in an increasing manner with gaps.
Keys 1 to 7 exist and should reside in the oldest chunk. Surprisingly to me, the pruning rates (and now I am not talking about dictionary pruning, but the optimizer's chunk pruning) differ for `o_orderkey = 1` and `o_orderkey = 2`.
I cannot explain that behavior since both the range filters as well as min/max filters should handle both filters the same.

![image](https://user-images.githubusercontent.com/1745857/59031997-84a52280-8865-11e9-8dd8-b9403767b1d6.png)
![image](https://user-images.githubusercontent.com/1745857/59032008-8c64c700-8865-11e9-9064-cc39d26ca368.png)
![image](https://user-images.githubusercontent.com/1745857/59032020-92f33e80-8865-11e9-9eb2-33c1df21c50c.png)

```
(release)> select o_orderkey from orders;
|        3000000|
(release)> select count(distinct o_orderkey) from orders;
|        3000000|
(release)> select max( o_orderkey) from orders;
|       12000000|```

**Comment by mrks** [comment]
Tried reproducing this, but the only way I found on 696abbaab94de41396e8d17d379678f1296167ca was to generate the data with one SF, fill the query plan cache, and generate bigger data. Any chance that is what happened? Could you try to reproduce this on a current master, which shows both the number of pruned and total chunks?

**Comment by mrks** [comment]
Ping @Bouncner 

Now that TPC-H data is sorted, we do use pruning and it seems to work quite well. Could you re-confirm or close this issue, please?

**Comment by Bouncner** [comment]
Cannot reproduce. As far as I can tell, everything looks fine.
