### ISSUE TITLE
Cast for non-equi scans so that fast scan implementation is used

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1712]
TPC-H 6 uses the slow ExpressionEvaluator for a `float between double and double` predicate, even though these doubles could be casted to the previous/next float without breaking correctness of the query if BETWEEN INCLUSIVE also gets rewritten to BETWEEN EXCLUSIVE

![image](https://user-images.githubusercontent.com/2679018/59603130-e8063e80-9108-11e9-9ff0-ab1c96495a72.png)

**Comment by mrks** [comment]
Why would we rewrite it to BETWEEN EXCLUSIVE? I'd rather say that we should take the next possible float value within the interval and always make it INCLUSIVE.

**Comment by mrzzzrm** [comment]
yes, that would work, too. I guess getting "the next bigger float of a double" is going to be the trickier part

**Comment by mrks** [comment]
Not bigger. The one towards the "other side" of the between.

https://en.cppreference.com/w/cpp/numeric/fenv/FE_round ?

**Comment by mrzzzrm** [comment]
Last time I checked, my clang ignored this pragma:

```
As with any floating-point environment functionality, rounding is only guaranteed if #pragma STDC FENV_ACCESS ON is set.
```
