### ISSUE TITLE
Running hyriseBenchmarkTPCH with prepared statements results in InvalidInputException

### ISSUE THREAD

**Issue by engelfa** [hyrise/hyrise#1717]
When calling `hyriseBenchmarkTPCH` with `--use_prepared_statements=true`, the following error is thrown:
```
terminate called after throwing an instance of 'opossum::InvalidInputException'
  what():  Invalid input error: Did not find a table or view with name lineitem
```

**Comment by mrks** [comment]
Mmh, that was broken for a while. This underlines the importance of the binary tests. I will push a fix in a minute.
