### ISSUE TITLE
Master does not build: enumeration value 'StaticTable' not handled

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1718]
The current master does not build due the following error in the tests (both for GCC and clang):
```
../../../src/lib/statistics/cardinality_estimator.cpp:118:11: error: enumeration value 'StaticTable' not handled in switch [-Werror,-Wswitch]
  switch (lqp->type) {
          ^
1 error generated.
```

Has the master been merged into #1702 before merging the PR?

**Comment by Bensk1** [comment]
@d-justen told me that he is going to look into that soon.
