### ISSUE TITLE
Error when fetching result-verification submodule

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1729]
When I was pulling the current master and updated my submodules, I got the following error (MacOS High Sierra):
```
$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object 0b68a82b233ec84d7964b3faf31fea90a1585833
Fetched in submodule path 'third_party/tpcds-result-reproduction', but it did not contain 0b68a82b233ec84d7964b3faf31fea90a1585833. Direct fetching of that commit failed.
```

A quick google search found that fix and it helped me:
```
$ git submodule sync
```

But I don't know exactly what the problem. Did anybody else have that problem?

**Comment by Bouncner** [comment]
Did not happen on another Hyrise instance. If nobody stumples upon the same issue, I will close it in a few days.

**Comment by mrks** [comment]
Tested on two machines, no issues.
