### ISSUE TITLE
COUNT(*) requires GROUP BY

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1741]
While
```sql
SELECT COUNT(*) FROM mixed GROUP BY a;
```
works fine in `sqlite_testrunner_queries.sql`, executed by `hyriseSystemTest` (with clang), the query
```sql
SELECT COUNT(*) FROM mixed;
```
crashes in `JITAggregate::before_specialization()`.

**Comment by mrks** [comment]
@FabianWiebe Not sure how much time you have left. Can you have a look at this or should I?

**Comment by FabianWiebe** [comment]
@mrks I will have a look at this and should be able to fix this.
