### ISSUE TITLE
Test both union operators in JoinGraphBuilder

### ISSUE THREAD

**Issue by d-justen** [hyrise/hyrise#1754]
as mentioned in #1752
The JoinGraphBuilder lacks in testing of building graphs that contain UnionAll operators.

**Comment by janetzki** [comment]
#1791 closes this, since the JoinGraphBuilder won't handle Unions anymore.

**Comment by mrks** [comment]
Please add "fixes #1791" to the PR and do not close issues before they are fixed in the master.
