### ISSUE TITLE
Index join tests crash for GroupKeyIndexes

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#1764]
Since #667 the index join is implemented in Hyrise. Already since this PR the GroupKeyIndex is not used for the index join tests.

https://github.com/sleighsoft/hyrise/blob/e40ac125e3e2dcedd3f808f1f9e8c5570111dd0f/src/test/operators/join_index_test.cpp#L103

Even if all current tests (in this version 7087c18bd8e94b69b86d26f564a69d25e520d530) are passing after adding `GroupKeyIndex` to the testing types, a segmentation fault arises after executing the test suite.

```
[==========] 5545 tests from 209 test cases ran. (5404 ms total)
[  PASSED  ] 5522 tests.
[  SKIPPED ] 23 tests, listed below:
[...]

Speicherzugriffsfehler (Speicherabzug geschrieben)
```

Has anyone investigated this issue before and knows more about the cause? Maybe @mrks or @Bouncner since you were involved in reviewing the mentioned PR?

**Comment by Bensk1** [comment]
I have not seen that before, we have to debug it.

**Comment by Bouncner** [comment]
I don’t understand what this list of skipped tests mean. Did you skip them because these are the failing ones?

Or is it “just” the final segfault you’re talking about? If so, could you post the backtrace?

**Comment by mweisgut** [comment]
I just mean the seg. fault that occurs after the tests were successfully executed.
I'll debug this soon.
