### ISSUE TITLE
TPC-DS Q24/Q85 fails / Test binary

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1782]
```
- Benchmarking 85
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/statistics/statistics_objects/abstract_histogram.cpp:621 Cannot split_at_bin_bounds() on string histogram
Aborted
```

**The TPC-DS should also become part of the binary tests.** If generation takes too long in CI, we should discuss ways of storing the table data outside the container.

**Comment by julianmenzler** [comment]
As a quick-fix: We'll put query 85 onto the blacklist.

**Comment by janetzki** [comment]
The happens for Q24 if we exclude the missing `UPPER` function.
