### ISSUE TITLE
Table returns wrong `max_chunk_size`?

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1792]
I don't know whether this is intended behavior:

The second [constructor](https://github.com/hyrise/hyrise/blob/4561d65c35d7cee9e07e049ae75b8c5a96e0cd64/src/lib/storage/table.cpp#L39) of `Table` is used by, e.g., the `GetTable` operator for creating a new data table without the pruned chunks. For this table `_max_chunk_size` is set to `Chunk::MAX_SIZE` even though the chunk size did not change compared to the original table.

**Comment by mrks** [comment]
max_chunk_size is effectively only needed by the insert operator. I have a branch where #749 is addressed and found that it will likely need to change, anyway. It's semantics are that new chunks are created after the last chunk has n rows (current behavior) or that new chunks have n rows pre-allocated (new behavior). We will then have one constructor for data tables and one for reference tables. For the latter, max_chunk_size will be unset.

**Comment by Bensk1** [comment]
It came up because we need the table's chunk size for the cost modelling. If I understand your description correctly, neither new nor old behavior would work with the current second constructor that is used in GetTable because it generates a data table and sets the size to Chunk::MAX_SIZE. Would you change GetTable to generate reference tables to make it work?

**Comment by mrks** [comment]
Got it. Maybe we need a third table type `Pruned` that (a) copies the max_chunk_size and (b) makes appends illegal?

**Comment by Bensk1** [comment]
Sounds reasonable to me.

**Comment by mrks** [comment]
In #1967, we decided that "max_chunk_size" (now target_chunk_size) has no defined semantics for referencing tables.

**Comment by Bensk1** [comment]
Also, the Table's constructor that is used by GetTable now sets the chunk size to Chunk::DEFAULT_SIZE instead of Chunk::MAX_SIZE
