### ISSUE TITLE
JoinSortMerge Benchmarks fail

### ISSUE THREAD

**Issue by d-justen** [hyrise/hyrise#1798]
Executing the `SortMergeSemiProbeRelationSmaller` and the `SortMergeSemiProbeRelationLarger` benchmarks in the `TPCHDataMicroBenchmark` both results in this error:
```console
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/operators/join_sort_merge.cpp:64 JoinHash doesn't support these parameters
```

These two benchmarks don't work since more than 3 months ago (specifically from here: https://github.com/hyrise/hyrise/commit/c2d90a17d1812366b2b7fd5f5d52de53f46edb07) without anyone ever noticing, so maybe we should think about a way to test this in the CI. Opinions?

**Comment by Bouncner** [comment]
That was a screw up on my side. The semi join benchmark was meant to test whether it’s worth implementing a semi join with the sort merge join. Before the test runner PR, we could misuse the sort merge join easily.

That should not have been committed. But anyhow, I would not run the micro benchmarks as part of the CI. At least I use them solely for developing and performance measuring. It’s more of a template for benchmarking that anything else.
