### ISSUE TITLE
Optimize comparisons of AbstractExpressions

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1803]
As the TPC-C will introduce more short-running queries, reducing the time spent in the optimizer becomes more important. This issue shall be a collection of ideas (one per comment). Please add your comments by editing the top-level comments lest this becomes unreadable.

**Comment by mrks** [comment]
`AbstractExpression::hash()` currently performs a deep hash. Test if hashing the type and maybe the type of its top-level arguments is sufficient for a low number of collisions.

**Comment by mrks** [comment]
Join ordering should only be performed if we have three tables or more.

**Comment by mrks** [comment]
abstract_expression.cpp:

```
bool AbstractExpression::operator==(const AbstractExpression& other) const {
  if (type != other.type) return false;
  if (!expressions_equal(arguments, other.arguments)) return false;
  return _shallow_equals(other);
}
```

`_shallow_equals` should be checked before we descend into the expressions.

**Comment by Bouncner** [comment]
> Join ordering should only be performed if we have three tables or more.

I know it’s more a note than a concrete task, but I’d guess  the threshold is rather the number of tuples to join than the number of tables. Even for three tables I would expect huge impacts of “wrong” join orders.

**Comment by mrks** [comment]
That's why I said "three or more". I'd like to remove those comments here so that we have a cleaner list. I think it's easier to have the discussion within the top-level comments.

**Comment by Bouncner** [comment]
Ok

**Comment by tobodner** [comment]
Do we have some means to distinguish "simple transactions" from "complex queries"? For simple transactions, we could try to exit early in the rule engine. The same mechanism may help to decide between JIT compilation and regular execution/interpretation down the road.
