### ISSUE TITLE
Optimize UNION in JoinGraphBuilder

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1829]
The JoinGraphBuilder cannot optimize a `UNION` that was introduced by the PredicateSplitUpRule because the join predicates would be above the `UNION` and the joins below it but the JoinGraph is built for nodes below and above vertices separately.
Therefore, we currently run the PredicateSplitUpRule twice: once before the JoinOrderingRule without disjunction split-up, and once after it with disjunction split-up.
If the JoinGraphBuilder supports `UNION`, we just need to run the PredicateSplitUpRule once before the JoinOrderingRule with disjunction split-up.
#1791 removes the `_parse_union()` function, which reverts the disjunction split-up. This could be a starting point for the new implementation.
TPC-H 7 and 19 are interesting queries to verify the correctness.

**Comment by mrks** [comment]
In the past months, were I spent a good amount of time looking at different optimizations, I haven't seen any major problem with the current approach. While it might be slightly more efficient if the JoinGraphBuilder knew how to handle this, it would also increase the complexity of the join ordering components. Not sure if that is worth the trade-off.

Additionally, I don't see anyone working on these components in the near future. The benefit of someone working their way into join graphs just to address this is probably limited.

Closing this for now.

**Comment by mrks** [comment]
(This is still referenced in optimizer.cpp, so the thought won't get lost:)

```
  // Run before the JoinOrderingRule so that the latter has simple (non-conjunctive) predicates. However, as the
  // JoinOrderingRule cannot handle UnionNodes (#1829), do not split disjunctions just yet.
  optimizer->add_rule(std::make_unique<PredicateSplitUpRule>(false));
```
