### ISSUE TITLE
Memoization: Add test

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1835]
There should be one test for diamond structures in the LQPTranslator and one for the memoization.

**Comment by mweisgut** [comment]
https://github.com/hyrise-mp/hyrise/blob/b054f0ccbf6d16f8ecb41bc7188167cdfc5eea04/src/benchmarklib/tpch/tpch_queries.cpp#L247-L254

**Comment by mweisgut** [comment]
scheduled for tuesday

**Comment by mweisgut** [comment]
A test for diamond structures is already in the test suite:
https://github.com/hyrise/hyrise/blob/23733d077ddb556cd759a230b0a3c2c2ebe14529/src/test/logical_query_plan/lqp_translator_test.cpp#L648-L694
