### ISSUE TITLE
Index join NULL value handling

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#1850]
Single segment indexes can handle NULL-values since #1800. Consequently, also the index join can be adjusted to be able to handle NULL values.

**Comment by mrks** [comment]
Could you give an example on how NULL values are relevant for a join?

**Comment by mweisgut** [comment]
Since the index scan on the index side is only executed if the probe value is not NULL, NULL-values should not be relevant for the index join.

https://github.com/hyrise/hyrise/blob/f79e2c99deb902bdc8632147ed6183c8cfcd015e/src/lib/operators/join_index.cpp#L332-L384
