### ISSUE TITLE
Find (and fix) index join bugs using the join test runner

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#1852]
With #1851 many different join index test configurations are created and therefore a comprehensive test suite for the index join is executed. By executing these tests, bugs are revealed which are currently not documented and investigated in detail.
Therefore, the following lines are currently commented out:
```c++
// INSTANTIATE_TEST_SUITE_P(JoinIndex, JoinTestRunner,
//                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinIndex>()));
```

**Comment by mrks** [comment]
When working on this, start by picking up where #1851 left off.
