### ISSUE TITLE
Clean up overlap between JoinPredicateOrderingRule and JoinOrderingRule

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1860]
The AbstractJoinOrderingAlgorithm already orders predicates based on their selectivity:

https://github.com/hyrise/hyrise/blob/7e98ab168755dfe00f31bb67056fb1b915357f87/src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp#L69-L79

I guess the JoinPredicateOrderingRule does more because it also handles the join predicates introduced by the SubqueryToJoinRule. We should either (a) teach the SubqueryToJoinRule to also order its predicate or (b) remove the ordering from the AbstractJoinOrderingAlgorithm and entirely rely on the JoinPredicateOrderingRule.

**Comment by mrzzzrm** [comment]
JOR *has* to impose some order in order to judge the cost of a subplan. Not optional to do this there, I think.

**Comment by mrks** [comment]
(1) The linked code is part of `AbstractJoinOrderingAlgorithm::_add_join_to_plan` - at that point, this does not seem mandatory.
(2) Is this really necessary? Why is the order of two join predicates on the same table important for a join ordering algorithm?

**Comment by mrzzzrm** [comment]
Well, the logical cost estimator will not care about predicate order - true. But for a general estimator, the order of join predicates would influence the cost of a candidate plan. Plan X might well be the most optimal plan for a subgraph but we will never learn if we do not order its join predicates properly.

**Comment by mrzzzrm** [comment]
If a join has two predicates, one very selective and one not very selective, changing the order of these two will result in vastly differently expensive plans, no?

**Comment by mrks** [comment]
> But for a general estimator, the order of join predicates would influence the cost of a candidate plan.

Agreed.

> If a join has two predicates, one very selective and one not very selective, changing the order of these two will result in vastly differently expensive plans, no?

Absolutely, and I am not saying that we should stop ordering them.

My point is that at the position cited above, the join ordering has already been decided. I am not sure if there is another place hidden inside the join ordering algorithms that *also* orders join predicates by selectivity. At this time, however, it does not matter if we do the ordering now (as one of the final steps of the JoinOrderingRule) or if we wait for the JoinPredicateOrderingRule to do it together with ordering the joins created by the SubqueryToJoinRule.

What we should do is decide who is responsible for the join predicate order.

**Comment by mrks** [comment]
Blocked by #1560

**Comment by mrks** [comment]
Similarly, we should question whether _add_predicates_to_plan needs to bring the predicates in an efficient order or if the PredicateReorderingRule is sufficient.
