### ISSUE TITLE
Benchmarks: Table sorting should be disableable

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1874]
It takes a good amount unproductive time, esp. when you're working on something unrelated. AFAICT there is no command line option to disable it.

**Comment by Bouncner** [comment]
Disableable!

**Comment by mrzzzrm** [comment]
It's googleable, therefore its existence is undebatable

**Comment by mrks** [comment]
Wouldn't #1864 make this a non-issue?

**Comment by Bouncner** [comment]
I wouldn’t say that this solves the issue.

**Comment by Bouncner** [comment]
I wouldn’t say that this solves the issue.

**Comment by mrks** [comment]
@Bouncner: Did you regularly have to change this in the code since October? As #2023 removes the cost of sorting the table, I again consider this to be a non-issue.

**Comment by Bouncner** [comment]
Feel free to close.
