### ISSUE TITLE
Enable Wshadow-field, Wshadow-field-in-constructor

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1877]
Currently, we have `-Wno-shadow-field-in-constructor` (and `-Wno-shadow-field` once we upgraded to clang 8) set. The idea is to have constructor arguments that match the fields that they fill:

```
TableColumnDefinition::TableColumnDefinition(const std::string& name, const DataType data_type, const bool nullable)
    : name(name), data_type(data_type), nullable(nullable) {}
```

This is problematic, as I just had to experience:

```
TableStatistics::TableStatistics(std::vector<std::shared_ptr<BaseAttributeStatistics>>&& column_statistics,
                                 const Cardinality row_count)
    : column_statistics(std::move(column_statistics)), row_count(row_count) {
      if constexpr (HYRISE_DEBUG) {
        // Check that the histogram height is not higher than the row_count. Lower is OK as NULL values are not
        // represented.
        for (const auto& single_column_statistics : column_statistics) {
```

`column_statistics` in the last line refers to the parameter, not the field. As the vector has been moved from, accessing it gives us an empty vector, but is actually UB. While `this->column_statistics` would work, it is a bad workaround.

We should find a common naming pattern for these cases.

**Comment by mrks** [comment]
Maybe  -Wshadow-field-in-constructor-modified is enough?

**Comment by mrks** [comment]
How do you feel about `new_` as a prefix? E.g.:

```
TableColumnDefinition::TableColumnDefinition(const std::string& new_name, const DataType new_data_type, const bool new_nullable)
    : name(new_name), data_type(new_data_type), nullable(new_nullable) {}
```

Other style guides solve this by having all class members annotated (e.g., `m_*` or `*_`), but I don't think we want to change that.

**Comment by Bouncner** [comment]
Don’t know where I’ve got that from but I usually use a underscore suffix (`name_`). Would that prefer over new, because what means new anyway?

**Comment by mrks** [comment]
> what means new anyway

Admittedly not much. In fact, we don't want to communicate anything here, we are just working around a smell in the language.

> Don’t know where I’ve got that from but I usually use a underscore suffix

That doesn't communicate anything either. Given that underscores are usually used to mark members of some type, this could lead to confusion for people who come from different code styles.

Also, it implies some syntactical relevance (cf. protected members). If we did that for every constructor argument, that might be fine, but we are only looking at those cases where we have a field with the same name. More specifically, this is something that the compiler would currently not complain about:

```
class A {
A (int i) : _i(i) {}

protected:
int _i;
};
```

Unless we plan to change this to `A (int i_) : _i(i_) {}`, I believe this "syntax" to be ambiguous.

Don't get me wrong though. I hate "new_" almost as much.

**Comment by Bouncner** [comment]
Good point with `_i{i_};`. That’s madness.
Since `constr_` would be confusing with const, constructor, and constexpr: maybe something like `init_` to signal the value with which the object is initialized?

**Comment by mrks** [comment]
Another example of this being an issue:

**Comment by mrks** [comment]
Adding another option: `*_in`.

Let's decide between these options on Wednesday:
* `init_name`
* `new_name`
* `name_in`

**Comment by mrks** [comment]
Decided for init_.
