### ISSUE TITLE
Different LQPs are equal when compared

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1898]
The test
```cpp
node_a = MockNode::make(MockNode::ColumnDefinitions{{DataType::Int, "a"}}, "a");
a_a = node_a->get_column("a");

node_b = MockNode::make(MockNode::ColumnDefinitions{{DataType::Int, "a"}}, "b");
b_a = node_b->get_column("a");

// clang-format off
const auto actual_lqp =
PredicateNode::make(equals_(a_a, 10),
  node_a);

const auto expected_lqp =
PredicateNode::make(equals_(b_a, 10),
  node_b);
// clang-format on

EXPECT_LQP_EQ(actual_lqp, expected_lqp);
```
should fail but actually succeeds. It seems that `node_a` and `node_b` are assumed to be identical.

**Comment by mrks** [comment]
For StoredTableNodes, this would be expected. For MockNodes, it is debatable. We could change `MockNode::_on_shallow_equals` to `return this == &rhs`, but I am not sure how much that breaks.

**Comment by mrks** [comment]
With #1029, we will take the name of the MockNode into account
