### ISSUE TITLE
SortedSegmentSearch for Between

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1916]
Using the l_shipdate order should help us in TPC-H Query 6. Also, we should make sure that the ordered_by property survives, e.g., the validate operator.

**Comment by Bouncner** [comment]
Are we sure that the flag would survive the scan? I remember that the PosList sorting in some cases might cause problems?

**Comment by mrks** [comment]
That should not be an issue, as all operators on the way `guarantee_single_chunk`.

**Comment by mrks** [comment]
Closing this as it is tracked in Trello and the seminar list
