### ISSUE TITLE
Make benchmark --runs parameter default to infinity

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1919]
The current max of 10000 runs means that a multi-threaded run of TPC-H 6 runs for less than there seconds on nemea. Not enough for reliable numbers. Instead of arbitrarily increasing that value, we should let it default to -1, meaning infinity.

I prefer -1 over 0 because I sometimes use `-r 0` to generate an empty JSON file for comparison.

**Comment by tobodner** [comment]
Good idea. -1 is consistent with GTest (https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#repeating-the-tests) and maybe avoids some confusion in our development workflow.
