### ISSUE TITLE
console load with encoding fails on mutable chunks

### ISSUE THREAD

**Issue by j-tr** [hyrise/hyrise#1920]
Console::_load_table tries to encode all chunks, even if they are mutable

Possible solutions: 
* finalize the last chunk
* encode only immutable chunks

**Comment by Bouncner** [comment]
@j-tr : Since you list two options and the solving PR does not mention it in the description: how did you fix the issue eventually?

**Comment by tobodner** [comment]
> @j-tr : Since you list two options and the solving PR does not mention it in the description: how did you fix the issue eventually?

Hi Martin, since I reviewed the mentioned change: We went with option 2 (please refer to src/bin/console/console.cpp).

**Comment by Bouncner** [comment]
That looks like a quick fix to me. Basically now `encode_all_chunks` is very likely to throw. Shouldn't we rename it to `encode_all_immutable_chunks()` and check within the function that only immutable chunks are encoded?

**Comment by mrks** [comment]
We should ask ourselves what the purpose of that method is. For me, it sounds like "I'm done, compress it.", in which case, I would expect the last chunk to be finalized

**Comment by Bouncner** [comment]
I think it's actually an artificial situation that we are currently in where every chunk is immutable. In a realistic scenario with reads and writes, that's never going to be the case. And I think the encoder should support this case.
Plus, the name `encode_all_immutable_chunks()` directly reflects Hyrise's encoding concept where only immutable chunks can be encoded.

**Comment by tobodner** [comment]
> We should ask ourselves what the purpose of that method is. For me, it sounds like "I'm done, compress it.", in which case, I would expect the last chunk to be finalized

@j-tr, @mrks: I gave this some more thought and generally agree with @mrks. While option 2 fixes the initial problem of failing loads, option 1 is cleaner in that it is easier to reason about the end product: all chunks are encoded and "kind of ready" for subsequent experiments.

**Comment by tobodner** [comment]
> > We should ask ourselves what the purpose of that method is. For me, it sounds like "I'm done, compress it.", in which case, I would expect the last chunk to be finalized
> 
> @j-tr, @mrks: I gave this some more thought and generally agree with @mrks. While option 2 fixes the initial problem of failing loads, option 1 is cleaner in that it is easier to reason about the end product: all chunks are encoded and "kind of ready" for subsequent experiments.

Do you prefer rephrasing the initial issue and reopening it or creating a new issue?

**Comment by Bouncner** [comment]
> option 1 is cleaner in that it is easier to reason about the end product: all chunks are encoded and "kind of ready" for subsequent experiments.

Yes, option one is cleaner from a pure "I want to run my synthetic benchmark" point of view. But I am not arguing about option 1 or option 2. I simply think that the `encode_all_chunks()` method is no longer useful now that we need to check for immutability and I think the code that is in the console (gathering immutable chunks) will be written a lot now because encoding does not make sense if the chunk is mutable.

**Comment by j-tr** [comment]
my idea was to restore the table exactly like the initially exported table. so encoding chunks that weren't encoded before would somehow alter the table, which I would not expect from an import/export functionality. 
however, i noticed that this quick fix basically "solves" the problem by not encoding at all. since the export does not export any information about the mutablility of the chunks, they are all mutable when constructed and consequently no chunks are ever encoded. 
In my opinion, it would be best, to export also the mutability information per chunk and encode only mutable chunks during import.

**Comment by Bouncner** [comment]
Please don't get me wrong here. My comment was triggered by your change, but I am fine with the PR. It's just the general question, what the chunk encoder should do.

And I am too lazy to open a new topic where we have to repeat the discussion.

**Comment by j-tr** [comment]
got it. but still, my code effectively does nothing which is not how i intended it and right now the user gets a message saying "... using [some encoding]" which could be confusing since nothing is encoded. So there is a more basic flaw in the code than the general question about the chunk encoder.
