### ISSUE TITLE
Change install.sh to install_dependencies.sh?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1922]
"Install" sounds like we would install Hyrise somewhere, which people might not want.

**Comment by tobodner** [comment]
Another established term is "bootstrap".

**Comment by mrks** [comment]
So far, I have only seen "bootstrap" in boost, where it has a different meaning:

> The directory specified by that location and the directories in BOOST_BUILD_PATH are then searched for a file called bootstrap.jam, which is expected to bootstrap the build system. This arrangement allows the build system to work without any command-line or environment variable settings.

Also, bootstrap is a name of an npm package.

Let's vote:
* install_dependencies (matches DEPENDENCIES.md, more popular on Google)
* install_prerequisites (similar to gcc's download_prerequisites)
* bootstrap
* (any other suggestions?)

I'd stick with the first.

**Comment by Bouncner** [comment]
I am fine with `bootstrap` but would assume that it also builds Hyrise. Hence,` install_dependencies` would be my favorite.
I wouldn't vote against any of the proposals though.

**Comment by tobodner** [comment]
Here is another example of bootstrap: https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh
This instance also builds the project in question, so @Bouncner's intuition is kind of right.

No hard feelings either way on my side, so install_dependencies?

**Comment by tobodner** [comment]
Alternatively, we could make the script more interactive and potentially include the build phase. The advantage would be that first-time or one-shot users would not need to manually put together their CMake build configuration strings. Not sure how much pain we cause others there, but https://github.com/hyrise/hyrise/issues/1914#event-2799069832 would have had it easier, I guess.

**Comment by tobodner** [comment]
Also, what do you think about moving this file to the scripts directory to cleanup our root directory a little?

**Comment by mrks** [comment]
> Alternatively, we could make the script more interactive and potentially include the build phase.

Why not - we just have to decide on gcc vs. clang on Linux. I'd go with gcc, but just out of personal preference.

> Also, what do you think about moving this file to the scripts directory to cleanup our root directory a little?

Nah, if we want it to be the central entry point to everything, it should be right there.

**Comment by Bouncner** [comment]
Do we have current numbers for Ubuntu with the latest compilers? I don’t have preferences, but defaulting to the faster compiler would make most sense IMO.

**Comment by tobodner** [comment]
> Why not - we just have to decide on gcc vs. clang on Linux. I'd go with gcc, but just out of personal preference.

With an interactive script, we can ask the user for her preference, defaulting to GCC.

**Comment by tobodner** [comment]
> Nah, if we want it to be the central entry point to everything, it should be right there.

That is a reasonable consideration as well *tumbs up*

**Comment by tobodner** [comment]
> Do we have current numbers for Ubuntu with the latest compilers? I don’t have preferences, but defaulting to the faster compiler would make most sense IMO.

@Bouncner: Faster in terms of compilation time or execution time?

If we default to clang on macOS, defaulting to GCC on Linux would make our coverage a little broader, hopefully detecting compiler-specific issues earlier.

**Comment by Bouncner** [comment]
Since the Linux variant will be the variant that others will use to benchmark and compare Hyrise, I’d vote for the fastest compiler in terms of (TPC-H) runtime.

**Comment by tobodner** [comment]
> Since the Linux variant will be the variant that others will use to benchmark and compare Hyrise, I’d vote for the fastest compiler in terms of (TPC-H) runtime.

Here is a comparison conducted on nemea (gcc -> clang). So, gcc is about 10% faster.

```diff
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s       | runs | new iter/s         | runs | change [%] |              p-value |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
+| TPC-H 01       | 0.5999099016189575 | 36   | 0.6333151459693909 | 38   | +6%        | (run time too short) |
-| TPC-H 02       | 10.782068252563477 | 647  | 9.682209014892578  | 581  | -10%       | (run time too short) |
-| TPC-H 03       | 7.682195663452148  | 461  | 6.449994087219238  | 387  | -16%       | (run time too short) |
-| TPC-H 04       | 6.149466514587402  | 369  | 4.8161702156066895 | 289  | -22%       | (run time too short) |
-| TPC-H 05       | 4.16607141494751   | 250  | 3.8160903453826904 | 229  | -8%        | (run time too short) |
 | TPC-H 06       | 99.23423767089844  | 5955 | 99.11084747314453  | 5947 | -0%        | (run time too short) |
-| TPC-H 07       | 7.665952205657959  | 460  | 6.716401100158691  | 403  | -12%       | (run time too short) |
-| TPC-H 08       | 6.61630392074585   | 397  | 5.6162333488464355 | 337  | -15%       | (run time too short) |
 | TPC-H 09       | 1.6330819129943848 | 98   | 1.599839448928833  | 96   | -2%        |               0.0000 |
-| TPC-H 10       | 2.9331514835357666 | 176  | 2.533158540725708  | 152  | -14%       | (run time too short) |
-| TPC-H 11       | 19.514755249023438 | 1171 | 16.015382766723633 | 961  | -18%       | (run time too short) |
-| TPC-H 12       | 15.965913772583008 | 958  | 14.148241996765137 | 849  | -11%       | (run time too short) |
+| TPC-H 13       | 3.1996777057647705 | 192  | 3.3999080657958984 | 204  | +6%        |               0.0000 |
-| TPC-H 14       | 31.462820053100586 | 1888 | 26.31363868713379  | 1579 | -16%       | (run time too short) |
-| TPC-H 15       | 34.91408157348633  | 2095 | 33.028160095214844 | 1982 | -5%        | (run time too short) |
-| TPC-H 16       | 6.466497421264648  | 388  | 5.749339580535889  | 345  | -11%       | (run time too short) |
-| TPC-H 17       | 1.6499314308166504 | 99   | 1.3165924549102783 | 79   | -20%       |               0.0000 |
-| TPC-H 18       | 0.5999724864959717 | 36   | 0.5166541934013367 | 31   | -14%       | (run time too short) |
 | TPC-H 19       | 49.8462028503418   | 2991 | 49.59983444213867  | 2976 | -0%        | (run time too short) |
-| TPC-H 20       | 2.3332438468933105 | 140  | 1.9830968379974365 | 119  | -15%       |               0.0000 |
-| TPC-H 21       | 2.2499921321868896 | 135  | 1.8666045665740967 | 112  | -17%       |               0.0000 |
 | TPC-H 22       | 17.26554298400879  | 1036 | 16.68305778503418  | 1001 | -3%        | (run time too short) |
-| geometric mean |                    |      |                    |      | -10%       |                      |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
```

**Comment by mrks** [comment]
Just realized a disadvantage of a single `bootstrap.sh` script: Currently, we have three steps - set up the environment, run cmake, run make (or ninja). If this is done all at once, it becomes more difficult for people to understand where they need to start if they want a second (e.g., release) build folder. Also, they might be tempted to run the bootstrap script to recompile. To prevent this, we would have to make our documentation more complicated, bringing us back to square one.

I'll open a PR for install_dependencies.sh.
