### ISSUE TITLE
Do we need the JSON configuration of benchmarks?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1926]
Instead of passing configuration options on the command line (`--clients 100`), we can also pass a JSON file:

```
============================
Benchmark Configuration JSON
============================
All options can also be provided as a JSON config file. This must be the only
argument passed in. The options are identical to and behave like the CLI options.
Example:
{
  "scheduler": true,
  "time": 5
}

The JSON config can also include benchmark-specific options (e.g. TPCH's scale
option). They will be parsed like the
CLI options.

{
  "scale": 0.1
}
```

The idea was that it makes benchmarks easier to re-execute. However, in the year(s) that this option exists, I have never used it outside of testing that very option.

If anyone uses it, we should keep it. Otherwise, "deleted code is debugged code". (Jeff Sickel)

**Comment by Bouncner** [comment]
There options that are not covered by the terminal params, right? E.g. encoding per column.

**Comment by mrks** [comment]
No, the encoding json, supplied via `-e` is yet another thing

**Comment by Bouncner** [comment]
Ok, apparently I have never used it. 😁

Removing it is ok for me.
