### ISSUE TITLE
Missing RunLengthSegment and FrameOfReferenceSegment tests

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1928]
I can't find anything that actually tests those segments. For funsies, I removed the part in run_length_encoder.hpp that identifies a continuing run and nothing broke.

While the generic encoding tests make sure that data does not get lost, we should still make sure that the encoding serves its purpose.

Also, I find this part in run_length_segment.hpp confusing:

> As in value segments, null values are represented as an additional boolean vector.

I would remove that sentence and change a sentence a couple of lines above (including a typo fix):

> Each run is represented by the value and the number of **occurrences. Runs can also be NULL, in which case `values` is undefined (but likely `T{}`) and `null_values` is set to true for that run.**

**Comment by Bouncner** [comment]
The  new comment makes sense.

But apart from that I cannot reproduce the problem. I changed the start index in RLE and a big chunk of tests broke. Can you provide the exact change?

Or do you mean that you basically enforced runs of length one and we do not check that?

**Comment by mrks** [comment]
> Or do you mean that you basically enforced runs of length one and we do not check that?

Exactly. Having an encoding that does not lose any data is nice, but as the whole idea of the encoding is a certain in-memory representation, we should make sure that this is the case.
