### ISSUE TITLE
SQL COPY command

### ISSUE THREAD

**Issue by tobodner** [hyrise/hyrise#1933]
Our new server implementation lacks support for
- loading/importing data from files into tables
- unloading/exporting data from tables into files

In order to facilitate experiments and benchmarks, we should support the SQL COPY command:
- https://www.postgresql.org/docs/current/sql-copy.html
- We may want to support more file formats than vanilla PostgreSQL, like Snowflake (https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-table.html)

**Comment by Bensk1** [comment]
Because we need this functionality soon for the bachelor's project, @dey4ss is going to work on it. The SQL standard of 1992 does neither contain a COPY or IMPORT command. Currently, the SQL parser is able to handle IMPORT but being consistent with PostgreSQL wouldn't be too bad.

**Comment by tobodner** [comment]
> Because we need this functionality soon for the bachelor's project, @dey4ss is going to work on it. The SQL standard of 1992 does neither contain a COPY or IMPORT command. Currently, the SQL parser is able to handle IMPORT but being consistent with PostgreSQL wouldn't be too bad.

Since the server supports Postgre's wire protocol, it seems most consistent to also align with Postgre's (derivative) SQL features.

**Comment by dey4ss** [comment]
Supporting the `COPY` command would require its implementation in the SQLParser. Therefore, I suggest to first add the general file import first by adding an LQPNode for it. Afterward, the specific interface could be adapted. Anyhow, the parser would need a little work on it since it is only aware of `.tbl` and `.csv` files.

**Comment by dey4ss** [comment]
The parser should be able to understand the COPY statement with my PR there (unfortunately I cannot request a review there). On the Hyrise side, I am currently after a (hopefully last) little bug, then imports will be supported. Afterward, I am going to add exporting functionality there.

**Comment by Bensk1** [comment]
Nice! Would it be a lot of effort to move the branch to our repo and file a new PR?

**Comment by dey4ss** [comment]
> 
> 
> Nice! Would it be a lot of effort to move the branch to our repo and file a new PR?

I think this would not be a problem I had write access to the parser repository :D

**Comment by Bensk1** [comment]
Ah, I thought this was for the hyrise/hyrise repo and not for the parser. Let's keep it like this for now.

**Comment by dey4ss** [comment]
The PR passes all tests now, I think it would make sense to merge the Parser PR first so I can add the new ImportTypes to the Hyrise file type translation and merge the Hyrise PR after the Parser PR (so we do not need to touch it later again).

**Comment by Bensk1** [comment]
Agreed

**Comment by mrks** [comment]
What's missing here?

**Comment by Bensk1** [comment]
Currently, we can import data. @dey4ss wants to provide the export part as well.

**Comment by mrks** [comment]
@Bensk1 @dey4ss Could you comment on the current state of this? Is something missing?

**Comment by Bensk1** [comment]
As far as I know, nothing should be missing.
