### ISSUE TITLE
Database checkpoints

### ISSUE THREAD

**Issue by tobodner** [hyrise/hyrise#1938]
Hyrise lacks means for persistency (i.e., logs and checkpoints a.k.a. the D in ACID).

Here is a brief proposal and design sketch for database checkpoints:
- No requirement for database log
- Based on MVCC version information (just another query)
- Based on import/export
- Schema information
- As asynchronous background task
  - Plugin
  - Scheduler integration

**Comment by mrks** [comment]
Is there any progress being made here? In one of the last fortnightlies, we decided to slim down the issue list and make it less of a wish list.

**Comment by tobodner** [comment]
This is a wish list item. Feel free to archive/remove it.
