### ISSUE TITLE
CSV loading in console is broken

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1945]
```
(release)> load resources/test_data/csv/int_float.csv
Loading resources/test_data/csv/int_float.csv into table "int_float"
Encoding "int_float" using Unencoded
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/storage/chunk_encoder.cpp:101 Only immutable chunks can be encoded.
Abort trap: 6
```

Add this (and tbl/bin import) to the pyexpect tests

**Comment by j-tr** [comment]
i cannot reproduce this on the current master. 
https://github.com/hyrise/hyrise/blob/4afbe3c9ff8865e180b647f6c4107da4906fe12c/src/bin/console/console.cpp#L593 should avoid encoding mutable chunks.

**Comment by mrks** [comment]
Weird. I thought I was on the master. Sorry.
