### ISSUE TITLE
TableScan's _scan_sorted_segment broken

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1950]
In cases where all values of a segment are equal or NULL and the search value is larger than the segment's value (in case of NULL the search value does not matter), `scan_sorted_segment` fails because it receives a BeginIterator that is equals to the EndIterator and then tries to dereference it.

**Comment by Bensk1** [comment]
It's even worse than I thought it would be. An equals predicate on a sorted segment and a search value that is larger than any value in the segment is sufficient.

**Comment by mrks** [comment]
Scary.
