### ISSUE TITLE
Semi join breaks references_single_chunk

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1964]
Found in #1958

old: https://hyrise-ci.epic-hpi.de/job/hyrise/job/hyrise/job/master/350/artifact/query_plans/tpcds/73-PQP.svg
new: https://hyrise-ci.epic-hpi.de/job/hyrise/job/hyrise/job/master/351/artifact/query_plans/tpcds/73-PQP.svg

This is not really related to the IN estimation, instead the validate now operates on more rows and takes 17 instead of 2 ms. @Bensk1 any idea why the magic MVCC optimization does not apply here?

**Comment by mrks** [comment]
Ah, this is caused by the semi join, which takes part in predicate ordering but does not produce a `references_single_chunk` PosList. I wonder if we can change the hash join in a way where, for 0 radix bits, we produce one result chunk for each input chunk.

That should also be good for parallelization, as we currently have only one chunk for most of the query plan.

**Comment by mrks** [comment]
Also pinging @Bouncner on this

**Comment by Bouncner** [comment]
Radix counts are difficult. I thought about making them dependent on the current scheduler (one small radix table is the most efficient and fastest in ST, but impacts all following operators with MT).
Yielding the “same” should be possible for the probe site. I don’t think there is a cheap way for the build site (without major rewrites), but I am not sure.

**Comment by Bouncner** [comment]
I have an old branch that clusters the results and returns (even sorted) chunks. Wasn’t worth it, but that was before sorting optimizations and smart pos lists.
