### ISSUE TITLE
Meta Tables: tables are created multiple times when being queried

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1979]
As discussed in #1968, meta tables are generated several times during a query.

Apparently, they are created 10 times during the SQL translation. What might be needed is something that allows users of the storage manager to retrieve the properties of the meta tables without generating the actual rows and then having the GetTable operator finally creating the rows.

**Comment by mrks** [comment]
@j-tr Is this resolved? If yes, please remember to add `fixes #...` to the PRs. If not, what is missing?
