### ISSUE TITLE
NULL behaviour in PosList.common_chunk_id()

### ISSUE THREAD

**Issue by leogeier** [hyrise/hyrise#1983]
It is possible that NULL behaviour in `PosList.common_chunk_id()` is faulty similarly to `ReferenceSegmentIterables` in #1421.
If the first value of the PosList references a NULL value, `common_chunk_id()` will return INVALID_CHUNK_ID. Calling code may not be aware of this.

For instance, the ChunkID retrieved in `validate.cpp:69` in  `_validate_chunks()`  would trigger the DebugAssert in `Table::get_chunk()`. The same thing happens in `abstract_dereferenced_column_table_scan_impl.cpp`.

Since guaranteeing to return a valid chunk id might be expensive, it may be ok just to make the caller aware of this problem (e.g. by renaming the function or adding a comment).

(discovered with @He3lixxx and @Xperianer)

**Comment by mrks** [comment]
> Since guaranteeing to return a valid chunk id might be expensive, it may be ok just to make the caller aware of this problem (e.g. by renaming the function or adding a comment).

Could we just have `guarantee_single_chunk` test that the first chunk ID is not invalid?
