### ISSUE TITLE
Storage Manager is not thread-safe

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1991]
The bachelor's project is currently discussing the parallel loading of benchmark tables (e.g., TPC-H) via the network interface. @Bensk1 and me just looked into the storage manager and we are not sure if parallel loading is safe.
Bot appear to be fine (insertion/deletion invalidate iterators, which wouldn't be a problem here), but calling `table_names()` can be UB when the iterator is invalidated in parallel.

Since the storage manager is probably not on any critical path, we could potentially use a simple `lock_guard` solution. Any opinions?

**Comment by mrks** [comment]
Locking inserts into StorageManager::_tables only makes sense if you also lock reads.

**Comment by Bouncner** [comment]
Yeah sure. Do you think that will have a performance impact?

**Comment by mrks** [comment]
Hopefully not too much. However, before we touch that, we should clearly define which concurrency guarantees we give and which we don't. "Don't do DDL concurrently with anything" is easier to understand than "Don't do DDL concurrently unless you add tables, but that won't be visible to already running transactions or maybe it might because GetTable retrieved a different table than Insert and now everything goes to hell".

On the other hand, it should make generating the TPC-H data faster, and I like that.

**Comment by mrks** [comment]
What's the status on this?

**Comment by Bensk1** [comment]
For the BP we have an implementation that does exactly the same as the methods manipulating views in the StorageManager. We could either stick with that or using a concurrent TBB data structure. Is there any preference?

**Comment by mrks** [comment]
Does it have any performance impact for MT on all nemea cores?

> we should clearly define which concurrency guarantees we give and which we don't.

Just realized that we should be fine if we declare `(add|get|has)_table` to be MT-safe and `drop_table` to be unsafe. The problems only come when you replace one table with another, which you can only do by dropping the existing one first.

**Comment by Bensk1** [comment]
Average over three TPCH runs on nemea with `-q 6 --scheduler --clients 200 -s 0.01:`

```
- Current: 2868420 executions
- TBB map: 2856636 executions
- Lock:    2238213 executions
```

I think the small difference of the `tbb::concurrent_hash_map` is either noise or should be acceptable. Should we also change the synchronization mechanism of the views? What do you think?

**Comment by mrks** [comment]
Sounds good. Couple of things:

> Should we also change the synchronization mechanism of the views?

(1) Makes sense. We can benchmark that with Q15, right?
(2) I'd consider preallocating maybe 100 entries for both maps.
(3) Please be aware of the concurrency limitations and invalidations of the data structure: https://software.intel.com/en-us/node/506194

**Comment by Bensk1** [comment]
(1): yes, but I would not expect that to differ from the `get_table()` performance, do you?
(2): that should work.
(3): that sounds like trouble. "The concurrent operations (count, find, insert, and erase) invalidate any iterators pointing into the affected instance even with a const qualifier. It is unsafe to use these operations concurrently with any other operation." Does that mean that multiple concurrent `find` operations are also unsafe?

**Comment by mrks** [comment]
(4) Thinking about it, I would reconsider the use of concurrent_hash_map in favor of concurrent_unordered_map. While the latter does not allow the removal of elements, its concurrency guarantees are much easier to understand. Instead of removing entries, we could simply set them to `nullptr` and would only have to add a `!= nullptr` check to the accessing methods in the StorageManager.

Might need to run another benchmark for this, but I'd expect it to be similar.

(5) The benchmark was the thing that you ran across all nodes, correct? These type of things tend to hide their performance issues well until multiple nodes access the lock-free data structure.

**Comment by mrks** [comment]
(1) I would expect something similar, but it will be interesting to see if the removal of that lock has any benefits.

**Comment by Bensk1** [comment]
(1) Maybe in such an extreme scenario, but most definitely not for the typical ST SF 1 benchmark.
(5) Correct, on all nodes with 200 threads.

**Comment by Bensk1** [comment]
It works, but all the `nullptr` checks in the `*_table` methods are a bit annoying.

**Comment by mrks** [comment]
Shouldn't be more than a handful of places and nothing outside of storage_manager.cpp, should it?

**Comment by mrks** [comment]
This seems to apply to prepared plans, too, doesn't it?

**Comment by Bensk1** [comment]
_This_ in terms of prepared plans cannot be added in a thread-safe way? Then, yes.

**Comment by Bensk1** [comment]
I added the figures for the `tbb::concurrent_unordered_map` above.

**Comment by mrks** [comment]
Looks like the way to go then. 

> This in terms of prepared plans cannot be added in a thread-safe way? Then, yes.

This means that the prepared plan part in the server is probably not thread-safe right now, doesn't it? We have a number of stress tests that should easily reveal that.

**Comment by Bensk1** [comment]
No performance difference when changing the views from using the mutex to a tbb::concurrent_unordered_map

**Comment by Bensk1** [comment]
> Looks like the way to go then.
> 
> > This in terms of prepared plans cannot be added in a thread-safe way? Then, yes.
> 
> This means that the prepared plan part in the server is probably not thread-safe right now, doesn't it? We have a number of stress tests that should easily reveal that.

At least the StorageManager part cannot be thread-safe. I would just add a another `tbb::concurrent_unordered_map` for the prepared plans then. Also, there are (and have been before) storage manager tests for views and tables but not for the prepared plans. I would add them. That should be it, right?

**Comment by mrks** [comment]
As far as I know, yes.
