### ISSUE TITLE
ColumnPruning Rule causes an error when running CREATE TABLE AS...

### ISSUE THREAD

**Issue by jackvincenow** [hyrise/hyrise#1996]
Running this script with the ColumnPruningRule will return an error: "Did not expect a useless join". Disabling the rule will run it as expected.

Here is the script to reproduce:
```
create table a1(x1 int, x2 int);
insert into a1 values (1,2);
create table b1(y1 int, y2 int);
insert into b1 values (1,2);
create table ab1 as select * from a1 join b1 on x2=y2;
```
Error:

src/lib/optimizer/strategy/column_pruning_rule.cpp:226 

> Did not expect a useless join

Detailed output:

[PERF] Hyrise is running as a debug build. at src/lib/utils/performance_warning.cpp:9
Performance can be affected. This warning is only shown once.

HYRISE SQL Interface

Type 'help' for more information.

Hyrise is running a (debug) build.

(debug)> create table a1(x1 int, x2 int);

=== Columns

|      OK|

|     int|

|not null|

===

0 rows total

Execution info: [PARSE: 53 µs 689 ns, SQL TRANSLATE: 1 ms 262 µs, OPTIMIZE: 4 ms 332 µs, LQP TRANSLATE: 888 µs 529 ns, EXECUTE: 11 ms 666 µs (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]

(debug)> insert into a1 values (1,2);

===

0 rows total

Execution info: [PARSE: 16 µs 552 ns, SQL TRANSLATE: 1 ms 12 µs, OPTIMIZE: 4 ms 48 µs, LQP TRANSLATE: 1 ms 203 µs, EXECUTE: 2 ms 919 µs (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]

(debug)> create table b1(y1 int, y2 int);

=== Columns

|      OK|

|     int|

|not null|

===

0 rows total

Execution info: [PARSE: 26 µs 226 ns, SQL TRANSLATE: 170 µs 235 ns, OPTIMIZE: 3 ms 97 µs, LQP TRANSLATE: 214 µs 136 ns, EXECUTE: 1 ms 90 µs (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]

(debug)> insert into b1 values (1,2);

===

0 rows total

Execution info: [PARSE: 20 µs 954 ns, SQL TRANSLATE: 167 µs 119 ns, OPTIMIZE: 3 ms 485 µs, LQP TRANSLATE: 252 µs 36 ns, EXECUTE: 677 µs 185 ns (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]

(debug)> create table ab1 as select * from a1 join b1 on x2=y2;

terminate called after throwing an instance of 'std::logic_error'

  what():  src/lib/optimizer/strategy/column_pruning_rule.cpp:226 Did not expect a useless join

**Comment by mrks** [comment]
We're working towards a paper deadline at the moment, so for the time being, please use the ColumnPruningRule workaround. Will fix soon.
