### ISSUE TITLE
Merge dereference position list implementations

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#200]
In at least two operators, functions are implemented that dereference a position list, i.e., they take a position list of a reference column and turn it into a position list of the underlying value or dictionary column.

The first implementation is in `JoinNestedLoopB::_dereference_pos_list`, the other one in `TableScan::on_execute` but there are probably more locations.

The task is to generalize the algorithm and extract it into a nicely parameterized method.

**Comment by mjendruk** [comment]
@mrzzzrm Is this related to #760? This didn’t seem possible to do because the dereferencing and caching mechanisms differ from join to join. Close?

**Comment by mrzzzrm** [comment]
While the JoinHash does things a bit different, I can't comment without further investigation whether it's impossible to merge e.g. the implementations from TableScan and SortMergeJoin.
