### ISSUE TITLE
Dynamically Load Plug-Ins and Persist Settings

### ISSUE THREAD

**Issue by dey4ss** [hyrise/hyrise#2003]
As we can load/unload plug-ins with the Console, we would like to also be able to do so via the server. The suggested approach is to do this with a new meta table: SELECT shows the loaded plug-ins, INSERT loads new ones and DELETE unloads them.
Since plugins (and other components) may have settings, we would like to have a central point for showing and changing those settings. This can also be done via a meta table.

Steps needed are:
- [x] add new meta tables `meta_plugins` and `meta_settings` in MetaTableManager that show the plugins fetched from the PluginManager/all settings that are configurable in Hyrise
- [x] for each meta table: indicate if an operation is valid
- [x] forward mutations to meta tables
- [x] add settings and a settings manager
- [x] tests

**Comment by dey4ss** [comment]
@Bensk1 @mrks Starting to impelemt what we discussed earlier, some questions came up to my mind:

1. updating/deleting in meta tables: As I know generating some meta tables takes a lot of time, I thought about making these operations not taking too long. When altering those "tables" as usual, we would need to generate the tables again to find the rows that match in the specific function. That is why I suggest to be the first column of such meta tables a key. Then, we would only need to generate the table in the MetaTableManager, find the rows and do the update directly.
2. inputs for update/delete/insert to meta tables: I thought about checking if the values match the column definitions of the meta tables. Let us assume the settings table we discussed. We cannot alter the description there, so we can only update name/value. Should the MetaSettingsTable only accept updates à la ('name', 'value') which does not fit the resulting table or ('name', 'value', 'description') and ignore the description? This also affects wehere we check if the values have the right format; the first version needs to be checked by the implementation, the second one can be checked by the abstract class looking on the column definitions, which are a member variable.

**Comment by mrks** [comment]
1: Not sure if I can follow. What do you mean by making them a key? Hyrise does not really have the notion of keys yet. In any case, the generation of meta tables being expensive is more a problem of the segments_accurate table (where a lot of work is done) and shouldn't be one for the settings table.
2: If I remember correctly, the update operator gets two input tables: References to the rows being updated and the new values. The second table is always complete (i.e., holds all columns), and values that are not modified are copied from the existing table. Thus, you will always get a value for the description. We could check if the description matches the old one if that does not take more than maybe five lines of code, but I won't lose sleep if modifications to the description are simply ignored.

**Comment by dey4ss** [comment]
1. Alright, I thought there can also be expensive meta table generations in the future. What came into my mind was that we do not want to generate the table for mutating operations then. If we would have a completely distinct column there, (likely the first one, that's what I meant with a key), we would not need to generate the result table for mutating operations rather than only doing one single <whatever is done by the operator> with that key (e.g. plugin name in plugins, settings name in settings, ...) . But if we do not expect generating mutable meta tables being expensive, this will not be a problem and we can generate the meta table to find out which tuples to update.
2. Okay, I only wanted to know where we can be save asserting the column definitions vs the values provided. If we always get a full table on UPDATE or DELETE (and we don't mind generating the meta table before for that), we can check if the values match the column definitions in the abstract meta table, as it will be the same for all derived classes. If we expect those table generations to be costly, it would be nicer to update/delete them if they can be identified with one key attribute. But that would be knowledge ot the derived classes and we needed to check the value format there.

**Comment by mrks** [comment]
The entire table being materialized and the changed rows being passed into Update is not a "feature" of the Update operator, but deeply ingrained in the way we handle updates across the translators. Changing that won't be easy (and hopefully not necessary).

In any case, I expect the expensive meta tables to be read-only. Currently this is only the exact collection of segment information. As such, I would hope that those are two disjoint problems.

**Comment by mrks** [comment]
#873 is the issue that I mentioned in our face-to-face discussion about meta_settings.

**Comment by dey4ss** [comment]
I have already talked to @Bensk1 about inserting and deleting in Meta tables a couple of minutes ago. We would like to go via the MetaTableManager, which is called by the operators, to manipulate meta tables. The problem is that an update results in an insert and a delete. Meta tables could have different access policies (e.g. settings may be updated, but not deleted). Now it is impossible to tell if a delete (or insert) operation may be done or not. We discussed two possibilities:

1. Leave everything as it is. The SQLParser asks a meta table which operation it supports and throws errors if the opertion is not allowed.
2. Add a flag in the remove/insert operator that tells if it was created from an update context. This flag would probably only be used in this specific case and is useless for any other operation.

Are there any further ideas, e.g. from @mrks ?

**Comment by mrks** [comment]
This sounds familiar. I seem to remember that we once considered making Update check its `table_to_update_name` for `meta_` and directly update the properties instead of using delete+insert.

We should still have a check in the SQLTranslator (not parser) if the table can be inserted into/updated/deleted from so that we can throw an input exception.

**Comment by dey4ss** [comment]
So would this be fine? I guess that's actually nicer and it is clear what is done with the table.

Of course this check would be done, too (by the SQLTranslator, typo 😄).

**Comment by mrks** [comment]
Sounds good

**Comment by dey4ss** [comment]
Another thing I just realized: The delete operator does not know the name of the table it deletes values from, but that is of course neccessary to determine if it is a meta table. Making this an optional constructor field would be the easiest way, I guess (so the interface for deleting from normal tables stays the same.)

**Comment by mrks** [comment]
Hmpf. I'd like to avoid adding any more meta table forks. For my taste, we are already building too many for a feature that has nothing to do with actual database operators. If we need to keep meta tables in mind in too many components, this makes our live difficult.

Maybe a link from Table to the meta class would be an idea. That could also be checked by the StaticTableNode in order to avoid a flag in the node @j-tr .

**Comment by dey4ss** [comment]
What would also leave the usual components the way they are could be a ManipulateMetaTable operator/node with a flag indicating the manipulation type. Then we would only have to do minor changes to the SQLTranslator without touching the other operators or the table.

**Comment by mrks** [comment]
> What would also leave the usual components the way they are could be a ManipulateMetaTable operator/node with a flag indicating the manipulation type

I'm not sure what needs to happen in the SQLTranslator for that, but if you think that this could be done, it sounds cleaner.

> Another note on settings

Interesting question. Isn't `Hyrise::reset()` something that's called exclusively in tests (that don't have command line parameters)? I'm not sure if we would want to call it in the console or the server.

**Comment by dey4ss** [comment]
> Interesting question. Isn't `Hyrise::reset()` something that's called exclusively in tests (that don't have command line parameters)? I'm not sure if we would want to call it in the console or the server.

Okay, I saw in #873 that there might be command-line options for tests. If it is okay not to support this, it is perfect to re-initialize the SettingsManager on `Hyrise::reset()`.

**Comment by mrks** [comment]
No, command line arguments for tests was a bad idea. Sorry.

**Comment by dey4ss** [comment]
@Bensk1 @mrks Earlier today we talked about transactions and meta table manipulations and that the meta table mutation operator should only be executed in auto-commit transactions. As far as I understand it right now, the SQLPipeline statement is the last element in the whole pipeline that knows if a transaction context was given (and gets a new one if not). I.e., the operator does not know whether it is called during a transaction or an auto-commit statement (as a transaction context is always provided). If we want to fail if a meta table is mutated during a transaction, I only see two options right now: (i) let SQLPipelineStatement check if the query plan manipulates a meta table (e.g. with a flag in SQLTranslator) or  (ii) adding a flag to TransactionContext if it is a real transaction or auto-commit (and let the operator fail then). I somehow dislike both. Does anyone have a better idea (or do I maybe miss some obvious things)?

**Comment by mrks** [comment]
The second option doesn't sound that bad to me. Whether a TransactionContext is auto-commit or not is an information that seems reasonable to keep. For instance, we could have an optimized version of the Validate operator that does not check the tid value for auto-commit transactions. Not saying we should do that, but it shows that such a flag would go beyond a hack just for the meta modification operator.
