### ISSUE TITLE
(Really) run SQLite tests with scheduler

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2014]
Currently, the scheduler is reset by BaseTest. The solution is to run

```
  Hyrise::get().topology.use_numa_topology();
  Hyrise::get().set_scheduler(std::make_shared<NodeQueueScheduler>());
```

as part of SQLiteTestRunner::SetUp, not SQLiteTestRunner::SetUpTestCase. However, this currently fails. I suspect #1643 to be the culprit.

**Comment by Bouncner** [comment]
Can't say for sure that test 106 (see #1643) is no longer a problem after #2315, but at least this test does not crash.

What crashes with an enabled scheduler is the following query:

Note: Google Test filter = *Line391WithUnencoded*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SQLiteTestRunnerUnencoded/SQLiteTestRunner
[ RUN      ] SQLiteTestRunnerUnencoded/SQLiteTestRunner.CompareToSQLite/Line391WithUnencoded
1
0x7fa33120fed8
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/operators/abstract_operator.cpp:72 Operator is already being executed.
[1]    12410 abort      ./hyriseTest --gtest_filter="*Line391WithUnencoded*"
Play around branch:
martin/#1643. Looks like the aggregate in the subquery is already executed?

**Comment by Bouncner** [comment]
Pinging @julianmenzler here. Sorry for the confusion, I posted this text in the wrong issue and Markus pinged you there.

Tests 34 and 390 fail as well, but less often. 391 triggers it every time on my laptop.

**Comment by julianmenzler** [comment]
<img width="706" alt="Untitled" src="https://user-images.githubusercontent.com/9380917/111286531-958de500-8642-11eb-8874-2c3e746fe357.png">

The scheduler schedules both inputs of the JoinHash for parallel execution. 
The TableScan uses the ExpressionEvaluator to spontaneously execute the first Projection which is already being executed as part of the JoinHash's right input. 

To fix the issue, we need to implement some waiting logic, maybe in conjunction with a state model for operators.

**Comment by mrks** [comment]
Yes please. This should have priority over #2312, as it looks as if we broke something here. Maybe we could discuss options tomorrow?

**Comment by julianmenzler** [comment]
> Maybe we could discuss options tomorrow?

Ok, so then I don't start with the code before our discussion.

**Comment by mrks** [comment]
Your call. If you find time to write code for this before tomorrow, by all means feel free to do so. :)
