### ISSUE TITLE
attribute distinct has some problem

### ISSUE THREAD

**Issue by k-lee9575** [hyrise/hyrise#2035]
`select count(distinct A) from table`
`select distinct A from table`

the two sql statements are all legal
but the second distinct is not recognized

then I read the source code and  find the attribute  distinct  is attached to function count but not column A

I think distinct should be equal to count as a special function

**Comment by mrks** [comment]
Mmh, I can't reproduce an issue:

```
(debug)!> load resources/test_data/tbl/int_float.tbl t
Loading resources/test_data/tbl/int_float.tbl into table "t"
Encoding "t" using Unencoded
(debug)> SELECT COUNT(DISTINCT a) FROM t
=== Columns
|COUNT(DISTINCT a)|
|             long|
|         not null|
=== Chunk 0 ===
|<ValueS>         |
|                3|
===
1 rows total
Execution info: [PARSE: 14 µs 510 ns, SQL TRANSLATE: 387 µs 664 ns, OPTIMIZE: 1 ms 142 µs, LQP TRANSLATE: 144 µs 873 ns, EXECUTE: 341 µs 146 ns (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]
(debug)> SELECT DISTINCT a FROM t
=== Columns
|       a|
|     int|
|not null|
=== Chunk 0 ===
|<ValueS>|
|   12345|
|     123|
|    1234|
===
3 rows total
Execution info: [PARSE: 6 µs 704 ns, SQL TRANSLATE: 139 µs 508 ns, OPTIMIZE: 899 µs 758 ns, LQP TRANSLATE: 71 µs 740 ns, EXECUTE: 245 µs 896 ns (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]
```

Could you provide us with the steps to reproduce?

> then I read the source code and find the attribute distinct is attached to function count but not column A

Which part of the code are you looking at?

**Comment by k-lee9575** [comment]
in sql-parser stage， after parse it will generate a struct SelectStatement，
refer [Expr.h](https://github.com/hyrise/sql-parser/blob/master/src/sql/Expr.h)

line87-lin108
`struct Expr {
    Expr(ExprType type);
    virtual ~Expr();

    ExprType type;

    // TODO: Replace expressions by list.
    Expr* expr;
    Expr* expr2;
    std::vector<Expr*>* exprList;
    SelectStatement* select;
    char* name;
    char* table;
    char* alias;
    double fval;
    int64_t ival;
    int64_t ival2;
    DatetimeField datetimeField;
    bool isBoolLiteral;

    OperatorType opType;
    bool distinct;
`
in line108 has a attribute distinct, is it means keyword DISTINCT or only for function type node?

if I use `select distinct A from ...` 

I can't find any distinct information in SelectStatement 
but if I use `select count(distinct A) from...` the count node's distinct is set as thue.

so, is there any detail I ignore？
thanks for help

**Comment by mrks** [comment]
The code that you quoted is from the expression. In `SELECT DISTINCT a`, the "distinct" is not a property of `a` but of the entire select query. As such, you will find it in SelectStatement::selectDistinct.

**Comment by k-lee9575** [comment]
thanks for your help
