### ISSUE TITLE
Bug: Endless loop in AbstractTableGenerator when the first value of the sorting column is NULL

### ISSUE THREAD

**Issue by aloeser** [hyrise/hyrise#2079]
Some benchmarks define sort orders, e.g. `lineitem` is sorted by `l_shipdate`
To avoid unnecessary sorting, the AbstractTableGenerator performs a check whether the table is already sorted.
This leads to an endless loop, if the first value of the sorting column is NULL.

Possible fix: add an `it++` before the `continue` in https://github.com/hyrise/hyrise/blob/master/src/benchmarklib/abstract_table_generator.cpp#L68

**Comment by mrks** [comment]
That's the bad part about while loops :/
