### ISSUE TITLE
Bug (?): SyntheticTableGenerator can't generate NULL values

### ISSUE THREAD

**Issue by ramboldio** [hyrise/hyrise#2082]
For the column calibration we wanted to explore how NULL values affect Scan performance.
During this we encountered that with the current version of
the Synthetic Table Generator it is not possible to generate these values.

Is this a bug?

On this branch the issue can be reproduced when running the playground:
https://github.com/ramboldio/hyrise/commit/443f8066bc80663a731b97b8e2d27d47a6757646

```
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/resolve_type.hpp:76 data_type cannot be null.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by mrks** [comment]
NULL is not available as the type of a column, however the data generator should have a null_ratio parameter. If, for some reason, you want a column that is entirely NULL, just set that value to 1 (i.e., 100%).

**Comment by mrks** [comment]
Did you look into this again? Anything we can do here?
