### ISSUE TITLE
Do we still use NUMAMemoryResource/pgasus?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2087]
Nothing wrong with it, but if we don't use it anymore, it shouldn't be lying around.

**Comment by mrks** [comment]
If we keep it in, we should have a look why this happens in a clean Docker image on imresx01:

```
[ RUN      ] NUMAMemoryResourceTest.BasicAllocate
/hyrise/src/test/memory/numa_memory_resource_test.cpp:39: Failure
Expected equality of these values:
  get_node_id_of(vec.data())
    Which is: 32766
  numa_node
    Which is: 1
[  FAILED  ] NUMAMemoryResourceTest.BasicAllocate (1 ms)
```

**Comment by Bouncner** [comment]
Since one of the major selling points of the chunking concept is potential NUMA placement optimization, I'd keep it in.
Somebody should do his master's thesis about that.

**Comment by mrks** [comment]
As discussed in person: Bringing it back in is as simple as reverting the commit that removes them and is almost guaranteed to be free of conflicts. Removing for now, as it is simply useful, but dead code.
