### ISSUE TITLE
Fix TestCacheAndSchedulerInitialization

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2088]
This has failed in a number of branches. Instead of

```
    // Wait to run the server and set the scheduler
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
```

(which I just increased), we should have a proper programmatic approach.

**Comment by mrks** [comment]
This is failing regularly. @dey4ss, could you have a look, please?

**Comment by dey4ss** [comment]
Would it be okay to let the server tell us if `run()` is completed via a `finished_setup()` method or something? Then we could wait until everything is ready the way it also is in a "real" scenario.

**Comment by mrks** [comment]
Are you talking about an actual callback or an `initialized` flag?

**Comment by dey4ss** [comment]
Basically a flag we check. Like
``` c++
server.cpp:
void run() {
  ...
  _finished_setup = true;
}

bool finished_setup() { return _finished_setup; }
```

``` c++
server_test_runner.cpp:
void SetUp() {
  _server_thread = std::make_unique<std::thread>(server_runner, std::ref(*_server));
  while (!server->finished_setup()) {
    // wait
  }
}
```

**Comment by mrks** [comment]
Yepp. If that works, we can do it like that.

**Comment by dey4ss** [comment]
Alright, I'm gonna add this
