### ISSUE TITLE
JoinIndex: support for JoinMode::Semi with IndexSide::Left

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2119]
Since #1851, the index join doesn't support a join scenario where the join mode is `JoinMode::Semi` and the index side is `IndexSide::Left`.

We claimed that
> if a Semi or Anti* join is executed, the left side is outputted by definition. Choosing the index join when indexes are not available for the right table would not be beneficial.

and
>For Semi or Anti* joins, the left side is the probe side, so the index needs to be on the right.

This might be true for the Anti* joins, but I'm not sure if this holds for every Semi join scenario. While inspecting [TPC-H PQPs](https://hyrise-ci.epic-hpi.de/job/hyrise/job/hyrise/job/master/lastStableBuild/artifact/query_plans/tpch/), I found some Semi join scenarios where the left input is a data table and the right input a relatively (very) small reference table. Using an indexed data table is the fastest execution path in the index join implementation. I could imagine that the index join can be profitable here. Currently, we cannot use an index join for that scenario.

The example below is an excerpt from the PQP of TPC-H Query 7.
![TPC-H_07-PQP_support_semi_left_side_indexed](https://user-images.githubusercontent.com/20044656/81067456-f9059d00-8ede-11ea-845c-24f6ed892c2b.png)

**Comment by mrks** [comment]
Yepp. I was too influenced by the hash join, which has that limitation. While it makes the code more complicated (at least in the hash join), it should be possible to probe the left side.

**Comment by Bouncner** [comment]
Good catch.
