### ISSUE TITLE
Scan shortcut: Use EntireChunkPosList

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2130]
If we store whether DictionarySegments contain NULL values, we can skip the scan here for non-NULL segments:

https://github.com/hyrise/hyrise/blob/ca9e9248357e1a1fdda76052726dab8389e57d92/src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp#L109-L114

@Bouncner: You are working on this type of meta information, aren't you?

**Comment by Bouncner** [comment]
Yes, sir.

**Comment by mrks** [comment]
Cool. I'll wait for that then. Was tempted to test this and ignore the NULL check, but as we just killed our benchmark system... :(

**Comment by mrks** [comment]
Not as easy as I thought. `_scan_dictionary_segment` is called multiple times in case we are scanning a ReferenceSegment. As such, we need to fill a RowIDPosList and cannot simply use a EntireChunkPosList. Skipping _scan_with_iterators alone and simply filling `matches` in a loop doesn't bring significant savings for Q6.
