### ISSUE TITLE
LZ4 binary exports appear to be corrupt

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2143]
Reproducible with executing the following command twice (first to create the binaries, second will read them): `./hyriseBenchmarkTPCH -e LZ4 -r 1 -s 0.1`.

The second TPC-H run segfaults in Q7:
```- Benchmarking TPC-H 07
[1]    4851 segmentation fault  ./hyriseBenchmarkTPCH -e LZ4 -r 1 -s 0.1
```

Tested on e54ee0 on MacOS and Linux (strangely, here Q5 failed).

**Comment by Bensk1** [comment]
@dey4ss could you have a short look at it for a first assessment of the issue? Bouncner said there is no need to hurry.

**Comment by dey4ss** [comment]
Yes of course, but I guess it will take some time for me to understand how LZ4 works 😅

**Comment by mrks** [comment]
I'm not sure if that is necessary. You could take the failing segment, export it, import it, and compare the objects element for element.

**Comment by Bouncner** [comment]
My bad, I thought it has been your implementation @dey4ss . @j-tr , could you have a look when you find the time?

**Comment by dey4ss** [comment]
Okay, the fault seems to be caused by [this assert](https://github.com/hyrise/hyrise/blob/ef808c8f16a000d7110c6515d5b7f389d7622dc1/src/lib/storage/lz4_segment.cpp#L266).

**Comment by dey4ss** [comment]
Nvm, while executing Q5 we call `_decompress_block_to_bytes()` with a block index of 1 where we only have one block. This does not fail immediately as we access the block vector with `[]` and the result is crap.

**Comment by j-tr** [comment]
not perfectly related to this... but if we the benchmark loads cached TPCH tables and needs to re-encodes them, do we want them to be cached in the new encoding or should the binary files stay untouched?
Currently it states that in the output that the files are saved but they actually aren't. This could potentially lead to confusion.

**Comment by mrks** [comment]
No strong opinion about this. They are re-encoded using dictionary encoding when the benchmark is run again without the `-e` parameter, right?

If yes, I'd say we leave it as is and change the text. It is more probable that the benchmark is run again with the same encoding, isn't it?

**Comment by j-tr** [comment]
right. but imagine running it one time with dictionary encoding and then a thousand times with lz4. thats where we would like the cache to take action but its not.

**Comment by mrks** [comment]
Oups. Read it the other way round. Agreed.
