### ISSUE TITLE
Use magic_enum in more place or remove it

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2154]
Thanks to magic_enum, introduced in #2073, this is now unnecessary:

```
const boost::bimap<EncodingType, std::string> encoding_type_to_string = make_bimap<EncodingType, std::string>({
    {EncodingType::Dictionary, "Dictionary"},
    {EncodingType::RunLength, "RunLength"},
    {EncodingType::FixedStringDictionary, "FixedStringDictionary"},
    {EncodingType::FrameOfReference, "FrameOfReference"},
    {EncodingType::LZ4, "LZ4"},
    {EncodingType::Unencoded, "Unencoded"},
});
```

Have a look at
* constant_mappings.hpp,
* types.cpp,
* SegmentAccessCounterAccessType::Count
* all uses of boost::bimap

If we are lucky, we can get rid of boost::bimap and upgrade to gcc-10 (#2074).

However, in #2325, we found that TSan reports data races caused by this line:

https://github.com/hyrise/hyrise/pull/2325/commits/ac35110ac41f488719a37fb0469b698645b4b703#diff-6e22d80821367cc3c2dbfd38c45747ac82bb5658d371447dd481b51bbaae2a0aL96

A quick look at magic_enum did not reveal any obvious reason for this. There is a good chance that this is a false positive. However, we should understand it before we add magic_enum to more places lest we get more surprising TSan warnings.

**Comment by Bensk1** [comment]
Related to: https://github.com/hyrise/hyrise/pull/2411#discussion_r735849390

**Comment by Bouncner** [comment]
We are using `magic_enum` is various places and haven't seen any TSAN issues for a long time.
As nobody is going to replace the bimaps any time soon, I will close this issue.
