### ISSUE TITLE
Specifically install lld-9

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#2175]
This was already done in #2167 but led to problems with gcc in #2169

**Comment by Bouncner** [comment]
Has anybody encountered problems since this discussion? The last MacOS and Ubuntu installs worked fine for me.

There is an issue, when we manually install clang11 and use an older lld-version for LTO builds. But that's probably an edge case?

**Comment by mrks** [comment]
Nope, didn't pop up again. I didn't specifically look for it though.

**Comment by Bensk1** [comment]
> Nope, didn't pop up again. I didn't specifically look for it though.

Same for me. I wouldn't feel bad about closing it and reopening it later.

**Comment by Bouncner** [comment]
Ok, I'll close it for now.
