### ISSUE TITLE
Python formatting broke pandas script

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2177]
Example:

```python
# Old:
rolling = filtered_df[filtered_df["success"] == True].copy()

# Changed to:
rolling = filtered_df[filtered_df["success"] is True].copy()
```

Pandas does not work that way. As (1) I am currently on a different branch and (2) this might be broken in other places, too, I am opening an issue instead of fixing it right away.

**Comment by Bouncner** [comment]
Is that `== True` required for Pandas filters or could we remove that altogether and get rid of the linter issue?

**Comment by mrks** [comment]
This particular issue was fixed in #2259 thanks to @julianmenzler. We should still check if we can somehow avoid `black` breaking our code in the future.

**Comment by Bouncner** [comment]
Wasn’t rather inperfect code than a black issue?

**Comment by mrks** [comment]
`== True` being pointless does not give black the right to break it...

**Comment by Bouncner** [comment]
And being pointless makes it imperfect.

**Comment by Bouncner** [comment]
HP does not want us to write imperfect code.

**Comment by mrks** [comment]
> And being pointless makes it imperfect.

Would you like us to port the scripts from Python to Vigil?

**Comment by Bouncner** [comment]
What is the english term for Lochkarten?

**Comment by mrks** [comment]
Turns out that this was not a `black` issue, but a `flake8` one. It is known but cannot be fixed: https://github.com/PyCQA/pycodestyle/issues/450

**Comment by mrks** [comment]
I believe that this was a one-time thing when @Bensk1 changed the Python scripts to comply with the linting rules and made that seemingly harmless modification. Since the linter now complains right away, this should not happen again.
