### ISSUE TITLE
LQP and/or PQP caches take up GBs

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2178]
I was investigating why the memory consumption was increasing constantly and not dropping to idle levels between different TPC-H items:

![Screenshot 2020-06-30 at 17 45 59](https://user-images.githubusercontent.com/575106/86147409-a79e1680-baf9-11ea-919e-b429e851dbf7.png)

The biggest jump in the orange line is TPC-H 15. I then ran `./hyriseBenchmarkTPCH -q 14,15,16 --metrics -o bothcaches.json` on the current master:

![bothcaches](https://user-images.githubusercontent.com/575106/86153002-48dc9b00-bb01-11ea-8cb0-e49f1a6c31a5.png)

For Q15, you can see the point where all query variations are cached. As there are only 58 of them, it seems as if each takes 13 MB.

Here it is with the PQP cache disabled:

![lqponly](https://user-images.githubusercontent.com/575106/86153280-b2f54000-bb01-11ea-857f-86a937e098f9.png)

And here without any plan caching:

![nocaches](https://user-images.githubusercontent.com/575106/86154093-e5ec0380-bb02-11ea-8370-ec3ed45ab96b.png)

Thoughts:
- [ ] Check why the LQP cache entries are that big in the first place.
- [ ] Evict more aggressively?
- [ ] Track actual cache size to help with eviction decisions?
- [ ] Does query parametrization help?
- [ ] How to detect these issues in the future?

**Comment by mrks** [comment]
More thoughts:

* Some operators (Delete, Insert, UnionPositions?) store their input tables. Operators should not do that, as it prevents tables from being released. If they do, they should at least implement `_on_cleanup`. Not sure how to enforce this.
* This gets aggravated when these operators are cached. Should we move to a model where a deep copy of the PQP is stored in the PQP cache? That would prevent operators that do not properly clean up after themselves from wasting memory once they are in the cache and only used for reproduction (hihi). However, it might make @Bouncner and @Bensk1 sad.
* The last operator's output is cached indefinitely as OperatorTask only calls clear_output on predecessors.
* Work done so far can be found in mrks/caching_explosion

**Comment by mrks** [comment]
Should `~SQLPipelineStatement` call clear_output on the top operator? @julianmenzler

**Comment by julianmenzler** [comment]
> For Q15, you can see the point where all query variations are cached. As there are only 58 of them, it seems as if each takes 13 MB.

The current changes of #2254 seem to have reduced the memory consumption for Q15. Per query variation, from 13 MB down to ~1.5 MB.

![metrics](https://user-images.githubusercontent.com/9380917/101081927-0127d700-35ab-11eb-92bb-d4a2b1f4e568.png)

**Comment by mrks** [comment]
@julianmenzler Fixed in #2254?

**Comment by julianmenzler** [comment]
> @julianmenzler Fixed in #2254?

I think so:

![bothcaches_master](https://user-images.githubusercontent.com/9380917/110634458-45c69e00-81aa-11eb-8383-d6cb41a4085a.jpg)
