### ISSUE TITLE
Clean up contributor guidelines

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2190]
@julianmenzler replaced some `#if HYRISE_DEBUG` with `if constexpr ...`. He also changed the `DebugAssert`s within to regular asserts. I think regular asserts make sense if we already have the debug check above.

Didn't want to add it to CONTRIBUTING.md just yet, as I feel like the list is becoming harder to read and to remember. Should we clean it up a bit and try to put the Top 10 rules on the top?

**Comment by mrks** [comment]
@Bensk1 - We should probably tackle this before we start DYOD.

**Comment by Bensk1** [comment]
I agree.

**Comment by mrks** [comment]
Regarding the issue originally discussed here: I think whether we use DebugAssert or Assert within an `if constexpr` block is too minor to put it into the guidelines. While it makes sense to make this consistent, the retentiveness when reading the guidelines is limited. If this becomes inconsistent, it won't jeopardize the success of Hyrise.
