### ISSUE TITLE
AggregateHash performance steps are broken

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2203]
This doesn't add up:

<img width="568" alt="Screenshot 2020-08-31 at 13 36 52" src="https://user-images.githubusercontent.com/575106/91716016-15fd6480-eb8f-11ea-9fc2-16db14fb6641.png">

**Comment by Bouncner** [comment]
Can you tell me the query id?

**Comment by mrks** [comment]
1 with SF .01.

I think I fixed it, but I'm still looking into something else.
