### ISSUE TITLE
Live-reporting of benchmarks should contain correct latency

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2226]
Single-Threaded:

```
- Benchmarking TPC-H 01
  -> Executed 76 times in 60.6665 seconds (1.25275 iter/s, 0.798243 s/iter)
```

Multi-Threaded:
```
- Benchmarking TPC-H 01
  -> Executed 1281 times in 60.0062 seconds (21.3478 iter/s, 0.0468432 s/iter)
```

`compare_benchmarks.py`, however, reports the latency correctly as the arithmetic mean of iterations:

```
+----------++----------+---------+---------++----------+----------+---------+---------+
| Item     || Latency (ms/iter)  |  Change || Throughput (iter/s) |  Change | p-value |
|          ||      old |     new |         ||      old |      new |         |         |
+----------++----------+---------+---------++----------+----------+---------+---------+
| TPC-H 01 ||    798.2 |  2284.9 |  +186%  ||     1.25 |    21.35 | +1604%  |  0.0000 |
```

**Comment by mrks** [comment]
While at it, please harmonize the units (ms/iter vs s/iter) and the order in which latency and throughput are reported.

**Comment by mweisgut** [comment]
If a query's execution is still in process after the query execution time limit is exceeded, the execution continues in single-threaded mode. In multi-threaded mode, however, the execution is aborted. We should add an info message that tells the user when a query execution is aborted in a multi-threaded benchmark execution.
