### ISSUE TITLE
unexpected identifier - decimal

### ISSUE THREAD

**Issue by tglanz** [hyrise/hyrise#2232]
hi,

am trying to create a tpch schema which includes decimal types but getting a syntax error saying that __decimal__ is an unexpected identifer.

also tried to use the tpcds schema in the repository with the same effect, taken from https://github.com/hyrise/hyrise/blob/1f1537eb6af695987bb0858a78293b1d2e147f62/resources/benchmark/tpcds/schema.sql#L9

so,

- is it expected? are decimals unsupported or am i missing something?
- if decimals are unsupported, what is the alternative?

the specific error

```bash
Invalid input error: SQL query not valid.
SQL query:
==========
create table store_sales
(
    ss_sold_date_sk           integer                       ,
    ss_sold_time_sk           integer                       ,
    ss_item_sk                integer               not null,
    ss_customer_sk            integer                       ,
    ss_cdemo_sk               integer                       ,
    ss_hdemo_sk               integer                       ,
    ss_addr_sk                integer                       ,
    ss_store_sk               integer                       ,
    ss_promo_sk               integer                       ,
    ss_ticket_number          integer               not null,
    ss_quantity               integer                       ,
    ss_wholesale_cost         decimal(7,2)                  ,
                              ^=== ERROR HERE!
    ss_list_price             decimal(7,2)                  ,
    ss_sales_price            decimal(7,2)                  ,
    ss_ext_discount_amt       decimal(7,2)                  ,
    ss_ext_sales_price        decimal(7,2)                  ,
    ss_ext_wholesale_cost     decimal(7,2)                  ,
    ss_ext_list_price         decimal(7,2)                  ,
    ss_ext_tax                decimal(7,2)                  ,
    ss_coupon_amt             decimal(7,2)                  ,
    ss_net_paid               decimal(7,2)                  ,
    ss_net_paid_inc_tax       decimal(7,2)                  ,
    ss_net_profit             decimal(7,2)                  ,
    primary key (ss_item_sk, ss_ticket_number)
);
==========
Error line: 13
Error column: 30
Error message: syntax error, unexpected IDENTIFIER
```

**Comment by mrks** [comment]
Hi,

Hyrise does not (yet) support decimals. Instead we use floats. At least for TPC-H, this is legal as per the specification. I am not sure about TPC-DS. 

For running the TPC-DS benchmark, we strongly suggest the hyriseBenchmarkTPCDS binary or, in the console, the `generate_tpcds` command.

**Comment by tglanz** [comment]
@mrks awsome thank you!

Indeed after loading the TPC schemas (H and DS), I notice now that the corresponding fields are floats.

Might be out of topic, but is there some way to serve the loaded schemas?
Either by some automatically loading it in a running hyriseServer process, or by opening a server through the hyriseConsole?
- If not, does a "serve" command in hyriseConsole sounds viable/helpful?

**Comment by mrks** [comment]
Could you clarify what you mean with "serve"? Something like "show create table" in MySQL?

That does not exist yet. You can look up the definition of the tables and columns using `SHOW TABLES` and `SHOW COLUMNS`.

An issue is that we do not support the full `CREATE TABLE` syntax yet. Most importantly, the primary key constraints cannot yet be set via the SQL interface. As such, a TPC-H/DS table created using that way would be less efficient than one created by the `generate_*` methods.

**Comment by mrks** [comment]
Maybe you could describe what you are trying to do on a more general level?

**Comment by tglanz** [comment]
This is really outside of the issues scope so feel free to close and move this.

Specifically, what I meant,
- hyriseServer boots hyrise with a server and I can contact it using standard PosgreSQL clients, such as psql or even JDBC. It doesn't have functionality to automatically load the TPC-H schema.
- hyriseConsole has a functionality to load the TPC-H schema, but it doesn't boot a server I can communicate with through psql, only through the console.

Practically, I'd like to contact hyrise through external clients over the wire and query it on TPC-H data.
I'm aware I can generated and upload the data manually, but am looking to use hyrise' functionality to generate the data.

**Comment by mrks** [comment]
@Bensk1 - did you have a solution to that in your project?

The easiest for now would probably be to simply add `TPCHTableGenerator{scale_factor, chunk_size}.generate_and_store();` to `int main(...)` in `server.cpp`. The needed include is `#include "tpch/tpch_table_generator.hpp"`.

**Comment by tglanz** [comment]
Thanks, it worked like  a charm!

Just for reference
1. linked ```hyriseBenchmarkLib``` with ```hyriseServer```
2. included ```tpch/tpch_table_generator.hpp``` at ```src/bin/server.cpp```
3. added ```opossum::TPCHTableGenerator(0.1).generate_and_store();``` just before initializing the server at ```src/bin/server.cpp```

**Comment by Bensk1** [comment]
> @Bensk1 - did you have a solution to that in your project?

Not really. We generated the tables, exported them as binary and imported them into the server.

**Comment by mrks** [comment]
Here's a quick hack to support different scale factors. It also caches the binary tables, which should significantly improve the startup time:


```diff
diff --git a/src/bin/CMakeLists.txt b/src/bin/CMakeLists.txt
index 77687e074..75057a3c4 100644
--- a/src/bin/CMakeLists.txt
+++ b/src/bin/CMakeLists.txt
@@ -7,6 +7,7 @@ add_executable(
 target_link_libraries(
     hyriseServer
     hyrise
+    hyriseBenchmarkLib
 )

 # Configure playground
diff --git a/src/bin/server.cpp b/src/bin/server.cpp
index a71947804..3b4681240 100644
--- a/src/bin/server.cpp
+++ b/src/bin/server.cpp
@@ -1,6 +1,8 @@
 #include "cxxopts.hpp"

+#include "benchmark_config.hpp"
 #include "server/server.hpp"
+#include "tpch/tpch_table_generator.hpp"

 cxxopts::Options get_server_cli_options() {
   cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise server in order to accept network requests.");
@@ -8,6 +10,7 @@ cxxopts::Options get_server_cli_options() {
   // clang-format off
   cli_options.add_options()
     ("help", "Display this help and exit") // NOLINT
+    ("s,scale_factor", "TPC-H Scale Factor", cxxopts::value<float>()) // NOLINT
     ("address", "Specify the address to run on", cxxopts::value<std::string>()->default_value("0.0.0.0"))  // NOLINT
     ("p,port", "Specify the port number. 0 means randomly select an available one. If no port is specified, the the server will start on PostgreSQL's official port", cxxopts::value<uint16_t>()->default_value("5432"))  // NOLINT
     ("execution_info", "Send execution information after statement execution", cxxopts::value<bool>()->default_value("false")) // NOLINT
@@ -27,6 +30,15 @@ int main(int argc, char* argv[]) {
     return 0;
   }

+  if (parsed_options.count("scale_factor")) {
+    const auto scale_factor = parsed_options["scale_factor"].as<float>();
+    if (scale_factor > 0) {
+      auto config = std::make_shared<opossum::BenchmarkConfig>(opossum::BenchmarkConfig::get_default_config());
+      config->cache_binary_tables = true;
+      opossum::TPCHTableGenerator{scale_factor, config}.generate_and_store();
+    }
+  }
+
   const auto execution_info = parsed_options["execution_info"].as<bool>();
   const auto port = parsed_options["port"].as<uint16_t>();
```

**Comment by tglanz** [comment]
It is VERY helpful, thank you!

**Comment by Bouncner** [comment]
@tglanz : this "hack" has found its way into the master with #2298.
