### ISSUE TITLE
plot_operator_breakdown uses arithmetic mean on percentages

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2250]
```
df.loc["Relative"] = df.head(-1).sum() / df.head(-1).count()
```

Should be the geomean instead? Not as clear cut as the compare_benchmarks case.

**Comment by mrks** [comment]
No. Three reasons:

* Geomean only makes sense for percentages that you can multiply. For `compare_benchmarks`, you can multiply the performance change of query A with that of query B and get the combine performance change.
* Geomean is not defined on lists containing 0
* Geomean would not end up at 100% here.

**Comment by Bouncner** [comment]
Sound reasonable.

Do you think this column is of help? To me, it's confusing and does not really add value. The absolute column in contrast is super interesting as it shows the overall impact of an operator.

**Comment by mrks** [comment]
Good point. Let's get rid of it.
