### ISSUE TITLE
CI stages: Separate stages for generating query plans and verification?

### ISSUE THREAD

**Issue by julianmenzler** [hyrise/hyrise#2261]
For TPC-H Q15, we skip the verification in the CI since #1378 as we cannot support it. Therefore, we also do not get any query plans for Q15 [as build artifacts](https://hyrise-ci.epic-hpi.de/job/hyrise/job/hyrise/job/master/lastStableBuild/artifact/query_plans/tpch/).

By making two stages out of it, we could ensure that query plans are generated for all queries.

**Comment by mrks** [comment]
Sounds good. Depending on how much this add to the runtime, an alternative would be to just run `-q 15 -r 1 --visualize` separately.
