### ISSUE TITLE
Incorrect performance counters in hash aggregate

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2266]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/1745857/99787992-c2147300-2b20-11eb-8531-91b06faa9235.png">

Here, it's 35 + 528 + 31 + 46 ms. Which is 640 ms, while the operator runtime is 615 ms.
~~Moreover, step "GroupByColumnsWriting" is often written twice, which overwrites the first runtime. So the error would be even larger, if we wouldn't overwrite.~~

I looked into the aggregate, but couldn't find a reason for the mismatch. @mrks : you did a lot lately on the aggregate, any ideas?

**Comment by Bouncner** [comment]
I'll try to add a debug assertion somewhere.

**Comment by mrks** [comment]
In some cases, `_write_aggregate_output` calls `_write_groupby_output` internally.

>  Moreover, step "GroupByColumnsWriting" is often written twice, which overwrites the first runtime. So the error would be even larger, if we wouldn't overwrite.

Are you sure? Shouldn't this assertion guard against it?

https://github.com/hyrise/hyrise/blob/a7e36e433e40422ba07f09f0b58088d26703c64f/src/lib/operators/operator_performance_data.hpp#L81

**Comment by Bouncner** [comment]
I am building it right now. My current guess is that it's not tested and it's a DebugAssert so never fails in the benchmarks. I am on it.

**Comment by Bouncner** [comment]
So, the write phase is not overwritten. My test was wrong.

Nevertheless, pretty  much all aggregates have a larger aggregated runtime than the wall time. Still can't find the reason.

**Comment by mrks** [comment]
Did you see this?

> In some cases, _write_aggregate_output calls _write_groupby_output internally.

**Comment by Bouncner** [comment]
Hmpf. Yes I saw that, but thought about it only in the context of the (non-existing) overwrite of the step duration.
Yeah, looks like this is the reason.

Do you remember the reason to have `_write_groupby_output` write the timer on its own? Will create a PR in a few minutes.
