### ISSUE TITLE
Kill AbstractRule::_apply_to_inputs

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2276]
This came up in a discussion with @julianmenzler. Optimizer rules should not be blindly applied recursively, as this will cause the plan below a diamond to be traversed twice. Instead, they should use `visit_lqp`, which avoids visiting a node twice.

* Remove the word *recursively* here and potentially in other places: https://github.com/hyrise/hyrise/blob/7047d0894cbad9d2d3b4711bd76244d0f2c826af/src/lib/optimizer/strategy/abstract_rule.hpp#L18
* Get rid of `_apply_to_inputs`, which is a helper method to do the wrong thing.

**Comment by julianmenzler** [comment]
`_apply_to_inputs` is used by

* BetweenCompositionRule
* ChunkPruningRule
* SubqueryToJoinRule

Refactoring is in progress.
