### ISSUE TITLE
Without caching binary tables, hyriseBenchmarkX fails when sorting a table by an already sorted column

### ISSUE THREAD

**Issue by aloeser** [hyrise/hyrise#2297]
Context:
For many benchmarks (e.g., TPC-H, TPC-DS), the generated tables are implicitly sorted by their primary key , but (afaik) the `individually_sorted_by` flags are not set.
For our project in the current research seminar (what-if-clustering), @dey4ss and me need those flags to be set. We tried to achieve this by modifying the `_sort_order_by_table()` function of the TPC-H table generator to contain each table with its respective primary key (same sorting order as before, but this time with flags). 
There is a shortcut in the abstract table generator that tries to avoid re-sorting if the table is already sorted (which it is). 
This shortcut, however, assumes (probably?) that the tables are loaded from cached binaries, with finalized and encoded chunks. Obviously, when not using cached tables, neither is the case, and the benchmark generator crashes when trying to set the flag on mutable chunks.

We are aware that sorting a table by an already sorted column might be a rather uncommon use case, and is not the proper way to go for capturing implicit sortedness. So if you decide not to address this issue, we are completely fine with that.
Internally, we solved the issue by letting the clustering algorithm from my master's thesis do the sorting.

**Comment by mrks** [comment]
> This shortcut, however, assumes (probably?) that the tables are loaded from cached binaries, with finalized and encoded chunks. Obviously, when not using cached tables, neither is the case, and the benchmark generator crashes when trying to set the flag on mutable chunks.

Sounds to me as if that was the actual issue. The encoding takes place after the sorting step, so this should not be an issue.

Could you try moving the `Finalizing all chunks of all tables that are still mutable.` block in front of the `Sort tables if a sort order was defined by the benchmark` block?

**Comment by aloeser** [comment]
> Could you try moving the Finalizing all chunks of all tables that are still mutable.

Runs without crashes

According to a 20sec/query benchmark on SF 1, performance of sorting by l_orderkey and not sorting at all remains identical, which I do not understand.
In line 110 of the abstract table generator https://github.com/hyrise/hyrise/blob/1a73d9b4cd2d7b0cd49f8edff13af48f2357dbbf/src/benchmarklib/abstract_table_generator.cpp#L110, there is a return statement. From my understanding, this should end `generate_and_store()` in case of an already sorted table before the encoding can take place (since encoding happens after the sorting). As a consequence, the already sorted table would not be encoded, which should make a difference in benchmarks.
 Both benchmark and console experiments prove me wrong, tho. Any idea what I am missing?

**Comment by mrks** [comment]
That code is part of a lambda. We return from the lambda, not from the entire method.

I guess it is partially my fault for just wrapping the lambda around the code to make it multi-threaded. We should probably move the inner part of the lambdas (in the following steps, too) into their own functions to clear this up a bit.

**Comment by mrks** [comment]
As far as I know, there are no operators in TPC-H that would profit from the sort flag. While, e.g., some joins and aggregates profit from the locality of the orderkeys, this happens with and without the flag. If I remember correctly, the flag is only used for binary searches and sort-based aggregates, neither of which are used for the TPC-H queries. @Bouncner might know more about this.

**Comment by aloeser** [comment]
> That code is part of a lambda. We return from the lambda, not from the entire method.
> 
> I guess it is partially my fault for just wrapping the lambda around the code to make it multi-threaded. We should probably move the inner part of the lambdas (in the following steps, too) into their own functions to clear this up a bit.

Thanks for clarification, didn't see the lambda :)

**Comment by aloeser** [comment]
> As far as I know, there are no operators in TPC-H that would profit from the sort flag. While, e.g., some joins and aggregates profit from the locality of the orderkeys, this happens with and without the flag. If I remember correctly, the flag is only used for binary searches and sort-based aggregates, neither of which are used for the TPC-H queries. @Bouncner might know more about this.

Agreed, join performance should not be impacted by the flag, but rather by key locality. However, I am not aware of a key-locality-measure (please tell me if something like that exists in Hyrise!), so we simply abused the fact that global sortedness implies key locality for a column. This is definitely not the best way to capture locality, but I doubt we have time for much more advanced metrics in the seminar

**Comment by mrks** [comment]
Perfect, just wanted to make sure that you are aware of that.

**Comment by dey4ss** [comment]
> As far as I know, there are no operators in TPC-H that would profit from the sort flag. 

Could other Benchmarks profit from that? I.e., the Sort operator could benefit from non-overlapping sorted chunks with some shortcut. If that would be implemented (and would be useful), we should ensure that we always set the chunk sorted flags.

**Comment by Bouncner** [comment]
Currently in Hyrise, we have non-overlapping and sorted chunks in some cases (e.g., result of sort-merge join), but non-overlapping here means that the intersection in empty (e.,g., [1,3] and [2,4]; we call that “value clustered”).
So could linearily merge them but not simply append.

**Comment by aloeser** [comment]
@mrks do you want me to make a PR that moves the finalization before the sorting?

**Comment by mrks** [comment]
Yes, please.
