### ISSUE TITLE
Server: hyriseServer runs at 70% without any connections

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2314]
On MacOS as well as Linux, the `hyriseServer` consumes between 50% and 80% while there are no connections at all.

When a complex query is issued on a single-core instance (i.e., no scheduler), the server thus consumes ~170%.

**Comment by mrks** [comment]
It would also be interesting to compare the throughput of the server (see https://github.com/mrks/psql_runner) with that of hyriseBenchmarkTPCH.

**Comment by Bouncner** [comment]
Still working on it, but currently it looks as if there is a significant impact. This is a single-threaded server on rapa.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1745857/114741917-85ede300-9d4b-11eb-9054-05029178a963.png">

Not sure yet where this comes from.

**Comment by mrks** [comment]
So we are _even_ faster?

**Comment by Bouncner** [comment]
What?

**Comment by mrks** [comment]
Compared to that other DBMS that we run the server benchmarks against ;)

**Comment by Bouncner** [comment]
Please ignore the measurement above. Having problems to reproduce.

**Comment by Bouncner** [comment]
I think I did something major wrong with the numa pinning, but I am not sure.

However, this is the current status on rapa:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1745857/114981705-b0948480-9e8e-11eb-8bc9-79b30ca8c092.png">

I cannot judge if the little difference is caused by the client overhead (this script uses the Python PostgreSQL bindings) or by  the server CPU load. But at least for me this difference is fine and acceptable.

**Comment by Bouncner** [comment]
I haven't re-evaluated the difference again. I would still consider the numbers shown above acceptable.

The high CPU usage of the server has been fixed by using semaphores in #2548.
