### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by istiakahmad** [hyrise/hyrise#2322]
I am doing my research on In-memory database. I try to install Hyrise but when I run "cmake .." command, I got an error. Here is the error:
CMake Error in src/benchmarklib/CMakeLists.txt:
  The CXX_STANDARD property on target "hyriseBenchmarkLib" contained an
  invalid value: "20".
So that, the "./cmake-build-debug/hyriseConsole" command also show an error like "bash: ./cmake-build-debug/hyriseConsole: No such file or directory".

Could you please help me to solve it. Thanks.

**Comment by mrks** [comment]
Could you let us know which cmake version you are using and try to update it?

**Comment by istiakahmad** [comment]
Actually,  first time I try to install  on ubuntu18.04 and I have faced that problem. Then I try ubuntu 20.10 and its successfully installed. Thanks.
