### ISSUE TITLE
Incorrect naming: `BaseVectorDecompressor`, `BaseVectorCompressor`

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2364]
According to the contribution guidelines, `BaseVectorDecompressor` should actually be named `AbstractVectorDecompressor` since it is a base class for multiple differing implementations.

It's the same with `BaseVectorCompressor`.

**Comment by Bouncner** [comment]
> Closing it for now. Feel free to reopen if it becomes a priority.

Closing as we decided to not further continue with the renaming.
