### ISSUE TITLE
Setup IMDB script: IMDB dataset link is broken

### ISSUE THREAD

**Issue by phoeinx** [hyrise/hyrise#2373]
Running `hyriseBenchmarkJoinOrder` fails in step `Retrieving the IMDB dataset.` with the following error message: `urllib.error.HTTPError: HTTP Error 404: Not Found`. 

Manually trying to access the given file location in the script (http://www.dropbox.com/s/fgju7cifpehqlww/imdb.zip?dl=1) also throws a 404 error.

**Comment by phoeinx** [comment]
As a short question in regards to a quick fix for me right now: As far as I can see, exchanging the link from archive.org to the dropbox link was for faster download and updates. But it should still be valid to use the archive.org link / the accessed dataset should be the same?

**Comment by julianmenzler** [comment]
> But it should still be valid to use the archive.org link / the accessed dataset should be the same?
Currently, it should still lead to valid results. 

After #2372, however, some Assertions will fail because some nullability metadata in the archive.org version is wrong.

**Comment by julianmenzler** [comment]
Can you fix the download link @Bensk1?

**Comment by Bensk1** [comment]
Thanks for bringing that up @phoeinx! Apparently, somebody deleted the zip file but it should be fixed by now.

**Comment by phoeinx** [comment]
Hi, thanks for the quick reply!
@Bensk1 yes, can confirm. Works like a charm now (and the download speed really is a dream compared to archive.org).
