### ISSUE TITLE
benchmark_all: runtime and general issues

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2381]
Currently, the `benchmark_all.sh` script runs ~7h. One major bottleneck is the Join Order Benchmark, which has ~100 queries.

Within this issue I would like to gather some feedback of the following possible adaptions:
 - add `-r 100` to the single-threaded executions in order to allow fast queries to finish in less than the current 60 s; this has a significant impact on JOB and a quite noticable impact on DS
 - remove the SF 1 benchmark
   - SF 1 is no longer our default and with SF 10 and SF 0.01 we sufficiently cover the relevant cases
   - I did not look once at the SF 1 results ever since we moved to SF 10
 - Instead of the `multi-threaded, clustering config 'Pruning', SF 10.0` setting, run `multi-threaded, shuffled, $ clients SF 10.0`
 - As the default client count, use the number of CPU cores (we don't really support NUMA, 99% of all cases run on a single CPU) as the client count (the current 50 works well for the nemea server, but not necessarily for all other machines)

Opinions?

**Comment by Bensk1** [comment]
> * add `-t 100` to the single-threaded executions in order to allow fast queries to finish in less than the current 60 s; this has a significant impact on JOB and a quite noticable impact on DS
> * remove the SF 1 benchmark

These two sound reasonable to me.   

> * Instead of the `multi-threaded, clustering config 'Pruning', SF 10.0` setting, run `multi-threaded, shuffled, $ clients SF 10.0`
> * As the default client count, use the number of CPU cores (we don't really support NUMA, 99% of all cases run on a single CPU) as the client count (the current 50 works well for the nemea server, but not necessarily for all other machines)

So there would be two changes for this case? The clustering config and the client count? How many clients do we use currently?

**Comment by julianmenzler** [comment]
I agree with most of your suggestions. But can you explain your thoughts on the following point?

> * Instead of the multi-threaded, clustering config 'Pruning', SF 10.0 setting, run multi-threaded, shuffled, $ clients SF 10.0

**Comment by Bouncner** [comment]
> So there would be two changes for this case? The clustering config and the client count? How many clients do we use currently?

Yes, removing the config (just the call, not the code) and using 1/2 commands to get the core count. Currently, it's fixed to 50, which is too extreme, e.g., when benchmarking the M1.

> I agree with most of your suggestions. But can you explain your thoughts on the following point?

Main thoughts:
 * get rid of configurations that we haven't talked about/discussed/analyzed for a long time
   * benchmarking is expensive and we should use the runtime for things we really care about
 * the shuffled mode is the more realistic scenario that our server is handling, compared to the synthetic case of everybody issuing the same query at the same time
   * as far as I can tell, all recent multi-threading measurements for papers and theses used the shuffled mode for this reason, but we don't use it in our main benchmark suite as of now

**Comment by Bensk1** [comment]
How about discussing these ideas on Wednesday to bring them forward? Until then, everybody should have an opinion about it. @mweisgut and @dey4ss mentioning you because I am not sure if you have seen this issue.

**Comment by mweisgut** [comment]
Just for the record: Today's fortnightly participants agreed to the proposed changes.

**Comment by julianmenzler** [comment]
Do we want to add a JCC-H run to the script?

**Comment by Bensk1** [comment]
> Do we want to add a JCC-H run to the script?

Good idea, I will include this in the list of remaining discussion points.

- [ ] Do we want to use warmups (`-w 5`) in the future? (The first run can be up to 5x slower for some queries)
- [ ] Do we want to use the median instead of the mean to calculate averages, i.e., do we want to practically exclude outliers? 
- [ ] Do we want to add JCC-H? (One of the queries leads to OOM even for SF 1)

**Comment by Bouncner** [comment]
One more thing. :)

The by far slowest query in TPC-DS runs over 200 times. I think we should switch TPC-DS to SF 10 as well.
