### ISSUE TITLE
[Mac OS x] [Installation] [Make error]

### ISSUE THREAD

**Issue by Rucchao** [hyrise/hyrise#2418]
**cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang 
-DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ 
-DCMAKE_BUILD_TYPE=Release ../**

The error information is as follows: 

/hyrise/src/lib/storage/table.hpp:240:55: error: no member named 'zero_allocator' in namespace 'tbb'
  tbb::concurrent_vector<std::shared_ptr<Chunk>, tbb::zero_allocator<std::shared_ptr<Chunk>>> _chunks;

/hyrise/src/lib/storage/table.hpp:240:92: error: expected '(' for function-style cast or type construction
  tbb::concurrent_vector<std::shared_ptr<Chunk>, tbb::zero_allocator<std::shared_ptr<Chunk>>> _chunks;

Could you please help me with this? Thanks!

llvm 13
Homebrew clang version 13.0.0

**Comment by Bensk1** [comment]
We just discovered this issue in the past days, thanks for indirectly forcing us to find a temporary solution :)

There are two problems, TBB removed the `zero_allocator` and we (or some of our dependencies) do not fully support llvm-13 at the moment. Currently, you need to use llvm-12 and an older TBB version. You should be able to install both via brew with:

```
brew install tbb@2020
brew install llvm@12
```

I hope this helps!

**Comment by Rucchao** [comment]
Now it works! Thanks for your quick response!

**Comment by mweisgut** [comment]
Related to #2419

**Comment by Daniel-Xu** [comment]
```
set(OLD_TBB_VERSION /usr/local/opt/tbb@2020)

find_path(TBB_INCLUDE_DIR NAME tbb/tbb.h
    HINTS ${OLD_TBB_VERSION} ${DEFAULT_LIB_DIRS}
    PATH_SUFFIXES include
)
```

I have to add this in findtbb.cmake file to inform cmake to pick up the right version.

**Comment by Bouncner** [comment]
I guess you're having multiple TBB versions installed? Our current problem with recent TBB versions is unfortunate. But we are working on the issue and hopefully fix it soon.

What might be easier than adapting the source is to pass the path to `cmake`:
`cmake .. DCMAKE_BUILD_TYPE=Release -DTBB_INCLUDE_DIR="/usr/local/opt/tbb@2020/include" -DTBB_LIBRARY="/usr/local/opt/tbb@2020/lib/libtbb.so"`

Could happen that you linker picks up the newer library while having the old source at hand.

**Comment by Daniel-Xu** [comment]
Actually,  I did manually `brew uninstall tbb`, however `cmake` still can't find the correct version. Anyway, I'm able to compile and run the server now, thanks for you support.
