### ISSUE TITLE
`zero_allocator` is missing in oneTBB 2021

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2419]
With the latest oneTBB version, Hyrise cannot be compiled since oneTBB does not contain the `tbb::zero_allocator` anymore (https://github.com/oneapi-src/oneTBB/issues/378), which we use in the `Table` class, see:
- https://github.com/hyrise/hyrise/blob/df1312625b74642afe36b016352d54acce19c399/src/lib/storage/table.hpp#L231-L240
- https://github.com/hyrise/hyrise/blob/df1312625b74642afe36b016352d54acce19c399/src/lib/storage/table.cpp#L251-L257

The `zero_allocator` is still available in the tbb_2020 branch: https://github.com/oneapi-src/oneTBB/blob/eca91f16d7490a8abfdee652dadf457ec820cc37/include/tbb/tbb_allocator.h#L144-L176

When fixing this issue, the link to the intel blog post, which is referenced in the code (see 2nd snippet) should also be updated or deleted.
- original (not available anymore): https://software.intel.com/en-us/blogs/2009/04/09/delusion-of-tbbconcurrent_vectors-size-or-3-ways-to-traverse-in-parallel-correctly
- archived: https://web.archive.org/web/20100103204609/http://software.intel.com/en-us/blogs/2009/04/09/delusion-of-tbbconcurrent_vectors-size-or-3-ways-to-traverse-in-parallel-correctly/

## related references
- concurrent vector user guide: https://github.com/oneapi-src/oneTBB/blob/master/doc/main/tbb_userguide/concurrent_vector_ug.rst

**Comment by mweisgut** [comment]
The last tbb version with the `zero_allocator` available is v2021.1-beta05 (see https://github.com/oneapi-src/oneTBB/blob/v2021.1-beta05/include/tbb/tbb_allocator.h). The `libtbb-dev` of the latest ubuntu release (20.10) is `2020.3-1` (see https://packages.ubuntu.com/search?keywords=libtbb-dev).

Since the ubuntu distributions don't provide a 2021.x tbb version, I'd suggest
- using tbb 2020 for both ubuntu and macOS platforms. To do so, we should modify the install script so that hyrise can be built after running the install script on macOS
- using a 2021.x version for both platforms by building oneTBB from source files

**Comment by Bouncner** [comment]
I don't really like any solution. The first is problematic with native developments of our students (MacOS brew already, Ubuntu probably soon). The second is my favorite, but means we carry an outdated library version with us.

**Comment by mweisgut** [comment]
> The second is my favorite, but means we carry an outdated library version with us.

Do you mean when we use an old version providing the `zero_allocator`? I was thinking about using a new 2021.x version that doesn't provide the `zero_alloator` anymore and changing Hyrise accordingly.

**Comment by Bouncner** [comment]
Ah ok. I got confused as you said some 2021.* versions still included the allocator.
Then the second points sounds good to me. But we should try to come up with a proper test to recognize when our implicit assumptions (the ones we rely on and which the Intel guys aren't so sure they are actually given) are really given. If we are just lucky, such a test might crash with an upcoming stdlib. Does that make sense?
