### ISSUE TITLE
NUMA-restricted benchmark binaries initialize too many workers

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2424]
When running something like `numactl -m 0 -N 0 ./rel_gcc/hyriseBenchmarkTPCH --scheduler`, the node scheduler for the data preparation phase is initialized with all the machines cores instead of the core count of numa node 0.
For many servers, that means we start 4x as many workers as CPU threads.

Pinging @mweisgut (as you have also looked into this topic; not to assign it to you).

**Comment by mweisgut** [comment]
How did you observe this behavior? I just tried to reproduce and observe that behavior by executing the following command on Sidon.
`numactl -m 2 -N 2 ./hyriseBenchmarkTPCH --scheduler`

I checked the number of workers (see `NodeQueueScheduler::_workers`), which was 30 with the numa binding used in the above command. 30 corresponds to the number of cores of one node on Sidon. Without the numa binding (i.e., executing `./hyriseBenchmarkTPCH --scheduler`), the benchmark execution resulted in 120 workers. Also, binding the benchmark to the node with index 0 (i.e., using `numactl -m 0 -N 0`) led to 30 workers.

**Comment by Bouncner** [comment]
I just realized the numbers differ, but it might be a totally different issue. No matter what `numactl` I am using, Hyrise uses all 256 cores from the single 0.
But actually, it's a two node server with 128 cores each.

So the issue might be something different.

**Comment by Bouncner** [comment]
@Bensk1 just made me aware that the build might be built without NUMA support. I will double check that.

**Comment by Bouncner** [comment]
Not reproducible. I was probably just confused by the core assignment as Hyrise was not built using libnuma.
