### ISSUE TITLE
`coverage.sh` fails on macOS

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2426]
Running `./scripts/coverage.sh` on macOS BigSur fails with llvm 12.0.1
```
dyld: Symbol not found: ___llvm_profile_runtime
  Referenced from: [...]/hyrise/build-coverage/lib/libhyriseMvccDeletePlugin.dylib
  Expected in: flat namespace
 in [...]/hyrise/build-coverage/lib/libhyriseMvccDeletePlugin.dylib
./scripts/coverage.sh: line 51:  3419 Abort trap: 6           ./build-coverage/hyriseTest build-coverage --gtest_filter=-SQLiteTestRunnerInstances/*
```

**Comment by dey4ss** [comment]
Maybe related: https://stackoverflow.com/questions/58127940/undefined-symbols-llvm-profile-runtime and https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1159#issuecomment-357711553

**Comment by dey4ss** [comment]
I could build when adding
```
if(${ENABLE_COVERAGE})
  add_link_options(-fprofile-instr-generate)
  set(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -fprofile-instr-generate")
endif()
```

to the main `CMakeLists.txt`. However, I get a warning (`warning: 1 functions have mismatched data`) and the reported coverage in `coverage.html` does not match the CI coverage report.
