### ISSUE TITLE
support arm64(centos7)?

### ISSUE THREAD

**Issue by louishust** [hyrise/hyrise#2427]
hi,

can hyrise compile and run on arm64 with OS centos7?

**Comment by Bouncner** [comment]
I have no CentOS system at hand, but I don't see a problem here. The distributions we tested apart from Ubuntu (e.g., Suse SLES) worked. The main difference is that the `install_dependencies` script does not work (assume to habe `apt` in place).

We test Apple M1 builds regularly in our CI pipeline. We built successfully on RaspPis, but the last time I have checked it probably a year ago.

**Comment by louishust** [comment]
@Bouncner Thanks, i will try it on centos

**Comment by Bouncner** [comment]
Please don't hesitate to open an issue if something does not work as expected.
