### ISSUE TITLE
Executing `install_dependencies.sh` results in a deprecation warning

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2428]
Running `install_dependencies.sh` on a fresh macOS system results in the below warning:
```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

Tested on macOS 12.0.1

**Comment by Bouncner** [comment]
Cannot test it. Need to buy a new mac.

But given the status of the mentioned issue (https://github.com/Homebrew/homebrew-core/issues/76621), I will close this issue assuming it is fixed.
