### ISSUE TITLE
Discussion: `PRAGMA` commands

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2437]
There is a growing number of plugins or projects on Hyrise that would benefit from "some way" of allowing the user to send some from of commands or to call a plugin-provided function.

Looking at the Postgres-Client, I have seen a suitable way to implement them with our parser. Another way could be to support `PRAGMA` queries in Hyrise (similar to SQLite or DuckDB; e.g., as a `simply query` in the request_handler).
We would extend to the Plugin Manager to accept hooks, that a plugin is responsible for certain `PRAGMAs`.

One example here is the decision that certain segments should be reenencoded or tiered. Enable us to instrument Hyrise from a simply Python script using PRAGMAs would ease a lot of such scenarios.

Any comments on that?

**Comment by Bensk1** [comment]
Good point.

We could also (mis)use the MetaTables and/or plugin settings from that. I don't like that idea from an interface and user experience perspective but it probably easy to implement.

**Comment by Bouncner** [comment]
Given that SQLite and co. do the same, I think it's one of better approaches concerning user experience.

The problem with the meta tables is that there is no clean way to articulate "an action" via SQL, as far as I know. I currently use a hacky plugin that creates a meta table `commands`. First, I insert the "command" into the table (inserting does currently not trigger an action) and then I need to use a `select * from meta_commands` which calls `_on_generate` of the meta table and here I can react.
We could extend the interfact to allow actions on insert (or I might have missed it?), but nothing "SQL'ish" looks better to me than `PRAGMA`.

**Comment by Bensk1** [comment]
Discussion moved to draft implementation in #2438.

**Comment by mrks** [comment]
> The problem with the meta tables is that there is no clean way to articulate "an action" via SQL, as far as I know.

`CALL` maybe?

**Comment by Bensk1** [comment]
The demanded functionality was implemented via #2438 even though it does neither use `PRAGMA` nor `CALL` for now but `INSERT INTO meta_exec...`.
