### ISSUE TITLE
Load data into hyriseServer with compression type

### ISSUE THREAD

**Issue by Rucchao** [hyrise/hyrise#2446]
Hi,
 I found hyrise is very interesting as a column store!
 I am able to load the data into hyriseServer with the COPY command, e.g., COPY nation FROM 'nation.tbl'; 
 However, it seems the data is unencoded, may I know how could I specify the compression type, e.g., LZ4?
 I know the LOAD command in the hyriseConsole can specify the compression type, but I'd like to test it in the hyriseServer, could you guys help me with this?

Thanks in advance!

**Comment by Bensk1** [comment]
Hi, great to hear that you find Hyrise interesting!

Unfortunately, it is currently not possible to load a .tbl file and encode it on the fly. We might add server functionality for triggering (re-)encoding in the future.

For now, I would suggest that you generate the data via the Hyrise benchmark binaries or the Hyrise console. Both options allow for specifying encoding configurations, e.g., LZ4. The benchmark binaries export the encoded table data as binary files to the local file system by default. The console offers exporting data explicitly. The exported, encoded data could then be loaded via `COPY`.

**Comment by Rucchao** [comment]
Hi Jan,

Glad to hear from you!

Thanks for your instruction! I'll take the workaround from Hyrise console as it enables different compression types for different tables. Thanks!

Best,
Chao

**Comment by Bouncner** [comment]
Do you use custom data or TPC-H?
For TPC-H, there are out-of-the-box ways to use different encoding per column, not only table.

**Comment by Rucchao** [comment]
Hi, 
   Yes, my first experiment is for TPC-H, maybe later I would like to use some synthetic data.
    May I know how could I encode the TPC-H per column?  Any details are appreciated. Thanks!

**Comment by Bouncner** [comment]
You can an exemplary configuration here: [simple__LPCompressionSelection_5033211488__no_fsst.json.zip](https://github.com/hyrise/hyrise/files/8351172/simple__LPCompressionSelection_5033211488__no_fsst.json.zip)

With that configuration, you can call `./hyriseBenchmarkTPCH -e simple__LPCompressionSelection_5033211488__no_fsst.json` to generate and encode TPC-H data, which can then be loaded via the console or server.

This exemplary configuration is determined by a project that you an find here: https://github.com/hyrise/encoding_selection

**Comment by Rucchao** [comment]
Hi, 
 
Thanks a lot for your instruction and reference! 

The project of automated encoding selection looks great! It would be nice to have more datasets such TPC-DS, JOB, or even custom data implemented with the same functionality.  Nevertheless, I'll start with the TPC-H data. Thanks!

**Comment by Bouncner** [comment]
You can use the same approach of providing a configuration JSON for the binaries `hyriseBenchmarkJoinOrder` and `hyriseBenchmarkTPCDS`.

For custom data, we only have plugin-based solutions (as done in https://github.com/hyrise/encoding_selection).

**Comment by Rucchao** [comment]
Good to know, thanks a lot!

**Comment by Bouncner** [comment]
Closing for now. Feel free to re-open any time you have questions.
