### ISSUE TITLE
Hyrise server crashes unexpectedly

### ISSUE THREAD

**Issue by Rucchao** [hyrise/hyrise#2491]
Hi,

I deployed a hyrise server on a remote machine, and I use a Python client to execute queries on the server. 

However, the hyrise server often crashes unexpectedly without any error throwed. When using the localhost server, this problem doesn't occur, has anyone encountered this problem and can help me with this? 

Thanks in advance!

**Comment by Bouncner** [comment]
Admittedly, I have never been using the server when the client was on another machine.

Can you give us some more information? What are you doing, which queries, sample data set?

**Comment by Bouncner** [comment]
What could also help is to build a `RelWithDebInfo` version of the server and execute it via `gdb/lldb` to get a stack trace of the crash.

**Comment by Rucchao** [comment]
[Generated-TPCH-SQL-30.csv](https://github.com/hyrise/hyrise/files/9258068/Generated-TPCH-SQL-30.csv)

We used the TPC-H SF1 dataset and generated some random queries above, we tried Hyrise Server with docker and without docker, the crash problem occurred in both deployment. We use the following function to run the queries:

def execute_column(conf, query):
    connection = None
    Hcur, connection = hyrise_connect(host=conf["hyrise_host"], port=conf["hyrise_port"], connection=connection)
    Qst = time.time()
    Hcur.execute(query)
    Qres = Hcur.fetchone()
    Htime = time.time() - Qst
    Hcur.close()
    return Htime

**Comment by Rucchao** [comment]
Thanks a lot for your experimental results! We are changing the workload and redoing the testing. Thanks!

Chao

**Comment by Bouncner** [comment]
Closing for now. Feel free to reopen any time if you are having issues with Hyrise.
