### ISSUE TITLE
Performance degradation with a docker deployment

### ISSUE THREAD

**Issue by Rucchao** [hyrise/hyrise#2503]
Hi,

By running the single-table queries, I found hyrise is an order of magnitude slower when using a docker deployment.

Is any thing I am doing wrong or do you have any suggestions on the performance tuning in a docker? Thanks!
 
<img width="548" alt="Screen Shot 2022-08-31 at 11 10 00 AM" src="https://user-images.githubusercontent.com/14036667/187584425-bfa0b870-5aa8-4528-82db-b6e39306b25f.png">

<img width="670" alt="Screen Shot 2022-08-31 at 11 10 16 AM" src="https://user-images.githubusercontent.com/14036667/187584457-4a21b887-6055-489b-b6b3-bcbd5639c296.png">

[singletable.txt](https://github.com/hyrise/hyrise/files/9458021/singletable.txt)

Thanks,
Chao

**Comment by tobodner** [comment]
Is your Docker container in any why resource-constraint as compared to your native setup: https://docs.docker.com/config/containers/resource_constraints/?

**Comment by Rucchao** [comment]
Thanks for the reference. I tried to figure out if the problem came from the docker, so I deployed Hyrise directly in a server (Intel(R) Xeon(R) Gold 6242R CPU @ 3.10GHz, 128GB) without docker. 

<img width="417" alt="Screen Shot 2022-08-31 at 3 02 45 PM" src="https://user-images.githubusercontent.com/14036667/187636284-4fb6c08a-794a-4eaf-a95c-e6a8a4b63a30.png">


However,  I found in the server side, hyrise is much slower than PostgreSQL. This is weired as in my own Mac (2.3 GHz 8-Core Intel Core i9, 16GB), it is faster than PostgreSQL.
<img width="212" alt="Screen Shot 2022-08-31 at 3 07 46 PM" src="https://user-images.githubusercontent.com/14036667/187636362-426177dd-5acf-4ac8-a290-0a343c138856.png">


I am wondering why Hyrise is slower than PostgreSQL in the server side? Any comments would be appreciated. 

Thanks,
Chao

**Comment by Bouncner** [comment]
That's strange. When Postgres is fully buffered, the performance for this query should be pretty good. But Hyrise shouldn't be that much slower though.
Is is possible that the server is a debug build?

**Comment by Rucchao** [comment]
Hi Martin,

Thanks for your timely response! Yes, the performance degradation was caused by the debug build rather than by docker. After rebuilding hyrise with the release argument, now the hyrise performance is consistent with my local setup. 

Best,
Chao
