### ISSUE TITLE
Get the query plan

### ISSUE THREAD

**Issue by Rucchao** [hyrise/hyrise#2510]
Hi,

I wonder is there a decent way that can get the physical/logical query plan from the console/server side? 

Currently I only know the "visualize" command from the console that can show an image of the query plan, I am curious about how to get the plan with the cost estimation using python. I think a good example is the Pragmas command from DuckDB https://duckdb.org/docs/sql/pragmas. 

Thanks!

**Comment by dey4ss** [comment]
The easiest way to get logical/physical plans IMO is writing a plugin for that purpose (see [abstract_plugin.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/utils/abstract_plugin.hpp)). Plugins can implement user-callable functions, and such a function (called by SQL interface: `INSERT INTO meta_exec VALUES ('<plugin_name>', '<function_name>')`) can do whatever you want with the query plans.

Our logical query plans are not attached to estimated logical cost or cardinalities, but you can get the logical cost ([cost_estimator_logical.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/cost_estimation/cost_estimator_logical.hpp), currently not used by Hyrise) or cardinality ([cardinality_estimator.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/statistics/cardinality_estimator.hpp)) for each LQP node. Hyrise can also print formatted LQPs by passing them to a stream, and you can perform custom actions to LQP nodes when iterating them with [visit_lqp](https://github.com/hyrise/hyrise/blob/master/src/lib/logical_query_plan/lqp_utils.hpp#L159).

If you have already executed the queries, you can access them with `Hyrise::get().default_lqp_cache->snapshot()`, which return a map SQL query -> cache entry ([abstract_cache.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/cache/abstract_cache.hpp)). If you want to increase the cache size, see [sql_plan_cache.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/sql/sql_plan_cache.hpp) or set the cache manually, e.g, when loading the plugin before executing the queries.

If you want to get query plans of queries that have not been executed yet, you can create an SQLPipeline (see [sql_pipeline_builder.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/sql/sql_pipeline_builder.hpp)) and get the optimized/unoptimized LQPs ([sql_pipeline.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/sql/sql_pipeline.hpp)). If you want to state these queries via the SQL interface, I suggest to create a setting ([abstract_setting.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/utils/settings/abstract_setting.hpp)) for your plugin that holds the query and then execute your user-callable function:
```SQL
UPDATE meta_settings SET value = '<SQL query>' WHERE name = '<setting_name>' ;
INSERT INTO meta_exec VALUES ('<plugin_name>', '<function_name>');
```

I hope this answer helps and feel free to ask further questions.

**Comment by Rucchao** [comment]
Thanks for your information! The user-callable functions are interesting!

I am getting stucking in the very first step: how to call the user-callable functions?

For example, after loading the hyriseTestPlugin, I tried the following:

INSERT INTO meta_exec VALUES ('hyriseTestPlugin', 'OurFreelyChoosableFunctionName');
INSERT INTO meta_exec VALUES ('hyriseTestPlugin', 'SpecialFunction17');

terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/utils/plugin_manager.cpp:85 There is no SpecialFunction17 defined for plugin hyriseTestPlugin.

Neither works for me. NB: I use the latest build in docker and habe tried both the release and debug build.

Would you help me with this issue?

Thanks!

**Comment by Rucchao** [comment]
Thanks for your instructions! The user-callable function is interesting. After loading the hyriseTestPlugin, now I can invoke the function with the following statement:

`INSERT INTO meta_exec VALUES ('hyriseTestPlugin', 'OurFreelyChoosableFunctionName')`

Could you please show a concrete example in OurFreelyChoosableFunctionName to output a physical query plan to the csv since I am not quite familiar with the source code?

Thanks in advance!

**Comment by dey4ss** [comment]
I provide you some code snippets that might help you, but it is up to your use case what an exact implementation looks like. If you want to set query plan caches on your own, call
```c++
Hyrise::get().default_lqp_cache = std::make_shared<SQLLogicalPlanCache>(<cache_size>);
Hyrise::get().default_pqp_cache = std::make_shared<SQLPhysicalPlanCache>(<cache_size>);
```
when, e.g., loading your plugin. If you run a Hyrise server or benchmark, the caches will already be set with the default cache size of 1024. You can increase this size to your needs.

You can access the cache entries with the following code:
```c++
const auto lqp_cache = Hyrise::get().default_lqp_cache;
Assert(lqp_cache, "No LQP cache set");
const auto& snapshot = lqp_cache->snapshot();
for (const auto& [query, entry] : snapshot) {
  std::cout << query << std::endl << *entry.value << std::endl << std::endl;
}
```
The example prints out the LQPs in a formated way (example for TPC-H Q13/SF 1). The stream you pipe the LQP node to can of course be any stream, including a [std::ofstream](https://en.cppreference.com/w/cpp/io/basic_ofstream).
```
[0] [Alias] COUNT(0x13d706618.o_orderkey) AS c_count, COUNT(0x13d706618.*) AS custdist @ 0x60004ae90258
 \_[1] [Sort] COUNT(0x13d706618.*) (Descending), COUNT(0x13d706618.o_orderkey) (Descending) @ 0x60004ae90198
    \_[2] [Aggregate] GroupBy: [COUNT(0x13d706618.o_orderkey)] Aggregates: [COUNT(0x13d706618.*)] @ 0x600042fc8178
       \_[3] [Alias] 0x13d708ab8.c_custkey AS c_custkey, COUNT(0x13d706618.o_orderkey) AS c_count @ 0x60004ae900d8
          \_[4] [Aggregate] GroupBy: [0x13d708ab8.c_custkey] Aggregates: [COUNT(0x13d706618.o_orderkey)] @ 0x600042fc80c8
             \_[5] [Join] Mode: Left [0x13d708ab8.c_custkey = 0x13d706618.o_custkey] @ 0x60004ae90018
                \_[6] [Validate] @ 0x600042de5558
                |  \_[7] [StoredTable] Name: 'customer' pruned: 0/3 chunk(s), 7/8 column(s) @ 0x13d708ab8
                \_[8] [Validate] @ 0x600042de55f8
                   \_[9] [Predicate] 0x13d706618.o_comment NOT LIKE '%special%request%' @ 0x600042fc8018
                      \_[10] [StoredTable] Name: 'orders' pruned: 0/23 chunk(s), 6/9 column(s) @ 0x13d706618
```

If you want to traverse an LQP, e.g., for writing it to a CSV file, you can use `visit_lqp()`:
```c++
auto query_id = size_t{0};
for (const auto& [_, entry] : snapshot) {
  auto cardinality_estimator = CardinalityEstimator{};
  visit_lqp(entry.value, [&](const auto lqp_node) {
    std::cout << query_id << ";" << lqp_node->hash() << ";" << lqp_node->description() << ";"
              << cardinality_estimator.estimate_cardinality(lqp_node) << std::endl;
    return LQPVisitation::VisitInputs;
  });
  ++query_id;
}
```
The snippet prints a query ID an LQPNode hash with a description and the estimated cardinality in a CSV-like fashion.
```
0;6617831115887340472;[Alias] COUNT(o_orderkey) AS c_count, COUNT(*) AS custdist;1.35e+06
0;10358727099204074706;[Sort] COUNT(*) (Descending), COUNT(o_orderkey) (Descending);1.35e+06
0;18188893597353127740;[Aggregate] GroupBy: [COUNT(o_orderkey)] Aggregates: [COUNT(*)];1.35e+06
0;1760472793567756230;[Alias] c_custkey, COUNT(o_orderkey) AS c_count;1.35e+06
0;12880918173907407;[Aggregate] GroupBy: [c_custkey] Aggregates: [COUNT(o_orderkey)];1.35e+06
0;4961357056106783000;[Join] Mode: Left [c_custkey = o_custkey];1.35e+06
0;10835441347415508976;[Validate];150000
0;6886701503580061802;[Validate];1.35e+06
0;1963042739727909745;[StoredTable] Name: 'customer' pruned: 0/3 chunk(s), 7/8 column(s);150000
0;1249455502524008855;[Predicate] o_comment NOT LIKE '%special%request%';1.35e+06
0;696405697405564788;[StoredTable] Name: 'orders' pruned: 0/23 chunk(s), 6/9 column(s);1.5e+06
```
If you do not want to execute your queries, you can get the LQP like that:
```c++
  const auto query = "SELECT * FROM nation where n_name = 'GERMANY'";
  const auto lqps = SQLPipelineBuilder{query}
                        .with_mvcc(UseMvcc::Yes)
                        .with_optimizer(Optimizer::create_default_optimizer())
                        .create_pipeline()
                        .get_optimized_logical_plans();
  for (const auto& lqp : lqps) {
    std::cout << *lqp << std::endl;
  }
```

Accessing the caches works similarly for physical plans. Once a query was executed, you can also get the runtime and other statistics of each operator (see [operator_performance_data.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/operators/operator_performance_data.hpp)):
```c++
const auto pqp_cache = Hyrise::get().default_pqp_cache;
const auto& pqp_snapshot = pqp_cache->snapshot();
for (const auto& [_, entry] : snapshot) {
  visit_pqp(entry.value, [](const auto& op) {
    std::cout << op->description() << ";" << op->performance_data->walltime.count() << std::endl;
    return PQPVisitation::VisitInputs;
  });
}
```
which outputs
```
Alias [c_count, custdist];625
Sort;10041
AggregateHash GroupBy {COUNT(o_orderkey)} COUNT(*);811750
Alias [c_custkey, c_count];2250
AggregateHash GroupBy {c_custkey} COUNT(o_orderkey);40075792
JoinHash (Left) c_custkey = o_custkey;101830917
Validate;2667
Validate;32667
GetTable (customer) pruned: 0/3 chunk(s), 7/8 column(s);5417
TableScan Impl: ColumnLike o_comment NOT LIKE '%special%request%';135852958
GetTable (orders) pruned: 0/23 chunk(s), 6/9 column(s);96875
```

**Comment by Rucchao** [comment]
Thanks a lot for your help and code!  I'll try to implement it.

**Comment by dey4ss** [comment]
Closing for now. Feel free to reopen if you have further questions.
