### ISSUE TITLE
Re-Evaluate Hash Maps

### ISSUE THREAD

**Issue by mweisgut** [hyrise/hyrise#2521]
We use different hash maps, e.g., `tsl::robin_map` for the histogram and hash-based aggregate, the `ska::bytell_hash_map` for the hash join, and potentially another hash map introduced with #2448 for the partial hash index.

We might re-evaluate end-to-end runtimes for different hash maps to see if we can find better hash maps for the different workloads. For this evaluation, we should take into account that
- the robin map has quite a high memory footprint
- the bytell hash map is not maintained anymore
- we currently use std::hash for these hash maps and that other hashes might result in better runtimes (see https://martin.ankerl.com/2022/08/27/hashmap-bench-01/#benchmark-results-table).

**Comment by Bouncner** [comment]
#2613 changes all third party maps to `boost::flat_unorderered_map`. To reduce the memory consumption, we still use the sparse map though (actual impact has not been evaluated).

**Comment by Bouncner** [comment]
Given that there is currently no relevant alternative to `tsl::sparse_map` (apart from Google's abseil, that that's basically the same idea) and we voted for the memory saving in this data structure, we should be currently fine with Boost's flat hash map of #2613 and `tsl::sparse_map`.
