### ISSUE TITLE
Stock Level transaction in  TPC-C

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2602]
### Transaction processing
In the stock level transaction, we currently obtain a list of items inefficiently by first fetching the list and then putting this list into an `IN()` selection in another query.
Instead, we should use a simple join to fetch the list and use it for filtering as mentioned in the standard and pytpc (https://github.com/apavlo/py-tpcc/blob/master/pytpcc/drivers/sqlitedriver.py).

### ~Visualization~
~When visualizing queries of TPC-C, no stock level plans are visualized.~

**Comment by dey4ss** [comment]
Just referencing the example implementation in the [TPC-C standard](https://www.tpc.org/TPC_Documents_Current_Versions/pdf/tpc-c_v5.11.0.pdf) (Appendix A.5, p.116)
