### ISSUE TITLE
CMake Warning when setting up build directory

### ISSUE THREAD

**Issue by tjeyy** [hyrise/hyrise#2672]
```
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:65 (message):
  Disable warning 'switch-default' for Clang version 19.1.4.


-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
```

**Comment by Bouncner** [comment]
We disabled the warning recently. Do you think we should be more descriptive?
The surrounding CMake states why we disable this warning.

https://github.com/hyrise/hyrise/blob/dd49c11087e592b503874c0dcda63dfe58bb0eed/CMakeLists.txt#L58-L68

**Comment by Bouncner** [comment]
I am kind of hoping that we will get rid of this warning soon as I don't really get why clang handles it as does right now.
A status might be too easy to ignore.

In the end, it's probably staying forever and nobody will ever give a ... :-/

**Comment by tjeyy** [comment]
Closed since it's not a warning indicating something went wrong.
