### ISSUE TITLE
Join Benchmarks

### ISSUE THREAD

**Issue by ArneMayer** [hyrise/hyrise#287]

**Comment by mrzzzrm** [comment]
Looking for issues to close?
Is this still considered worth doing or planned at all? Otherwise let's close it @ArneMayer

**Comment by mrks** [comment]
@Bouncner - your call. But I believe I saw something in the open PRs?

**Comment by ArneMayer** [comment]
Im not working on something meant for this.

**Comment by Bouncner** [comment]
Jep, PR #667 does include much better benchmarks (e.g., with skewed data).

Don't know if that's enough though.
