### ISSUE TITLE
Refactor or remove SQLQueryOperator?

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#304]
I have found this `SQLQueryOperator` in `lib/sql/` and I’m wondering if it should be used in the console instead of `SQLPlanner`. The bigger question however is: why is it an operator? Semantically it looks more like a task (or perhaps not even that) as it doesn’t operate on tables and it sidesteps the operator interface a bit.

**Comment by mrks** [comment]
Right now, it is not even used by anyone.

The main feature of this class is to allow for async SQL parsing and query plan generation. That would be much better off in a task. Maybe the pipeline that is created in #367 could be used either in a synchronous or asynchronous mode.

**Comment by mrzzzrm** [comment]
@lawben assigning to you to close once pipeline contains cache
