### ISSUE TITLE
Joins mistreat input NULLs

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#314]
NULL values that are in one of the input tables are currently not handled correctly:

```
(debug)> load src/test/tables/aggregateoperator/groupby_int_1gb_0agg/input_null.tbl n
Loading src/test/tables/aggregateoperator/groupby_int_1gb_0agg/input_null.tbl into table "n" ...
(debug)> SELECT * FROM n
=== Columns
|       a|       b|
|     int|   float|
=== Chunk 0 ===
|   12345|   456.7|
|   12345|   457.7|
|     123|   458.7|
|      12|   350.7|
|    NULL|     342|
|    NULL|     234|
===
6 rows (PARSE: 0.000006 ms, COMPILE: 0.000062 ms, EXECUTE: 0.000105 ms (wall time))
(debug)> SELECT * FROM n n1 LEFT JOIN n n2 ON n1.a = n2.a
=== Columns
|       a|       b|       a|       b|
|     int|   float|     int|   float|
=== Chunk 0 ===
|      12|   350.7|      12|   350.7|
|     123|   458.7|     123|   458.7|
|   12345|   456.7|   12345|   456.7|
|   12345|   456.7|   12345|   457.7|
|   12345|   457.7|   12345|   456.7|
|   12345|   457.7|   12345|   457.7|
===
6 rows (PARSE: 0.000015 ms, COMPILE: 0.001712 ms, EXECUTE: 0.002004 ms (wall time))
```

Expected (courtesy of SQLFiddle):
```
a       b       a       b
12345   457     12345   457
12345   458     12345   457
12345   457     12345   458
12345   458     12345   458
123     459     123     459
12      351     12      351
(null)  342     (null)  (null)
(null)  234     (null)  (null)
```

I have tested this with both the hash and the sort merge join. Neither works correctly.

There should be a test for all implemented joins that this is fixed.

>          9) For every column CR of the result of the <joined table> that
>             is a corresponding join column and that corresponds to a column
>             C1 of T1 and C2 of T2, CR is possibly nullable if any of the
>             following conditions are true:
> 
>             a) RIGHT, FULL, or UNION is specified and 1 is possibly nul-
>               lable, or
> 
>             b) LEFT, FULL, or UNION is specified and 2 is possibly nul-
>               lable.

**Comment by lawben** [comment]
@ArneMayer have you had a look into this for the SMJ? Otherwise I will have a look to see if this is fixable.

**Comment by lawben** [comment]
As far as I can tell, this is fixed in #503. Someone should definitely double check this though, as I am not that familiar with the Join implementations.

**Comment by mrks** [comment]
The full outer join still looks broken:

<pre>
(debug)!> SELECT * FROM n n1 OUTER JOIN n n2 ON n1.a = n2.a
=== Columns
|       a|       b|       a|       b|
|     int|   float|     int|   float|
=== Chunk 0 ===
|    NULL|     342|    NULL|     342|
|    NULL|     342|    NULL|     234|
|    NULL|     234|    NULL|     342|
|    NULL|     234|    NULL|     234|
|      12|   350.7|      12|   350.7|
|     123|   458.7|     123|   458.7|
|   12345|   456.7|   12345|   456.7|
|   12345|   456.7|   12345|   457.7|
|   12345|   457.7|   12345|   456.7|
|   12345|   457.7|   12345|   457.7|
===
10 rows total (PARSE: 0.000007 ms, COMPILE: 0.000302 ms, EXECUTE: 0.001497 ms (wall time))
</pre>

**Comment by Bensk1** [comment]
@ArneMayer will look into that as soon as he gets time

**Comment by ArneMayer** [comment]
It is in progress now.
