### ISSUE TITLE
Issues during CSV import

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#315]
When we try to import certain CSV files we encounter a variety of errors. We seem to have issues with:

- [x] proper handling of quotes for escaping
- [x] problems with parsing of doubles (`template <>
 inline std::function<double(const std::string &)> CsvConverter<double>::_get_conversion_function() {`)
- [x] importing all rows of a file (miss around 3%)
- [x] import flag for auto compression of chunks (merged from #159)
- [x] json meta file (as suggested in #281)
- [x] evaluate std::stoi/... vs. boost::lexical_cast (see below)

**Comment by mrks** [comment]
While reviewing #396, I started wondering if `std::stoi` is really the best thing to use. First, it requires us to have template specializations for every type - something that `boost::lexical_cast` would do more elegantly. Second, I am not sure if we really want `std::string{"4bla"}` to be converted to `int{4}`. Unfortunately, neither has a strict mode where they complain about everything non-numbery.

**Comment by Bensk1** [comment]
Do we only use `std:stoi` if the column's data type was specified as `int`? Following the rule that we do not want to cover strange edge cases: If a column is specified (keeping in mind that the user has to explicitly define the meta file for csv import) as `int` and the csv contains `std::string{"4bla"}` any returned integer is fine in my opinion.

**Comment by lanice** [comment]
> Do we only use std:stoi if the column's data type was specified as int

Yes. For each column we create a `CsvConverter<column_type>`, and depending on the column type we call the different conversion functions.

**Comment by lanice** [comment]
One advantage of using `lexical_cast` would be that we wouldn't need to use different functions for each type, `stoi`, `stod`, etc. and could just use the templated `lexical_cast`

**Comment by lanice** [comment]
I've just run a very quick test using a) `boost::lexical_cast` and b) `std::stod` to import a 20k lines big CSV file containing a mixture of strings and doubles, and so far `boost::lexical_cast` is significantly slower than `std::stod` (~10.9 seconds vs ~10.1 seconds in Debug, ~1.64 seconds vs ~1.29 seconds in Release, on the pella).

**Comment by mrks** [comment]
Let's stick with the `std` methods then. We should use the second parameter `std::size_t* pos = 0` and assure that there are no unconverted characters:
http://en.cppreference.com/w/cpp/string/basic_string/stol

**Comment by lanice** [comment]
With all the points checked off, I think it is time to close this issue, @mrks , @Bensk1 ?

**Comment by mrks** [comment]
Nice :)
