### ISSUE TITLE
Refactor Visualization

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#326]
First, the code duplication between the two visualizers should be removed.

Second, if you break up the query below into multiple lines, things will fail.
```
load src/test/tables/tpch/customer.tbl customer
load src/test/tables/tpch/orders.tbl orders
load src/test/tables/tpch/lineitem.tbl lineitem

visualize astopt SELECT l_orderkey, SUM(l_extendedprice*(1.0-l_discount)) as revenue, o_orderdate, o_shippriority FROM customer, orders, lineitem WHERE c_mktsegment = 'BUILDING' AND c_custkey = o_custkey AND l_orderkey = o_orderkey AND o_orderdate < '1995-03-15' AND l_shipdate > '1995-03-15' GROUP BY l_orderkey, o_orderdate, o_shippriority ORDER BY revenue DESC, o_orderdate;
```
Instead of `visualize` as its own method in the console, it should be an option that can be prepended to any SQL statement. This removes code duplication between `_eval_sql` and `visualize`.

Furthermore, the console should store the last AST, optimized AST and query plan in a variable so that you can call `visualize [opt]` without a SQL statement and it visualizes the last executed statement.

**Comment by lawben** [comment]
@mrzzzrm I am looking into this refactoring and tried the command you said would fail. It doesn't fail when I execute it. Is it fixed already?

Some thoughts on refactoring:
  - I would keep `visualize` as a separate command and **not** append it to a query.  So we have a clean command to visualize, either with or without a query (i.e. using the last query). 
  - Code duplication in `visualize` and `_eval_sql` is a problem for now, but their are some ambitions to create a unified interface for SQL execution, which would reduce this duplication (#367) to a minimum.
  - Having a common method that wraps the creation and execution of the graphviz files is nice.

**Comment by mrzzzrm** [comment]
Are you in tomorrow? I'd probably rather talk about this in person. I've got a bit of graphviz stuff flying around on my join-graph branch.

**Comment by mrzzzrm** [comment]
@lawben this can probably be closed then, right?

**Comment by lawben** [comment]
No, because we still wanted to integrate the `visualize` command with the last executed SQL query. This is still in progress.

**Comment by mrzzzrm** [comment]
@lawben: @mrks thinks this is done?

**Comment by lawben** [comment]
I've started looking at this in regard to #565, but it looks like we'll just need a simple function that adds newlines every n characters. Haven't implemented it because I was hoping there's a boost function for it but I couldn't find one. Will fix this early next week unless someone feels like doing this beforehand.

**Comment by mrks** [comment]
That is a different issue though. Is there anything else to be done for the visualization?

**Comment by lawben** [comment]
If we do not want to keep this as an umbrella issue, then it can be closed. AFAIK there is no more viz refactoring necessary.
