### ISSUE TITLE
TPCH: Support OR in HAVING

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#328]
TPCH7 needs this, e.g.

**Comment by mrks** [comment]
Is this done? Do we have OR in both WHERE and HAVING?

**Comment by mrzzzrm** [comment]
Practically its missing in HAVING because the translator puts two different Aggregates (which are new, materialized tables) below the OR, which UnionPositions can't merge. This needs multiple parents per ASTNode and some sort of common subtree detection
