### ISSUE TITLE
Improve printed info on EXPECT_TABLE_EQ failure

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#397]
Currently, if the aforementioned function detects dissimilarities, different things will be printed. Sometimes just the info "mismatched column counts", sometimes the tables get printed...

If cells mismatch it looks like this:

```
/home/moritz/Coding/dryrice/src/test/base_test.cpp:151: Failure
The difference between left_val and right_val is 0.199981689453125, which exceeds 0.0001, where
left_val evaluates to 458.70001220703125,
right_val evaluates to 458.89999389648438, and
0.0001 evaluates to 0.0001.
Row/Col:1/1
```
(where "Row/Col:1/1" and "458.7" vs "458.89 are the actually interesting pieces of information)

We should streamline this! The following information should be available on EXPECT_TABLE_EQ-failure:

- Type of error: Column/Row Count mismatch, Column Type/Name mismatch, Cell data mismatch
- The conflicting tables with the clear information of which table was generated by Hyrise and which comes from SQLite/tbl-file
- Highlights (`!!!` prefix?) for the mismatching cells. Maybe even color-highlighting.
- Anything else?

**Comment by mrks** [comment]
@lanice

**Comment by mrzzzrm** [comment]
Quick shoutout: A failing EXPECT_TABLE_EQ causes all following EXPECT_TABLE_EQ in the same test to print as well, no matter whether they failed too, or not.
