### ISSUE TITLE
Use enum class for column type

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#425]
It feels out of place that we're still using string here and not enum classes and this should be changed. Or does anybody disagree?

**Comment by mrks** [comment]
Agreed

**Comment by TwoLaid** [comment]
100% agreed

**Comment by mrks** [comment]
We should start by looking into how `all_type_variant.hpp` has to change. Optimally, we could get the constants out of `type_strings` and avoid writing more conversion methods.

**Comment by mjendruk** [comment]
May I?

**Comment by mrks** [comment]
Sure, go for it!
