### ISSUE TITLE
Change AST name to convey graph nature

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#445]
@mrks wrote:

```

I don't even want to bring it up, that's why I'm adding this comment at the bottom: With the changes in this PR, we don't have an AST anymore. Technically, the tree is now a DAG. Do we want to change names? This will also come up once we touch the operator tree.

Also paging @Bensk1 @klauck @Bouncner
```

I would really like to go for `QueryGraph` or `QueryPlan` (name already taken :( ) with `AbstractQuery(Plan)Nodes` here, and refer to our Operators as the `Execution/OperatorGraph`. Mostly since that is what we're doing, we're "planning" the query. One might mistake it for the actual execution plan if we name it `QueryGraph/Plan` but then again, the Operator-Tree is a 1-1 mapping from the AST, with the exception of `_translate_aggregate_node()`.

(Maybe we could get rid of the logic in `_translate_aggregate_node()` and the bloody `AbstractOperator::recreate()` and just call the `ASTToOperatorTranslator0` to recreate Operator-Trees)

**Comment by Bouncner** [comment]
I am too far away from the current implementation, but I'm with you on the topic of finding another name for the AST (which always confused anyhow).

Does the separation into QueryPlan and PhysQueryPlan make sense? This should solve that nobody thinks the QueryPlan handles execution and the terms are also used by other databases.

**Comment by mrks** [comment]
Not a full answer, but an idea that I had when I received the notification email: I think I like `LogicalQueryPlan` and `PhysicalQueryPlan`. Since we don't really write that much but only use it as the name for the concept, the length should be not an issue.

**Comment by mrks** [comment]
* Conceptually, we will talk about logical and physical query plans.

* `PredicateNode : public AbstractLogicalPlanNode`
