### ISSUE TITLE
Use bigger tables for SQLiteTestRunner

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#460]
When we still had to write test tables by hand, it was ok to have smaller ones. For the test runner, we should have bigger ones with more columns, more rows, more values and NULL values (but not in all columns).

**Comment by mrks** [comment]
@lanice

**Comment by mrzzzrm** [comment]
With the new TpchDbGenerator merged, using TPCH tables might be an (additional) option

**Comment by lanice** [comment]
Can we close this?
