### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#461]
https://github.com/hyrise/hyrise/pull/439 had issues with the clone mechanism and the node concept. Rinse and repeat

**Comment by mrks** [comment]
I will sum up the options that we discussed in three comments below. Let us first add anything that is missing and then (not now!) vote on the three options using thumbs up ("yes, that's good"), abstention, or thumbs down ("I don't think that's a good idea").

**1. SQLToASTTranslator directly creates views**
+ Requires the smallest amount of new classes and additional code
- A translator should only translate things, not change them. We might need to rename it from translator.
- If we have more expensive operations, such as creating an index, doing this in the translator would block the execution

**Comment by mrks** [comment]
**2. SQLToASTTranslator returns tasks (or other DDL-specific things)**
+ It is clear that the returned thing is not an AST node or anything that can be translated into an operator.
- The return value of the translator is unclear and the caller has to distinguish between different cases.

**Comment by mrks** [comment]
**3. SQLToASTTranslator returns DDL-Nodes**
(+) We don't have to change existing interfaces
(-) DDL instructions have to be added as a node, into the ASTToOpTranslator, and as an operator
(-) The operator subsystem needs to be made aware of ASTs
(-) The semantics of `set_transaction_context` become unclear

**Comment by mrks** [comment]
Paging people who were in that discussion on Thursday... @Bensk1 @mrzzzrm @mjendruk @TwoLaid @ArneMayer @lawben

**Comment by TwoLaid** [comment]
I still prefer solution *3*, but 2 is also fine with me

**Comment by TwoLaid** [comment]
But didn't we also discuss an alternative solution to 2 and 3? Where (I think) the `ASTTranslator` was able to output both Nodes but also "other nodes" (for DDL)

**Comment by mrks** [comment]
Isn't that 2?

**Comment by mrzzzrm** [comment]
I'm for 3. Let's create DDL nodes. To me it feels like the least of all evils.

**Comment by mrks** [comment]
Ok, 3 it is. I'll work on this once I find the time.
