### ISSUE TITLE
TableScan: If ScanType::OpBetween is set, the scheduler will be bypassed

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#462]

**Comment by mrks** [comment]
We should define if the workaround with two table scans should happen in the ASTToOperatorTranslator or in the TableScan itself. I believe the translator would be the better place.

**Comment by Bensk1** [comment]
Agreed

**Comment by Bensk1** [comment]
There would be no standalone between-TableScan with the proposed solution. But it appears like the cleaner option to me.

**Comment by mrks** [comment]
And I think there shouldn't be. We don't support it atm, so we shouldn't pretend that we do.
