### ISSUE TITLE
ChunkSize of Operators with two Inputs

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#474]
We are using the `chunk_size` of the input tables. However, operators such as the table scan don't set the `chunk_size` of the temporary table. As a result, this is always 0:

https://github.com/hyrise/hyrise/blob/03730edda332b221feff7fddf61987ca9db07ac7/src/lib/operators/union_positions.cpp#L107

Furthermore, this code is never executed and is untested:

https://github.com/hyrise/hyrise/blob/03730edda332b221feff7fddf61987ca9db07ac7/src/lib/operators/union_positions.cpp#L178

**Comment by mrzzzrm** [comment]
I believe the first issue is broader: How do we set the chunk size for operators with two inputs? JoinHash and JoinNestedLoop use chunk size 0 as well. I'll take the freedom to rephrase this issue. The second part of this issue is fixed by #491

**Comment by mrks** [comment]
This should be irrelevant as of #512
