### ISSUE TITLE
Logical+Physical Query Plan with all Operators

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#476]
Should we build one LQP and one PQP that contains all nodes / operators that we have? We could use that one to test the visualizations as well as the recreate methods.

**Comment by mrzzzrm** [comment]
Looking for issues to close. 
Is this something we would do? I'm not overly excited by it, tbh.

**Comment by mrks** [comment]
#742 has shown that `recreate` is not (properly) tested yet. That could have helped with that. I would leave this open for now, but it's probably not the highest priority.

**Comment by mrks** [comment]
Since 66f93de9049b39052d58ce5be1a8e784bd820392 added more LQP tests, this only has limited sense.
