### ISSUE TITLE
Discuss return type policy

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#478]
We do have strong type definitions like `ColumnID, ChunkOffset and ChunkID`. The interfaces of `Table, Chunk and [Base|Value|Reference|Dictionary]Column` are inconsistent. For example, `Table::column_count` [returns](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/table.hpp#L43) `uint16_t` while `Table::chunk_count` [returns](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/table.hpp#L57) `ChunkID`.

It is questionable whether `ChunkID, ChunkOffset or ColumnID` are correct return types for count- or size-like methods. On the other hand, `uint16-t` seems a bit arbitrary, too.

What are your opinions on that? In either way, we should have a consistent solution.

**Comment by TwoLaid** [comment]
We could use member types like the standard, e.g., `std::vector::size_type`:

```C++
class Table {

  using ChunkSizeType = ChunkID;
  using ColumnSizeType = ColumnID;

  ChunkSizeType chunk_count() const;

  ColumnSizeType column_count() const;
};
```

**Comment by Bensk1** [comment]
I like that. We could discuss it during our next fortnightly, I believe some others had an opinion on that one.

**Comment by mrks** [comment]
Ohne *Type.
In types.hpp (explizit, nicht für alle, den TransactionSize gibt keinen Sinn)

**Comment by mrks** [comment]
Mmmh. Thinking about it, `ChunkSize` is not that good because it is completely different from `Chunk::MAX_SIZE` but named similarly.

`ChunkCount`?

**Comment by Bensk1** [comment]
Sure!

**Comment by mrks** [comment]
duplicate
