### ISSUE TITLE
Clarification of chunk_size = 0

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#480]
If a table's `chunk_size` is set to 0, the table holds a chunk of unlimited size. Does this also mean that there will only be a single chunk? This would make sense to me. We would have to enforce this in `Table::create_new_chunk()`.

**Comment by TwoLaid** [comment]
+1

**Comment by Bouncner** [comment]
Are we sure that we should limit ourselves this way?

Maybe we can find something like chunksize = 0/infinity, where 0 means "let it grow until we decide to fix it and compress" and infinity means "let it grow forever, there will ALWAYS be only a single chunk".

Especially since we do not yet have an idea how to set the chunk sizes (NUMA, joining, parallel processing, dictionary overhead, ...), there might come situations where Jan's "Self-Pimping Database" would like to compress a chunk at a given point in time?

**Comment by mrks** [comment]
I am not fully happy with the current chunk size concept either, especially when it comes to temporary tables where the chunk size becomes somewhat random.

Adding such a limitation, however, does not make sense to me. First, I don't see a reason where that limitation helps. Second, this would limit us to a table size of 2^32.

What we should do in any case is to make "0" mean ChunkOffset's max value. Currently, exceeding that value might break everything.

**Comment by Bensk1** [comment]
> What we should do in any case is to make "0" mean ChunkOffset's max value. Currently, exceeding that value might break everything.

This is correct, but if "0" would mean ChunkOffset's max value, wouldn't this also limit the table size to 2^32?

**Comment by mrks** [comment]
No, the table size is and will be (ChunkID::max * ChunkOffset::max).

**Comment by mrks** [comment]
Additionally, we might want to have a mode where we don't start a new chunk at a certain row count, but whenever we have some free resources and feel like compressing something.

Instead, we should consider if we want for the default to be the maximum allowable chunk size and disallow a max chunk size of 0. This would allow us to remove all the edge cases for 0 and avoid the ambiguity that led to this issue. Also, I propose renaming it `maximum_chunk_size`.

**Comment by lanice** [comment]
Having it the maximum allowable chunk size sounds good I think. How would that look like in the meta file? We could allow leaving `chunk_size` blank to be the default value (max). If we want to be able to specifically set it to maximum allowable we'd have to make the `chunk_size` value a string, then we can also allow something like `max`.

**Comment by mrks** [comment]
Leaving it blank sounds good to me.
