### ISSUE TITLE
Document all failing/disabled tests // add to lint

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#489]
#488 is introducing more tests that currently fail and thus are disabled. We already have 15 disabled tests and chances are that each and every one of them documents a problem.

Adding tests that currently break is a great thing - it greatly helps in reproducing the error. It does, however, not replace an issue in GitHub. I propose that every disabled test should have a comment referencing the issue:

    TEST_F(SQLExpressionTranslatorTest, DISABLED_ExpressionIn /* #123 */) {

Once this is done for all existing tests, I would add this to `lint.sh`:

    set -e
    // current lint
    ! grep -r 'DISABLED_' src/test | grep -v '#[0-9]asf\+' # check that all disabled tests are documented in an issue

**Comment by mrks** [comment]
Thinking about it, this might disrupt the development workflow. If you add tests first (we all to TDD, right?), you don't have an issue number. Thus, the CI will not get past the lint stage.

Do we want to move the lint stage to the back of the CI pipeline?

**Comment by lanice** [comment]
I prefer the linting stage at the front to be honest, just because as you said, you have the whole CI pipeline run just to learn that you forgot the linter.

**Comment by mrks** [comment]
I could also move this into another Github Status Report, just like the coverage. Not sure if this is overkill.
