### ISSUE TITLE
How to include dbgen

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#490]
- As a module built by our build system and invoked as a separate executable generating tbl files.
- Integrated into `hyriseLib` directly generating `opossum::Tables`. When generating bigger tables for TPCH benchmarks this is probably the best choice, since importing the generated tbl files takes a lot of time.

**Comment by mrks** [comment]
How long does generating the test files take if we choose option 2?

**Comment by mrzzzrm** [comment]
Generating TPCH tables with scale factor 1 (i.e. 1GB of text) takes 12s here. Not sure how much of this is generating the tbl files via fprintf(), but I guess it's a lot.

**Comment by mrks** [comment]
That's fine. In that case, we don't even need to cache the generated files anywhere. I would go with option 2.

**Comment by mrks** [comment]
@mrzzzrm close?
