### ISSUE TITLE
CASE statements

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#493]
Needed for TPC-H. For now, we don't need to implement nasty things such as subselects in the cases, but we should keep in mind that it is possible.

**Comment by mrzzzrm** [comment]
On it and currently wrapping my head around it. I think the implementation of this will also include support for Projection-After-Aggregate stuff also needed for TPCH, e.g. `SUM(a) / SUM(case ...)`

**Comment by mrks** [comment]
Just added this issue for #497
