### ISSUE TITLE
Further improvements for CI

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#5]
- [x] Indicate that a build is currently running
- [x] Mr. Keller tear down that wall! (Make Jenkins status visible for everybody, not only logged in users)
- [x] Fix broken status images in readme
- [x] Coverage Badge
- [x] Add gcc-7 support
- [x] Build branch and pr
- [x] Restrict CI access to known users. Prevent building of PRs from unknown users. (Arbitrary code execution)
- [x] Have NUMA and Non-NUMA runs (make them run in parallel)

**Comment by mrks** [comment]
Removed "Cancel Jenkins build on Update of PR" from the list. This is not easy to achieve with the current setup. Since the builds are reasonable fast now, the original need for this is gone, too.

**Comment by Bensk1** [comment]
The check list is completed, but what about coveralls?
