### ISSUE TITLE
Make Coverage/Sanitizer build an option for the entire build directory

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#504]
Currently we're generating special target for a number of targets that are compiled/linked with the coverage/sanitizer flags. This has some downsides:

- adding a new target (such as `hyriseSystemTest`) requires thinking about whether one wants coverage/sanitization for it. 
- If you decide something needs coverage/sanitization, you have to mess with cmake.
- Playground/Console don't have coverage/sanitization by default, but scenarios are thinkable where one would like to investigate something in the console with enabled sanitization.

I therefore propose to introduce cmake options `HYRISE_COVERAGE_ENABLED` and `HYRISE_SANITIZERS_ENABLED` which, if set to `TRUE` when calling `cmake` enable their respective option for ALL targets.
This would reduce cmake code, the number of targets that appear in the IDE menu and gets us rid of the `EXCLUDE_FROM_ALL` hacking we did a while back for the coverage/sanitization tests.

**Comment by mrzzzrm** [comment]
(I don't think this would be much work)

**Comment by mrks** [comment]
Sounds good. Is there any cmake standard for passing these options?

**Comment by mrzzzrm** [comment]
There is this poorly documents, but simple function called `option` https://cmake.org/cmake/help/v3.8/command/option.html

So we would have two lines like `option(HYRISE_COVERAGE_ENABLED "Set this to TRUE to enable gcov for gcc under Linux etc..." FALSE)` and when you call `cmake -DHYRISE_COVERAGE_ENABLED=TRUE` when configuring the projection, coverage is enabled, otherwise it isn't.

**Comment by mrzzzrm** [comment]
Made this a DevOps issue. Is this DevOps stuff? Not too fit with the words of fancy.....

**Comment by Bensk1** [comment]
This fits our definition of DevOps. The clean way to use this would be to have four build folders?

- `cmake-build-debug`
- `cmake-build-release`
- `cmake-build-sanitize`
- `cmake-build-coverage`

**Comment by mrks** [comment]
You mean in the Jenkins file? In general, cmake standard is that everyone can name their build forder however they like.
