### ISSUE TITLE
Generate statistics for Projections and Aggregates

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#511]
This one breaks in `column_statistics.cpp:365`. I have not investigated yet what is going wrong here.

```
load src/test/tables/int_float6.tbl int_float6
load src/test/tables/int_float4.tbl int_float4
SELECT * FROM int_float4 T1 NATURAL JOIN (SELECT b, a FROM int_float6) AS T2;
```

The associated test is disabled in the sqlite query runner.

**Comment by mrks** [comment]
The problem is that the ProjectionNode currently does nothing to the statistics but simply passes the input statistics forward. When we reorder columns as done in the example above, this means that we suddenly have float stats for an int column.

We need to add `derive_statistics_from` in the `PredicateNode` and add `TableStatistics::generate_predicate_statistics`. The second method will have to look at the expressions to see how the affect the statistics.

For column reordering, this should be just a remapping. For arithmetic operations, we need to update min/max accordingly.

**Comment by mrzzzrm** [comment]
Do this for AggregateNodes as well

**Comment by mrzzzrm** [comment]
The herein described issue doesn't exist anymore, dummy statistics are generated for Aggregate and Projection; and column reordering is taken into account. With the statistics rewrite in progress, this is an non-actionable issue anyway.
