### ISSUE TITLE
Aggregate: Counting NULL values fails

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#531]
```
script src/test/tables/tpch/load.script
SELECT c_custkey, count(o_orderkey) FROM customer left join orders on c_custkey = o_custkey WHERE o_comment = 'bla' GROUP BY c_custkey;
```

Expected result:
A table `(c_custkey, 0)` because no order has the comment "bla".

Actual result:
An empty table.

I would expect the error to be in `aggregate.cpp`, somewhere around here:

```
if (value.is_null()) {
        /**
         * If the value is NULL, the current aggregate value does not change.
         * However, if we do not have a result entry for the current hash key, i.e., group value, 
         * we need to insert an empty AggregateResult into the results.
         * Hence, the try_emplace with no constructing arguments.
         */
        results.try_emplace((*hash_keys)[chunk_offset]);
      }
```

**Comment by TwoLaid** [comment]
I'm confused. [This SQL fiddle](http://sqlfiddle.com/#!9/034f63/3) should replicate that query and it returns an empty tables as well. Just like we get on the console:

```
(debug)> SELECT c_custkey, count(o_orderkey) FROM customer left join orders on c_custkey = o_custkey WHERE o_comment = 'bla' GROUP BY c_custkey
=== Columns
|c_custkey|COUNT(o_orderkey)|
|      int|             long|
=== Chunk 0 ===
Empty chunk.
===
```

Can you please explain the problem a little more?

**Comment by mrks** [comment]
Ah, I slightly modified the query. What it should have been is this:

`SELECT c_custkey, count(o_orderkey) FROM customer left join orders on c_custkey = o_custkey AND o_comment = 'bla' GROUP BY c_custkey;`

It actually is an issue with JOIN ... ON ... AND ..., not with the aggregate - sorry!
