### ISSUE TITLE
Check sanity of parallel inserts

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#533]
`insert.cpp` calls `Chunk::grow_mvcc_column_size_by` to increase the size of the MVCC vector:

```
void Chunk::grow_mvcc_column_size_by(size_t delta, CommitID begin_cid) {
  auto mvcc_columns = this->mvcc_columns();

  mvcc_columns->tids.grow_to_at_least(size() + delta);
  mvcc_columns->begin_cids.grow_to_at_least(size() + delta, begin_cid);
  mvcc_columns->end_cids.grow_to_at_least(size() + delta, MAX_COMMIT_ID);
}
```

What if `size() == 1` and two threads call this method at the exact same time, one with `delta == 2`, the other with `delta == 3`.

Let's say that both threads execute `size() + delta` at the same time. Wouldn't that leave us with `3` and `4`? That would mean that the final size of the vectors is `4`, not `6` as it should be.

**Comment by mrzzzrm** [comment]
Calling this->mvcc_columns() creates a SharedLockingPtr which should nicely line up these two operations. Closing, please reopen if I missed something.

**Comment by mrks** [comment]
Yes, also we have `auto scoped_lock = _target_table->acquire_append_mutex();`. That should deal with the situation described above.
