### ISSUE TITLE
TransactionContext hides exceptions

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#535]
In some cases, the transaction context (line 34) hides the actual exception by bringing up another one which can be really confusing.

Example in hyriseConsole:
> generate ITEM 
SELECT * FROM ITEM;

shows a problem with the ValidateOperator even though the error is caused by the unquoted keyword `ITEM`

**Comment by mrks** [comment]
This is messed up in a completely different way:

https://github.com/hyrise/hyrise/blob/5866e28db166896ecc433f0aa5acc2dcd8a9197d/src/benchmarklib/tpcc/tpcc_table_generator.cpp#L33-L35

**Comment by mrks** [comment]
```
(debug)> setting scheduler off
Scheduler turned off
(debug)> SELECT * FROM ITEM
===
100000 rows total (PARSE: 0.000005 ms, COMPILE: 0.004645 ms, EXECUTE: 0.046815 ms (wall time))
(debug)> setting scheduler on
Scheduler turned on
(debug)> SELECT * FROM ITEM
===
0 rows total (PARSE: 0.000005 ms, COMPILE: 0.000176 ms, EXECUTE: 0.000084 ms (wall time))
(debug)> terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/operators/abstract_operator.cpp:82 TransactionContext is expired, but SQL Query Executor should still own it (Operator: Projection)
Abort trap: 6
```
