### ISSUE TITLE
JOIN behaves incorrectly when NULL-values are present

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#538]
Test in the console:
```
load src/test/tables/aggregateoperator/groupby_int_1gb_0agg/input_null.tbl table_a;
load src/test/tables/aggregateoperator/groupby_int_1gb_1agg/input_null.tbl table_b;
SELECT "l".a, "r".a FROM table_a AS "l" JOIN table_b AS "r" ON "l".a = "r".a;
```
Result:
```
=== Columns
|       a|       a|
|     int|     int|
=== Chunk 0 === 
|      12|     123|
|      12|     123|
|      12|      12|
=== Chunk 1 === 
|     123|   12345|
|     123|   12345|
=== Chunk 2 === 
|   12345|   12345|
|   12345|   12345|
|   12345|    NULL|
|   12345|    NULL|
|   12345|    NULL|
|   12345|    NULL|
|   12345|   12345|
|   12345|   12345|
===
13 rows total (PARSE: 0.000010 ms, COMPILE: 0.000249 ms, EXECUTE: 0.011026 ms (wall time))
```

**Comment by lanice** [comment]
Expected result (according to SQLite):
```
      12       12 
      12       12 
      12       12 
     123      123 
     123      123 
   12345    12345 
   12345    12345 
   12345    12345 
   12345    12345 
   12345    12345 
   12345    12345 
   12345    12345 
   12345    12345 
```

**Comment by TwoLaid** [comment]
stop breaking the joins! :( I'll look into it (for the HashJoin)

**Comment by lanice** [comment]
That's one of the reasons why I'll add bigger tables for tests now, so that these things actually come up in tests :sweat_smile:

**Comment by mrks** [comment]
Whenever we find a bug in the sqlite runner, we should also add a regular unit test. This is especially important for the join, because the sqlite runner only sees the type of join selected by the optimizer/LQPTranslator.

**Comment by ArneMayer** [comment]
I am doing the null value fix for the sort merge join right now. I will look into this as well.

**Comment by mrks** [comment]
I added a test doing what @lanice is doing above in #543. The Hash Join seems to be fine.

**Comment by lanice** [comment]
This is not fixed when using the Console or the SqliteTestrunner. I don't know why it behaves differently on the explicit test case you created.

**Comment by mrks** [comment]
Confirmed - thank you for verifying this.

```
[  FAILED  ] JoinNullTest/0.InnerJoinWithNullRef2, where TypeParam = opossum::JoinHash
```

Added in #550 (currently disabled). The other joins are fine.

**Comment by mrks** [comment]
@TwoLaid - Could you please have a look?

**Comment by TwoLaid** [comment]
Sorry @mrks , I didn't look into this further because you mentioned that the HashJoin was fine. But thank you for fixing it!
