### ISSUE TITLE
Deal with exceptions in worker threads

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#545]
Currently, an exception in a worker thread is uncaught and kills everything. We need to find a way where those don't break everything while still making sure that we don't hide any issues.

**Comment by mrks** [comment]
I have something prepared, but it currently blocked because of the exception problem with TBB.

**Comment by mrks** [comment]
https://github.com/hyrise/hyrise/tree/mrks/scheduling-throw

**Comment by mrks** [comment]
* don't catch "serious" issues, only `invalid_argument`
* serious issues (e.g., (Debug)Assert should still lead to `std::terminate`
* check if the rethrown exception can still be used for debugging

**Comment by nilsthamm** [comment]
After discussing this topic offline we came to the following conclusion. An additional exception handling layer in the workers is not worth it if the sole purpose of this would be to catch user input related exceptions in the operators. Rather we want to detect all typos and simple errors during translation and still crash always if an operator throws an exception
