### ISSUE TITLE
Console visualization unreadable for nodes with long texts

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#565]
The statement `visualize lqp SELECT * FROM "ORDER" o JOIN "ORDER_LINE" ol ON o.O_ID=ol.OL_O_ID WHERE o.O_ID=17` yields a rather long projection list, which is not readable within the console.
For the generated png is readable when zooming in.

We might want to break the projection (or any operator with long outputs) into multiple lines.

![lqp](https://user-images.githubusercontent.com/1745857/33567078-4b11c3fa-d922-11e7-9fe5-a26b4d5cec24.png)

**Comment by Bouncner** [comment]
The output png has a transparent output, in case you wonder why you don't see anything.

Here is a screenshot of the console.
![screen shot 2017-12-04 at 18 19 12](https://user-images.githubusercontent.com/1745857/33567615-11d145dc-d924-11e7-9558-6bcaaf03ada9.png)

**Comment by mrzzzrm** [comment]
graphviz is so bad at layouting sometimes.... I'd add this to #326
