### ISSUE TITLE
Columns from subqueries incorrectly marked ambiguous

### ISSUE THREAD

**Issue by TwoLaid** [hyrise/hyrise#568]
Doing this in the console:

```
(debug)> load src/test/tables/int_float.tbl int_float
(debug)> load src/test/tables/int_float2.tbl int_float2

(debug)> SELECT * FROM (SELECT "right".a a, "left".b b FROM int_float AS "left" LEFT JOIN int_float2 AS "right" ON "left".a = "right".a) t where t.a > 0
```

throws this exception: `Column name a is ambiguous.`.

Any idea why @mrzzzrm  ?

**Comment by mrzzzrm** [comment]
yeah, `ProjectionNode::find_column_id_by_named_column_reference` assumes it can just ask its input for its ColumnID of a specific NamedColumnReference, but in this case the input is a Join and each of its inputs has a Column "a". Not trivial to fix, will tackle this at some point with the upcoming ColumnOrigins in mind.
