### ISSUE TITLE
Investigate test coverage randomness and wrong results

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#587]
In my latest pull request #566, the test coverage of reference_column_iterable.hpp dropped 100% to 15% from one commit to the next. Some methods (mostly inline / templated methods like `SimdBp128Decoder::get`) are shown as not covered although they are. I have no idea where to start fixing this.

**Comment by mrks** [comment]
Since switching to clang coverage, the coverage of the last master builds seems quite stable. I guess that fixed it.
