### ISSUE TITLE
Shuffled test fails CSV export

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#588]
In PR #586 Jenkins failed on [clangDebugRunShuffled](https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/lawben%2Fsingle_roots/5/pipeline) with the following error:
```
[----------] 10 tests from OperatorsExportCsvTest
[ RUN      ] OperatorsExportCsvTest.NonsensePath
[       OK ] OperatorsExportCsvTest.NonsensePath (1 ms)
[ RUN      ] OperatorsExportCsvTest.DictionaryColumn
../../../src/test/operators/export_csv_test.cpp:123: Failure
Value of: file_exists(filename)
  Actual: false
Expected: true
../../../src/test/operators/export_csv_test.cpp:124: Failure
Value of: file_exists(meta_filename)
  Actual: false
Expected: true
unknown file: Failure
C++ exception with description "compare_file: Could not find file /tmp/export_test.csv" thrown in the test body.
[  FAILED  ] OperatorsExportCsvTest.DictionaryColumn (1 ms)
```

Someone should fix this :)

**Comment by mrks** [comment]
When reporting fails in the shuffled test, please include the seed that is printed at the top of the log.

**Comment by lawben** [comment]
The seed message:
`Note: Randomizing tests' orders with a seed of 29410 .`

**Comment by lanice** [comment]
The actual seed where the tests fail is `29412`. However I cannot reproduce the error even with this seed.
