### ISSUE TITLE
TableScan takes value2, but doesn't support BETWEEN

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#591]
According to @mjendruk the current TableScan doesn't support BETWEEN, but the constructor still makes it look like it does (by taking two value parameters).
This shortcoming should either be documented in the TableScan class, or, if we do not plan to support it in the foreseeable future, the TableScan interface should be adjusted.

**Comment by Bensk1** [comment]
I vote for adjusting the interface.

**Comment by mrks** [comment]
I think we will have to look at to that in the future, because `between` is twice as fast as `>` and `<`. Putting it back into the interface wouldn't be a big issue - we probably could even just revert the commit that takes it out.

For now, feel free to remove it.

**Comment by mjendruk** [comment]
This has already been removed in the master.
