### ISSUE TITLE
Optimizer not threadsafe

### ISSUE THREAD

**Issue by apopiak** [hyrise/hyrise#592]
Hey, Looking at the [`Optimizer`](https://github.com/hyrise/hyrise/blob/4bb839abc6665dfeac6e1563c84409988d99c0a7/src/lib/optimizer/optimizer.cpp#L11), I see that it is a singleton, but the access is not threadsafe. Is that intentional because it is only ever called from one thread?

**Comment by mrzzzrm** [comment]
Can you point me to where the "access is not threadsafe"? The Optimizer is not explicitly designed to be thread safe, but from a quick glance at it I can't tell where it has races. There is no mutable state as well, so...

**Comment by apopiak** [comment]
Well `get` could be called from 2 threads simultaneously and AFAIK `static` doesn't make sure the object is not created twice.

**Comment by apopiak** [comment]
Probably doesn't matter much here, because it's not important to get the same object, because it's just and algorithm anyway.

**Comment by apopiak** [comment]
Never mind, just saw this: https://stackoverflow.com/a/8102145

**Comment by apopiak** [comment]
Aaaand the Microsoft people claim something different o.O (https://blogs.msdn.microsoft.com/oldnewthing/20040308-00/?p=40363)

**Comment by mrks** [comment]
" [Note: After this article was written, the C++ standard has been revised. Starting in C++11, scoped static initialization is now thread-safe, but it comes with a cost: Reentrancy now invokes undefined behavior.] "
