### ISSUE TITLE
Remove old MP tag

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#593]
Apparently there is "1 release" for hyrise which turns out to be an old MP tag. 
![image](https://user-images.githubusercontent.com/2679018/34112562-3be32a0e-e40d-11e7-95cb-e83dd09b6cc8.png)

I think this can be removed and just makes the github profile unclean. However, I ain't gonna ever do anything to this project that doesn't exclusively affect a branch of mine.

**Comment by mrks** [comment]
done
