### ISSUE TITLE
Add skew to TPC-H table data

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#595]
Apparently, there is some existing work:

- https://link.springer.com/chapter/10.1007/978-3-642-32627-1_10
- JCC-H: adding Join Crossing Correlations with Skew to TPC-H
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=52430

**Comment by Bensk1** [comment]
@ArneMayer eventuell nach der Masterarbeit

**Comment by mrks** [comment]
As TPC-DS is skewed, I don't consider it to be that important anymore to have a skewed TPC-H, too. Moved it to Trello, closing here.
