### ISSUE TITLE
Remove operator specific methods from BaseColumn interface

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#599]
Currently the `BaseColumn` interface includes two methods which are each only used in one operator.  

- [x] `copy_value_to_value_column`: used in `Sort`
- [x] `write_string_representation`: used in `Difference`

I don’t think they are general enough to be part of the interface. The functionality should therefore be moved to the operators.

**Comment by mrzzzrm** [comment]
YES. Our base class interfaces (or any class interface, really) should be as lean and clean as possible. Otherwise they remind me of OpenSceneGraph and I get angry. 

What do you think of the arguments made for free functions here, @mjendruk https://youtu.be/WLDT1lDOsb4

**Comment by mrzzzrm** [comment]
Also I want our own compiler with this implemented https://en.wikipedia.org/wiki/Uniform_Function_Call_Syntax

**Comment by mjendruk** [comment]
Done! Shohoo 🎉
