### ISSUE TITLE
CI is too slow... again

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#605]
#603 has been building for 15 minutes now. That is annoying.

**Comment by mjendruk** [comment]
We could set `-j 50` (it’s 10 right now).

**Comment by mrzzzrm** [comment]
Looking for issues to close. 
Is this still a relevant issue? @mrks

**Comment by mrks** [comment]
I just discussed this two days ago with our admin. We still have to find a better solution - if it was 15 minutes now, I would be happy...

**Comment by tbjoern** [comment]
not sure if this is known already, but i found that compiling jit_llvm_bundle takes forever, at least 10 minutes in total.
```
[ 59%] Building CXX object src/lib/CMakeFiles/hyrise.dir/utils/numa_memory_resource.cpp.o
[ 59%] Building CXX object src/lib/CMakeFiles/hyrise.dir/utils/pausable_loop_thread.cpp.o
[ 60%] Building CXX object src/lib/CMakeFiles/hyrise.dir/utils/performance_warning.cpp.o
[ 60%] Building CXX object src/lib/CMakeFiles/hyrise.dir/operators/jit_operator/jit_types.cpp.o
[ 60%] Building ASM object src/lib/CMakeFiles/hyrise.dir/embed_llvm/jit_llvm_bundle.s.o
```

**Comment by mrks** [comment]
Did you run `make` single-threaded? Otherwise it might also be one of the files somewhere before.

**Comment by tbjoern** [comment]
Its an observation from this build https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/PR-668/32/pipeline/
i did not configure anything in particular

**Comment by mrks** [comment]
I talked to @jfrohnhofen about this and he is quite sure that it is not that file. Probably, it is just the last task to be created. Chances are that we are waiting for `join_nested_loop.cpp.o`

**Comment by mrzzzrm** [comment]
Closing this issue as it has no value currently. The issue with building `jit_llvm_bundle.s.o` is definitely another file building very long, from personal experience.
