### ISSUE TITLE
Comment style

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#611]
Personally I do it like this

```c++
// comment about the next line 
int a = 5; // i.e. about this line
int b = 6; // ...but not this

// Or about the purpose of a block
if (true) {
  // Lot's of things 
}

/**
 * Comment about the next section of code 
 */
int c = 7; // all these
int d = 8; // lines
int e = c + d; // are covered
```

comments in headers I always do like this: 

```c++
/**
 * Explanation of foo()
 * @param i <about i>
 */
void foo(int i);
```
that seems to be what most people do, yet some code uses `// <doc>` for methods docs as well. 
I think it's worth settling on some simple comment style rules for future code, not advocating changing existing code unless someone feels really bored.

**Comment by mrks** [comment]
I haven't seen any example so far where the lack of a convention caused any understanding problems for me. If we introduce a rule, we have to make sure that it's followed. Since we already have a number of rules, I wonder what the benefit of having another one is.

**Comment by mrzzzrm** [comment]
meeeh, fair point, I guess. I just like rules I suppose :(
