### ISSUE TITLE
Run Lint in parallel or after everything else in CI

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#614]
I sometimes fire&forget-commit only to return to a failed CI build some hours later. Why did it fail? Oh lint of course but I don't get the information whether the rest of the build was fine because right after lint failure, CI just stops.

Does anything speak against changing this?

**Comment by mrks** [comment]
Part of the reason for this is to reduce the load on the CI. Maybe allow for the fastest build to run (clang-release, I believe) and skip the others?
