### ISSUE TITLE
Console: script dirname does not fail

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#615]
```
(debug)!> script src
Executing script file: src
Executing script file done
```

**Comment by lanice** [comment]
I'd postpone this until C++17s `filesystem` is out of <experimental> (for GCC at least), then this is a no-brainer.

**Comment by mrks** [comment]
Since GCC 8 will not arrive for a while and the filesystem part needs a library to be linked, I am not sure if this is really better than a call to `stat`.

**Comment by mrks** [comment]
Not saying anything against filesystem, but this looks like using a sledgehammer to crack a nut to me

**Comment by lanice** [comment]
I assumed that we'd use `filesystem` for more than just this once it's out. And you're right, it's probably not better than `stat`, just cleaner.
