### ISSUE TITLE
Help text in paged console output not wrapped if terminal too small

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#620]
<img width="640" alt="screen shot 2018-01-10 at 14 33 04" src="https://user-images.githubusercontent.com/7422656/34775367-356e172a-f613-11e7-9033-163b33d91222.png">

My terminal ends after the 'a' and I did not resize it after starting the console. I guess this should be wrapped if the terminal is too small?

**Comment by mrks** [comment]
The console does not support horizontal scrolling in the ncurses environment yet. That is in the list of postponed issues.
