### ISSUE TITLE
LQP cloning probably broken for diamond structures

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#625]
Haven't tested this, but think of a typical Union shape. The cloned LQP wouldn't have that shape with our current cloning code.

**Comment by mrks** [comment]
Confirmed:

<img width="761" alt="screen shot 2018-02-14 at 15 50 57" src="https://user-images.githubusercontent.com/575106/36210512-e0e59a78-119e-11e8-8d7e-0df3ca75a642.png">
