### ISSUE TITLE
Optimizer vs LQPTranslator: Who picks the JoinOperator

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#628]
When ordering Joins, SortMerge- and HashJoins have different cost functions, so the Optimizers choice of JoinOrder depends on a certain JoinOperator being used.
Currently the LQPTranslator decides which one is used. Should the Optimizer set a flag in a JoinNode, indicating which JoinOperator it wants, or should it just assume which Operator the LQPTranslator will pick (i.e. HashJoin for Non-Outer-Equi Joins and SortMerge for everything else)? Another alternative would be the JoinNode figuring this out itself (i.e. by providing a method `JoinOperatorType join_operator()`, where JoinOperatorType is `enum class JoinOperatorType { SortMerge, Cross, Hash }`.) I think this is currently my preferred solution.

**Comment by mrks** [comment]
I think that everything that has to do with choosing between logically equivalent plans should be in the optimizer (i.e., in a rule). The optimizer could set flags in the node which are then used by the translator.

Having "smart" nodes (as opposed to the struct-like things that we have now) doesn't feel right to me. What is your reason to prefer that approach?

**Comment by Bensk1** [comment]
I also think that this decision should be in the optimizer. In addition, the optimizer's choice of JoinOrder depends on the particular join algorithm, but the choice of a join algorithm can also depend on the JoinOrder, e.g., prefer SortMerge if we need a sorted output afterwards.

**Comment by mrzzzrm** [comment]
It's simple that's all, but smart nodes are not a good idea, I agree. Good point about the SortProperty, @Bouncner - so a flag in JoinNode it is, Thank You!
