### ISSUE TITLE
Improve docs for Chunk::use_mvcc_columns_from() (or remove it)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#633]
Only the Projection uses this and from the docs I can't grasp why it is necessary. Why does any operator have to deal with MVCC, shouldn't Validate take care of this?

Either update the docs to clarify this, or, if the operation is unnecessary, remove it.

@mjendruk maybe you can give me a clue here?

**Comment by mjendruk** [comment]
This is only necessary if the table is validated after the projection is applied. A simple projection reuses the columns of the original table and it doesn’t create reference columns. If we didn’t copy the MVCC columns here too, it would mean losing the ability to validate afterwards. Does this make it a bit clearer?

**Comment by mrzzzrm** [comment]
Yeah, I get the idea, I guess... But why should a Projection happen before a Validate? (I thought the idea was that no Operator needs to know about MVCC, except for Validate (and the DML operators).) If there is no convincing reason, I think we should remove it (clean separation between concepts, that's a good thing!!) @mrks

**Comment by mrks** [comment]
In general, no other operator should have to deal with MVCC information, except for having to pass it through. Currently, the validation happens right after the GetTable. When we consider it to be just another filtering predicate, it makes sense to execute more selective predicates first. I am not sure if there is a reason to execute a projection first - if so, only to remove columns.

Right now, I don't see a big problem with enforcing that validation always happens before projections.

**Comment by mrzzzrm** [comment]
I smell removal - unless MVCC wizard @mjendruk convinces me otherwise. Even if TableScans supported being executed before Validate, they would need a different mechanism than `use_mvcc_columns_from()`

**Comment by mrks** [comment]
TableScans are not a problem, because ReferenceColumns point to the original table and Validate can get the MVCC vectors from there.

**Comment by mjendruk** [comment]
Remove it. I honestly don’t mind.
