### ISSUE TITLE
Release / Optimized build with symbols

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#645]
We should check if having symbols has any measurable performance impact. If yes, we should add a third build type "optimized", which is "release" with symbols. If not (which is my gut feeling), we should simply add symbols to our release build.

**Comment by mrzzzrm** [comment]
Cmake calls this RelWithDebInfo and and we can already use it, probably, by setting CMAKE_BUILD_TYPE to "RelWithDebInfo" on the command line

**Comment by mrks** [comment]
I think we have some special cases for the release builds (march=native, LTO) that would not be automatically used with `RelWithDebInfo`. At least, we should make sure that it is treated the same as release.
