### ISSUE TITLE
Benchmarks as part of CI

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#648]
As @mrzzzrm rightly said in #647, we need a solid way of verifying potential performance improvements. Similar to how the CI tells us how a PR changed the coverage, it should look at the performance. For now, this means TPC-H throughput.

Things to keep in mind:

- Benchmarks should run in isolation, preferably on an otherwise empty machine
- We should check both gcc and clang release performance

**Comment by mrks** [comment]
#2115 again showed how nice this would be :/

**Comment by Bouncner** [comment]
Closing this issue. Our CI pipeline grew fairly large and as well as our standard benchmark script `benchmark_all.sh`. Running this script properly (a.k.a. isolated on a dedicated, beefy machine) as part of the CI would be a major effort and an overkill for many PRs. At the same time, results of `benchmark_all.sh` in PRs are now common.
