### ISSUE TITLE
Remove SQLQueryOperator and SQLResultOperator

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#650]
I reckon the consensus is that they don't really fit into our understanding of what an Operator is and should go. As far as I recall the Query Caching somehow goes into the SQLPipeline and then these will be deleted?!  @mrks @lawben

**Comment by Bensk1** [comment]
Correct.

**Comment by lawben** [comment]
I'm working on caching in the SQLPipeline. PR possibly coming today. We needed the newest sql-parser version for this, which was still causing some problems. As soon as they are gone, the caching can begin. I will remove both operators in that PR.

**Comment by mrks** [comment]
duplicate of #304
