### ISSUE TITLE
Join on <float> = <int> does neither abort nor work

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#651]
```c++
  StorageManager::get().add_table("A", load_table("src/test/tables/float_int.tbl", 2));
  StorageManager::get().add_table("B", load_table("src/test/tables/float_int.tbl", 2));
  SQLPipeline("select * from A inner join B on A.a = B.b;").get_result_table();
```

This will fail, but just because the final Projection doesn't get any input data. The JoinHash will run through without aborting even though it can't compare float and int columns. Haven't tested on the other JoinOperators, but they should be investigated as well.

**Comment by Bouncner** [comment]
I distrust any join on non equally-typed columns if involves floats or strings.
Better assert and abort than adapt?

Or are there “good ways” to compare int to float?

**Comment by mrks** [comment]
Probably related to #649 

@Bouncner:

>          Values of the data types NUMERIC, DECIMAL, INTEGER, SMALLINT,
>          FLOAT, REAL, and DOUBLE PRECISION are numbers and are all mutually
>          comparable and mutually assignable. If an assignment would result
>          in a loss of the most significant digits, an exception condition
>          is raised. If least significant digits are lost, implementation-
>          defined rounding or truncating occurs with no exception condition
>          being raised. The rules for arithmetic are generally governed by
>          Subclause 6.12, "<numeric value expression>".

**Comment by TwoLaid** [comment]
`JoinHash` should definitely be able to join int and float columns. Will investigate.

**Comment by mrzzzrm** [comment]
According to PR description in #653 this is fixed
