### ISSUE TITLE
Remove the empty initial Chunk and make Table layout immutable

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#652]
This will also fix #649 

The Table's initial empty Chunk is an architectural confusion. Operators producing no output will have it in their output table and subsequent operators will fail because they assume the Chunk layout to be the same as the Table's - which it isn't. 
**Secondly** and closely related: The fact that you can add column definitions to a Table is another potential source of mistakes, because again Chunk and Table layout may start to differ. I want the Table's layout to be passed in in the constructor and then remain immutable.
**Thirdly** you can add Columns to Chunks after they have been added to a table. Again, you easily (and probably accidentally) reach an invalid Table-Chunk state.

**Table and Chunk layouts shouldn't be allowed to diverge.** 

Does this sound reasonable @mrks @Bensk1?

I propose the following:

```c++
const auto layout = HorizontalTableLayout{}; // Name to be discussed. Maybe just HorizontalLayout since it also goes into the Chunk?
layout.add_column_definition(DataType::Int, "a");
layout.add_column_definition(DataType::Float, "b");

auto table = std::make_shared<Table>(layout);

std::vector<std::shared_ptr<BaseColumn>> columns;
/** ...fill columns with data */

table->create_new_chunk(columns, [allocator, access_counter]);  // Calls Chunk::Chunk(_layout, /**mvcc*/ columns);

// Remove Table::add_column, Table::add_column_defintion, Chunk::add_column
```

**Comment by mrzzzrm** [comment]
ChunkUseMVCC should probably be Table-wide state as well since e.g. Validate assumes it to be _based on whether the first chunk uses MVCC_

**Comment by lawben** [comment]
I literally just stumbled over this 5 minutes ago. I think making this more 'logical' is a good thing. Not a fan of `HorizontalTableLayout`, but not sure what would be better, so no real complaint from my side.

**Comment by TwoLaid** [comment]
First of all, I approve of the notion that chunk and table layout shouldnt be allowed to diverge. And the weird initial empty chunk also seemed odd to me as well.

> I want the Table's layout to be passed in in the constructor and then remain immutable.

What would that mean for scenarios where we would like to add columns to a table during runtime? Think `ALTER TABLE ... ADD COLUMN ...`. We would have to make a new `Table` ?

**Comment by lawben** [comment]
I'm not sure we really need immutability. It would just be nice to have a clean interface for adding to a layout, e.g. here `layout->add_column()`. Then it's less confusing where to add what to which chunk/table.

**Comment by mrzzzrm** [comment]
Always forget about the ALTER TABLE thing - Yes, I believe creating a new Table and using the same columns as the original table is the good solution here. Putting the new table into the StorageManager needs to be made ready for concurrency in that context as well.

**Comment by mrzzzrm** [comment]
Just ran into this again - it's a bit frustrating, because upon some random operator crashing on Column access it takes some time to realise "ah, it's that empty table bug again". I'd really like to tackle this.

@mrks @Bensk1 any opinions on the proposal in the first post?

**Comment by mrzzzrm** [comment]
Looked into this some more. Refactoring the Table and Chunk code was trivial (Table API becomes pretty minimal, which is good) and now there are about ~100 places in the code base where we create Chunks or Tables that need to be refactored which of course would take a bit of time. 0.5-0.75/days, maybe? I'd do it.

**Comment by lawben** [comment]
Go for it :)

**Comment by mrks** [comment]
@mrzzzrm - I believe we discussed this in person. Could you remind me what we decided on?
