### ISSUE TITLE
ColumnStatistics generation is unnecessarily slow

### ISSUE THREAD

**Issue by adi64** [hyrise/hyrise#654]
Generating ColumnStatistics for e.g. a string column with a high number of unique values takes really long. Internally, it uses the `Aggregate` operator.

1. Profiling the `Aggregate` operator shows that a lot of time is spent in a map doing lexicographic compares of `std::vector<std::string>` which does not sound like a good idea.

2. `ColumnStatistics::distinct_count()` does not use `AggregateFunction::CountDistinct`, but no `AggregateFunction` at all, apparently causing the `Aggregate` implementation to fallback to a `DISTINCT` implementation, with counting the rows of the result table in the end. This takes more than 40 seconds on my machine when compared to a `SELECT COUNT(DISTINCT NAME) FROM CUSTOMER)` which takes only about 1 second when using the *hyriseConsole* (1 million rows). I tried adding the `AggregateFunction::CountDistinct` to the implementation, but apparently didn't get it right on first try.

**Comment by adi64** [comment]
@mrzzzrm

**Comment by Bouncner** [comment]
Just as a side note: the pruning group will store the distinct count per chunk as part of the `ChunkStatistics`. So at least for compacted chunks, we will have accurate counts more or less for free.
