### ISSUE TITLE
Test fail in NumaPlacementManager

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#660]
https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/optimizer-index-scan/10/pipeline/33

**Comment by mrks** [comment]
If we find issues in the CI builds, we should copy the text to gist.github.com. The CI build is lost now, so we have no idea what we're looking at. I don't remember seeing any NumaPlacementManager issues in the last weeks though.
