### ISSUE TITLE
AdaptiveRadixTreeIndex behaves differently from other CompositeGroupKeyIndex

### ISSUE THREAD

**Issue by Beta-Alf** [hyrise/hyrise#670]
For #667 we test the index join with multiple Index implementations. One test (OuterJoinWithNull) is failed with the AdaptiveRadixTreeIndex implementation. When stepping through the code we can confirm that the index returns a wrong range (returning NULLs also when asked for elements equal to 12345).

Repro: check out the join_index branch and enable the test OuterJoinWithNull. Run the test and it will fail. The Index is queried in _join_two_columns in join_index.cpp.

**Comment by Bensk1** [comment]
The indexes were implemented when NULL values where not supported at all in Hyrise.

**Comment by Bouncner** [comment]
So disable it as a return of getIndexes?
@bensk , can you estimate how much work the fix would be? We probably need to add NULL-tests to all indices as well. Does it make sense for your index group to have a look into this?

**Comment by mrzzzrm** [comment]
@mweisgut Have you seen this? If this is included on your current work on the indices, can you assign yourself? (trying to tidy up the issue list a bit)

**Comment by mweisgut** [comment]
> @mweisgut Have you seen this? If this is included on your current work on the indices, can you assign yourself? (trying to tidy up the issue list a bit)

I have only used GroupKeyIndex and BTreeIndex, so I have not seen it yet.
