### ISSUE TITLE
Multiple predicates for joins

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#679]
We won't get around implementing multiple predicates for the join. Ani's suggestion was to first evaluate the first predicate the way we do it now and if it matches, continue with others.

Ugly Pseudo Code for `SELECT * FROM t1 LEFT JOIN t2 on t1.a = t2.a AND t1.b = t2.b`:
```
JoinHash j(left, right, equals, {0,0}, JoinMode::Left);
j.add_predicate("something that expresses t1.b=t2.b")
```

**Comment by Bouncner** [comment]
Can you elaborate on "won't get around"?
From a performance perspective or are there other issues that cannot be solved at all with our current implementation?

**Comment by mrks** [comment]
The query above cannot be translated at the moment.

There is a workaround for TPC-H:

In some cases, we can extract the predicate into a predicate node:
"You can push down everything that IS in the null-supplying side."
"You can pull up everything that IS NOT in a null-supplying side (the preserve side)."
For TPC-H 13, we can push down `O_COMMENT not like '%%special%%requests%%'`.

**Comment by Bouncner** [comment]
Did you mean `t1.b = 3` in the example?

**Comment by mrks** [comment]
No, we can already handle that by pull-up/push-down. I meant `t1.b=t2.b`, but that was wrong in the pseudo code. Thanks!

**Comment by Bouncner** [comment]
Ok, got you.

I actually wonder what the status-quo in research is. Haven't read a paper focussing this issue recently. Might be a nice use case for jitting (tuple-by-tuple processing).

**Comment by mrks** [comment]
Someone we know said that performing the join on the first predicate and doing the other attributes as some type of lambda is a reasonable approach.

Since we can work around this for TPC-H 13, let's postpone it for now.

**Comment by Bouncner** [comment]
Why can we not use a simple scan on `t1_t2.b1=t1_t2.b2` after we performed the join on columns `a` (resulting in join table `t1_t2`)?

**Comment by mrks** [comment]
Because it will break with outer joins. I've tried it.

**Comment by Bouncner** [comment]
Do you have an example?

**Comment by mrks** [comment]
`SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a AND t1.b = t2.b` is not the same as `SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a WHERE t1.b = t2.b`

**Comment by Bouncner** [comment]
Yes, but that's something different, isn't it?
The second example is another query.

**Comment by mrks** [comment]
Sure it is a different query. That's my point - moving the predicate outside of the join makes it a different query.

Imagine two tables t1 and t2:
```
(debug)> SELECT * FROM t1
=== Columns
|       a|       b|
|     int|     int|
=== Chunk 0 ===
|   12345|       1|
|     123|       2|
|    1234|       3|
===
3 rows total (COMPILE: 27 µs, EXECUTE: 113 µs (wall time))
(debug)> SELECT * FROM t2
=== Columns
|       a|       b|
|     int|   float|
=== Chunk 0 ===
|   12345|   456.7|
|   12345|   457.7|
|     123|   458.7|
|      12|   350.7|
===
4 rows total (COMPILE: 24 µs, EXECUTE: 102 µs (wall time))
```

Now a single-predicate select looks like this:

```
(debug)> SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a
=== Columns
|       a|       b|       a|       b|
|     int|     int|     int|   float|
=== Chunk 0 ===
|    1234|       3|    NULL|    NULL|
=== Chunk 1 ===
|     123|       2|     123|   458.7|
=== Chunk 2 ===
|   12345|       1|   12345|   456.7|
|   12345|       1|   12345|   457.7|
===
4 rows total (COMPILE: 48 µs, EXECUTE: 4407 µs (wall time))
```

If I add `AND t1.b = t2.b` to the join predicate, the right side would be entirely NULL.
If I add it as another predicate outside of the join, the condition would always be false and all rows would be removed.

**Comment by Bouncner** [comment]
Ok, got you. That's nasty.
