### ISSUE TITLE
Discussion: How to make tuning decisions trackable?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#683]
We are starting to have multiple tuning components (NUMA, Index, ...). As these are heuristic and we don't really know what is happening, we should be able to track what they are doing.

Maybe we want to write that into a csv file, combined with timestamps. When we do timeline analyses, we could bring that log in and plot it in the graph.

**Comment by mrks** [comment]
@Bensk1 - with the Plugin infrastructure, I would say that every plugin is responsible for that. As it is unlikely that we will have a plethora of plugins running at the same time, printf could already be enough.

**Comment by Bensk1** [comment]
I agree, it should be the plugin's responsibility.
