### ISSUE TITLE
Discussion: How to bring non-standard syntax into the SQL-Parser

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#684]
When we look into things like partitioning, we need the SQL-Parser to support non-standard syntax. Because the parser is a stand-alone project that is actually used by others as well, I wouldn't want to make it Hyrise-specific. Any idea how to approach this?

**Comment by lawben** [comment]
(We encountered a similar problem in the networking effort, when we need to load tables into the DB externally.)
As the sql parser is used outside of Hyrise and we don't want a mix of different dialects or custom commands in it, the cleanest solution (maybe not the easiest one) would be to fork the parser and work of of that. We could integrate hyrise-specific features, like the SQL statement splitting, LOAD, or PARTITION and keep the original parser "clean". As the development in the original parser is not that much, I think the overhead of having to be in-sync with the upstream once in a while is worth the benefit.

**Comment by mrks** [comment]
In the optimal case, I would like to avoid any impact on the development process.

Do yacc/bison have some type of compile time flags so that we can do a "strict" and a "hyrise" build?

**Comment by mrzzzrm** [comment]
I'm all for compile time flags for non-standard extensions in the sql-parser and against a fork.

**Comment by mrzzzrm** [comment]
We could probably just use gcc (-E) to do the preprocessing

**Comment by mrzzzrm** [comment]
Looking for issues to close. 
Do we settle for trying to make them compile-time-enabled features of the upstream sql-parser?
@mrks

**Comment by mrks** [comment]
Yes, using the preprocessor seems to be an accepted method and I have not found anything better.

https://stackoverflow.com/a/13171385/2204581
