### ISSUE TITLE
Old SQL query now is invalid

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#687]
While looking into the sql_benchmark to delete the SQLQueryOperator, I found this query with the following parser error

```sql
SELECT customer.c_custkey, customer.c_name, COUNT(orderitems.orders.o_orderkey)
        FROM customer
        JOIN (SELECT * FROM
          orders
          JOIN lineitem ON o_orderkey = l_orderkey
        ) AS orderitems ON c_custkey = orders.o_custkey
        GROUP BY customer.c_custkey, customer.c_name
        HAVING COUNT(orderitems.orders.o_orderkey) >= 100;
```

error: 
```sql
SELECT customer.c_custkey, customer.c_name, COUNT(orderitems.orders.o_orderkey)
                                                                   ^=== ERROR HERE!
Error message: syntax error, unexpected '.', expecting ')' or ','
```

if I change that to: (the indirection via oders seems to be the problem)
```sql
SELECT customer.c_custkey, customer.c_name, COUNT(orderitems.o_orderkey)
```
then I get: `Right operand orders.o_custkey must be in exactly one of the input nodes`

It cannot be parsed/planned, so I assume this benchmark has not been executed in a while. Can any of you tell me why this now doesn't work any more (and should be fixed) or if we can just completely discard the benchmark?

**Comment by mrks** [comment]
As discussed in person, that query is wrong. Not sure where it comes from.

There is no such thing as "indirection" via table names. The only place where `orderitems.orders.o_orderkey` would be valid is when `orderitems` is a schema name. Currently, we don't support schemas.

It should be `orders.o_orderkey`.

**Comment by lawben** [comment]
This still results in the second error stated above, i.e. `Right operand orders.o_custkey must be in exactly one of the input nodes`

**Comment by mrks** [comment]
Did you fix the `HAVING` part as well?

**Comment by lawben** [comment]
Jup, The query looks like this now:

```sql
SELECT customer.c_custkey, customer.c_name, COUNT(orders.o_orderkey)
        FROM customer
        JOIN (SELECT * FROM
          orders
          JOIN lineitem ON o_orderkey = l_orderkey
        ) AS orderitems ON c_custkey = orders.o_custkey
        GROUP BY customer.c_custkey, customer.c_name
        HAVING COUNT(orders.o_orderkey) >= 100;
```

**Comment by mrks** [comment]
Aaaah. That is because the queries gives the subselect the alias `orderitems`. I have no %@*^( idea why it does that.

```
SELECT customer.c_custkey, customer.c_name, COUNT(orderitems.o_orderkey)
        FROM customer
        JOIN (SELECT * FROM
          orders
          JOIN lineitem ON o_orderkey = l_orderkey
        ) AS orderitems ON c_custkey = orderitems.o_custkey
        GROUP BY customer.c_custkey, customer.c_name
        HAVING COUNT(orderitems.o_orderkey) >= 100;
```

I also have no idea where that query comes from and what it is supposed to test. Maybe we should replace it with something that does the same, but without weird renamings.

**Comment by Bensk1** [comment]
Is it forbidden to assign aliases to subselects?

**Comment by mrks** [comment]
No, and looking at it again, I now understand what was intended.


Am 14. Februar 2018 17:28:22 schrieb Jan Koßmann <notifications@github.com>:
