### ISSUE TITLE
Add optimizer rules

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#692]
- [ ] UselessSortRemovalRule: If we find that a sort is useless (because the table's order will be changed by a following operator), we should either remove the sort or throw an error.

- [ ] ProjectionCombinationRule: Subsequent Projections should be combined.

**Comment by lanice** [comment]
[self-assign] Working on the ProjectionCombinationRule part of this issue.

**Comment by mrzzzrm** [comment]
@lanice you're not currently on this, right? I may or may not implement these if you aren't

**Comment by lanice** [comment]
That's correct, I'm not on this

**Comment by mrks** [comment]
Long-term issue maintained in Trello
