### ISSUE TITLE
Proper CPU-Cache Clearance Mechanism

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#700]
Currently, we do have a built-in method to clear the cache, but during some benchmarks we had the feeling that it did not work to the full extent. Compiler optimizations might be the reason.

We do have code for another mechanism based on the `clflush` instruction and could replace the old version by this mechanism after verification.

**Comment by mrks** [comment]
This is something that would be a walk in the park with #682 - we could say "Yo, hierarchical allocator, flush everything that belongs to this table". Wouldn't even have to touch the data structures for it.

**Comment by mrks** [comment]
In the past weeks / months, we focused on the TPC-H as the main benchmark. There, we do not (want to) clear the cache. Should we really spend time on this? Reopen if you disagree.
