### ISSUE TITLE
Compiling join_nested_loop.cpp is a pain

### ISSUE THREAD

**Issue by adi64** [hyrise/hyrise#702]
Compiling join_nested_loop.cpp just took over 10 minutes on my machine and consumed nearly 5 GB of RAM. Compiling it with GCC is even worse. It seems to be caused by excessive template instantiation - can this be limited or refactored?

![2018-02-16-143836_3200x1200_scrot_s](https://user-images.githubusercontent.com/5867277/36310407-336eedf0-1328-11e8-86b6-3ff80e14d00a.png)

**Comment by mjendruk** [comment]
I'm on it: #704
