### ISSUE TITLE
Do we need extended logging functionality?

### ISSUE THREAD

**Issue by AtiX** [hyrise/hyrise#714]
As we (+ @adi64 @lw0) have implemented a simple logging functionality for our purposes, we would like
to start the discussion whether/what extended logging functionality is desirable for hyrise.

Use cases / nice to have functionality not offered by `std::cout`:
- Have an additional LOG_DEBUG("...") for detailed information that is stripped out in release mode
- Log ceratin subsystems into a file to not clutter `std::cout` (e.g. a `tuning.log`)
- Disable all logging in tests
- Indicate severity level, module name, add timestamps to log lines

What we have implemented right now (open for discussion) are `LOG_INFO(...)` and `LOG_DEBUG(...)`
precompiler macros that wrap `std::cout`, with `LOG_DEBUG` being removed when built in release mode.
You can have a look at the code [here](https://github.com/hyrise/hyrise/pull/715/files#diff-80f0638990ab64f930bd1d3c71464251).

**Comment by mrzzzrm** [comment]
y not https://github.com/gabime/spdlog

also logging in a db context is easily confused with https://en.wikipedia.org/wiki/Transaction_log

**Comment by AtiX** [comment]
Just for completeness: boost also has logging functionality, although hyrise only seems to use the boost headers and not link the lib itself

**Comment by mrzzzrm** [comment]
I want https://github.com/fmtlib/fmt - like functionality in hyrise. If only for more information-rich Assert messages.

**Comment by adi64** [comment]
@mrzzzrm Good point. This was not about pushing our implementation at any cost. We just started off with cout-debugging, then realized that tuning information is actually very useful for the user -- albeit it does not happen in an interactive manner usually (as compared to, e.g. the `hyriseConsole`) -- and added the most basic functionality we needed. After a quick look, spdlog looks nice. I do not have strong opinions on formatting, but agree with you that providing more information in Asserts is a good thing.

**Comment by mrks** [comment]
Just a bunch of thoughts - I am still unsure on what I like:

Whatever we do, I think that the changes should be minimal - especially for code that does not use any of the new features.

As a negative example, consider Log4J. Even after months of working with Java, I still had to copy the bloody code needed to just write something to the console.

FMT looks interesting, but might be like cracking a nut with a sledgehammer.

I kind of like the macro idea, because it prevents arguments that are not printed from being evaluated.

Also, we should consider #683. Having a log system that puts this into a separate file is nice, but doesn't make it parseable.

**Comment by Bensk1** [comment]
Regarding the ability to parse tuning decisions: We might need a parseable file to automatically evaluate or visualize tuning decisions and also a human-friendly written log which could also be put into a file or simply printed to stdout.

**Comment by lw0** [comment]
I think we are beginning to talk about two separate things at once: A parseable tuning report seems not to fall into the category of logging, especially as it is not continuous but bounded by a single invocation of a tuning process. Perhaps we should move this part of the discussion to a separate issue #719?

**Comment by tobodner** [comment]
Tracing via macros is common/popular in commercial database systems. The dimensions time stamps, severity level, component/module name are all very useful and so is output to trace files (including file rotation to not fill up local disk space).

**Comment by mrks** [comment]
We brought this up in the Fortnightly a while ago and seemed to agree that a full logging component would be overkill. To be useful, we would have to add debug prints in various places and even then, it is unlikely that they will tell us what we need to know. In the end, everyone will use printf/gdb anyway.

Feel free to reopen if I am leaving anything out.
