### ISSUE TITLE
CI for mac

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#722]
To prevent things like #721

**Comment by mrks** [comment]
Maybe we could get the iMac in the Hyrise room to run tests in addition to simulating a fireplace?

**Comment by Bensk1** [comment]
Sure. There is a Jenkins runner software for macOS. But this old Mac will be terribly slow. I think we should get a Mac Pro.

**Comment by Bouncner** [comment]
If we build Hyrise on the fireplace Mac, it shows both the visual as well as thermal effects of an fireplace. Humongous!

**Comment by mrks** [comment]
A friend told me about Macstadium yesterday, where you can rent a Mac for these purposes. Apparently, there are other offers as well: http://stackoverflow.com/questions/7308039/ddg#8214011

**Comment by mrks** [comment]
<img width="877" alt="Screenshot 2019-04-24 at 12 12 22" src="https://user-images.githubusercontent.com/575106/56655195-665add00-6692-11e9-9e52-dfe865c0a499.png">
