### ISSUE TITLE
IndexColumnScan Refactoring

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#73]
The IndexColumnScan is more or less a copy of the table scan. The code duplication should be kept to a minimum. Furthermore, there is currently no possibility to take advantage of multi column indexes during scans.

Also, the current implementation cannot deal with NULLs.

**Comment by mrks** [comment]
@mjendruk and I discussed heterogeneous chunks offline.

I think we agreed on passing chunk lists to operators. For a table with chunks 1-5 where 1-3 are indexed, a predicate could be executed by an IndexScan (chunks 1-3) and a TableScan (chunks 4 and 5).

Additionally, it might make sense to have positive and negative lists. A positive list is described above. A negative list would mean that the TableScan is told NOT to scan chunks 1-3. The advantage is that nothing breaks if another chunk is added. That chunk would also be scanned by the TableScan. This enables reuse of query plans.

**Comment by Bensk1** [comment]
It seems we found a decision regarding the question whether optimizer or scan decides about using an index scan. Did you also talk about the multi column index part of the issue?

**Comment by mrks** [comment]
I think we did not. We should have.

@mjendruk - There are multicolumn indexes. A new IndexScan should be aware of those. We can discuss this in detail if needed.

**Comment by mjendruk** [comment]
Thanks for the info 👍 ^^

**Comment by Bensk1** [comment]
I believe the optimizer has to take the decision on using a multi column index scan. Otherwise every index scan needs to know about all other scanned columns.

**Comment by Bouncner** [comment]
Wow, that introduces predicate pathsnof different lenghts, doesn’t it?
If we have three predicates, several chunks have a multicol index for these three attrs, some have single col indices, and others don’t have an index at all. That sounds tough!
Can we deal with the fact that one indexscan operation can answer all three predicates in a single step while the others have to execute three steps?

**Comment by Bensk1** [comment]
You are right, that sounds tough. Maybe, we could introduce some placeholder NoOp nodes for columns of chunks that have been part of a multicolumn index scan to keep the plans interoperable.

**Comment by mrks** [comment]
Idea:
`IndexScan(Table, IndexID, vector<tuple<ColumnId, OpType, AllParameterVariant>>)`

**Comment by mjendruk** [comment]
I think this is done. The only thing left is to make the translator use the new index scan, but this is probably a new issue. Close?
