### ISSUE TITLE
Discussion: Revisit usage of visitor pattern in operators?

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#74]
The visitor pattern removes some boilerplate code in terms of e.g. switch statements, multiple if-else blocks, which is good. After working with the TableScan now for a while to fix #52, there were two issues with this that came up:
- Readability: While it does help, to not have a huge if-else block, the number of indirections in an operator is quit high. Reconstructing the flow/behaviour of an on_execute call of an operator is quite tidious. The major problem is the next one though:
- Changes: In order to fix #52, I need to change the parameters the ReferenceColumn passes on to its visitable in ReferenceColumn::visit_dereferenced. This is not possible without making an adjustment to ALL other operators who implement the ColumnVisitableContext constructor for use in ReferenceColumn::visit_dereferenced. I actually just want to change the TableScan operator, there should be no need to make any changes at all at other operators. This makes for really weird workarounds which should be avoided.

I'd like to open this up for discussion. Can we change our implementation of the pattern to improve this? Or would it be better to revert back to not using it at all?

**Comment by mrzzzrm** [comment]
I just had the unfortunate honour of fixing a bug in IsNullTableScan that a refactoring of mine triggered. It happened when IsNullTableScan was scanning a ReferenceColumn for NULL values. You know, NULL values in ReferenceColumns can be NULL_ROW_IDs in the PosList, or NULL values in the referencED table. 

There were nested calls to handle_column(), you had to track weird state in some context, AND of course there was the additional complexity of the Iterable/Iterator stuff - it was horrible. Thankfully it's mostly the table scans (and the ExportCSV) still relying on the visitor pattern. What do you think @mjendruk, can this be refactored into more readable code without performance loss?

**Comment by mjendruk** [comment]
I think it’s a bit better here: #707 although I don’t like the visitor pattern either. Let’s talk about this in person next week!
