### ISSUE TITLE
Some bugs / missing features in the IndexScan

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#740]
Chris and I tried to use this in the TPC-H and found the following

- [ ] The two operators should print their inclusion/exclusion lists (if set) in the visualization
- [ ] The index scan should be able to be recreated
- [ ] When recreating, both should keep their inclusion/exclusion lists
- [ ] When translating a between query, the TableScan part should have the exclusion list on the first operator (table_scan_gt), not the second one
- [ ] I believe we don't need UnionPositions (which is expensive) but could use UnionAll
- [ ] We cannot use an empty inclusion list to mean "everything" (see below)
- [ ] `IS (NOT) NULL` (was #551)

**Comment by Bouncner** [comment]
Whoever handles this issue, could you add a comment to be cautious with recreating inclusion lists? Espcially when @Bensk1 does some automatic tuning, this might cause some hard to find problems.

**Comment by mrks** [comment]
_We cannot use an empty inclusion list to mean "everything" (see below):_

If I create an empty table and add an index and submit a query, the optimizer might decide to use an IndexScan (right now it doesn't, but we shouldn't rely on that).  Because it is empty, the inclusion/exclusion list is empty. If rows get inserted before the operators execute, both the IndexScan and the TableScan would scan everything.

**Comment by Bensk1** [comment]
Check if the IndexScan can handle all types of indexes

**Comment by mrks** [comment]
superseded by #1790
