### ISSUE TITLE
TPC-H Benchmark Enhancements

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#741]
- [x] Make it show up in the Speed Center
- [x] With and without MVCC
- [x] With and without JIT
- [x] Allow for compression schemes
- [x] Allow for indexes
- [x] Don't be so shy about `--queries` (which doesn't show up in `--help`)
- [x] Optionally use prepared statements
- [x] Validate results with the table from TPC-H
- [ ] Implement the refresh method

**Comment by mrzzzrm** [comment]
> Validate results with the table from TPC-H

We do this in the tpch_test. 

> Implement the refresh method

that sounds like "nice-to-have" rather than something we'll work on in the foreseeable future?

> Allow for indexes

This, to me, seems like the only really actionable issue. Close this issue and open a new one specifically for index support in benchmarks?

@mrks

**Comment by mrks** [comment]
>> Validate results with the table from TPC-H

> We do this in the tpch_test.

This means the result tables provided in the TPC-H specification for SF 1.

>> Implement the refresh method

> that sounds like "nice-to-have" rather than something we'll work on in the foreseeable future?

We talked to outside people who complained about the lack of this and how we are "not really running the TPC-H". It won't happen in the next weeks, but should be done.

**Comment by mrks** [comment]
The only thing remaining is the refresh method. As we do not really plan to produce certified TPC-H scores and most research papers seem to omit it, the value of investing time of this seems limited.
