### ISSUE TITLE
Fix Operator::recreate for diamonds

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#742]
This looks nice, but is... inefficient:

<img width="1810" alt="screen shot 2018-02-27 at 16 04 57" src="https://user-images.githubusercontent.com/575106/36736098-ff747a8e-1bd7-11e8-8b94-e00dd452fed5.png">

 I would expect a diamond shape.
To avoid confusion: The screenshot says query 6 because it is zero-indexed.

**Comment by mrzzzrm** [comment]
corresponding LQP has the same layout?

**Comment by mrks** [comment]
<img width="1837" alt="screen shot 2018-02-27 at 16 26 47" src="https://user-images.githubusercontent.com/575106/36737305-08f74124-1bdb-11e8-981b-64093f2aa452.png">

**Comment by mrzzzrm** [comment]
Nope, LQP is just as broken, look at the double pointers in the lower part. It's just visualized "differently"

**Comment by mrzzzrm** [comment]
`LQPTranslator::translate_node` claims it is handling this case.

**Comment by mrzzzrm** [comment]
I'm a bit baffled because I'm using the same query for my experiments and the PQP is just fine:

```
[0] Sort
 \_[1] Sort
    \_[2] Sort
       \_[3] [Projection] Expression (Column)[ColumnID #0], Expression (Column)[ColumnID #1], Expression (Column)[ColumnID #2], Expression (Column)[ColumnID #3]
          \_[4] [Aggregate] GroupBy ColumnIDs: 0, 1, 2 Aggregates: SUM(Column #3) AS revenue
             \_[5] [Projection] Expression (Column)[ColumnID #41], Expression (Column)[ColumnID #45], Expression (Column)[ColumnID #17], Expression (Multiplication)
                \_[6] TableScan (Col #17 <= 1996-12-31)
                   \_[7] TableScan (Col #17 >= 1995-01-01)
                      \_[8] UnionPositions
                         \_[9] TableScan (Col #45 = IRAQ)
                         |  \_[10] TableScan (Col #41 = IRAN)
                         |     \_[11] TableScan (Col #35 = Col #44)
                         |        \_[12] TableScan (Col #3 = Col #40)
                         |           \_[13] TableScan (Col #32 = Col #24)
                         |              \_[14] TableScan (Col #23 = Col #7)
                         |                 \_[15] TableScan (Col #0 = Col #9)
                         |                    \_[16] Product
                         |                       \_[17] Product
                         |                       |  \_[18] Product
                         |                       |  |  \_[19] Product
                         |                       |  |  |  \_[20] Product
                         |                       |  |  |  |  \_[21] GetTable (supplier)
                         |                       |  |  |  |  \_[22] GetTable (lineitem)
                         |                       |  |  |  \_[23] GetTable (orders)
                         |                       |  |  \_[24] GetTable (customer)
                         |                       |  \_[25] GetTable (nation)
                         |                       \_[26] GetTable (nation)
                         \_[27] TableScan (Col #45 = IRAN)
                            \_[28] TableScan (Col #41 = IRAQ)
                               \_Recurring Node --> [11]
```

**Comment by mrks** [comment]
This is the commit that we were on:
https://github.com/hyrise/hyrise/commit/cae1809406f0d1ee4dbc02327a52451549b9ad60

We generated the visualization as part of the benchmark, not from the console.

Right now, I don't see any difference to the master that would explain this behavior.

**Comment by mrks** [comment]
Any chance that this has something to do with the query plans being recreated for the TPC-H execution?

**Comment by mrzzzrm** [comment]
Is this possibily due to Operator::recreate breaking diamond shapes? Because it does.

**Comment by mrzzzrm** [comment]
You just have to love data structure cloning. never gets you into trouble.

**Comment by mrzzzrm** [comment]
@mrks I could fix this quickly, or are you on it?
