### ISSUE TITLE
Projection doesn't work with all columns; materialize_values() for all columns?

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#745]
...only with ValueColumn, DeprecatedDictionaryColumn and ReferenceColumn. If none of these is encountered in `Projection::_evaluate_expression`, then Fail() is called.

Quickyhacky fix is this universal materialization, but we should probably have a virtual `materialize_values()` function for `BaseColumn` 
```
    pmr_concurrent_vector<std::optional<T>> materialized_values;
    materialized_values.reserve(table->get_chunk(chunk_id)->size());
    resolve_column_type<T>(*column, [&](auto& resolved_column) {
      const auto iterable = create_iterable_from_column<T>(resolved_column);
      iterable.for_each([&](const auto& value) {
        materialized_values.emplace_back(value.value());
      });
    });
    return materialized_values;
```

@mjendruk

**Comment by mrks** [comment]
To identify such problems in the future, does it make sense to run the tests with different default compressions?

**Comment by mrzzzrm** [comment]
All Operator Tests at least. That seems like quite some work, but should probably be done.

**Comment by mjendruk** [comment]
#695 I was faster :P
