### ISSUE TITLE
Retire Chunk::AccessCounter (and the Chunk allocator)

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#748]
Currently only TableScan und IndexScan claim to be NUMA-aware by forwarding the allocator and using `get_chunk_with_access_counting` but neither actually allocate the new columns on that node (just forwarding the allocator does nothing here, really). 
All other operators blindly ignore access counting and allocator fowarding. Because of this hyrise's codebase is confusing with regards to NUMA awareness and I vote to remove the AccessCounter and the allocator forwarding for now. That shouldn't be much of a change and would make TableScan, IndexScan, Table and Chunk interface clearer to read.

**Comment by mrks** [comment]
What would be missing to get the TableScan to respect the NUMA placement? Wouldn't we just have to allocate the PosList(s) for the result chunks on the correct node?

**Comment by mrzzzrm** [comment]
Yes, that should do it. I'd probably put a comment next to it explaining the prototypical state of the NUMA awareness. Same for the AccessCounter.

I'd rather remove both, but since you really seem to want to keep them I'd settle for fixing these two operators and proper doc as well.

**Comment by mjendruk** [comment]
I would probably make sense being able to tell any kind of operator which allocator to use or even better add a method that returns an allocator for node the operator is running on.

**Comment by mrks** [comment]
@lanice will likely use the counters. Fixing the allocator is #623, so I'm closing this one.
