### ISSUE TITLE
Get rid of concurrent_vector

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#749]
Yesterday @mjendruk and I discussed the possibility of abandoning dynamic row counts in Chunks and instead having a fixed number of maximum row, instead of `Chunk::MAX_SIZE`.

In operators the chunk size is known before the Chunk is created, it's just tests that rely on dynamic `append()`. 

Doing so would mean we could get rid of the concurrent vector usage, but would have to use some more memory for the tables in the StorageManager (to allow Insert).

**Comment by mjendruk** [comment]
It also so sloooooooow …

#### Benchmark using `std::vector`
![screen shot 2018-04-05 at 17 59 40](https://user-images.githubusercontent.com/2190123/38377499-5d84fc58-38fb-11e8-9de7-c5dc3160828d.png)

#### Benchmark using `tbb::concurrent_vector`
![screen shot 2018-04-05 at 18 00 01](https://user-images.githubusercontent.com/2190123/38377508-653c9974-38fb-11e8-9bf3-98b7f543b019.png)

![screen shot 2018-04-05 at 18 00 06](https://user-images.githubusercontent.com/2190123/38377550-79a0cb56-38fb-11e8-9e24-022570ae6a31.png)

**Comment by mrks** [comment]
I wrote a lot about this and then I lost it. :(

We should discuss this in the round table. I can see the advantages, but we have to see if they outweigh the additional memory usage. For an ERP with 10,000 tables, 20 columns on average, preallocating 100,000 rows would be ~75 GB.

Besides the performance gain, we can also get rid of the PMR issues that we have with TBB.

**Comment by mrks** [comment]
- We believe that the space overhead is negligible (max 32GB for a database with 10,000 string columns)
- Once we have TPC-C, compare it to `std::vector` and `uninitialized_vector`, then get rid of it.

**Comment by Bensk1** [comment]
Maybe, this could be helpful: http://www.vldb.org/pvldb/vol9/p768-schuhknecht.pdf

**Comment by mrzzzrm** [comment]
@mrks name.bin takes roughly 70s to load into ValueSegments and 18s to load into a DictionarySegment - even though the actual filesize doesn't differ much between the encodings. Getting rid of concurrent_vector could speed up loading binary tables by a factor of >3! (Similar numbers for other imdb tables)

**Comment by mrks** [comment]
We should also compare `std::vector` to `uninitialized_vector` when we work on this.

**Comment by mrks** [comment]
Get rid of `get_scoped_mvcc_data_lock` when we don't need to shrink the MVCC data anymore (see the comment referenced above this one).

**Comment by mrks** [comment]
Here's the impact of replacing the concurrent_vector with a regular one for MVCC data:

```
+----------------+----------------+------+----------------+------+------------+-----------------------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] |               p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+-----------------------------------------------+
| TPC-H 1        | 0.42155122757  | 5    | 0.420345366001 | 5    | -0%        | (run time too short) (not enough runs) 0.9204 |
| TPC-H 2        | 6.76054811478  | 68   | 6.99962997437  | 71   | +4%        |                   (run time too short) 0.0000 |
| TPC-H 3        | 6.29697704315  | 63   | 6.62154865265  | 67   | +5%        |                   (run time too short) 0.0000 |
| TPC-H 4        | 2.1995742321   | 22   | 2.32971143723  | 24   | +6%        |                   (run time too short) 0.0000 |
| TPC-H 5        | 3.89468789101  | 39   | 4.08242893219  | 41   | +5%        |                   (run time too short) 0.0000 |
| TPC-H 6        | 21.4303569794  | 215  | 23.3984298706  | 234  | +9%        |                   (run time too short) 0.0000 |
| TPC-H 7        | 1.44852221012  | 15   | 1.46031594276  | 15   | +1%        |                   (run time too short) 0.4561 |
| TPC-H 8        | 5.24962186813  | 53   | 5.61059427261  | 57   | +7%        |                   (run time too short) 0.0000 |
| TPC-H 9        | 1.40513062477  | 15   | 1.42427003384  | 15   | +1%        |                   (run time too short) 0.1633 |
| TPC-H 10       | 2.79722976685  | 28   | 2.83272242546  | 29   | +1%        |                   (run time too short) 0.0166 |
| TPC-H 11       | 22.526102066   | 226  | 24.2903671265  | 243  | +8%        |                   (run time too short) 0.0000 |
| TPC-H 12       | 7.12229681015  | 72   | 7.42777919769  | 75   | +4%        |                   (run time too short) 0.0000 |
| TPC-H 13       | 2.22776532173  | 23   | 2.27175450325  | 23   | +2%        |                   (run time too short) 0.0367 |
| TPC-H 14       | 21.0300235748  | 211  | 22.9658069611  | 230  | +9%        |                   (run time too short) 0.0000 |
| TPC-H 15       | 13.6221647263  | 137  | 15.0357103348  | 151  | +10%       |                   (run time too short) 0.0000 |
| TPC-H 16       | 6.74990177155  | 68   | 6.75028324127  | 68   | +0%        |                   (run time too short) 0.9865 |
| TPC-H 17       | 1.10464942455  | 12   | 1.20496022701  | 13   | +9%        |                   (run time too short) 0.0000 |
| TPC-H 18       | 1.4168368578   | 15   | 1.36271476746  | 14   | -4%        |                   (run time too short) 0.0714 |
| TPC-H 19       | 5.45627164841  | 55   | 5.49447011948  | 55   | +1%        |                   (run time too short) 0.0507 |
| TPC-H 20       | 1.89534187317  | 20   | 1.8179820776   | 19   | -4%        |                   (run time too short) 0.0076 |
| TPC-H 21       | 0.351791858673 | 4    | 0.360680609941 | 4    | +3%        | (run time too short) (not enough runs) 0.2560 |
| TPC-H 22       | 10.7620391846  | 108  | 11.3541145325  | 114  | +6%        |                   (run time too short) 0.0000 |
| geometric mean |                |      |                |      | +4%        |                                               |
+----------------+----------------+------+----------------+------+------------+-----------------------------------------------+
```

I started a branch where both can be used (concurrent for mutable chunks, regular for encoded chunks), which can be found at mrks/templated-mvcc. It comes with some template hacking to allow access to `begin_cids` and alike no matter what the used vector is. `hyriseBenchmarkTPCH` works, I didn't change the tests and will not pursue this further for now.

**Comment by Bouncner** [comment]
Haven't we concluded that it's fine to drop `tbb` altogether?

**Comment by mrks** [comment]
After benchmarking it with an OLTP workload, yes.

**Comment by mrks** [comment]
Yet another reason to get rid of it: https://software.intel.com/en-us/blogs/2009/04/09/delusion-of-tbbconcurrent_vectors-size-or-3-ways-to-traverse-in-parallel-correctly
