### ISSUE TITLE
Refactor Operator tests to work on all EncodingTypes

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#751]
As previously discussed this could get us some better coverage. #750 introduces a base class for tests that should work with all EncodingTypes `class EncodingTest´ The operator tests currently sit at 1s here, so we can probably afford running them 5 times.

**Comment by mjendruk** [comment]
Please be aware that starting with FOR encoding, there will be encoding schemes that do not support all data types.

**Comment by mrzzzrm** [comment]
#828 could have been detected earlier if we'd run e.g. the sqlite testrunner on all compression types.

**Comment by mrks** [comment]
Also, we should have one single list of all encoding types, so that we don't have to add encodings in too many places.

**Comment by mrks** [comment]
We already have enough tests covering the iterators. The join tests and the SQLite tests run on all encodings. I wouldn't know what to add, so maybe it's time to close this?
