### ISSUE TITLE
CI seems weird/broken/slow

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#752]
Not sure what exactly what is wrong with Jenkins, but this looks wrong. Somehow the new changes aren't being scheduled for quite some time...

![screen shot 2018-03-01 at 16 18 19](https://user-images.githubusercontent.com/7422656/36852588-5106cb64-1d6c-11e8-9ff5-63330a50da0e.png)

**Comment by mrks** [comment]
Not sure what you mean. We have two workers, so two builds are running at the same time.

**Comment by lawben** [comment]
It seemed odd that a PR update took more than one hour before the build even startet. I just had the feeling this used to be a lot quicker. But if this is all fine and expected behaviour, this issue can be closed.

**Comment by mrks** [comment]
Well, no - it’s not fine, because the CI should be not that slow. I just don’t know how to speed it up (#605 )
