### ISSUE TITLE
Detecting incorrect STL usage

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#755]
Just dumping this here, should be trivial to enable for CI

https://kristerw.blogspot.de/2018/03/detecting-incorrect-c-stl-usage.html

**Comment by mrks** [comment]
I like it. Is this something that we should put in CI or in the Makefile?

**Comment by mrzzzrm** [comment]
I'd make it an easy to use CMake option and put it into our debug CI builds.

**Comment by mrks** [comment]
Not going to happen because of libboost incompatibility.
