### ISSUE TITLE
Find better name for column and column

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#764]
My misunderstanding in #760 showed me (again) that calling both the column thingy in the table and the column thingy in the chunk "column" is confusing. We already had this discussion in another PR, but I can't remember which one it is.

We should find a different name for the *part of a column* that is stored in a chunk.

Also, considering that we might want to bring hybrid layouts back (e.g., two columns grouped together or an actual row-store chunk), "column" is not the best name. That data structure (e.g., a ValueColumn) could hold multiple columns in contiguous memory. Maybe something like "ValueStorage" and "DictionaryStorage" is better?

In any case, let's wait with the actual changes until the list of PRs is short and only a few people are working on the project.

**Comment by mrzzzrm** [comment]
You probably mean #760?

**Comment by mjendruk** [comment]
Or this one #697?

**Comment by mrks** [comment]
Max used "column segment", which I kinda like. Maybe a bit shorter "segment", e.g., ValueSegment and DictionarySegment?

**Comment by Bouncner** [comment]
I like segment.

**Comment by Bensk1** [comment]
I like segment as well. When looking for synonyms, I even think it’s my favorite. I associate other alternatives like section or slice more with something on chunk-level.

**Comment by mrks** [comment]
ok.

How about `chunk->mvcc_columns`. I think I would rather call it `chunk->mvcc_data` and leave "segment" for things that are actually part of a column.

**Comment by mrks** [comment]
Another question: `Chunk::column_count()` or `Chunk::segment_count()`?

**Comment by mrzzzrm** [comment]
column_count() - makes reading the code mentioning it more intuitive, imo.

**Comment by Bouncner** [comment]
Could also use `attribute_count` which completely leaves out the actual implementation.

**Comment by mrks** [comment]
Hmm, I don't think that we use attribute anywhere, and introducing a new term doesn't make things besser.
