### ISSUE TITLE
Sort uses ValueColumn<>::operator[]

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#768]
```c++
const auto value = (*column)[chunk_offset];
(*column_it)->append(value);
```
this results in perf warnings that confuse me and might actually be slower than necessary

**Comment by mrks** [comment]
@marcelja - That should be easy to fix once we have `BaseTypedColumn<T>`, right?

**Comment by marcelja** [comment]
yes 😄

**Comment by mrks** [comment]
Fixed a long time ago
