### ISSUE TITLE
Cache broken for subqueries

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#777]
Once #727 is merged, cached queries will be broken:

```
(debug)> load src/test/tables/int_int_int.tbl int_int_int
Loading src/test/tables/int_int_int.tbl into table "int_int_int" ...
(debug)> SELECT * FROM int_int_int WHERE a = (SELECT MAX(b) FROM int_int_int)
=== Columns
|       a|       b|       c|
|     int|     int|     int|
=== Chunk 0 ===
|      10|      10|      10|
===
1 rows total (COMPILE: 57 µs, EXECUTE: 284 µs (wall time))
(debug)> INSERT INTO int_int_int VALUES (11,11,11)
===
0 rows total (COMPILE: 178 µs, EXECUTE: 159 µs (wall time))
(debug)> SELECT * FROM int_int_int WHERE a = (SELECT MAX(b) FROM int_int_int)
=== Columns
|       a|       b|       c|
|     int|     int|     int|
=== Chunk 0 ===
|      10|      10|      10|
===
1 rows total (COMPILE: 57 µs, EXECUTE: 284 µs (wall time))
```
The PQPExpression that holds the subquery does not get re-executed.

Of course this should be tested.

I think it is easier if someone from our team who has dealt with recreation and the cache before looks at this. @lawben maybe?

**Comment by lawben** [comment]
I'll have a look at this tomorrow. As I'll be looking into subselects in the future anyway, maybe I can find a good solution. It seems like caching is causing a few edge cases now that we need to consider.

**Comment by lawben** [comment]
@mrks I think your example above is incorrect. you insert `(11,11,11)` at the beginning and so the first SELECT is already wrong in the example. I guess that is just a copy-paste error?

**Comment by mrks** [comment]
Yepp, I copied too much. Thanks.
