### ISSUE TITLE
Naming scheme for compile time concepts

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#778]
I’m still not satisfied how we name template variables and variables holding compile time objects at the moment.

First issue: Our enumerations have all names like `EncodingType` and `DataType`. In some other situations, these names would be also appropriate. 

Second issue: There is no naming scheme for variables holding compile time objects such as `hana::type`.

I suggest we do the following:

```c++
auto data_type = DataType{};
resolve_data_type(data_type, [&](auto data_type_c) {
  using DataT = typename decltype(data_type_c)::type;
});
```

- We add the suffix `_c` (for constant) to variable names of compile time objects (good because it makes the link between `data_type` and `data_type_c` clearer)
- We use the suffix `T` (for template / type); in order to make it consistent, this would also imply `ColumnT`, and `BaseColumnT` instead of `ColumnType` and `BaseColumnType`.

__Second idea__: We rename the enumerations. `EncodingType` could be `EncodingEnum` instead, and `DataType` could be `DataEnum`.

**Comment by mrks** [comment]
Could you clarify what you mean by „constant“ here? I don‘t have a full grasp on what ˋdata_type_cˋ actually is in your example. What is the difference to data_type here? Could we pass a constexpr into the lambda?

**Comment by mjendruk** [comment]
`data_type_c` can have type `hana::type<int32_t>`, `hana::type<int64_t>`, etc. This is its definition:
```c++
template <typename T>
struct type {
  using type = T;
};
```

In this case, it comes out of the `data_type_pairs` tuple consisting of tuples of `DataType` and `hana::type<>`. Other examples for such compile-time objects are `std::integral_constant<>` and `enum_constant<>`

**Comment by mrzzzrm** [comment]
I like data_type_c, ColumnT (for ValueColumn, DictionaryColumn) and DataT (for int32_t, float).

**Comment by mrzzzrm** [comment]
Max ist right that there currently is a possible confusing between enum names and template parameter names.

**Comment by mjendruk** [comment]
Another idea: since aliases get a t suffix, objects of type `hana::type` get one too, so `DataT` and `data_t`.

**Comment by mrks** [comment]
I never really ran into any ambiguity problems with this, so I wouldn't spend time on it. If someone disagrees, please reopen.
