### ISSUE TITLE
Add internal tests for networking

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#796]
Currently, there is an external integration test. The parts of the networking interface should be tested internally as well.

**Comment by lawben** [comment]
What exactly should the scope of these tests be? Similar to the script as an integration test, just with a C++ postgres client instead of a command line tool?

**Comment by mrks** [comment]
I am not quite sure to what degree we can mock the different steps. At the least, we should have an integration test that gets automatically executed as a part of our test suite and contributes to the coverage measure.
