### ISSUE TITLE
Dedicated DATE(TIME?) data type - anything but strings

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#803]
Currently we use strings to represent DATE, e.g., "2015-12-21". This works nicely for comparisons (even greater and less!), but doesn't allow for statistical estimations. Currently, when strings are involved, `Table/ColumnStatistics` assumes a selectivity of `1.0` leading to incorrect estimations/optimizations for TPCH queries involving dates.

Can we store Datetime as (signed?) seconds since epoch or something in `uint64_t` instead? http://en.cppreference.com/w/cpp/chrono/c could probably be used for conversions.

Would be useful for my MA, so I'd implement it, just need opinions for now.

**Comment by mrks** [comment]
I haven't spend a lot of time thinking about this yet. A class that internally holds an int would be my first thought. While you're at it, maybe think about how we do those time calculations. If we can translate `DATE_ADD(a, INTERVAL 1 MONTH)` to an addition of two of those objects, we could get by without a lot of changes. For now, a minimal version should be sufficient.

Also, please check with Keven. I know that he started to do something a while ago, but I don't know the status.

**Comment by mrks** [comment]
Long-term issue maintained in Trello now
