### ISSUE TITLE
How to get rid of temporary Tables?

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#806]
Currently we keep all temporary Tables when executing a query plan, leading to higher memory consumption than necessary - thus limiting the size of the Tables we can use for benchmarks.

There should be the option to free the memory, once all operators working on these tables have finished. This should be opt-in, as often you'll want temporary tables to stick around and be available for later visualization/debugging.

**Comment by mrks** [comment]
My first guess was to simply delete the input `shared_ptr`, so that when no one refers to the operator anymore, it gets deleted. Maybe there should be a (global?) setting „keep PQPs intact“ that is set when you‘re debugging?

**Comment by mrzzzrm** [comment]
Just resetting the shared_ptr would work in an ideal world, but in practice we need to Assert that the last operator working on an input actually makes the final ref-decrease and the input actually gets deleted. Otherwise I guarantee rogue code referencing operators will keep things from being free'd and we would never know.

Also I'm totally against global settings ;)

Currently I'm imagining each Operator having a counter of outputs which will be decreased once the succeeding operators finish. If it reaches zero, the Operator will Assert there is just one use_count() on its output table and then reset it. All of this only happens if the PQP is in "Delete temporary data"-mode which should be opt in.

**Comment by mrks** [comment]
For the most part, I agree.

I am not a fan of making this a property of the PQP, though. A PQP should only hold properties that are relevant to its execution, not obscure debugging features.

Also, I just realized that we have to reconsider this w.r.t. the printing of the PQP. If we reset the `shared_ptr<AbstractOperator>`, we can’t call `visualize` after a query any more. Maybe we should just clean the output table and store the number of rows in the already existing performance struct?
