### ISSUE TITLE
Gracelessly kill (benchmark) queries

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#808]
I'm running different query plans to evaluate join ordering. Some join orderings are so bad that they take orders of magnitudes more time and memory.
I want to timeout these queries, not after an operator, but while it is running. So probably expensive operators (hello Joins!) need to regularly check a flag and then quit, returning a nullptr output table.

What do you think?

**Comment by mrks** [comment]
Makes sense. We could use the transaction context for that. I think it makes semantically sense to abort a transaction if it takes too long.

Good thing about using the transactions is that following operators will not start.

Maybe that could also be part of the console. Ctrl-C for a running query aborts it.

**Comment by mrzzzrm** [comment]
Would you be okay with operators (e.g. TableScan each 1024 row, JoinHash after each phase, etc.) checking the `TransactionPhase::Aborted` state occasionally and returning nullptr from _on_execute()?

**Comment by mrzzzrm** [comment]
I think that would probably be 10-15 critical places across all operators that would have one liners checking the transaction context state.

**Comment by mrks** [comment]
That’s exactly what I was hinting at. I wouldn’t directly check the state in the operators though, instead I would add a `yield` method in the transaction (maybe not the best name, as scheduling is unaffected).

Doing this after 1024 rows seems excessive to me.

Also, remember that while scheduled operators will not be executed if their tx is aborted, scheduled `JobTask`s will. That is something that should be added to the operators that spawn tasks.

**Comment by mrzzzrm** [comment]
The problem is that sometimes its just that one or two JoinHashs/TableScans that are just taking too long, all other operators are fast. So you either abort somewhere within the operator or you still have to wait a long time until the query actually stops. 

When iterating a Chunk via `chunk_offset`, the check pattern could look like this `if ((chunk_offset & 0x3FF) == 0 && _is_kill_flag_set()) /* stop doing things in this operator */ `

`0x3FF` is just a randomly chosen number of LSB, could probably be way more. `_is_kill_flag_set()` will load an atomic, which you probably don't want to do for every single row for performance reasons.

**Comment by mrzzzrm** [comment]
What would `TransactionContext::yield()` do? Set the transaction state to Aborted, to a new state "Killed", or something entirely different?

**Comment by mrks** [comment]
Yes, you will have to check within the operators during different phases. For instance, after you have processed x rows in a scan or have probed y rows in a join. Those numbers should be chosen so that they are very roughly hit once a second - we don’t need the granularity that checking every 1000 rows would give us. In some cases, it might actually make more sense to do that on a chunk-level granularity. After every chunk, we could check if we should continue. That keeps the check (even if cheap) out of the main loop.

`yield` would relinquish control to a class (Tx? AbstractOperator?) that checks if the transaction is still alive. If it is, everything continues as normal. If not, it stops the current operator.

**Comment by mrzzzrm** [comment]
I've hacked this into JoinHash, Product and TableScan for my MA and it works fine so far. 

Clean integration will take a bit of refactoring since the interface of TransactionContext would need a few changes to not get inconsistent.

Spotted a few corpses while looking into it, I think TransactionContext has at least one race and there is unclear responsibility as to who should call, e.g. rollback(). (OperatorTask? Console? SQLPipeline?)

Also, the Console handles Ctrl+C via longjmp right now, which I'd consider pretty dangerous even though I can't prove it hurting us right now without looking deeper into it.

**Comment by mrzzzrm** [comment]
Ah, fuu. Alright, will doc that.

**Comment by mrks** [comment]
We should add tests that make sure that whenever a transaction is aborted, its operators are cancelled / not executed as well.

**Comment by mrzzzrm** [comment]
I have transaction aborting working quite nicely locally (I timeout plans if they take longer than the best plans). TableScan and JoinHash have checks like these (`if (_join_hash.aborted()) return nullptr;` or `if ((left.chunk_offset() & 0xFFF) == 0 && _table_scan.aborted()) return;`) sprinkled all over them. Is this a price we're willing to pay for getting responsive query aborts? Or is aborting after an operator has executed sufficient for the master?

**Comment by mrks** [comment]
I think we can and should bring that in

**Comment by mrks** [comment]
I wonder if we could use something like `pthread_cancel` and `pthread_setcancelstate` to stop running tasks. This will also become relevant when we want to add `LIMIT 1` support to the table scan, where potentially multiple segment scans are executed in parallel.

**Comment by mrzzzrm** [comment]
Closing this one, feel free to reopen
* I cannot remember a necessity for this coming up in the past months
* Hacking "abort-points" into operators is ugly and hard/ugly to test properly

**Comment by mrks** [comment]
Agreed.
