### ISSUE TITLE
CsvParser requires fields representing NULL to be empty

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#812]
Otherwise 

```c++
    Assert(boost::to_lower_copy(value) != ParseConfig::NULL_STRING,
           "Unquoted null found in CSV file. Either quote it for string literal \"null\" or leave field empty.");
```

fires at us. This makes importing the imdb (which uses "NULL" as the null value) impossible without pre-processing it. I guess many dbs would use "NULL" as their null value identifier, maybe we should just support it? At least make it an opt-in option for `CsvParser`?

**Comment by mrks** [comment]
Similar to `bool reject_quoted_nonstrings = true;`, we could have `bool reject_null_string = true;`.
