### ISSUE TITLE
Statistics concept

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#824]
In our roundtable discussion we figured out that there are quite a few aspects to talk/think about

**Comment by mrks** [comment]
Could you elaborate a bit? I see this issue becoming useless if we don't get around to work on it

**Comment by Bouncner** [comment]
I think I see two issues for the new weeks:
* terminology: when to use `statistics`, `aggregates`, `data statistics`; we should agree on them and clarify/align them in the code
* a meeting with all stake holders (e.g., Moritz and Tim) talking about the path we'd like to take with creating, storing, and updating "statistics"

We already started on the second item in the last roundtable, but I wouldn't consider it to be finally agreed. :)

**Comment by Bensk1** [comment]
Also, what kind of "statistics" we plan on implementing in the near future, e.g., histograms, sampling-based statistics etc. We could discuss this during or after the next fortnightly and then transform this issue into actionable items.

**Comment by mrks** [comment]
We know that we should improve the statistics, but I don't think that there is a big value in having a lot of issues that are not really actionable. Closing this for now.
