### ISSUE TITLE
Use integer compression in (Composite)GroupKey

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#827]
We should be able to use the vector compression for the two vectors stored in the group key. At index creation time, we know the maximum value, so compression should be possible. The `FixedSizeByteAligned` should be a safe bet for both `_index_offsets` and `_index_postings`. I am not sure about the SIMD BP128 one, because we don't do sequential accesses. We might save some space by trading off lookup speed.

**Comment by Bouncner** [comment]
Good idea.
From the tiny bits I remember about the group key, frame of reference might be a superb candidate for the sorted `_index_offsets` with a good performance/space trade-off for integers.

**Comment by mrks** [comment]
FOR is currently not a compression scheme but a column type. That shouldn't keep us from doing so, but we should discuss it first.

**Comment by mrks** [comment]
Long-term issue maintained in Trello
