### ISSUE TITLE
boost::bad_get when executing ChunkPruningRule

### ISSUE THREAD

**Issue by adi64** [hyrise/hyrise#828]
Reproduce e.g. in `hyriseConsole`:
```
(debug)> generate CUSTOMER;
Generating TPCC table: "CUSTOMER" ...
(debug)> select * from CUSTOMER where C_ZIP=953411111;
Error while translating query plan:
  Error while optimizing query plan:
  boost::bad_get: failed value get using boost::get
```
This does not happen with string or float values.

Call stack:
![image](https://user-images.githubusercontent.com/5867277/38669347-6e6d74f0-3e46-11e8-91f8-42c1f2ed3537.png)

**Comment by mrks** [comment]
`C_ZIP` is a string column. Right now, we don't support type conversions, so that is somewhat expected. This is more of an issue, because `C_SINCE` is an int column:

```
(debug)> SELECT * FROM CUSTOMER WHERE C_SINCE = 1523540183
Error while translating query plan:
  Error while optimizing query plan:
  boost::bad_get: failed value get using boost::get
```

**Comment by adi64** [comment]
Oh, I see. I tried to find a minimal example with an int column and didn't check too carefully.
