### ISSUE TITLE
Speed up LIKE scans

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#833]
The JoinOrderBenchmark I am using for my MT uses LIKE scans quite heavily, like, e.g., so:

```sql
SELECT t.title AS american_vhs_movie
FROM company_type AS ct,
     info_type AS it,
     movie_companies AS mc,
     movie_info AS mi,
     title AS t
WHERE ct.kind = 'production companies'
  AND mc.note LIKE '%(VHS)%'
  AND mc.note LIKE '%(USA)%'
  AND mc.note LIKE '%(1994)%'
  AND mi.info IN ('USA',
                  'America')
  AND t.production_year > 2010
  AND t.id = mi.movie_id
  AND t.id = mc.movie_id
  AND mc.movie_id = mi.movie_id
  AND ct.id = mc.company_type_id
  AND it.id = mi.info_type_id;
```

when this happens on a big table, the runtime cost for LIKE scans often come on par with the Join costs of a query, and I am worried that they will obfuscate my results to some degree.
Currently we implement LIKE using regex which I expect to be slower than necessary, given LIKE only has the most basic wildcards.
Is anyone aware of any simple to implement (like, a day) research for LIKE predicates? @mrks @Bensk1 @mrks

**Comment by mrks** [comment]
As discussed in person: Please check if the wildcards `%` and `_` are only in prefix or suffix and use `substr`. Theoretically, we could do some more optimizations for prefixes on dictionary columns, but maybe this is already good enough

**Comment by mrzzzrm** [comment]
Alright will do this, justification attached :dagger: 
![job-1a-costmodellinear-release_0_20664666](https://user-images.githubusercontent.com/2679018/38825486-0b329824-41ad-11e8-9bde-491cf90af65f.png)

**Comment by mrks** [comment]
Please also have a look at the impact of icase. In any case, that should be handled consistently. Unless SQL mentions something, case sensitive is fine for me

**Comment by mrzzzrm** [comment]
Good point, thats already a lot faster. I'll attempt a faster non-regex implementation anyway.
![job-1a-costmodellinear-release_0_6516599](https://user-images.githubusercontent.com/2679018/38828750-4e8518a4-41b7-11e8-8e6e-bc2aa8e3339b.png)
