### ISSUE TITLE
Bug in JoinMPSM

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#837]
There is some discussion on the closed quick-fix PR #829 

Master CI is failing because of this.

The Join Tests fail for me locally as well now. Do we disable/revert the JoinMPSM until it is fixed?
@Beta-Alf  (for some reason I can't assign you)

**Comment by Bouncner** [comment]
@Beta-Alf : do you have any news for us here?

**Comment by lanice** [comment]
Closing with #969 being merged.
