### ISSUE TITLE
General Purpose SQL Benchmark

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#839]
A binary to facilitate running any benchmark based on some Table files (.csv/.tbl) and some queries (.sql). An example could be the JoinOrderBenchmark: https://github.com/gregrahn/join-order-benchmark

### Possible Options
* Load benchmark description from file describing table files and queries
* Offer encoding scheme
* Save query results into files
* Output benchmark resuls in google-benchmark like json (see TpchBenchmark)
* Run each query once; multiple times or until timeout. In order or shuffled.
* Cache tables as binary files to speed up loading them. One binary per table/encoding scheme
* Cache statistics as files (after #822 is merged)
* Create visualizations of query plans.
* ...

The current `TpchBenchmark` provides some of these features already and code duplication should be avoided

**Comment by mrks** [comment]
@Bouncner - Do you think we could also use this to run *that* workload?

**Comment by Bouncner** [comment]
Should be doable. But lots of questions to discuss upfront (generated insert workload, including views?, upserts, ...).

**Comment by lawben** [comment]
as I am currently without task, I could look into this. any objections? 

if I understand correctly, this is supposed to be used somewhat like this:
```bash
./benchmark --tables=/path/to/tables --queries=/path/to/queries --visualize --store-results=false --...
```

**Comment by mrks** [comment]
Sounds good!
