### ISSUE TITLE
[CLion Console] Error during SELECT on table (found via console, MacOS)

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#842]
When trying to retrieve values from tables via the CLion console the programme exits with `Error opening terminal: unknown`.

SELECT with only an aggregate works.

Console output on current master on current MacOS with CLion console:
> Hyrise is running a (debug) build.
> (debug)\> load src/test/tables/tpch/sf-0.001/nation.tbl nation
> Loading src/test/tables/tpch/sf-0.001/nation.tbl into table "nation" ...
> (debug)\> SELECT COUNT(\*) FROM nation;
> \=\=\= Columns
> \|COUNT(\*)\|
> \|    long\|
> \=\=\= Chunk 0 \=\=\= 
> \|      25\|
> \=\=\=
> 1 rows total (COMPILE: 506 µs, EXECUTE: 353 µs (wall time))
> (debug)\> SELECT \* FROM nation;
> Error opening terminal: unknown.
> Process finished with exit code 1

I discovered it on MacOS with CLion console via Hyrise console but I am not sure whether it is console related.

**Comment by mrks** [comment]
This looks like an issue with the pagination (i.e., ncurses). When you say that it worked before, did you use the same setup? [Are you in a docker container](https://andykdocs.de/development/Docker/Fixing+the+Docker+TERM+variable+issue)?

In any case, this should be caught and replaced with a better error message.

**Comment by FabianWiebe** [comment]
Error only occurs when using the CLion console. It works with the normal MacOS console.

**Comment by mrks** [comment]
https://youtrack.jetbrains.com/issue/CPP-822

Disable pagination within clion?

**Comment by FabianWiebe** [comment]
I am not sure how to disable pagination in clion. This answer https://github.com/alfajango/jquery-dynatable/issues/90#issuecomment-102023603 describes how to turn it off but not where in clion.

**Comment by mrks** [comment]
maybe check if the `TERM` environment variable is properly set

**Comment by FabianWiebe** [comment]
Setting environment variable `TERM` to `xterm-256color` solved the issue. Issue can be closed, except the original error message should be improved.
