### ISSUE TITLE
SortMergeJoin segfaults when executed with active scheduler

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#845]
When the SortMergeJoin gets executed with an active NodeQueueScheduler it segfaults.

From my initial debugging attempt it looks like it crashes in line 225 of the [radix_cluster_sort.hpp](https://github.com/hyrise/hyrise/blob/b17ac9db6370d09033a13c336c3d04c02b457150/src/lib/operators/join_sort_merge/radix_cluster_sort.hpp#L225):
```
    // Move each entry into its appropriate cluster in parallel
    std::vector<std::shared_ptr<AbstractTask>> cluster_jobs;
    for (size_t chunk_number = 0; chunk_number < input_chunks->size(); ++chunk_number) {
      auto job =
          std::make_shared<JobTask>([chunk_number, &output_table, &input_chunks, &table_information, &clusterer] {
            auto& chunk_information = table_information.chunk_information[chunk_number];
            for (auto& entry : *(*input_chunks)[chunk_number]) {
              auto cluster_id = clusterer(entry.value);
              auto& output_cluster = *(*output_table)[cluster_id];
              auto& insert_position = chunk_information.insert_position[cluster_id];
line 225      output_cluster[insert_position] = entry;
              ++insert_position;
            }
          });
      cluster_jobs.push_back(job);
      job->schedule();
    }

    CurrentScheduler::wait_for_tasks(cluster_jobs);
```
I have uploaded a minimal example in the playground in [this branch](https://github.com/hyrise/hyrise/tree/leander/sortmergejoin_segfault).

@ArneMayer do you have any idea, you implemented this a while ago right?

**Comment by ArneMayer** [comment]
Maybe the output clusters are not pre-sized appropriately.
