### ISSUE TITLE
Add column encoding option for benchmarks

### ISSUE THREAD

**Issue by adi64** [hyrise/hyrise#861]
Operator implementations are often created with compressed chunks in mind. However, `hyriseBenchmarkTPCH` for example creates test tables without chunk encoding. Since these tables are generated at program startup, it would be nice to have an option like **`--encoding`** taking an `EncodingType` enum as argument, defaulting to `Unencoded` or whatever. Thoughts?

**Comment by mrks** [comment]
A very good idea. @lawben? Could you add that to the TPC-H benchmarks as well as #839?

**Comment by mrks** [comment]
Or does it make more sense to have this in some kind of configuration file where we can set the compression method per column? @Bouncner @Bensk1

**Comment by mrzzzrm** [comment]
Encoding wasn't left out of the TPCH benchmark for any particular reason and can be added easily, if @lawben doesn't add it as part of #839. Need it yesterday @adi64?

**Comment by Bensk1** [comment]
Having something like `--encoding` would be really useful. Setting the compression method per column might be handy in the future for experiments.

**Comment by adi64** [comment]
We realized this a bit late and probably won't be able to get this done *and* have fresh benchmarks until 4pm today :wink: So no time pressure.

**Comment by lawben** [comment]
I can add this, no problem. But not within the next 50 minutes, sorry @adi64 ;)

**Comment by Bouncner** [comment]
Concerning the compression-per-column: that would definitely be very useful. Maybe something simple like setting a default and then list columns that depart from the default?

```
[
  {
    default_encoding: 'Dict',
    departures: 
    {
      'ITEMS.DATE': 'RLE',
      'ITEMS.CUST_ID': 'SIMDPD128'
    }
  }
]```

**Comment by adi64** [comment]
Since #876 (General Purpose Benchmark Runner) is merged, we now do have an option to encode all columns with the same style. For me, this is enough for now. @Bensk1 @Bouncner -- keep this open for future support of per-column encoding? Otherwise, I'd close this.

**Comment by lawben** [comment]
I'm working on per column encoding. PR should be there next week. Keep this open until that PR is merged.
