### ISSUE TITLE
Statistics: Negative Row Count when joining columns without an overlapping range

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#865]
Just noticed this, issue lest I forget.

**Comment by mrks** [comment]
Uuuuh @lanice @timzimmermann - we can use that for DLP! If the system is triggered, we return antirows that cancel out the rows that were already exposed!

**Comment by timzimmermann** [comment]
@mrks I don't think I follow.

**Comment by Bouncner** [comment]
@timzimmermann Actually, I think you do.

**Comment by timzimmermann** [comment]
🙈
