### ISSUE TITLE
<boost/asio/detail/memory.hpp> not found

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#871]
On pella I'm getting the following error during compilation:
```
In file included from /home/Leander.Neiss/hyrise/src/lib/server/use_boost_future.hpp:64:0,
                 from /home/Leander.Neiss/hyrise/src/lib/server/task_runner.hpp:11,
                 from /home/Leander.Neiss/hyrise/src/lib/server/server_session.hpp:12,
                 from /home/Leander.Neiss/hyrise/src/lib/server/server_session.cpp:1:
/home/Leander.Neiss/hyrise/src/lib/server/use_boost_future_impl.hpp:5:10: fatal error: boost/asio/detail/memory.hpp: No such file or directory
 #include <boost/asio/detail/memory.hpp>
```
Boost version on Pella is 1.58, the required version for Hyrise is 1.65 now IIRC?
There is no newer Boost version in the package sources of Pella either, since it runs Ubuntu 16 still.

**Comment by mrzzzrm** [comment]
Dependencies say >= 1.65.0

My local Ubuntu 17.10 installation doesn't build the master anymore, I thought this was still intended to work, reading this: https://github.com/hyrise/hyrise/pull/862#issuecomment-386228164

Personally, I'll start upgrading my machines to 18.04, I guess... :cry:

**Comment by mrks** [comment]
Hmm, I thought I built it successfully. oO

Should we do a dist-upgrade on pella?

**Comment by lanice** [comment]
I am not against an upgrade on pella (hoping that it goes smoothly :sweat_smile: ), if others have no problem with it..

**Comment by lanice** [comment]
Anyone against dist-upgrading pella, or good to go?

**Comment by mrks** [comment]
I just spoke to Admin-Matthias. Because there are some nastities in the setup of that machine, he would rather do a fresh install. I will send a mail to everyone involved.

**Comment by mrzzzrm** [comment]
I have a call tomorrow at 2pm, and would like to run experiments until then, can we hold that upgrade back until then?

**Comment by mrks** [comment]
See mail - we are waiting until tomorrow evening anyway

**Comment by mrks** [comment]
That depends on Matthias. Probably tomorrow.

**Comment by mrzzzrm** [comment]
Pella is updated. Closing.
