### ISSUE TITLE
Test tables loaded with load_table() can not be compresed with FrameOfReference encoding

### ISSUE THREAD

**Issue by nilsthamm** [hyrise/hyrise#875]
Loading a test table with an integer column and trying to compress it causes the BaseColumnEncoder to throw the exception `Passed data type not supported by encoding.` if the encoding type is 'FrameOfReference'.

(~~It works with float columns~~)

**Comment by mrks** [comment]
But... it should not work with float columns...

**Comment by nilsthamm** [comment]
My fault. Don't know what I tested but it was not on float columns, couldn't produce it again...
So this behavior is intended?
Is there a reason why we don't want loaded tables to be compressed?
I think it would be very helpful to have a consistent test structure regarding the test tables.

**Comment by mrks** [comment]
This is probably part of the bigger question on how we can run tests with all available encodings. Right now, I don't have an answer for that.

**Comment by nilsthamm** [comment]
With #877 I replaced all float columns with integer columns so that the tests can run with all encodings and no tests need to be skipped

**Comment by mrks** [comment]
Ignoring floats for our tests is not a solution...

**Comment by mrks** [comment]
Ah, ok - the replacement was only for those two tests. Nevermind. We still should look into testing all compression schemes.
