### ISSUE TITLE
LLVMgold not available on pella, configuration fails

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#881]
pella has cmake 3.10, thus the build script tries to enable LTO in Release builds - but the check for this fails as LLVMgold is not installed. Should LLVMgold be in the install script?

**Comment by mrks** [comment]
Yes - could you check what steps are necessary for that? Maybe this helps:
https://github.com/Project-OSRM/osrm-backend/issues/2120

**Comment by mrks** [comment]
on it
