### ISSUE TITLE
Extend hyriseConsole output to distinguish between parse and optimize

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#885]
As we have seen yesterday during the fortnightly, the current console output is not sufficient for cases where the sole optimization time is of high interest. Hence, it would be nice to distinguish between parsing and optimization times.

**Comment by Bouncner** [comment]
Done through #886 .

**Comment by mrks** [comment]
@Bouncner - You can write 'closes #885' in the PR so that the issue is closed together with the PR, not earlier
