### ISSUE TITLE
Third party included in code coverage / fix coverage link

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#902]
It seems like the third party libs are included in the coverage of our code base. PR #893 apparently decreased by 1.4%. If you look at the [diff](https://ares.epic.hpi.uni-potsdam.de/jenkins/job/Hyrise/job/hyrise/job/lawben%252Fjson_benchmark/8//artifact/coverage_diff.html), it looks like most of this is caused by `third_party/json/json.hpp`. 

I assume this is not expected behaviour?

**Comment by mrks** [comment]
This should be excluded - see coverage.sh (`--exclude='.*/(?:third_party|src/test|src/benchmark).*'`). No idea why it's not.

**Comment by mrks** [comment]
(on it)

**Comment by mrks** [comment]
@Bensk1 Any chance that the Jenkins updates have broken the coverage reports? If you look at the two commits from yesterday, one has the coverage report and the other has not.

**Comment by mrks** [comment]
@lawben Does the change in mrks/fixcov help?

**Comment by lawben** [comment]
I've added it to the PR. We'll see in about 15 minutes if it worked :)

**Comment by Bensk1** [comment]
That might actually be the case, but all updates went through smoothly. I will have a quick look at it.

**Comment by lawben** [comment]
No change.. still showing json.hpp at -30%

**Comment by Bensk1** [comment]
@lawben: When I look at the [coverage report](https://ares.epic.hpi.uni-potsdam.de/jenkins/job/Hyrise/job/hyrise/job/lawben%252Fjson_benchmark/5//artifact/coverage_diff.html) report of this [commit](https://github.com/hyrise/hyrise/pull/893/commits/d45299472fe5b76e461150b48f99d904f4b98d05) that is two weeks old, I do not see any coverage in json.hpp, but I do [see](https://ares.epic.hpi.uni-potsdam.de/jenkins/job/Hyrise/job/hyrise/job/lawben%252Fjson_benchmark/7//artifact/coverage_diff.html) it in that [commit's](https://github.com/hyrise/hyrise/pull/893/commits/fc0e3f64fbfc27faa9d8dcefd1c7a9126bf8bc87) report, which is also two weeks old.

**Comment by lawben** [comment]
Is the second commit the first one that included the coverage of json.hpp? Then the fault is probably somewhere else. I don't see how that commit could introduce any coverage or json related change.

**Comment by Bensk1** [comment]
Yes, it apparently is. I don't see that either.

**Comment by mrks** [comment]
Ok, so the exclusions only apply to gcovr, which is responsible for the overall coverage report. pycobertura, which does the diff, does not have an exclude option.

Meaning that the percentage change comes from somewhere else. Are you on the current master?

**Comment by lawben** [comment]
The PR has been open for 2 weeks, so there are probably quite a few changes. I can merge the current master into the PR and see if this helps.

**Comment by Bensk1** [comment]
I believe it was PR #862

**Comment by lawben** [comment]
It still contains json.hpp. Interestingly, a newer branch I'm working on (builds on top of the JSON benchmark one, so it's not a PR yet) [doesn't have the json.hpp in the diff](https://ares.epic.hpi.uni-potsdam.de/jenkins/job/Hyrise/job/hyrise/job/lawben%252Fencoding_config/8/artifact/coverage_diff.html), but other third_party files. But I guess they are both diff'ing against the same master - so why is it different?

**Comment by mrks** [comment]
The diff is somewhat weird.

**Comment by Bensk1** [comment]
Also, the exclusion does not even work for the coverage report. It also shows third party libraries.
