### ISSUE TITLE
Auto-kill Jenkins jobs if newer commit is available

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#903]
TravisCI offers an options to stop jobs if a newer version is available, as the currently running jobs is now useless. As a general question: Do we want something similar to reduce the load and/or potential backlog of jobs or do we want a history of failing/non-failing commits to a branch.

I just encountered this myself and manually killed the running jobs to speed up the next one.

If we want this, does Jenkins even offer this as on option. I guess there's a plugin for it .

![screen shot 2018-06-14 at 11 35 19](https://user-images.githubusercontent.com/7422656/41404285-1804d24a-6fc7-11e8-974d-8db71b66e40d.png)

**Comment by mrks** [comment]
I looked at this a while ago and found no good way of doing this. :/

**Comment by lawben** [comment]
As I can't change the settings of this repository, maybe [gharcombe-minson's answer](https://github.com/jenkinsci/ghprb-plugin/issues/379) could work. Not sure if this is possible in our case though. But it seems like a quick check.

**Comment by mrks** [comment]
We don't use the *GitHub Pull Request Builder Plugin* but the *Pipeline Multibranch Plugin*. I am a bit afraid to touch that, because tbh, I don't quite know why it works right now :D

**Comment by lawben** [comment]
Well then it'll just stay as is. Luckily it's not a major inconvenience.
