### ISSUE TITLE
JitFilter is a confusing name

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#907]
`JitFilter` is a confusing name because we have other filters like `RangeFilter` and `MinMaxFilter` and soon Arne's Counting Quotient Filter. All of these are data structures used for access avoidance. The JitFilter is the jit version of a column or table scan. Should we change the name?

**Comment by mrks** [comment]
+1

Not sure why it's not `JitTableScan`.

**Comment by Bouncner** [comment]
Might this use indices at one point? If so, maybe `JitPredicate` might be even better. If not, never mind.

**Comment by FabianWiebe** [comment]
The operator is mainly a jittable `TableScan` operator with the difference that no expression is evaluated but a result value of an already evaluated expression is checked.
@Bensk1 I think that if indices are used by JIT, `JitExpression` will use them. `JitExpression` is executed by the JIT operator `JitCompute`. 
So I would rename `JitFilter` to `JitTableScan`.

**Comment by mrks** [comment]
Mmmh, maybe that explains what is scanned? `TableScan` scans an entire table, `IndexScan` scans an index, so this could be a `JitTupleScan`?

**Comment by Bensk1** [comment]
Does it really scan a full tuple?

Talking about that, we would actually have to call it ColumnScan instead of TableScan?

**Comment by FabianWiebe** [comment]
The scan operator scans all tuples of a table.
All jittable operators use tuple-based processing. So one could also add the tuple prefix to all jittable operators’ names.

**Comment by mrks** [comment]
Given that a "full table scan" is an established phrase from row-storage days and there is no confusion even if it only scans a column today, I don't see any dangerous ambiguity here. What would scanning a tuple even mean?

**Comment by FabianWiebe** [comment]
@Bensk1 Yes, the jit Scan Operator only scans one value of each tuple.

**Comment by Bouncner** [comment]
To me that does not sounds like a scan. Scanning sounds like a sequential operation.

**Comment by Bouncner** [comment]
You mean with in the JIT context?
In general, now that you bring it up I'd prefer `IndexSearch` over `IndexScan`, but good old System R uses `index scan` as well.

**Comment by Bensk1** [comment]
We might be able to speed up that discussion and reduce the pain by discussing the issue in person?
