### ISSUE TITLE
Profile / improve template instantiation with templight

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#915]
[Templight](https://github.com/mikael-s-persson/templight) looks quite cool, especially together with [templight-tools](https://github.com/mikael-s-persson/templight-tools). It can generate things like this (click me):

![](https://raw.githubusercontent.com/mikael-s-persson/templight-tools/master/images/fibonacci.o.trace.gv.png)

I think that this might be helpful in reducing the compile time for our heavy weights (`JoinIndex`, `JoinNestedLoop`, ...). Unfortunately, I could not build it on my llvm checkout:

```
/Users/markus/tmp/llvm/tools/clang/tools/templight/templight_driver.cpp:489:44: error: no member named 'GetArgumentVector' in 'llvm::sys::Process'
  std::error_code EC = llvm::sys::Process::GetArgumentVector(
                       ~~~~~~~~~~~~~~~~~~~~^
```

The problem [is known](https://github.com/mikael-s-persson/templight/issues/65), but even the official llvm/clang version does not work for me:

```
[:~/tmp/llvm] trunk ‡ cat tools/clang/tools/templight/templight_clang_version.txt
'templight_clang_patch*.diff' was created using the following LLVM/Clang versions:

LLVM git: 7256bf169ac3709b3c3ad5c6d541cf809ec341fb
LLVM svn: https://llvm.org/svn/llvm-project/llvm/trunk@330373
Clang git: c33e1469f018cf71327e06df054a0ffc87f4d9f8
Clang svn: https://llvm.org/svn/llvm-project/cfe/trunk@330382
[:~/tmp/llvm] trunk ‡ svn info --show-item revision
330373
[:~/tmp/llvm] trunk ‡ cd tools/clang
/Users/markus/tmp/llvm/tools/clang
[:~/tmp/llvm/tools/clang] trunk(1) ‡ svn info --show-item revision
330382
```

**Comment by mrks** [comment]
No, I didn't look into it again yet. My guess is that taking an older version of clang and templight should be the easiest approach. Maybe templight's 11ae4fcff6a208b484ecc554c7aae67ab86b9a10, the commit before the clang version was updated.

If you try it, it would be great to hear if it worked.

**Comment by 0xd34df00d** [comment]
Nope, I haven't tried that, but this patch (basically applying the aforementioned review contents) works for me:

```
diff --git a/templight_driver.cpp b/templight_driver.cpp
index 1731687..47ffd19 100644
--- a/templight_driver.cpp
+++ b/templight_driver.cpp
@@ -485,13 +485,8 @@ int main(int argc_, const char **argv_) {
     return 1;
 
   SmallVector<const char *, 256> argv;
-  llvm::SpecificBumpPtrAllocator<char> ArgAllocator;
-  std::error_code EC = llvm::sys::Process::GetArgumentVector(
-      argv, llvm::makeArrayRef(argv_, argc_), ArgAllocator);
-  if (EC) {
-    llvm::errs() << "error: couldn't get arguments: " << EC.message() << '\n';
-    return 1;
-  }
+  const auto ArgsIn = llvm::makeArrayRef(argv_, argc_);
+  argv.append(ArgsIn.begin(), ArgsIn.end());
 
   std::string ProgName = normalizeProgramName(argv[0]);
   const DriverSuffix *DS = parseDriverSuffix(ProgName);
```

I basically pasted in the implementation of `GetArgumentVector` for non-Windows OS, which is fine for me, since I don't profile on it.

templight works like a charm after that.

**Comment by mrks** [comment]
Works like a charm.
