### ISSUE TITLE
Find out why the sanitizer lies to us

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#920]
Issue in [line 275](https://github.com/hyrise/hyrise/blob/f76bc39ac5dc0ac804da8cb8f7ba15246abed89c/src/lib/operators/union_positions.cpp) `if (column_id == _column_segment_offsets[next_segment_id]) {`
At some point `next_segment_id` is `1` and `_column_segment_offsets` has a size of `1`.
To show issue on [Jenkins](https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/rest/organizations/jenkins/pipelines/Hyrise/pipelines/hyrise/branches/fabian%252Ftest_jenkins_sanitizer/runs/2/nodes/62/steps/114/log/?start=0), I added a function `at`: `_column_segment_offsets.at(next_segment_id)` to enable bounds checking.

Found via locally running sanitizer tests. Somehow, Jenkins sanitizer does not find them.

Found via running following tests:
* UnionPositionsTest:SelfUnionOverlappingRangesMultipleColumns
* UnionPositionsTest:MultipleReferencedTables
* SQLPipelineStatementTest:PreparedStatementMultiPlaceholderExecute
* SQLPipelineStatementTest:MultiplePreparedStatementsExecute

**Comment by FabianWiebe** [comment]
This was not the only issue I found locally during my sanitzer runs. So far I thought that the Jenkins was right and I had an issue with my local installation and, therefore, did not trust my own results. I will now create issues for the other findings.

**Comment by FabianWiebe** [comment]
I actually only found issue #922 . All others seem to be already resolved with the previous fixes.

**Comment by mrks** [comment]
The only thing I can think of that is different is the OS. Can we easily reduce the test case in #922 to an [SSCCE](http://sscce.org/)?

**Comment by FabianWiebe** [comment]
I created two SSCCE tests which pass on Jenkins but not on my locale installation: [Jenkins](https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/fabian%2Ftest_jenkins_sanitizer/10/pipeline/62/)

> TEST_F(UnionPositionsTest, OutOfBoundsCheckSSCCE) {
  std::vector<int> tmp_vec{1, 2, 3};
  tmp_vec.resize(1);
  EXPECT_TRUE(tmp_vec[1]);
}

> TEST_F(UnionPositionsTest, NonNullCheckSSCCE) {
  std::map<int, int> tmp_map;
  std::vector<int> tmp_vec(1);
  auto find = tmp_map.find(1);
  tmp_vec[find->second];
}

**Comment by mrks** [comment]
Please use markdown ` ``` ` so that `<int>` is not removed by some broken HTML check.

Do you want to prepare a StackOverflow question or should I have a look at it?

**Comment by mrks** [comment]
(I can confirm this with clang-6 on my OS X machine and pella)

**Comment by mrks** [comment]
Ah, I think this might be a question of the stdlib. Let me have a look.

**Comment by mrks** [comment]
Yepp. We need to add `libc++-dev` and `libc++abi-dev` to the Jenkins image and change one build to `-stdlib=libc++`.

I'll have a look at that tomorrow because I will have to upload a new Docker image for that.

Thanks for the SSCCE - that helped a lot!

**Comment by mrks** [comment]
For future reference:
https://stackoverflow.com/questions/51011673/addresssanitizer-only-finds-overflow-on-os-x
https://github.com/google/sanitizers/wiki/AddressSanitizerClangVsGCC-(6.0-vs-8.1)

**Comment by mrks** [comment]
Building with libc++ on Linux is not recommended. Maybe we get #722 at one point. Until then, let's use `-D_GLIBCXX_SANITIZE_VECTOR`. I'll prepare a PR.
