### ISSUE TITLE
Check whether benchmarks actually use encoding

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#928]
Probably a question mostly for @lawben .

If we keep the default chunk size at 2^32, there will be no immutable chunks. As such, there will be no encoding at all. Am I right?

I think we should discuss the default chunk size for the benchmarks. Especially since some algorithms (most joins) parallelize over chunks, which will be discarded by the benchmarks in the default setting.

**Comment by lanice** [comment]
I have just checked that for the TPCH benchmark, and apparently we encode the chunk(s) of the generated tables:
```
const auto tables = opossum::TpchDbGenerator(scale_factor, config->chunk_size).generate();

for (auto& tpch_table : tables) {
  const auto& table_name = opossum::tpch_table_names.at(tpch_table.first);
  auto& table = tpch_table.second;

  opossum::BenchmarkRunner::encode_table(table_name, table, *config);
  opossum::StorageManager::get().add_table(table_name, table);
}
```
(the default encoding in the config is DictionaryEncoding)

**Comment by mrks** [comment]
Ah, @Bouncner was thinking about `ChunkCompressionTask::chunk_is_completed`, which is only used by automatic compression. If we explicitly call the encoder, the chunks are not checked for "completeness".

**Comment by Bouncner** [comment]
Ok, that solves the encoding part but does not address that the default chunk size is very different from what we intended with the chunk design of Hyrise.

**Comment by mrks** [comment]
Correct, and I have "the quest for a good chunk size default" in the list of potential group topics.

**Comment by lanice** [comment]
It's difficult to set a chunk size default, since the "optimal" chunk size is different from machine to machine, or not?
I would say a good starting point would be cache size, which is 30 MB for the pella. BUT this then makes the optimal chunk size different depending on the data, since our chunk_size represents the number of rows, not MB, right?
