### ISSUE TITLE
Switch tpch-dbgen repo?

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#935]
The current tpch-dbgen repo has last been updated in 2011 and has a number of compiler warnings.

https://github.com/eyalroz/tpch-dbgen says "It's not the intention of this repository to make all of those disappear, or to effect a rewrite - but avoiding compiler warnings, ensuring the build passes on more platforms, and other such minor issues are what this endeavor is about."

@mrzzzrm - You added the tpch-dbgen repo. Any reason why we should not switch to the newer one?

**Comment by mrzzzrm** [comment]
Would be a bit of work, IIRC I had to alter some stuff in dbgen

**Comment by mrks** [comment]
Ok, moved to postponed.

**Comment by mrks** [comment]
Ok, moved to postponed.
