### ISSUE TITLE
Same interface for TPCC and TPCH table generation

### ISSUE THREAD

**Issue by lawben** [hyrise/hyrise#936]
Currently, the `TpccTableGenerator` create the tables and takes care of encoding them (after PR #927  is merged, via an `EncodingConfig`). The `TpchDbGenerator` (maybe naming could be more consistent here) creates the table and takes care of storing them in the storage manager but does not take care of encoding them. 

So we have:

| TPC-? | Generate Tables | Stores Tables | Encodes Tables |
|:---------:|:-------------:|:-----:|:------:|
| TPC-**H** | yes | yes | no |
| TPC-**C** | yes |   no | yes |

Maybe this should be unified with the same interface. There is an `AbstractBenchmarkTableGenerator`, which only TPCC uses. We should/could use that and extend its interface to included the options we want.

Up for discussion:
------------------

Should a table generator:

- [ ] store tables in the storage manager
- [ ] encoded tables

**Comment by ArneMayer** [comment]
#1150

**Comment by mrks** [comment]
> Should a table generator:
> *    store tables in the storage manager

Yes. What use are tables that cannot be used in a query?

> *    encode tables

I would say no. Encoding is independent of the generated data and can be the same for TPC-C and -H. Thus, the caller of the generator should be responsible.

**Comment by Bensk1** [comment]
If anyone starts working on that again, take a look at #1150

**Comment by mrzzzrm** [comment]
@mrks since you're reworking(?) tpcc support anyway, is it worth keeping this open?

**Comment by mrks** [comment]
I am still using the same TPC-C generator, so yes.
