### ISSUE TITLE
Error in SQLTranslator when a group by column has an alias

### ISSUE THREAD

**Issue by FabianWiebe** [hyrise/hyrise#939]
Running the queries below on a table `table_a` with a column `a`
`SELECT a AS b FROM table_a GROUP BY a;`
or
`SELECT a AS b FROM table_a GROUP BY b;`
results in
`src/lib/sql/sql_translator.cpp:809 Couldn't resolve groupby column.`
I believe this is a similar issue as #578 and #485 .

**Comment by mrzzzrm** [comment]
Will double check, but #882 should support this.
