### ISSUE TITLE
Null value awareness in indices

### ISSUE THREAD

**Issue by ArneMayer** [hyrise/hyrise#944]
-ART, Group Key, and Composite Group Key Index only operate on Value IDs, so they implicitly handle NULL values
-B-Tree index (#929) does not support null values as of now
-How does the query optimizer know which implementations support null values?
-Should we fall back to a table scan if null values are not supported?
-How should the interface look like if null values are explicitly supported?

**Comment by ArneMayer** [comment]
The index interface has lower bound and upper bound methods. How does this translate to null values? Are null values assumed to be less than any real value?

**Comment by mrks** [comment]
NULL values cannot be compared to any non-NULL values: http://sqlfiddle.com/#!9/e74d5f/2

This might be an issue with the current implementation for dictionary columns - if we use INT_MAX for NULL, we must make sure that it is not included in `WHERE a > 3`. I think we need an additional interface for the indexes that queries NULL values.

**Comment by mrks** [comment]
@mweisgut Have you already seen this?

**Comment by mrks** [comment]
For single-segment indexes, this was done in #1800, for multi-segment indexes, this is #1818.
