### ISSUE TITLE
Unencoded TPC-H fails

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#949]
```
./hyriseBenchmarkTPCH -e Unencoded
[PERF] Hyrise is running as a debug build. at src/lib/utils/performance_warning.cpp:13
	Performance can be affected. This warning is only shown once.

libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/statistics/chunk_statistics/chunk_statistics.cpp:10 The statistics should not contain any empty shared_ptrs.
Abort trap: 6
```

**Comment by Bouncner** [comment]
@ArneMayer & @lawben : do we "encode" the columns in case they stay uncompressed?
The vectors used for immutable and mutable unencoded chunks differ significantly in terms of scan performance.

**Comment by lawben** [comment]
So the CLI parser will just create an `EncodingConfig` with a default `ColumnEncodingSpec` with `EncodingType::Unencoded`. This is then passed to the `ChunkEncoder`. No idea what happens after that, but it seems like the `ChunkEncoder` doesn't create any statistics but then later on the column is marked as encoded and that would require statistics(?). I can investigate tomorrow.
