### ISSUE TITLE
Chunk::is_mutable()

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#957]
...is currently defined as 

```c++

bool Chunk::is_mutable() const {
  return std::all_of(_columns.begin(), _columns.end(),
                     [](const auto& column) { return std::dynamic_pointer_cast<BaseValueColumn>(column) != nullptr; });
}
```

however, @Bouncner pointed out in https://github.com/hyrise/hyrise/pull/956#issuecomment-402512336, that chunks might still contain ValueColumns and still be immutable - e.g. (i.e.?) if they have column statistics.

Do we want `is_mutable()` to return `(bool)_statistics`? and rely on this implicit connection?

**Comment by lawben** [comment]
Not entirely sure what all the different ways to encode a chunk are, but in the benchmarks we just call `ChunkEncoder::encode_all_chunks`. If this is (or should be) the only way to encode all columns of a chunk, wouldn't an explicit flag be better? `Chunk::mark_immutable() { _immutable = true; }`. 

Or am I missing something?

**Comment by mrzzzrm** [comment]
There is a dependency between `immutable` and `_statistics != nullptr` (`_statistics != nullptr` implies `_immutable == true`), but some Asserts should suffice to make sure that this dependency isn't violated.

**Comment by lawben** [comment]
In that case, I guess returning `_statistics != nullptr` with a comment should be clear enough

**Comment by mrks** [comment]
That seems both quite hacky to me. Any reason we don't have a set-once flag "is_immutable"?

**Comment by Bouncner** [comment]
I also don't like hiding that set-once-and-never-touch-it-again flag by some "magic checks".

**Comment by lawben** [comment]
This is now part of PR #956
