### ISSUE TITLE
Evaluate sqllogictest

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#962]
Just stumbled up this, looks like a great tool in addition/as replacement for our handwritten SQLTestRunner-Queries:

" Sqllogictest was originally designed to test SQLite, but it is database engine neutral and can just as easily be used to test other database products. "

https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki

**Comment by mrzzzrm** [comment]
Linking #598 in as I understand it to follow the same idea of large scale generative testing. 
Both concepts should probably be evaluated keeping the other one in mind.

**Comment by lanice** [comment]
It looks like a useful tool. Especially their vision of having a huge collection of automatically generated prototype scripts, which would cover much more than our few hand-written SQL queries.

A few thoughts:
1. If I'm reading this correctly, we'd need to offer an ODBC API
2. We would need to support CREATE TABLE shenanigans (#815)
3. It does not integrate as neatly into our `hyriseTest` suite as our SQLiteRunner. I imagine it would rather be an additional stand-alone tool next to tests, benchmarks, coverage, etc.

**Comment by mrks** [comment]
Long-term issue maintained in Trello now
