### ISSUE TITLE
Rule out useless compressions/encodings

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#963]
There is no point in using a 4-Byte ValueID to compress a uint32_t. Or is there?

This should reduce the number of instantiated templates.

**Comment by Bouncner** [comment]
Cannot think of a good (non-synthetic) reason.

**Comment by mrzzzrm** [comment]
Fast log-n lookup whether value is in Column because dictionary is sorted, maybe?

**Comment by Bouncner** [comment]
as long as we don’t sort chunks, that should not matter as we cannot bi-search. Or did I get you wrong?

Besides, is there a measurable difference between a search on uint32 vs 64? Would not expect one.

**Comment by mrks** [comment]
I was thinking that using 32bit-Value-IDs for 32 bit values doesn't make sense, and so we should not spend time to compile it.

I'm not 100 percent sure though, because things like Groupkey Indexes wouldn't work otherwise, right?

**Comment by mrks** [comment]
I understand that @mrzzzrm was thinking about existence checks, I.e., early pruning if the value does not exist

**Comment by mrks** [comment]
Looking through the code, I don't think we actually have this problem. We do initialize `FixedSizeByteAlignedCompressor<uint32_t>`, but that is used by everyone. We can't reduce the compile time here.
