### ISSUE TITLE
Sort-Merge-Join: Jobs with empty clusters

### ISSUE THREAD

**Issue by marcelja** [hyrise/hyrise#964]
Clusters with the size of zero are creating jobs which don't perform a join. Maybe a check if clusters are empty could be added before creating the jobs. This could lead to less scheduling overhead.

_determine_number_of_clusters() might needs to be updated as well.

**Comment by ArneMayer** [comment]
For outer joins and for non-equi joins (<, <=, >, >=) empty clusters can still produce rows. For Equi Inner joins there is a simple fix.

**Comment by mrks** [comment]
Let's do the simple fix then.
