### ISSUE TITLE
StringLength and ColumnNameLength

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#965]
```c++
using StringLength = uint16_t;     // The length of column value strings must fit in this type.
using ColumnNameLength = uint8_t;  // The length of column names must fit in this type.
```

Just had an auto-generated column name > 255 chars. We can't deal with that right now and I don't see why. Both of these should be `size_t`. We can't just increase the resolution of these because all our binary tests have these conservative resolutions baked in. 

Anyway, these should go, imo, and be replaced with size_t or at least be aliases of size_t. And we need to adjust all these test binaries (should be 28 of them)

**Comment by mrks** [comment]
@dimitri-schmidt - do you have to store column names anywhere in the logs?

**Comment by dimitri-schmidt** [comment]
nope, I don't use column information in logs.
