### ISSUE TITLE
Insert operator behaviour on column type mismatch

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#972]
`INSERT INTO int_float VALUES (1,2);` leads to `This ValueColumn does not support null values.`. Looking into this and you find 

```c++
 if (auto casted_dummy_source = std::dynamic_pointer_cast<const ValueColumn<int32_t>>(source)) {
      // We use the column type of the Dummy table used to insert a single null value.
      // A few asserts are needed to guarantee correct behaviour.
      Assert(length == 1, "Cannot insert multiple unknown null values at once.");
      Assert(casted_dummy_source->size() == 1, "Source column is of wrong type.");
      Assert(casted_dummy_source->null_values().front() == true, "Only value in dummy table must be NULL!");
      Assert(target_is_nullable, "Cannot insert NULL into NOT NULL target.");

      // Ignore source value and only set null to true
      casted_target->null_values()[target_start_index] = true;
    }
```
I speculate that this if block was written under the assumption that the input to the Insert operator might be the DummyTable. As far as I know, the DummyTable is never the input table of the Insert. Neither before or after #882

The Insert operator needs rework, imo. It needs to handle all input column types via one code path and not one for input ValueColumns and one for any other column type, it needs to deal with type mismatches with readable error messages. Its naming needs to be fixed (there is "i"s and "TypedColumnProcessor" and "length"s and "casted_source"s and "rows_to_insert_this_loop", ...). 
Right now I find the Insert operator very hard to read, happens every time I need to look into it.

Also there is this: `auto total_rows_to_insert = static_cast<uint32_t>(input_table_left()->row_count());` which will obviously fail if there is more than 4B rows and there is no apparent reason for it.

**Comment by mrks** [comment]
```
(debug)> load src/test/tables/int.tbl t
Loading src/test/tables/int.tbl into table "t" ...
(debug)> print t
=== Columns
|       a||        MVCC        |
|     int||_BEGIN|_END  |_TID  |
=== Chunk 0 ===
|     123||     0|      |      |
|    1234||     0|      |      |
|   12345||     0|      |      |
(debug)> INSERT INTO t (a) VALUES (3.2);
===
0 rows total
Execution info: [PARSE: 4 µs, TRANSLATE: 123 µs, OPTIMIZE: 57 µs, COMPILE: 94 µs, EXECUTE: 283 µs (wall time) | QUERY PLAN CACHE HITS: 0/1 statement(s)]
(debug)> print t
=== Columns
|       a||        MVCC        |
|     int||_BEGIN|_END  |_TID  |
=== Chunk 0 ===
|     123||     0|      |      |
|    1234||     0|      |      |
|   12345||     0|      |      |
|       3||     2|      |      |
```
