### ISSUE TITLE
Bug: Projection on Dictionary-encoded chunks does not work

### ISSUE THREAD

**Issue by SvenLehmann** [hyrise/hyrise#975]
Since #956 projections on Dictionary-encoded chunks do not work anymore and fail with the following error:
```
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/storage/chunk.cpp:62 Cannot get mutable column from immutable chunk.
```

#956 added an assertion that forbids returning a non-const pointer to a column when the chunk is immutable, e.g. dictionary-encoded. The ProjectionOperator is trying to reuse the input column for its own output, but expects a non-const pointer regardless of the encoding.

So far there are no tests for the ProjectionOperator that test simple column projections on dictionary-encoded chunks, but here is a simple playground to reproduce:
```
// Setup simple, dictionary-encoded table
auto t = std::make_shared<Table>(
    TableColumnDefinitions{{"a", DataType::Int}}, TableType::Data, 2, UseMvcc::Yes);
t->append({1});
ChunkEncoder::encode_all_chunks(t, ColumnEncodingSpec(EncodingType::Dictionary));
StorageManager::get().add_table("some_table", t);

// Run simple query against that table
auto gt = std::make_shared<opossum::GetTable>("some_table");
gt->execute();
auto a_expr = Projection::ColumnExpressions{PQPExpression::create_column(ColumnID{0})};
auto projection = std::make_shared<Projection>(gt, a_expr);
projection->execute();

return 0;
```

**Comment by mrzzzrm** [comment]
...haha, and there goes the myth of feasible const-correctness for anything but local variables.
