### ISSUE TITLE
SQLiteWrapper returns empty table if last char is a newline

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#984]
Don't know if this is SQLite or the wrapper, but

```sql
SELECT * FROM t;
```
returns some table, whereas
```sql
SELECT * FROM t;
<newline>

```
doesn't.

If this can be fixed, we can re-add DROP VIEW to TPC-H 15 and patch the string before handing it to sqlite in the tpch_test.cpp
While the behaviour is as described above, this is too shaky, imo.

@lanice any idea?

**Comment by mrks** [comment]
Those two look the same to me?!
