### ISSUE TITLE
README not available

### ISSUE THREAD

**Issue by coveritytest** [hyrise/hyrise#988]
README not available:

https://github.com/hyrise/hyrise/blob/master/README

**Comment by lanice** [comment]
You can find the readme file here:

https://github.com/hyrise/hyrise/blob/master/README.md

**Comment by coveritytest** [comment]
Thanks, but then there is a wrong link in the first line of

https://github.com/hyrise/hyrise/wiki/Step-by-Step-Guide

**Comment by mrks** [comment]
Thank you. Fixed.
