### ISSUE TITLE
install.sh breaks if /etc/lsb_release is missing

### ISSUE THREAD

**Issue by coveritytest** [hyrise/hyrise#989]
On Debian Stretch:

root@ma:~/hyrise# ./install.sh
This script installs the dependencies of Hyrise. It might upgrade already installed packages. Continue? [y|n] y
cat: /etc/lsb-release: No such file or directory

**Comment by mrks** [comment]
To make efficient use of our limited resources, we only support the latest versions of OS X and Ubuntu. In this particular case, you will probably get away with removing the line containing `/etc/lsb-release`.
