### ISSUE TITLE
SQLPipeline handles Prepare/Execute internally

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#991]
...I would have expected to see `PrepareNode`, `ExecuteNode` here, created by the SQLTranslator.
Imo this would be in accordance with our existing architecture.

Instead, the SQLPipelineState handles prepared statements internally, making  `SQLPipelineStatement::get_unoptimized_logical_plan()` and especially `SQLPipelineStatement::get_query_plan()` hard to read, at least for me.

The server does another thing for `EXECUTE`, handing the SQL to execute (still with placeholders) into the SQLPipeline and adds the parameters to the physical plan itself. 

@lawben, you're probably (understandably ;) ) to busy to comment on this, I guess?

**Comment by lawben** [comment]
I can have a look at this tomorrow :)

**Comment by lawben** [comment]
Sorry, didn't get a chance yesterday due to some personal reasons. I guess that means you may molest the pipeline in whichever way you see fit ;)
